// @profile B
// Profile B · Calculator-AI · ModelLatencyCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< 0.5s", label: { zh: "即時", en: "Instant" }, desc: { zh: "回應極快，使用者幾乎無感等待，適合即時對話與互動式體驗。", en: "Very fast response; users feel almost no wait—ideal for real-time chat and interactive experiences." } },
  { key: "low", range: "0.5–1.5s", label: { zh: "流暢", en: "Smooth" }, desc: { zh: "流暢區間，多數對話應用可接受，建議搭配串流輸出減少體感延遲。", en: "Smooth band; acceptable for most chat apps—pair with streaming output to reduce perceived latency." } },
  { key: "healthy", range: "1.5–3s", label: { zh: "可接受", en: "Acceptable" }, desc: { zh: "可接受區間，需加上載入提示與串流，避免使用者誤以為卡住。", en: "Acceptable band; add a loading hint and streaming so users don't think it has stalled." } },
  { key: "good", range: "3–6s", label: { zh: "偏慢", en: "Slow" }, desc: { zh: "偏慢，建議縮短輸出長度、改用較快硬體階層或啟用快取加速。", en: "Slow; shorten output length, switch to a faster hardware tier, or enable cache acceleration." } },
  { key: "strong", range: "6–12s", label: { zh: "明顯延遲", en: "Laggy" }, desc: { zh: "明顯延遲，務必檢視批次大小、上下文長度與排隊等待時間。", en: "Noticeable lag; review batch size, context length, and queue wait time." } },
  { key: "elite", range: "> 12s", label: { zh: "嚴重", en: "Critical" }, desc: { zh: "嚴重延遲，須擴充推論資源、分片並行或改用較小較快的模型。", en: "Critical latency; scale inference resources, shard in parallel, or switch to a smaller faster model." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "AI準確率計算機", en: "AI Accuracy Calculator" }, href: "/tools/ai/ai-accuracy-calculator" },
  { label: { zh: "AI錯誤率計算機", en: "AI Error Rate Calculator" }, href: "/tools/ai/ai-error-rate-calculator" },
  { label: { zh: "AI模型比較器", en: "AI Model Comparison" }, href: "/tools/ai/ai-model-comparison" },
  { label: { zh: "AI Token成本計算機", en: "AI Token Cost Calculator" }, href: "/tools/ai/ai-token-cost-calculator" },
];

const ui = {
  zh: {
    badge: "AI · Latency · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "模型延遲計算機 · Latency", subtitle: "用輸出 token 數、吞吐量與硬體階層算出總回應延遲、每 token 延遲與延遲分數",
    intro: "Model Latency Calculator 依據輸出 token 數、每秒吞吐量與硬體階層（節能、標準或高速），計算模型總回應延遲、每 token 延遲與延遲分數，協助你判斷回應速度是否符合使用者期待、該選哪種硬體階層、是否需要串流輸出或縮短上下文，讓你在部署 AI 模型前就把延遲體驗算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以你輸入的吞吐量估算延遲，未含網路往返、排隊等待、首 token 延遲與批次效應；實際延遲請以真實壓力測試與監控數據為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立延遲範例", examplePreview: "延遲預覽", examplePerson: "輸出 token 數", fillExample: "一鍵填入標準硬體範例", previewActivePath: "填入高速硬體範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入輸出 token 數、吞吐量與硬體階層", examplesHelper: "先用範例理解 token 數與吞吐量如何決定總延遲與每 token 延遲，再改成自己的部署數據。",
    metric: "公制", imperial: "占比檢視", exampleCards: "範例卡", baselineExample: "標準硬體模式", activeExample: "高速硬體示範", baselineExampleNote: "token 500 · 吞吐 50 · 標準", activeExampleNote: "token 500 · 吞吐 50 · 高速", carbsLabel: "每 token 延遲", carbsName: "毫秒", proteinLabel: "延遲分數", flowDemo: "吞吐量", calculator: "計算機",
    weight: "輸出 token 數", tdee: "吞吐量 (token/秒)", goal: "硬體階層", goalCut: "節能 (×1.4)", goalMaintain: "標準 (×1.0)", goalBulk: "高速 (×0.5)",
    resultCard: "延遲結果", unit: "秒 (總回應延遲)", primaryValue: "主要數值", maintenanceTarget: "延遲分數", actionTarget: "總延遲", estimatedTdee: "吞吐量", maintenance: "分", fatLossTarget: "秒",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格回應延遲判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前總延遲放進常見區間；這是規劃參考，不是壓測結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把延遲結果轉成可執行的效能優化策略", conversionNote: "L9 會連動目前計算結果，顯示延遲分數、總延遲與每 token 延遲提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前部署概況", dailyGap: "總延遲", weeklyTrend: "延遲分數", motivation: "動力卡", keepMomentum: "從延遲分析走向最順暢的回應體驗節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的延遲結果帶回團隊", journeyHint: "用 AI 準確率計算機一起看，把延遲與準確率一併納入上線決策。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用 AI 準確率計算機評估模型品質", nextActionItem2: "用 AI 錯誤率計算機拆解失敗重試延遲", nextActionItem3: "用 AI 模型比較器找出速度與品質最佳模型",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Tokens → Latency → Tier → Throughput", bmrStep: "Token數", deficitStep: "延遲分數", trendStep: "硬體階層", mealStep: "吞吐量",
    knowledge: "知識", knowledgeTitle: "回應延遲與延遲分數在模型部署中的意義", definition: "定義", definitionText: "總回應延遲是輸出 token 數除以每秒吞吐量再乘以硬體係數所得的秒數；延遲分數則把總延遲對照三秒可接受門檻換算，衡量回應速度相對使用者期待的達成度。", formula: "公式", formulaText: "總延遲 = 輸出 token ÷ 吞吐量 × 硬體係數（秒）。每 token 延遲 = 總延遲 ÷ token 數 × 1000（毫秒）。延遲分數 = (1 − 總延遲 ÷ 6) × 100，下限 0 分。", limitations: "限制", limitationsText: "本工具以穩定吞吐量估算；真實延遲還受網路往返、排隊等待、首 token 延遲、批次大小、上下文長度與硬體競爭影響，且尖峰時段差異大。", interpretation: "解讀", interpretationText: "總延遲超過三秒多需優化；可透過串流輸出、縮短回應、減少上下文、改用較快硬體階層或快取重複查詢來降低延遲。", context: "脈絡", contextText: "延遲結果應與模型準確率、錯誤率與模型比較一起看，才能在速度、品質與成本之間取得平衡。", example: "範例", exampleText: "輸出 500 token、吞吐 50 token/秒、標準硬體（×1.0）→ 總延遲約 10 秒，每 token 約 20 毫秒。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "延遲的下一步工具", premiumTitle: "PRO 延遲效能分析包", premiumText: "解鎖首 token 延遲模擬、批次吞吐曲線、排隊等待估算與多硬體階層延遲比較矩陣。",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供效能規劃與教育用途，不取代真實壓力測試、生產監控數據或正式效能審查。", relatedTools: "相關工具", relatedToolsText: "AI Accuracy · AI Error Rate · Model Comparison · Token Cost", references: "參考資料", referencesText: "推論吞吐量基準文件；首 token 延遲定義；批次推論方法；GPU 與加速器規格表與壓測指南。",
    q1: "總延遲怎麼算的？", a1: "本工具以輸出 token 數除以吞吐量再乘硬體係數得總延遲；實際還受網路往返與排隊等待影響。",
    q2: "延遲分數多少才合理？", a2: "延遲分數越高代表回應越快；若分數偏低，建議串流輸出、縮短回應或改用較快硬體階層。",
    q3: "節能還是高速硬體？", a3: "批次離線任務可用節能階層；即時對話與互動場景才用高速階層，並用模型比較評估成本取捨。",
    q4: "延遲太高怎麼降低？", a4: "啟用串流輸出、設定回應上限、壓縮上下文、改用較快硬體、批次合併推論並快取重複查詢。",
    q5: "要不要看首 token 延遲？", a5: "建議要。本工具估算整體生成時間；若重視體感速度，請另看首 token 延遲與串流輸出表現。",
    q6: "這個工具能取代壓測嗎？", a6: "不能。它只是快速估算與教育用途；實際延遲應以真實壓力測試與生產監控數據為準。",
  },
  en: {
    badge: "AI · Latency · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Model Latency Calculator", subtitle: "Compute total response latency, per-token latency, and latency score from output tokens, throughput, and hardware tier",
    intro: "This calculator uses output tokens, throughput per second, and hardware tier (eco, standard, or fast) to compute total response latency, per-token latency, and a latency score, helping you judge whether response speed meets user expectations, which hardware tier to choose, and whether to use streaming output or shorten context, so you compute the latency experience clearly before deploying an AI model.",
    trustNoteLabel: "Note:", trustNote: "This tool estimates latency from the throughput you enter, excluding network round trips, queue wait, time-to-first-token, and batch effects; for actual latency, follow real load tests and monitoring data.",
    quickActionCard: "Quick Action Card", tryExample: "Create a latency example instantly", examplePreview: "Latency preview", examplePerson: "Output tokens", fillExample: "One-click standard hardware example", previewActivePath: "Fill fast hardware example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter output tokens, throughput, and hardware tier", examplesHelper: "Start with an example to see how token count and throughput set total latency and per-token latency, then replace with your own deployment data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard hardware mode", activeExample: "Fast hardware demo", baselineExampleNote: "token 500 · throughput 50 · standard", activeExampleNote: "token 500 · throughput 50 · fast", carbsLabel: "Per-token latency", carbsName: "ms", proteinLabel: "Latency score", flowDemo: "Throughput", calculator: "Calculator",
    weight: "Output tokens", tdee: "Throughput (tokens/sec)", goal: "Hardware tier", goalCut: "Eco (×1.4)", goalMaintain: "Standard (×1.0)", goalBulk: "Fast (×0.5)",
    resultCard: "Latency Result", unit: "sec (total response latency)", primaryValue: "Primary Value", maintenanceTarget: "Latency score", actionTarget: "Total latency", estimatedTdee: "Throughput", maintenance: "pts", fatLossTarget: "sec",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card response-latency interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place current total latency into common zones. This is planning guidance, not a load-test conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the latency result into an actionable performance-optimization strategy", conversionNote: "L9 values update from the computed result: latency score, total latency, and per-token latency hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current deployment snapshot", dailyGap: "Total latency", weeklyTrend: "Latency score", motivation: "Motivation Card", keepMomentum: "Move from latency analysis to the smoothest response-experience rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's latency result to your team", journeyHint: "Review it with the AI Accuracy Calculator to fold latency and accuracy into the deployment decision.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Assess model quality with the AI Accuracy Calculator", nextActionItem2: "Break down retry latency with the AI Error Rate Calculator", nextActionItem3: "Find the best speed-quality model with AI Model Comparison",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Tokens → Latency → Tier → Throughput", bmrStep: "Tokens", deficitStep: "Latency score", trendStep: "Hardware tier", mealStep: "Throughput",
    knowledge: "Knowledge", knowledgeTitle: "What response latency and latency score mean in model deployment", definition: "Definition", definitionText: "Total response latency is output tokens divided by throughput per second times a hardware factor in seconds; the latency score maps total latency against a three-second acceptable threshold, measuring how close response speed is to user expectations.", formula: "Formula", formulaText: "Total latency = output tokens ÷ throughput × hardware factor (sec). Per-token latency = total latency ÷ tokens × 1000 (ms). Latency score = (1 − total latency ÷ 6) × 100, floored at 0 points.", limitations: "Limitations", limitationsText: "This tool estimates from steady throughput; real latency is also affected by network round trips, queue wait, time-to-first-token, batch size, context length, and hardware contention, with large peak-time variance.", interpretation: "Interpretation", interpretationText: "Total latency over three seconds usually warrants optimization; reduce latency with streaming output, shorter responses, less context, faster hardware tiers, or caching repeat queries.", context: "Context", contextText: "Latency results should be evaluated with model accuracy, error rate, and model comparison to balance speed, quality, and cost.", example: "Example", exampleText: "Output 500 tokens, throughput 50 tokens/sec, standard hardware (×1.0) → total latency about 10 sec, per token about 20 ms.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for latency", premiumTitle: "PRO Latency Performance Analytics Pack", premiumText: "Unlock time-to-first-token simulation, batch throughput curves, queue-wait estimation, and a multi-hardware-tier latency comparison matrix.",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for performance planning and education. It does not replace real load testing, production monitoring data, or formal performance review.", relatedTools: "Related Tools", relatedToolsText: "AI Accuracy · AI Error Rate · Model Comparison · Token Cost", references: "References", referencesText: "Inference throughput benchmark docs; time-to-first-token definitions; batch inference methods; GPU and accelerator spec sheets and load-test guides.",
    q1: "How is total latency calculated?", a1: "This tool divides output tokens by throughput then multiplies by a hardware factor for total latency; actual is also affected by network round trips and queue wait.",
    q2: "What latency score is reasonable?", a2: "The higher the latency score the faster the response; if the score is low, use streaming output, shorten responses, or switch to faster hardware.",
    q3: "Eco or fast hardware?", a3: "Use the eco tier for batch offline tasks; use the fast tier only for real-time chat and interactive scenarios, and assess cost trade-offs with Model Comparison.",
    q4: "How do I reduce high latency?", a4: "Enable streaming output, cap response length, compress context, switch to faster hardware, batch inference, and cache repeat queries.",
    q5: "Should I look at time-to-first-token?", a5: "Recommended. This tool estimates total generation time; if perceived speed matters, also check time-to-first-token and streaming output performance.",
    q6: "Can this tool replace load testing?", a6: "No. It is a quick estimate for education; actual latency should follow real load testing and production monitoring data.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function hardwareFactor(mode: TierMode): number {
  if (mode === "relaxed") return 1.4;
  if (mode === "fast") return 0.5;
  return 1.0;
}

export default function ModelLatencyCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("500");
  const [tdee, setTdee] = useState("50");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const tokens = Number(weight);
    const throughput = Number(tdee);
    if (tokens <= 0 || throughput <= 0) return null;
    const totalLatency = (tokens / throughput) * hardwareFactor(goal);
    const perTokenMs = (totalLatency / tokens) * 1000;
    const latencyScore = Math.max((1 - totalLatency / 6) * 100, 0);
    return { totalLatency, perTokenMs, latencyScore };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.latencyScore, 0) : "—";
  const fatDisplay = result ? fmt(result.totalLatency, 1) : "—";
  const carbDisplay = result ? fmt(result.perTokenMs, 1) : "—";
  const totalDisplay = result ? fmt(result.totalLatency, 1) : "—";

  function fillStandard() { setUnit("metric"); setWeight("500"); setTdee("50"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("500"); setTdee("50"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">10.0</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">5.0</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">s</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">ms</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">s</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="model-latency-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.totalLatency, 1) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.latencyScore, 0) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Tokens", note: t.bmrStep }, { label: "Latency", note: t.deficitStep }, { label: "Tier", note: t.trendStep }, { label: "Throughput", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="model-latency-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{["FirstTokenSim", "ThroughputCurve", "QueueEstimate", "HardwareMatrix"].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
