// @profile B
// Profile B · Calculator-Science · HeatEnergyCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< 100", label: { zh: "微量級", en: "Tiny" }, desc: { zh: "熱量極低，落在微量區間，常見於小樣本或微小溫差，數值小，適合精密實驗與教學示範。", en: "Very low heat in the tiny range, common in small samples or small temperature differences; small values fit for precision experiments and teaching." } },
  { key: "low", range: "100–1k", label: { zh: "低熱級", en: "Low" }, desc: { zh: "熱量偏低，適合杯水加溫或小型加熱情境，常見於生活與基礎實驗，數值直觀易理解。", en: "Low heat, fit for warming a cup of water or small heating scenarios, common in daily life and basic experiments, intuitive to understand." } },
  { key: "medium", range: "1k–10k", label: { zh: "中熱級", en: "Medium" }, desc: { zh: "熱量落在常見的中等區間，多數家用加熱與烹飪情境的能量範圍，數值直觀易估算。", en: "Heat in the common medium range, the band for most household heating and cooking scenarios, intuitive to estimate." } },
  { key: "high", range: "10k–100k", label: { zh: "高熱級", en: "High" }, desc: { zh: "熱量偏高，涵蓋大量加熱與工業製程，能量明顯可觀，常用於熱水系統與製程設計。", en: "High heat covering bulk heating and industrial processes; the energy is noticeably significant, common in hot-water systems and process design." } },
  { key: "veryhigh", range: "100k–1M", label: { zh: "超高熱", en: "Very High" }, desc: { zh: "熱量非常高，常見於大型熱系統或工業鍋爐，建議結合保溫與安全規範一併評估。", en: "Very high heat, common in large thermal systems or industrial boilers; evaluate with insulation and safety standards." } },
  { key: "extreme", range: "> 1M", label: { zh: "極熱級", en: "Extreme" }, desc: { zh: "熱量極高，屬於大型工業或特殊能量範疇，務必交叉驗證質量與溫差的單位與量測精度。", en: "Extremely high heat in the large-industrial or special-energy range; always verify mass and temperature-difference units and measurement precision." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "功率計算機", en: "Power Calculator" }, href: "/tools/science/power-calculator" },
  { label: { zh: "通用單位換算計算機", en: "Unit Converter Calculator" }, href: "/tools/science/unit-converter-calculator" },
  { label: { zh: "密度計算機", en: "Density Calculator" }, href: "/tools/science/density-calculator" },
  { label: { zh: "理想氣體定律計算機", en: "Ideal Gas Law Calculator" }, href: "/tools/science/ideal-gas-law-calculator" },
];

const ui = {
  zh: {
    badge: "Science · 熱能 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "熱能計算機 · Heat", subtitle: "用質量、溫度變化與精度等級算出熱量、相對量級與精度分數",
    intro: "Heat Energy Calculator 依據質量、溫度變化與精度等級（粗略、標準或精密），以熱量公式 Q = m × c × ΔT（取水的比熱 c = 4.186 J/g·K）計算吸放熱、相對量級與精度分數，協助你判斷熱量是否合理、落在哪個量級、是否需要檢查單位，讓你在熱力計算與能量設計前就把熱量算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以 Q = m × c × ΔT 計算，取水的比熱且假設無相變；正式熱力分析請以實際比熱、相變潛熱與標準參考資料為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立熱量範例", examplePreview: "熱量預覽", examplePerson: "質量 (g)", fillExample: "一鍵填入標準範例", previewActivePath: "填入精密範例",
    examplesCalculator: "範例 → 計算器", enterValues: "輸入質量、溫度變化與精度等級", examplesHelper: "先用範例理解質量與溫差如何決定熱量與量級，再改成自己的熱力數據。",
    metric: "公制", imperial: "佔比檢視", exampleCards: "範例卡", baselineExample: "標準熱量模式", activeExample: "精密示範", baselineExampleNote: "100g × 10K · 標準", activeExampleNote: "100g × 50K · 精密", carbsLabel: "精度餘量", carbsName: "百分比", proteinLabel: "精度分數", flowDemo: "溫度變化 (K)", calculator: "計算器",
    weight: "質量 (g)", tdee: "溫度變化 (K)", goal: "精度等級", goalCut: "粗略 (0 位)", goalMaintain: "標準 (1 位)", goalBulk: "精密 (3 位)",
    resultCard: "熱量結果", unit: "J (熱量)", primaryValue: "主要數值", maintenanceTarget: "精度分數", actionTarget: "熱量", estimatedTdee: "溫差", maintenance: "分", fatLossTarget: "J",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格熱量量級判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前熱量放進常見量級；這是能量參考，不是熱力鑑定結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把熱量結果轉成可執行的熱力計算與能量設計策略", conversionNote: "L9 會連動目前計算結果，顯示精度分數、熱量與量級提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前熱量概況", dailyGap: "熱量", weeklyTrend: "精度分數", motivation: "動力卡", keepMomentum: "從熱量計算走向最精確一致的熱力計算節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的熱量結果帶回團隊", journeyHint: "用功率計算機一起看，把熱量與功率一併納入能量設計規劃。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用功率計算機推算加熱功率", nextActionItem2: "用通用單位換算計算機轉換能量單位", nextActionItem3: "用密度計算機計算質量分布",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Mass → 精度分數 → 等級 → Heat", bmrStep: "Mass", deficitStep: "精度分數", trendStep: "等級", mealStep: "Heat",
    knowledge: "知識", knowledgeTitle: "熱量在熱力計算中的意義", definition: "定義", definitionText: "熱量是物質溫度改變時吸收或釋放的能量，以公式 Q = m × c × ΔT 表示；熱量反映加熱或冷卻所需的能量，是判斷能量需求、設計熱系統與分析熱效率的核心物理量。", formula: "公式", formulaText: "熱量 Q = 質量 m × 比熱 c × 溫度變化 ΔT，本工具取水的比熱 c = 4.186 J/g·K。精度分數 = min(有效位數 / 目標位數 × 100, 100)。精度餘量 = (有效位數 − 目標位數) / 目標位數 × 100%。", limitations: "限制", limitationsText: "本工具取水的比熱且假設無相變；真實熱量還受材料比熱、相變潛熱與熱損失影響，沸騰或凝固等相變過程須另計潛熱。", interpretation: "解讀", interpretationText: "熱量落在低熱級（100–1k）常見於杯水加溫，中熱級以上多為家用與工業加熱，溫差或質量越大熱量越高，請用精度分數確認有效位數足夠。", context: "脈絡", contextText: "熱量結果應與質量、溫差與單位換算一起看，才能在能量準確性、熱力計算與可讀性之間取得平衡。", example: "範例", exampleText: "質量 100g、溫度變化 10K、標準精度（1 位）→ 熱量 4186.0 J，精度餘量 0%，精度分數 100。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "熱能的下一步工具", premiumTitle: "PRO 熱力分析包", premiumText: "解鎖多材料比熱對照表、相變潛熱計算、熱損失修正與熱效率與能量成本推算。", feat1: "比熱對照表", feat2: "相變潛熱", feat3: "熱損修正", feat4: "能源成本",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供熱力計算與教育用途，不取代專業熱力鑑定、能量量測或實驗室分析報告。", relatedTools: "相關工具", relatedToolsText: "Power · Unit Converter · Density · Ideal Gas", references: "參考資料", referencesText: "熱量物理定義；材料比熱標準參考表；SI 質量溫度能量單位定義；熱力學基礎文獻。",
    q1: "熱量怎麼算的？", a1: "本工具以 Q = m × c × ΔT，將質量、比熱與溫度變化相乘得到熱量；本工具取水的比熱 4.186 J/g·K。",
    q2: "精度分數多少才合理？", a2: "精度分數達 100 代表有效位數已達所選精度等級；若低於 100，建議提高有效位數或檢查量測精度。",
    q3: "粗略還是精密等級？", a3: "日常估算用粗略（0 位），一般熱力計算用標準（1 位），實驗室或精密分析用精密（3 位）。",
    q4: "怎麼判斷熱量量級？", a4: "熱量低於 1k J 屬低熱常見於杯水加溫，1k 至 100k 為中高熱多用於家用加熱；比較熱量與量級提示即可判斷。",
    q5: "比熱會影響熱量嗎？", a5: "會。不同材料比熱差異大，本工具固定取水的比熱 4.186 J/g·K；其他材料請改用實際比熱重新計算。",
    q6: "這個工具能取代熱力鑑定嗎？", a6: "不能。它只是快速估算與教育用途；正式熱力鑑定應以專業量熱儀與標準參考資料為準。",
  },
  en: {
    badge: "Science · Heat · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Heat Energy Calculator", subtitle: "Compute heat, relative magnitude, and precision score from mass, temperature change, and precision level",
    intro: "This calculator uses mass, temperature change, and precision level (rough, standard, or precise) with the heat formula Q = m x c x delta-T (taking the specific heat of water c = 4.186 J/g.K) to compute absorbed or released heat, relative magnitude, and precision score, helping you judge whether the heat is reasonable, which magnitude it falls into, and whether to check units, so you compute heat clearly before thermal calculations and energy design.",
    trustNoteLabel: "Note:", trustNote: "This tool computes Q = m x c x delta-T, taking the specific heat of water and assuming no phase change; for formal thermal analysis, follow actual specific heat, latent heat, and standard reference data.",
    quickActionCard: "Quick Action Card", tryExample: "Create a heat example instantly", examplePreview: "Heat preview", examplePerson: "Mass (g)", fillExample: "One-click standard example", previewActivePath: "Fill precise example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter mass, temperature change, and precision level", examplesHelper: "Start with an example to see how mass and temperature difference set the heat and magnitude, then replace with your own thermal data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard heat mode", activeExample: "Precise demo", baselineExampleNote: "100g x 10K · standard", activeExampleNote: "100g x 50K · precise", carbsLabel: "Precision margin", carbsName: "percent", proteinLabel: "Precision score", flowDemo: "Temperature change (K)", calculator: "Calculator",
    weight: "Mass (g)", tdee: "Temperature change (K)", goal: "Precision level", goalCut: "Rough (0 digit)", goalMaintain: "Standard (1 digit)", goalBulk: "Precise (3 digits)",
    resultCard: "Heat Result", unit: "J (heat)", primaryValue: "Primary Value", maintenanceTarget: "Precision score", actionTarget: "Heat", estimatedTdee: "Temp change", maintenance: "pts", fatLossTarget: "J",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card heat magnitude interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current heat into common magnitudes. This is energy guidance, not a thermal identification conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the heat result into an actionable thermal-calculation and energy-design strategy", conversionNote: "L9 values update from the computed result: precision score, heat, and magnitude hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current heat snapshot", dailyGap: "Heat", weeklyTrend: "Precision score", motivation: "Motivation Card", keepMomentum: "Move from heat calculation to the most precise and consistent thermal-calculation rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's heat result to your team", journeyHint: "Review it with the Power Calculator to fold heat and power into energy-design planning.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Derive heating power with the Power Calculator", nextActionItem2: "Convert energy units with the Unit Converter Calculator", nextActionItem3: "Compute mass distribution with the Density Calculator",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Mass → Precision → Level → Heat", bmrStep: "Mass", deficitStep: "Precision", trendStep: "Level", mealStep: "Heat",
    knowledge: "Knowledge", knowledgeTitle: "What heat means in thermal calculation", definition: "Definition", definitionText: "Heat is the energy absorbed or released when a substance changes temperature, expressed as Q = m x c x delta-T; heat reflects the energy needed for heating or cooling, the core physical quantity for judging energy demand, designing thermal systems, and analyzing thermal efficiency.", formula: "Formula", formulaText: "Heat Q = mass m x specific heat c x temperature change delta-T; this tool takes the specific heat of water c = 4.186 J/g.K. Precision score = min(significant digits / target digits x 100, 100). Precision margin = (significant digits - target digits) / target digits x 100%.", limitations: "Limitations", limitationsText: "This tool takes the specific heat of water and assumes no phase change; real heat is also affected by material specific heat, latent heat, and heat loss, and phase changes such as boiling or freezing need separate latent-heat calculation.", interpretation: "Interpretation", interpretationText: "Heat in the low range (100 to 1k) is common in warming a cup of water, the medium range and above is mostly household and industrial heating, larger temperature difference or mass means more heat, and use the precision score to confirm sufficient significant digits.", context: "Context", contextText: "Heat results should be evaluated with mass, temperature difference, and unit conversion to balance energy accuracy, thermal calculation, and readability.", example: "Example", exampleText: "Mass 100g, temperature change 10K, standard precision (1 digit) gives heat 4186.0 J, precision margin 0 percent, precision score 100.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for heat", premiumTitle: "PRO Heat Analytics Pack", premiumText: "Unlock multi-material specific-heat reference tables, latent-heat calculation, heat-loss correction, and thermal-efficiency and energy-cost estimation.", feat1: "Specific Heat Tables", feat2: "Latent Heat", feat3: "Heat Loss Fix", feat4: "Energy Cost",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for thermal calculation and education. It does not replace professional thermal identification, energy measurement, or laboratory analysis reports.", relatedTools: "Related Tools", relatedToolsText: "Power · Unit Converter · Density · Ideal Gas", references: "References", referencesText: "Physical definition of heat; material specific-heat standard reference tables; SI mass, temperature, and energy unit definitions; thermodynamics fundamentals.",
    q1: "How is heat calculated?", a1: "This tool uses Q = m x c x delta-T, multiplying mass, specific heat, and temperature change to get heat; this tool takes the specific heat of water 4.186 J/g.K.",
    q2: "What precision score is reasonable?", a2: "A precision score of 100 means significant digits meet the chosen precision level; if below 100, increase significant digits or check measurement precision.",
    q3: "Rough or precise level?", a3: "Use rough (0 digit) for daily estimates, standard (1 digit) for general thermal calculations, and precise (3 digits) for lab or precision analysis.",
    q4: "How do I judge heat magnitude?", a4: "Heat below 1k J is low common in warming a cup of water, 1k to 100k is medium-high mostly for household heating; compare heat with the magnitude hint to decide.",
    q5: "Does specific heat affect heat?", a5: "Yes. Different materials have very different specific heats; this tool fixes the specific heat of water at 4.186 J/g.K, so use the actual specific heat for other materials and recompute.",
    q6: "Can this tool replace thermal identification?", a6: "No. It is a quick estimate for education; formal thermal identification should follow professional calorimeters and standard reference data.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function targetDigits(mode: TierMode): number {
  if (mode === "relaxed") return 0;
  if (mode === "fast") return 3;
  return 1;
}

export default function HeatEnergyCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("100");
  const [tdee, setTdee] = useState("10");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const mass = Number(weight);
    const deltaT = Number(tdee);
    if (!Number.isFinite(mass) || !Number.isFinite(deltaT) || mass < 0) return null;
    const digits = targetDigits(goal);
    const heat = mass * 4.186 * deltaT;
    const sigDigits = digits;
    const precisionScore = Math.min((sigDigits / Math.max(digits, 1)) * 100, 100);
    const precisionMargin = ((sigDigits - digits) / Math.max(digits, 1)) * 100;
    return { heat, precisionScore, precisionMargin, digits };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.precisionScore, 1) : "—";
  const fatDisplay = result ? fmt(result.heat, result.digits) : "—";
  const carbDisplay = result ? fmt(result.precisionMargin, 1) : "—";
  const totalDisplay = result ? fmt(result.heat, result.digits) : "—";

  function fillStandard() { setUnit("metric"); setWeight("100"); setTdee("10"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("100"); setTdee("50"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">4186</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">20930</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">J</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">%</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">J</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="heat-energy-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.heat, result.digits) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.precisionScore, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Mass", note: t.bmrStep }, { label: "Precision", note: t.deficitStep }, { label: "Level", note: t.trendStep }, { label: "Heat", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="heat-energy-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
