// @profile B
// Profile B · Calculator-YMYL · NetWorthCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "negative", range: "< $0", label: { zh: "負淨資產", en: "Negative net worth" }, desc: { zh: "負債超過資產，需優先處理高息債務。", en: "Liabilities exceed assets — prioritize paying down high-interest debt." } },
  { key: "starting", range: "$0–$10k", label: { zh: "起步期", en: "Starting out" }, desc: { zh: "剛開始累積，重點在建立儲蓄習慣。", en: "Just starting to build — focus on the savings habit first." } },
  { key: "building", range: "$10k–$100k", label: { zh: "穩步累積", en: "Building" }, desc: { zh: "已有基礎，開始考慮投資組合。", en: "You have a base — start thinking about an investment portfolio." } },
  { key: "solid", range: "$100k–$500k", label: { zh: "穩健資產", en: "Solid" }, desc: { zh: "資產穩定，可增加多元投資。", en: "Assets are stable — diversify across multiple investments." } },
  { key: "high", range: "$500k–$2M", label: { zh: "高資產", en: "High net worth" }, desc: { zh: "進入財富自由規劃區間，考慮稅務策略。", en: "Entering the financial-independence zone — consider tax-planning strategies." } },
  { key: "ultra", range: "$2M+", label: { zh: "超高資產", en: "Ultra-high net worth" }, desc: { zh: "需專業財富管理與傳承規劃。", en: "Calls for professional wealth management and estate planning." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "貸款計算機", en: "Loan Calculator" }, href: "/tools/finance/loan-calculator" },
  { label: { zh: "複利計算機", en: "Compound Interest Calculator" }, href: "/tools/finance/compound-interest-calculator" },
  { label: { zh: "負債收入比計算機", en: "Debt-to-Income Calculator" }, href: "/tools/finance/debt-to-income-calculator" },
  { label: { zh: "退休計算機", en: "Retirement Calculator" }, href: "/tools/finance/retirement-calculator" },
];

const ui = {
  zh: {
    badge: "財務 · 資產規劃 · 黃金工具", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Net Worth Calculator · 淨資產計算機", subtitle: "盤點資產與負債，計算淨資產並掌握財務健康",
    intro: "本工具把你的總資產（現金、投資、不動產）減去總負債（貸款、信用卡），得出淨資產數值，協助了解目前財務健康並規劃改善方向。",
    trustNoteLabel: "注意事項：", trustNote: "資產估值可能與市場實際變動有差異；不動產與投資需定期重新估算。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立淨資產範例", examplePreview: "淨資產預覽", examplePerson: "標準範例", fillExample: "一鍵填入標準範例", previewActivePath: "填入高負債範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入資產與負債", examplesHelper: "先用範例理解淨資產計算，再改成自己的數字。",
    metric: "簡易", imperial: "詳細", exampleCards: "範例卡", baselineExample: "穩健型 · 淨資產 $250k", activeExample: "高負債型", flowDemo: "資產 $350k", calculator: "計算機",
    cashSavings: "現金與存款 ($)", investments: "投資組合 ($)", property: "不動產估值 ($)", otherAssets: "其他資產 ($)", mortgage: "房貸餘額 ($)", creditCard: "信用卡債務 ($)", otherDebts: "其他負債 ($)",
    resultCard: "淨資產計算結果", unit: "淨資產 ($)", primaryValue: "主要數值", maintenanceTarget: "淨資產 ($)", actionTarget: "負債比率", estimatedTdee: "總資產", maintenance: "淨資產", fatLossTarget: "負債比",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格淨資產判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前淨資產放進常見規劃區間；這是規劃參考，不是投資建議。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把淨資產盤點轉成可執行計畫", conversionNote: "L9 會連動目前計算結果，顯示資產配置、負債償還順序與改善提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前資產規劃", dailyGap: "負債佔比", weeklyTrend: "資產/負債", motivation: "動力卡", keepMomentum: "從淨資產盤點走向穩定追蹤",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的淨資產盤點帶回家", journeyHint: "每季重新盤點一次，追蹤資產成長與負債縮減進度。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用貸款計算機檢視房貸或貸款償還方案", nextActionItem2: "用複利計算機規劃投資組合成長", nextActionItem3: "用負債收入比確認整體償債能力",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給朋友", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "淨資產 → 負債收入比 → 貸款 → 複利", bmrStep: "淨資產", deficitStep: "負債收入比", trendStep: "貸款", mealStep: "複利",
    knowledge: "知識", knowledgeTitle: "淨資產在財務規劃中的意義", definition: "定義", definitionText: "淨資產 = 總資產 − 總負債。它是衡量個人或家庭財務健康的核心指標。", formula: "公式", formulaText: "淨資產 = (現金 + 投資 + 不動產 + 其他資產) − (房貸 + 信用卡 + 其他負債)。負債比率 = 總負債 ÷ 總資產 × 100%。", limitations: "限制", limitationsText: "資產估值為估計值，實際變現可能有折價；不動產估值受市場波動影響。某些資產（如退休金）不易提前動用。", interpretation: "解讀", interpretationText: "負債比率低於 40% 通常視為健康；高於 50% 需關注；負淨資產需優先處理高息債務。", context: "脈絡", contextText: "淨資產盤點應搭配負債收入比、貸款方案與投資成長一起看。", example: "範例", exampleText: "資產：現金 $50k + 投資 $200k + 不動產 $100k = $350k。負債：房貸 $80k + 信用卡 $20k = $100k。淨資產 = $250k，負債比率 = 28.6%。",
    faq: "常見問答", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "淨資產規劃的下一步工具", premiumTitle: "專業版資產追蹤包", premiumText: "解鎖資產變化趨勢圖、品類佔比分析、負債償還模擬與個人化財務報告。",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供教育與規劃用途，不取代投資建議、理財顧問或專業財務規劃。", relatedTools: "相關工具", relatedToolsText: "貸款計算機 · 複利計算機 · 負債收入比計算機 · 退休計算機", references: "參考資料", referencesText: "美國聯準會消費者財務調查；美國勞工統計局消費支出調查；美國消費者金融保護局財務幸福感量表；AICPA 個人財務規劃框架。",
    q1: "多久應該盤點一次淨資產？", a1: "建議每季一次；重大資產變動（買房、換工作）後也應重新盤點。", q2: "退休帳戶算在資產裡嗎？", a2: "是的，但需注意提前動用的罰則與稅務影響；計算時可用目前餘額。", q3: "負債比率多少算健康？", a3: "一般建議低於 40%；房貸為主的負債可容忍較高比率，信用卡債則越低越好。", q4: "負淨資產怎麼辦？", a4: "優先清償高息債務，建立緊急預備金，同時避免新增負債。", q5: "不動產該用買價還是市價？", a5: "建議用目前估計市價，可參考實價登錄或專業估價；買價會低估資產。", q6: "這個工具能提供投資建議或資產配置建議嗎？", a6: "不能。它只是教育用估算；若有投資、稅務或重大財務決策，請諮詢專業人員。",
  },
  en: {
    badge: "Finance · Net worth · Gold tool", switchToEnglish: "Switch to English", switchToChinese: "Switch to Chinese", chineseShort: "中", englishShort: "EN",
    title: "Net Worth Calculator", subtitle: "List your assets and liabilities, calculate net worth, and check your financial health",
    intro: "This tool subtracts your total liabilities (mortgage, credit cards, other loans) from your total assets (cash, investments, property) to produce your net worth — a clear snapshot of where you stand financially and where to improve.",
    trustNoteLabel: "Note:", trustNote: "Asset estimates may differ from real market values; property and investments should be re-valued periodically.",
    quickActionCard: "Quick example", tryExample: "Try a net-worth example", examplePreview: "Net-worth preview", examplePerson: "Standard example", fillExample: "Fill the standard example", previewActivePath: "Try the high-debt example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter assets and liabilities", examplesHelper: "Start from an example to understand how net worth is calculated, then change the numbers to match your own situation.",
    metric: "Simple", imperial: "Detailed", exampleCards: "Example cards", baselineExample: "Solid · Net worth $250k", activeExample: "High-debt example", flowDemo: "Assets $350k", calculator: "Calculator",
    cashSavings: "Cash & savings ($)", investments: "Investment portfolio ($)", property: "Property value ($)", otherAssets: "Other assets ($)", mortgage: "Mortgage balance ($)", creditCard: "Credit-card debt ($)", otherDebts: "Other debts ($)",
    resultCard: "Net-worth result", unit: "Net worth ($)", primaryValue: "Headline number", maintenanceTarget: "Net worth ($)", actionTarget: "Debt ratio", estimatedTdee: "Total assets", maintenance: "Net worth", fatLossTarget: "Debt ratio",
    resultIntelligence: "Result intelligence", tdeeMatrix: "Six-band net-worth matrix", tdeeMatrixNote: "L7 fixed six-band matrix — places your net worth into common planning ranges. This is a planning reference, not investment advice.",
    emotionConversionLayer: "Emotion & conversion layer", turnIntoPlan: "Turn the net-worth snapshot into an action plan", conversionNote: "L9 reflects your current calculation — asset allocation, debt-payoff order, and improvement hints.",
    progressInsight: "Progress insight", possibleTarget: "Your current asset plan", dailyGap: "Debt share", weeklyTrend: "Assets / debt", motivation: "Motivation", keepMomentum: "Move from a snapshot to steady tracking",
    saveShareJourney: "Save / share", journeyTitle: "Take today’s net-worth snapshot home", journeyHint: "Recheck once a quarter to track asset growth and debt reduction.",
    nextActionLabel: "Next action", nextActionTitle: "Carry the result to the next tool", nextActionItem1: "Use Loan Calculator to review mortgage or loan-payoff scenarios", nextActionItem2: "Use Compound Interest Calculator to plan portfolio growth", nextActionItem3: "Use Debt-to-Income Calculator to confirm overall debt-service capacity",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with a friend", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision path", decisionTitle: "Net worth → DTI → Loan → Compounding", bmrStep: "Net worth", deficitStep: "DTI", trendStep: "Loan", mealStep: "Compounding",
    knowledge: "Knowledge", knowledgeTitle: "What net worth means in financial planning", definition: "Definition", definitionText: "Net worth = total assets − total liabilities. It is the core indicator of personal or household financial health.", formula: "Formula", formulaText: "Net worth = (cash + investments + property + other assets) − (mortgage + credit cards + other debts). Debt ratio = total liabilities ÷ total assets × 100%.", limitations: "Limitations", limitationsText: "Asset estimates are approximations; market sale prices may differ. Property values vary with the market. Some assets (e.g., retirement accounts) are not easily liquidated.", interpretation: "Interpretation", interpretationText: "A debt ratio below 40% is generally considered healthy; above 50% deserves attention; negative net worth means high-interest debt should be tackled first.", context: "Context", contextText: "Read net worth alongside debt-to-income ratio, loan plan, and investment growth — not in isolation.", example: "Example", exampleText: "Assets: cash $50k + investments $200k + property $100k = $350k. Liabilities: mortgage $80k + credit cards $20k = $100k. Net worth = $250k, debt ratio = 28.6%.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended tools", affiliateTitle: "Next-step tools for net-worth planning", premiumTitle: "Pro Net-Worth Tracker", premiumText: "Unlock asset-trend charts, category breakdown, debt-payoff simulation, and personalized financial reports.",
    trustReferences: "Trust · Related tools · References", trust: "Trust", trustText: "This tool is for educational and planning purposes only and is not a substitute for investment advice, financial advisors, or professional financial planning.", relatedTools: "Related tools", relatedToolsText: "Loan Calculator · Compound Interest Calculator · Debt-to-Income Calculator · Retirement Calculator", references: "References", referencesText: "U.S. Federal Reserve Survey of Consumer Finances; U.S. Bureau of Labor Statistics consumer expenditure surveys; CFPB financial well-being scale; AICPA personal financial planning framework.",
    q1: "How often should I recheck my net worth?", a1: "Quarterly is recommended; also recheck after major asset changes (buying a home, changing jobs).",
    q2: "Do retirement accounts count as assets?", a2: "Yes, but be aware of early-withdrawal penalties and tax impact; you can use the current balance in this calculation.",
    q3: "What debt ratio is considered healthy?", a3: "Below 40% is the general guideline; mortgage-heavy debt can tolerate higher ratios, while credit-card debt should be as low as possible.",
    q4: "What should I do with negative net worth?", a4: "Pay down high-interest debt first, build an emergency fund, and avoid taking on new debt at the same time.",
    q5: "Should property be valued at purchase price or market price?", a5: "Use the current estimated market price — reference recent transaction data or a professional appraisal. Purchase price would understate the asset.",
    q6: "Can this tool give investment or asset-allocation advice?", a6: "No. It is an educational estimate; for investment, tax, or major financial decisions, consult a professional.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

export default function NetWorthCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [cashSavings, setCashSavings] = useState("50000");
  const [investments, setInvestments] = useState("200000");
  const [property, setProperty] = useState("100000");
  const [otherAssets, setOtherAssets] = useState("0");
  const [mortgage, setMortgage] = useState("80000");
  const [creditCard, setCreditCard] = useState("20000");
  const [otherDebts, setOtherDebts] = useState("0");
  const t = ui[lang];

  const result = useMemo(() => {
    const totalAssets = Number(cashSavings) + Number(investments) + Number(property) + Number(otherAssets);
    const totalLiabilities = Number(mortgage) + Number(creditCard) + Number(otherDebts);
    const netWorth = totalAssets - totalLiabilities;
    const debtRatio = totalAssets > 0 ? (totalLiabilities / totalAssets) * 100 : 0;
    return { totalAssets, totalLiabilities, netWorth, debtRatio };
  }, [cashSavings, investments, property, otherAssets, mortgage, creditCard, otherDebts]);

  const netWorthDisplay = fmt(result.netWorth, 0);
  const debtRatioDisplay = fmt(result.debtRatio, 1);

  function fillStandard() { setUnit("metric"); setCashSavings("50000"); setInvestments("200000"); setProperty("100000"); setOtherAssets("0"); setMortgage("80000"); setCreditCard("20000"); setOtherDebts("0"); }
  function fillHighDebt() { setUnit("metric"); setCashSavings("10000"); setInvestments("30000"); setProperty("0"); setOtherAssets("0"); setMortgage("50000"); setCreditCard("40000"); setOtherDebts("10000"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#fef3c7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-amber-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-amber-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-amber-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-amber-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-amber-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-amber-100 bg-white/90 p-6 shadow-2xl shadow-amber-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-amber-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-amber-600 p-5 text-white"><div className="text-xs font-bold uppercase text-amber-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">${netWorthDisplay}</div><div className="text-sm font-bold text-amber-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">${result.totalAssets / 1000}k</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">${fmt(result.totalAssets, 0)}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.fatLossTarget}</div><div className="font-black">{debtRatioDisplay}%</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillHighDebt} className="mt-3 w-full rounded-2xl border border-red-200 bg-red-50 px-5 py-4 text-sm font-black text-red-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-amber-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-amber-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-amber-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-700">28.6%</span></div><p className="mt-2 text-sm text-slate-600">{lang === "zh" ? "資產 $350k · 負債 $100k" : "Assets $350k · Debt $100k"}</p></button><button onClick={fillHighDebt} className="w-full rounded-2xl border border-red-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-red-100 px-3 py-1 text-xs font-black text-red-700">−$70k</span></div><p className="mt-2 text-sm text-slate-600">{lang === "zh" ? "資產 $40k · 負債 $100k" : "Assets $40k · Debt $100k"}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.cashSavings}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={cashSavings} onChange={(e) => setCashSavings(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.investments}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={investments} onChange={(e) => setInvestments(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.property}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={property} onChange={(e) => setProperty(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.otherAssets}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={otherAssets} onChange={(e) => setOtherAssets(e.target.value)} /></label><label className="block text-sm font-black text-red-700">{t.mortgage}<input className="mt-2 w-full rounded-2xl border border-red-200 px-4 py-3 text-lg font-bold" value={mortgage} onChange={(e) => setMortgage(e.target.value)} /></label><label className="block text-sm font-black text-red-700">{t.creditCard}<input className="mt-2 w-full rounded-2xl border border-red-200 px-4 py-3 text-lg font-bold" value={creditCard} onChange={(e) => setCreditCard(e.target.value)} /></label><label className="block text-sm font-black text-red-700">{t.otherDebts}<input className="mt-2 w-full rounded-2xl border border-red-200 px-4 py-3 text-lg font-bold" value={otherDebts} onChange={(e) => setOtherDebts(e.target.value)} /></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-amber-400 to-emerald-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">${netWorthDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">${fmt(result.totalAssets, 0)}</div><div className="mt-1 text-xs text-slate-300">{lang === "zh" ? "資產" : "Assets"}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-emerald-950">${netWorthDisplay}</p><p className="text-sm font-bold text-emerald-700">{lang === "zh" ? "淨值" : "Net"}</p></div><div className="rounded-2xl bg-red-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-red-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-red-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-red-950">{debtRatioDisplay}%</p><p className="text-sm font-bold text-red-700">{lang === "zh" ? "比率" : "Ratio"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-500">{t.estimatedTdee}</div><div className="mt-1 text-xs font-black uppercase text-slate-700">{lang === "zh" ? "總計" : "Total"}</div><p className="mt-2 text-3xl font-black text-slate-950">${fmt(result.totalAssets, 0)}</p><p className="text-sm font-bold text-slate-700">{lang === "zh" ? "資產" : "Assets"}</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="net-worth-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-amber-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{lang === "zh" ? "淨資產" : "Net worth"}</div><div className="mt-1 text-3xl font-black">${netWorthDisplay}</div></div><div className="rounded-2xl bg-red-50 p-4"><div className="text-xs font-black uppercase text-red-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-red-950">{debtRatioDisplay}%</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{fmt(result.totalAssets / Math.max(result.totalLiabilities, 1), 1)}x</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-amber-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-amber-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-amber-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: lang === "zh" ? "淨資產" : "Net worth", note: t.bmrStep }, { label: lang === "zh" ? "負債比" : "DTI", note: t.deficitStep }, { label: lang === "zh" ? "貸款" : "Loan", note: t.trendStep }, { label: lang === "zh" ? "成長" : "Growth", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 0 ? "border-amber-300 bg-amber-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="net-worth-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-amber-100 bg-amber-50 p-5 text-center font-black text-amber-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-amber-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-amber-200 bg-gradient-to-br from-amber-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{(lang === "zh" ? ["趨勢", "分類", "模擬", "報告"] : ["Trends", "Breakdown", "Simulation", "Reports"]).map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
