// @profile B
// Profile B · Calculator-AI · AiApiCostEstimator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< $20", label: { zh: "極省", en: "Minimal" }, desc: { zh: "整月 API 費用極低，適合驗證或低流量服務，幾乎無預算壓力。", en: "Very low monthly API cost—great for validation or low traffic, almost no budget pressure." } },
  { key: "low", range: "$20–80", label: { zh: "輕量", en: "Light" }, desc: { zh: "輕量用量區間，成本可控，記得保留輸出 token 暴衝的緩衝。", en: "Light usage band; cost is manageable—keep buffer for output-token spikes." } },
  { key: "healthy", range: "$80–300", label: { zh: "成長", en: "Growing" }, desc: { zh: "多數成長期服務常見區間，宜開始監控輸出輸入比與每呼叫成本。", en: "Common growth-stage band; start monitoring output-input ratio and per-call cost." } },
  { key: "good", range: "$300–800", label: { zh: "規模化", en: "Scaling" }, desc: { zh: "已進入規模化成本，建議縮短輸出、導入快取與較便宜模型分流。", en: "Scaling cost; shorten output, introduce caching, and cheaper-model routing." } },
  { key: "strong", range: "$800–2500", label: { zh: "高負擔", en: "Heavy" }, desc: { zh: "成本偏高，務必比較輸出截斷、批次推論與供應商分層計價。", en: "Heavy cost; compare output truncation, batch inference, and tiered vendor pricing." } },
  { key: "elite", range: "> $2500", label: { zh: "企業級", en: "Enterprise" }, desc: { zh: "企業級用量，建議談量價合約、自建快取層並評估開源模型自託管。", en: "Enterprise usage; negotiate volume pricing, build a cache layer, and assess self-hosting open models." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "AI Token成本計算機", en: "AI Token Cost Calculator" }, href: "/tools/ai/ai-token-cost-calculator" },
  { label: { zh: "Prompt Token計算機", en: "Prompt Token Calculator" }, href: "/tools/ai/prompt-token-calculator" },
  { label: { zh: "AI專案成本計算機", en: "AI Project Cost Calculator" }, href: "/tools/ai/ai-project-cost-calculator" },
  { label: { zh: "AI模型比較器", en: "AI Model Comparison" }, href: "/tools/ai/ai-model-comparison" },
];

const ui = {
  zh: {
    badge: "AI · API 成本 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "AI API 成本估算器 · API Cost", subtitle: "用輸入 token、輸出 token 與輸出計價倍率估算整月 API 總成本與每呼叫成本",
    intro: "AI API Cost Estimator 依據每次呼叫的輸入 token 數、輸出 token 數與輸出計價倍率（經濟、標準或旗艦），把輸入與輸出分開計價，算出整月 API 總成本、每呼叫成本與輸出成本占比，協助您判斷預算是否合理、輸出是否太長、是否該截斷回應或改用較便宜模型，讓您在串接任何 AI API 前就把輸入輸出花費算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以輸入單價 $1/百萬與您設定的輸出倍率估算，未含各家最新調價、快取折扣與批次 API 折扣；實際費用請以各 AI 供應商官方計價頁為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立 API 範例", examplePreview: "成本預覽", examplePerson: "輸入 token", fillExample: "一鍵填入標準範例", previewActivePath: "填入旗艦輸出範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入 輸入 token、輸出 token 與輸出倍率", examplesHelper: "先用範例理解輸入輸出 token 與倍率如何決定總成本與每呼叫成本，再改成自己的用量數據。",
    metric: "公制", imperial: "占比檢視", exampleCards: "範例卡", baselineExample: "標準輸出模式", activeExample: "旗艦輸出示範", baselineExampleNote: "輸入 800 · 輸出 200 · 標準", activeExampleNote: "輸入 800 · 輸出 200 · 旗艦", carbsLabel: "每呼叫成本", carbsName: "美分", proteinLabel: "輸出成本占比", flowDemo: "輸出 token", calculator: "計算機",
    weight: "輸入 token (每次)", tdee: "輸出 token (每次)", goal: "輸出計價倍率", goalCut: "經濟 (x2)", goalMaintain: "標準 (x3)", goalBulk: "旗艦 (x4)",
    resultCard: "API 成本結果", unit: "USD (整月總成本)", primaryValue: "主要數值", maintenanceTarget: "輸出成本占比", actionTarget: "總成本", estimatedTdee: "輸出 token", maintenance: "%", fatLossTarget: "USD",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格整月總成本判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前整月總成本放進常見區間；這是規劃參考，不是會計結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把 API 結果轉成可執行的成本控制策略", conversionNote: "L9 會連動目前計算結果，顯示輸出成本占比、總成本與輸出 token 提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前用量概況", dailyGap: "總成本", weeklyTrend: "輸出占比", motivation: "動力卡", keepMomentum: "從成本分析走向最省的輸入輸出節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的 API 結果帶回團隊", journeyHint: "用 AI Token 成本計算機一起看，把單一綜合單價與輸入輸出分離計價交叉比對。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用 AI Token 成本計算機快速估綜合單價", nextActionItem2: "用 AI 模型比較器找出最划算階層", nextActionItem3: "用 AI 專案成本把 API 費納入總預算",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Input → OutputShare → Multiplier → Output", bmrStep: "輸入 token", deficitStep: "輸出占比", trendStep: "計價倍率", mealStep: "輸出 token",
    knowledge: "知識", knowledgeTitle: "輸出成本占比在 API 計價中的意義", definition: "定義", definitionText: "API 成本估算是把輸入 token 與輸出 token 分開乘上各自單價得每呼叫成本，再乘呼叫量得總成本；輸出成本占比衡量輸出花費相對於整呼叫成本的比重，是判斷是否該截斷回應的核心指標。", formula: "公式", formulaText: "輸入成本 = 輸入 token ÷ 100 萬 × 輸入單價。輸出成本 = 輸出 token ÷ 100 萬 × 輸入單價 × 倍率。每呼叫成本 = 輸入成本 + 輸出成本。總成本 = 每呼叫成本 × 假設呼叫量。", limitations: "限制", limitationsText: "本工具以固定輸入單價與倍率估算；真實費用還受各家最新調價、快取折扣、批次 API、長上下文加成與不同模型同階層單價差異影響，且輸入輸出單價差距可能很大。", interpretation: "解讀", interpretationText: "整月成本超過 $300 宜開始優化；可透過截斷回應、限制最大輸出 token、快取重複查詢、改用較便宜階層或批次推論來降低 API 花費。", context: "脈絡", contextText: "API 結果應與 AI Token 成本、模型比較與 AI 專案成本一起看，才能在效能、成本與品質之間取得平衡。", example: "範例", exampleText: "輸入 800 token、輸出 200 token、標準倍率 x3、輸入單價 $1/1M、假設 5 萬次 → 每呼叫約 0.14 美分，整月約 $70。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "API 的下一步工具", premiumTitle: "PRO API 成本分析包", premiumText: "解鎖各家即時輸入輸出單價、快取命中率模擬、批次折扣試算與多模型成本比較矩陣。", feat1: "即時報價", feat2: "快取模擬", feat3: "批次折扣", feat4: "模型矩陣",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供成本規劃與教育用途，不取代各 AI 供應商官方計價、帳單明細或合約報價。", relatedTools: "相關工具", relatedToolsText: "AI Token Cost · Prompt Token · AI Project Cost · Model Comparison", references: "參考資料", referencesText: "各 AI 供應商官方計價頁；輸入輸出 token 分離計價文件；模型上下文長度規格；批次 API 折扣公告。",
    q1: "API 總成本怎麼算的？", a1: "本工具把輸入 token 與輸出 token 分開乘上各自單價得每呼叫成本，再乘呼叫量得總成本；輸出單價多以輸入單價乘倍率估算。",
    q2: "輸出成本占比多少才合理？", a2: "輸出占比越高代表回應越長越貴；若占比偏高，建議限制最大輸出 token、截斷回應或改用較便宜階層。",
    q3: "輸入和輸出單價差很多嗎？", a3: "多數模型輸出單價是輸入的二到四倍，因此控制輸出長度通常比縮短輸入更省，可用模型比較器評估性價比。",
    q4: "API 成本太高怎麼降？", a4: "限制最大輸出 token、截斷冗長回應、快取重複查詢、改用較便宜階層、批次推論，並把長上下文壓縮成摘要。",
    q5: "要用綜合單價還是分離計價？", a5: "建議分離。本工具用輸入單價乘倍率估輸出；若要更快的單一估算，請用 AI Token 成本計算機的綜合單價。",
    q6: "這個工具能取代官方帳單嗎？", a6: "不能。它只是快速估算與教育用途；實際費用應以各 AI 供應商官方計價頁與帳單明細為準。",
  },
  en: {
    badge: "AI · API Cost · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "AI API Cost Estimator", subtitle: "Estimate monthly total API cost and per-call cost from input tokens, output tokens, and output price multiplier",
    intro: "This estimator uses input tokens per call, output tokens per call, and an output price multiplier (economy, standard, or premium) to price input and output separately, computing monthly total API cost, per-call cost, and output-cost share, helping you judge whether the budget is reasonable, whether output is too long, whether to truncate responses or switch to a cheaper model, so you compute input/output spend clearly before integrating any AI API.",
    trustNoteLabel: "Note:", trustNote: "This tool estimates from a $1/million input price and the output multiplier you set, excluding each vendor's latest price changes, cache discounts, and batch API discounts; for actual cost, follow each AI provider's official pricing page.",
    quickActionCard: "Quick Action Card", tryExample: "Create an API example instantly", examplePreview: "Cost preview", examplePerson: "Input tokens", fillExample: "One-click standard example", previewActivePath: "Fill premium output example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter input tokens, output tokens, and output multiplier", examplesHelper: "Start with an example to see how input/output tokens and the multiplier set the total and per-call cost, then replace with your own usage data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard output mode", activeExample: "Premium output demo", baselineExampleNote: "input 800 · output 200 · standard", activeExampleNote: "input 800 · output 200 · premium", carbsLabel: "Per-call cost", carbsName: "cents", proteinLabel: "Output-cost share", flowDemo: "Output tokens", calculator: "Calculator",
    weight: "Input tokens (per call)", tdee: "Output tokens (per call)", goal: "Output price multiplier", goalCut: "Economy (x2)", goalMaintain: "Standard (x3)", goalBulk: "Premium (x4)",
    resultCard: "API Cost Result", unit: "USD (monthly total cost)", primaryValue: "Primary Value", maintenanceTarget: "Output-cost share", actionTarget: "Total cost", estimatedTdee: "Output tokens", maintenance: "%", fatLossTarget: "USD",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card monthly total-cost interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current monthly total cost into common zones. This is planning guidance, not an accounting conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the API result into an actionable cost-control strategy", conversionNote: "L9 values update from the computed result: output-cost share, total cost, and output-token hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current usage snapshot", dailyGap: "Total cost", weeklyTrend: "Output share", motivation: "Motivation Card", keepMomentum: "Move from cost analysis to the cheapest input/output rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's API result to your team", journeyHint: "Review it with the AI Token Cost Calculator to cross-compare a single blended price against split input/output pricing.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Estimate a blended price with the AI Token Cost Calculator", nextActionItem2: "Find the best-value tier with AI Model Comparison", nextActionItem3: "Fold API fees into total budget with AI Project Cost",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Input → OutputShare → Multiplier → Output", bmrStep: "Input tokens", deficitStep: "Output share", trendStep: "Multiplier", mealStep: "Output tokens",
    knowledge: "Knowledge", knowledgeTitle: "What output-cost share means in API pricing", definition: "Definition", definitionText: "API cost estimation prices input and output tokens separately by their unit prices for per-call cost, then multiplies by call volume for total cost; output-cost share measures output spend relative to total per-call cost, the core indicator for whether to truncate responses.", formula: "Formula", formulaText: "Input cost = input tokens ÷ 1M × input price. Output cost = output tokens ÷ 1M × input price × multiplier. Per-call cost = input cost + output cost. Total cost = per-call cost × assumed call volume.", limitations: "Limitations", limitationsText: "This tool estimates from a fixed input price and multiplier; real cost is also affected by each vendor's latest price changes, cache discounts, batch APIs, long-context surcharges, and tier price differences between models, and input vs output prices can differ widely.", interpretation: "Interpretation", interpretationText: "Monthly cost over $300 warrants optimization; reduce API spend by truncating responses, capping max output tokens, caching repeat queries, switching to cheaper tiers, or batch inference.", context: "Context", contextText: "API results should be evaluated with AI token cost, model comparison, and AI project cost to balance performance, cost, and quality.", example: "Example", exampleText: "Input 800 tokens, output 200 tokens, standard multiplier x3, input price $1/1M, assumed 50K calls → about 0.14 cents per call, about $70 monthly.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for the API", premiumTitle: "PRO API Cost Analytics Pack", premiumText: "Unlock per-vendor live input/output prices, cache-hit-rate simulation, batch discount estimation, and a multi-model cost comparison matrix.", feat1: "Live Pricing", feat2: "Cache Simulation", feat3: "Batch Discount", feat4: "Model Matrix",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for cost planning and education. It does not replace each AI provider's official pricing, billing detail, or contract quote.", relatedTools: "Related Tools", relatedToolsText: "AI Token Cost · Prompt Token · AI Project Cost · Model Comparison", references: "References", referencesText: "Per-AI-provider official pricing pages; split input/output pricing docs; model context-length specs; batch API discount announcements.",
    q1: "How is total API cost calculated?", a1: "This tool prices input and output tokens separately by their unit prices for per-call cost, then multiplies by call volume; output price is usually estimated as input price times a multiplier.",
    q2: "What output-cost share is reasonable?", a2: "The higher the output share the longer and pricier the response; if the share is high, cap max output tokens, truncate responses, or switch to a cheaper tier.",
    q3: "Do input and output prices differ much?", a3: "Most models price output two to four times input, so controlling output length is usually cheaper than trimming input; assess value with Model Comparison.",
    q4: "How do I reduce API cost?", a4: "Cap max output tokens, truncate verbose responses, cache repeat queries, switch to a cheaper tier, batch inference, and compress long context into summaries.",
    q5: "Should I use a blended price or split pricing?", a5: "Split is recommended. This tool estimates output as input price times a multiplier; for a faster single estimate, use the blended price in the AI Token Cost Calculator.",
    q6: "Can this tool replace the official bill?", a6: "No. It is a quick estimate for education; actual cost should follow each AI provider's official pricing page and billing detail.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function outputMultiplier(mode: TierMode): number {
  if (mode === "relaxed") return 2;
  if (mode === "fast") return 4;
  return 3;
}

export default function AiApiCostEstimator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("800");
  const [tdee, setTdee] = useState("200");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const inputTokens = Number(weight);
    const outputTokens = Number(tdee);
    if (inputTokens <= 0 || outputTokens <= 0) return null;
    const calls = 50000;
    const inputCost = (inputTokens / 1_000_000) * 1;
    const outputCost = (outputTokens / 1_000_000) * 1 * outputMultiplier(goal);
    const perCallCost = inputCost + outputCost;
    const totalCost = perCallCost * calls;
    const costPerCallCents = perCallCost * 100;
    const outputShare = perCallCost > 0 ? Math.min((outputCost / perCallCost) * 100, 100) : 0;
    return { totalCost, costPerCallCents, outputShare, perCallCost };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.outputShare, 1) : "—";
  const fatDisplay = result ? fmt(result.totalCost, 2) : "—";
  const carbDisplay = result ? fmt(result.costPerCallCents, 2) : "—";
  const totalDisplay = result ? fmt(result.totalCost, 2) : "—";

  function fillStandard() { setUnit("metric"); setWeight("800"); setTdee("200"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("800"); setTdee("200"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl font-black tracking-tight text-slate-950 [font-size:clamp(1.75rem,4vw,2.5rem)] [line-height:1.2]">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">70.00</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">80.00</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">%</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">$</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">¢</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">$</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="ai-api-cost-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.totalCost, 2) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.outputShare, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Input", note: t.bmrStep }, { label: "OutputShare", note: t.deficitStep }, { label: "Multiplier", note: t.trendStep }, { label: "Output", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
