// @profile B
// Profile B · Calculator-AI · PromptTokenCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< 1k", label: { zh: "極短", en: "Tiny" }, desc: { zh: "Token 用量極低，單輪短提示，幾乎不占上下文視窗，無截斷風險。", en: "Very low token usage—single short prompt, barely uses the context window, no truncation risk." } },
  { key: "low", range: "1k–4k", label: { zh: "輕量", en: "Light" }, desc: { zh: "輕量提示區間，多數模型可輕鬆容納，記得保留回應 token 空間。", en: "Light prompt band; most models handle it easily—keep space for response tokens." } },
  { key: "healthy", range: "4k–8k", label: { zh: "中量", en: "Moderate" }, desc: { zh: "多數對話應用常見區間，宜開始監控上下文占比與多輪累積。", en: "Common chat-application band; start monitoring context share and multi-turn accumulation." } },
  { key: "good", range: "8k–16k", label: { zh: "偏長", en: "Long" }, desc: { zh: "已逼近標準視窗，建議精簡系統提示、摘要歷史或改用長上下文模型。", en: "Approaching standard window; trim system prompts, summarize history, or use a long-context model." } },
  { key: "strong", range: "16k–32k", label: { zh: "長文", en: "Heavy" }, desc: { zh: "Token 偏高，務必比較長上下文加成、檢索增強與分段處理策略。", en: "Heavy tokens; compare long-context surcharges, retrieval augmentation, and chunking strategies." } },
  { key: "elite", range: "> 32k", label: { zh: "超長", en: "Extreme" }, desc: { zh: "超長上下文，建議導入檢索增強生成、向量檢索並嚴格控管每輪累積。", en: "Extreme context; introduce retrieval-augmented generation, vector search, and strictly control per-turn accumulation." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "AI Token成本計算機", en: "AI Token Cost Calculator" }, href: "/tools/ai/ai-token-cost-calculator" },
  { label: { zh: "AI API成本估算器", en: "AI API Cost Estimator" }, href: "/tools/ai/ai-api-cost-estimator" },
  { label: { zh: "AI模型比較器", en: "AI Model Comparison" }, href: "/tools/ai/ai-model-comparison" },
  { label: { zh: "聊天機器人成本計算機", en: "Chatbot Cost Calculator" }, href: "/tools/ai/chatbot-cost-calculator" },
];

const ui = {
  zh: {
    badge: "AI · Token 估算 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Prompt Token 計算機 · Token Count", subtitle: "用提示字數、對話輪數與語言密度比估算 Prompt 總 token 與上下文占比",
    intro: "Prompt Token Calculator 依據提示字數、對話輪數與語言密度比（精簡英文、標準混合或中日韓密集），估算單輪提示 token、多輪累積總 token 與相對於八千 token 視窗的上下文占比，協助你判斷提示是否太長、是否會被截斷、該不該摘要歷史或改用長上下文模型，讓你在送出任何提示前就把 token 量算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以字數乘語言密度比近似估算，未含實際分詞器差異、特殊符號與多語言切換；精確 token 數請以各模型官方分詞器為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立 Token 範例", examplePreview: "Token 預覽", examplePerson: "提示字數", fillExample: "一鍵填入標準範例", previewActivePath: "填入密集語言範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入 提示字數、對話輪數與語言密度比", examplesHelper: "先用範例理解字數、輪數與密度比如何決定總 token 與上下文占比，再改成自己的提示數據。",
    metric: "公制", imperial: "占比檢視", exampleCards: "範例卡", baselineExample: "標準混合模式", activeExample: "密集語言示範", baselineExampleNote: "字數 500 · 輪數 3 · 標準", activeExampleNote: "字數 500 · 輪數 3 · 密集", carbsLabel: "上下文占比", carbsName: "百分比", proteinLabel: "上下文占比", flowDemo: "對話輪數", calculator: "計算機",
    weight: "提示字數 (字)", tdee: "對話輪數 (輪)", goal: "語言密度比", goalCut: "精簡英文 (x1.2)", goalMaintain: "標準混合 (x1.33)", goalBulk: "密集語言 (x1.5)",
    resultCard: "Token 估算結果", unit: "tokens (多輪累積總量)", primaryValue: "主要數值", maintenanceTarget: "上下文占比", actionTarget: "總 token", estimatedTdee: "對話輪數", maintenance: "%", fatLossTarget: "tokens",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格多輪累積總 token 判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前累積總 token 放進常見區間；這是規劃參考，不是會計結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把 Token 結果轉成可執行的提示精簡策略", conversionNote: "L9 會連動目前計算結果，顯示上下文占比、總 token 與對話輪數提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前用量概況", dailyGap: "總 token", weeklyTrend: "上下文占比", motivation: "動力卡", keepMomentum: "從 token 分析走向最精簡的提示節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的 Token 結果帶回團隊", journeyHint: "用 AI Token 成本計算機一起看，把估算 token 量直接換算成整月成本。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用 AI Token 成本計算機把 token 換成費用", nextActionItem2: "用 AI 模型比較器找出最大上下文視窗", nextActionItem3: "用聊天機器人成本計算機估多輪累積花費",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Words → ContextShare → Density → Turns", bmrStep: "提示字數", deficitStep: "上下文占比", trendStep: "語言密度", mealStep: "對話輪數",
    knowledge: "知識", knowledgeTitle: "上下文占比在 Token 估算中的意義", definition: "定義", definitionText: "Token 估算是把提示字數乘語言密度比得單輪 token，再乘對話輪數得多輪累積總 token；上下文占比衡量累積 token 相對於模型視窗的比重，是判斷是否會被截斷的核心指標。", formula: "公式", formulaText: "單輪 token = 提示字數 × 語言密度比。累積總 token = 單輪 token × 對話輪數。上下文占比 = 累積總 token ÷ 8192 × 100%。占比越高越接近視窗上限。", limitations: "限制", limitationsText: "本工具以字數乘密度比近似；真實 token 數受實際分詞器、特殊符號、程式碼、多語言切換與標點密度影響，且不同模型分詞規則差異大。", interpretation: "解讀", interpretationText: "上下文占比超過 80% 宜開始精簡；可透過縮短系統提示、摘要對話歷史、檢索增強只帶相關片段或改用長上下文模型來降低 token 量。", context: "脈絡", contextText: "Token 估算應與 AI Token 成本、模型比較與聊天機器人成本一起看，才能在長度、成本與品質之間取得平衡。", example: "範例", exampleText: "提示 500 字、標準混合密度 x1.33、對話 3 輪 → 單輪約 665 token，累積約 1995 token，占 8k 視窗約 24%。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "Token 的下一步工具", premiumTitle: "PRO Token 估算分析包", premiumText: "解鎖各模型實際分詞器、程式碼與多語言精確計數、上下文視窗對照與多輪累積成本模擬。",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供 token 規劃與教育用途，不取代各模型官方分詞器或 API 回傳的精確 token 計數。", relatedTools: "相關工具", relatedToolsText: "AI Token Cost · AI API Cost · Model Comparison · Chatbot Cost", references: "參考資料", referencesText: "各模型官方分詞器文件；上下文視窗長度規格；檢索增強生成最佳實務；多語言 token 化研究。",
    q1: "Token 數怎麼估的？", a1: "本工具把提示字數乘語言密度比得單輪 token，再乘對話輪數得累積總 token；精確值請以各模型官方分詞器計算。",
    q2: "上下文占比多少要小心？", a2: "占比越高越接近視窗上限；超過 80% 時應精簡系統提示、摘要歷史或改用長上下文模型，以免提示被截斷。",
    q3: "中文和英文 token 差很多嗎？", a3: "中日韓等密集語言每字 token 通常較高，英文較低；本工具用語言密度比近似，精確值仍以官方分詞器為準。",
    q4: "Token 太高怎麼降？", a4: "縮短系統提示、摘要對話歷史、檢索增強只帶相關片段、移除冗餘範例，並改用上下文視窗較大的模型。",
    q5: "要算回應 token 嗎？", a5: "本工具只估提示輸入 token；回應輸出 token 另計，請用 AI API 成本估算器把輸入輸出分開計價。",
    q6: "這個估算準嗎？", a6: "它是快速近似，足以做提示規劃；精確 token 數應以各模型官方分詞器或 API 回傳的 usage 計數為準。",
  },
  en: {
    badge: "AI · Token Estimate · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Prompt Token Calculator", subtitle: "Estimate total prompt tokens and context share from prompt words, conversation turns, and language density ratio",
    intro: "This calculator uses prompt words, conversation turns, and language density ratio (lean English, standard mixed, or dense CJK) to estimate single-turn prompt tokens, multi-turn cumulative total tokens, and context share against an eight-thousand-token window, helping you judge whether the prompt is too long, whether it will be truncated, whether to summarize history or use a long-context model, so you compute token volume clearly before sending any prompt.",
    trustNoteLabel: "Note:", trustNote: "This tool approximates from words times a language density ratio, excluding actual tokenizer differences, special symbols, and multilingual switching; for exact token counts, follow each model's official tokenizer.",
    quickActionCard: "Quick Action Card", tryExample: "Create a token example instantly", examplePreview: "Token preview", examplePerson: "Prompt words", fillExample: "One-click standard example", previewActivePath: "Fill dense language example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter prompt words, conversation turns, and language density ratio", examplesHelper: "Start with an example to see how words, turns, and density ratio set the total tokens and context share, then replace with your own prompt data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard mixed mode", activeExample: "Dense language demo", baselineExampleNote: "words 500 · turns 3 · standard", activeExampleNote: "words 500 · turns 3 · dense", carbsLabel: "Context share", carbsName: "percent", proteinLabel: "Context share", flowDemo: "Conversation turns", calculator: "Calculator",
    weight: "Prompt words (words)", tdee: "Conversation turns (turns)", goal: "Language density ratio", goalCut: "Lean English (x1.2)", goalMaintain: "Standard mixed (x1.33)", goalBulk: "Dense language (x1.5)",
    resultCard: "Token Estimate Result", unit: "tokens (multi-turn cumulative)", primaryValue: "Primary Value", maintenanceTarget: "Context share", actionTarget: "Total tokens", estimatedTdee: "Conversation turns", maintenance: "%", fatLossTarget: "tokens",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card multi-turn cumulative-token interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current cumulative tokens into common zones. This is planning guidance, not an accounting conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the token result into an actionable prompt-trimming strategy", conversionNote: "L9 values update from the computed result: context share, total tokens, and conversation-turns hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current usage snapshot", dailyGap: "Total tokens", weeklyTrend: "Context share", motivation: "Motivation Card", keepMomentum: "Move from token analysis to the leanest prompt rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's token result to your team", journeyHint: "Review it with the AI Token Cost Calculator to convert the estimated token volume directly into monthly cost.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Convert tokens into fees with the AI Token Cost Calculator", nextActionItem2: "Find the largest context window with AI Model Comparison", nextActionItem3: "Estimate multi-turn cumulative spend with the Chatbot Cost Calculator",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Words → ContextShare → Density → Turns", bmrStep: "Prompt words", deficitStep: "Context share", trendStep: "Language density", mealStep: "Conversation turns",
    knowledge: "Knowledge", knowledgeTitle: "What context share means in token estimation", definition: "Definition", definitionText: "Token estimation multiplies prompt words by a language density ratio for single-turn tokens, then by conversation turns for multi-turn cumulative tokens; context share measures cumulative tokens relative to the model window, the core indicator for whether content will be truncated.", formula: "Formula", formulaText: "Single-turn tokens = prompt words × language density ratio. Cumulative tokens = single-turn tokens × turns. Context share = cumulative tokens ÷ 8192 × 100%. Higher share is closer to the window limit.", limitations: "Limitations", limitationsText: "This tool approximates from words times a density ratio; real token counts are affected by the actual tokenizer, special symbols, code, multilingual switching, and punctuation density, and tokenization rules differ widely between models.", interpretation: "Interpretation", interpretationText: "Context share over 80% warrants trimming; reduce tokens by shortening system prompts, summarizing conversation history, retrieval-augmenting only relevant chunks, or using a long-context model.", context: "Context", contextText: "Token estimation should be evaluated with AI token cost, model comparison, and chatbot cost to balance length, cost, and quality.", example: "Example", exampleText: "Prompt 500 words, standard mixed density x1.33, 3 turns → single turn about 665 tokens, cumulative about 1995 tokens, about 24% of an 8k window.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for tokens", premiumTitle: "PRO Token Estimation Analytics Pack", premiumText: "Unlock per-model actual tokenizers, exact code and multilingual counting, context-window mapping, and multi-turn cumulative cost simulation.",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for token planning and education. It does not replace each model's official tokenizer or the exact token count returned by the API.", relatedTools: "Related Tools", relatedToolsText: "AI Token Cost · AI API Cost · Model Comparison · Chatbot Cost", references: "References", referencesText: "Per-model official tokenizer docs; context-window length specs; retrieval-augmented generation best practices; multilingual tokenization research.",
    q1: "How are tokens estimated?", a1: "This tool multiplies prompt words by a language density ratio for single-turn tokens, then by turns for cumulative tokens; for exact values use each model's official tokenizer.",
    q2: "What context share should I watch?", a2: "The higher the share the closer to the window limit; over 80% you should trim system prompts, summarize history, or use a long-context model to avoid truncation.",
    q3: "Do Chinese and English tokens differ much?", a3: "Dense languages like CJK usually use more tokens per character, English fewer; this tool approximates with a density ratio—exact values still follow the official tokenizer.",
    q4: "How do I reduce tokens?", a4: "Shorten system prompts, summarize conversation history, retrieval-augment only relevant chunks, remove redundant examples, and use a model with a larger context window.",
    q5: "Should I count response tokens?", a5: "This tool only estimates prompt input tokens; response output tokens are separate—use the AI API Cost Estimator to price input and output separately.",
    q6: "Is this estimate accurate?", a6: "It is a quick approximation, enough for prompt planning; exact token counts should follow each model's official tokenizer or the usage count returned by the API.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function tokensPerWord(mode: TierMode): number {
  if (mode === "relaxed") return 1.2;
  if (mode === "fast") return 1.5;
  return 1.33;
}

export default function PromptTokenCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("500");
  const [tdee, setTdee] = useState("3");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const words = Number(weight);
    const turns = Number(tdee);
    if (words <= 0 || turns <= 0) return null;
    const singleTurnTokens = words * tokensPerWord(goal);
    const totalTokens = singleTurnTokens * turns;
    const contextShare = Math.min((totalTokens / 8192) * 100, 100);
    const perTurnTokens = singleTurnTokens;
    return { totalTokens, contextShare, perTurnTokens };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.contextShare, 1) : "—";
  const fatDisplay = result ? fmt(result.totalTokens, 0) : "—";
  const carbDisplay = result ? fmt(result.contextShare, 1) : "—";
  const totalDisplay = result ? fmt(result.totalTokens, 0) : "—";

  function fillStandard() { setUnit("metric"); setWeight("500"); setTdee("3"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("500"); setTdee("3"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">1995</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">2250</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">%</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">T</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">%</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">T</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="prompt-token-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.totalTokens, 0) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.contextShare, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Words", note: t.bmrStep }, { label: "ContextShare", note: t.deficitStep }, { label: "Density", note: t.trendStep }, { label: "Turns", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="prompt-token-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{["RealTokenizer", "CodeCounting", "WindowMapping", "TurnSimulation"].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
