// @profile B
// Profile B · Calculator-Science · VoltageDropCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< 1", label: { zh: "微壓降", en: "Tiny" }, desc: { zh: "壓降極低，落在微量區間，常見於短導線或低電流情境，壓降可忽略，線路效率高。", en: "Very low drop in the tiny range, common in short wires or low-current scenarios; the drop is negligible and the circuit is efficient." } },
  { key: "low", range: "1–5", label: { zh: "低壓降", en: "Low" }, desc: { zh: "壓降偏低，適合一般低壓電路，常見於電子裝置與小型線路，壓降可控且安全。", en: "Low drop, fit for general low-voltage circuits, common in electronic devices and small wiring; the drop is controllable and safe." } },
  { key: "medium", range: "5–12", label: { zh: "中壓降", en: "Medium" }, desc: { zh: "壓降落在常見的中等區間，多數家用與小型供電線路的壓降範圍，數值直觀易估算。", en: "Drop in the common medium range, the band for most household and small power wiring, intuitive to estimate." } },
  { key: "high", range: "12–24", label: { zh: "高壓降", en: "High" }, desc: { zh: "壓降偏高，涵蓋長距離或高電流線路，壓降明顯，常需檢查導線截面與線損。", en: "High drop covering long-distance or high-current wiring; the drop is noticeable, often requiring wire cross-section and line-loss checks." } },
  { key: "veryhigh", range: "24–48", label: { zh: "超高壓降", en: "Very High" }, desc: { zh: "壓降非常高，常見於長配線或大電流系統，建議結合導線規格與安全規範一併評估。", en: "Very high drop, common in long wiring or high-current systems; evaluate with wire specification and safety standards." } },
  { key: "extreme", range: "> 48", label: { zh: "極壓降", en: "Extreme" }, desc: { zh: "壓降極高，屬於異常線損或特殊高功率範疇，務必交叉驗證電流與電阻的單位與量測精度。", en: "Extremely high drop in the abnormal line-loss or special high-power range; always verify current and resistance units and measurement precision." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "歐姆定律計算機", en: "Ohms Law Calculator" }, href: "/tools/science/ohms-law-calculator" },
  { label: { zh: "功率計算機", en: "Power Calculator" }, href: "/tools/science/power-calculator" },
  { label: { zh: "通用單位換算計算機", en: "Unit Converter Calculator" }, href: "/tools/science/unit-converter-calculator" },
  { label: { zh: "熱能計算機", en: "Heat Energy Calculator" }, href: "/tools/science/heat-energy-calculator" },
];

const ui = {
  zh: {
    badge: "Science · 電壓降 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "電壓降計算機 · Voltage Drop", subtitle: "用電流、電阻與精度等級算出電壓降、相對量級與精度分數",
    intro: "Voltage Drop Calculator 依據電流、電阻與精度等級（粗略、標準或精密），以電壓降公式 V = I × R 計算線路電壓降、相對量級與精度分數，協助你判斷壓降是否合理、落在哪個量級、是否需要檢查導線規格，讓你在配線設計與電路分析前就把電壓降算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以 V = I × R 計算，假設導線電阻恆定且溫度穩定；正式配線設計請以實際導線規格、溫度修正與標準參考資料為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立電壓降範例", examplePreview: "電壓降預覽", examplePerson: "電流 (A)", fillExample: "一鍵填入標準範例", previewActivePath: "填入精密範例",
    examplesCalculator: "範例 → 計算器", enterValues: "輸入電流、電阻與精度等級", examplesHelper: "先用範例理解電流與電阻如何決定電壓降與量級，再改成自己的線路數據。",
    metric: "公制", imperial: "佔比檢視", exampleCards: "範例卡", baselineExample: "標準壓降模式", activeExample: "精密示範", baselineExampleNote: "10A × 0.5Ω · 標準", activeExampleNote: "20A × 0.5Ω · 精密", carbsLabel: "精度餘量", carbsName: "百分比", proteinLabel: "精度分數", flowDemo: "電阻 (Ω)", calculator: "計算器",
    weight: "電流 (A)", tdee: "電阻 (Ω)", goal: "精度等級", goalCut: "粗略 (1 位)", goalMaintain: "標準 (2 位)", goalBulk: "精密 (4 位)",
    resultCard: "電壓降結果", unit: "V (電壓降)", primaryValue: "主要數值", maintenanceTarget: "精度分數", actionTarget: "電壓降", estimatedTdee: "電阻", maintenance: "分", fatLossTarget: "V",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格壓降量級判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前電壓降放進常見量級；這是配線參考，不是電路鑑定結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把電壓降結果轉成可執行的配線設計與電路分析策略", conversionNote: "L9 會連動目前計算結果，顯示精度分數、電壓降與量級提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前電壓降概況", dailyGap: "電壓降", weeklyTrend: "精度分數", motivation: "動力卡", keepMomentum: "從電壓降計算走向最精確一致的配線設計節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的電壓降結果帶回團隊", journeyHint: "用歐姆定律計算機一起看，把電壓降與電流電阻一併納入配線設計規劃。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用歐姆定律計算機推算電流電阻", nextActionItem2: "用功率計算機計算線路功率損耗", nextActionItem3: "用通用單位換算計算機轉換電氣單位",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Current → 精度分數 → 等級 → Voltage Drop", bmrStep: "Current", deficitStep: "精度分數", trendStep: "等級", mealStep: "Voltage Drop",
    knowledge: "知識", knowledgeTitle: "電壓降在配線設計中的意義", definition: "定義", definitionText: "電壓降是電流通過導線電阻時損失的電壓，以公式 V = I × R 表示；電壓降反映線路的電能損耗，是判斷配線是否合格、導線截面是否足夠與電路效率的核心物理量。", formula: "公式", formulaText: "電壓降 V = 電流 I × 電阻 R，單位為伏特 V。精度分數 = min(有效位數 / 目標位數 × 100, 100)。精度餘量 = (有效位數 − 目標位數) / 目標位數 × 100%。", limitations: "限制", limitationsText: "本工具假設導線電阻恆定且溫度穩定；真實電壓降還受導線溫度、長度、材質與接點電阻影響，長距離或高電流下偏差更明顯。", interpretation: "解讀", interpretationText: "電壓降落在低壓降級（1–5）常見於短線路，中壓降以上多需檢查導線截面，壓降過高代表線損偏大，請用精度分數確認有效位數足夠。", context: "脈絡", contextText: "電壓降結果應與電流、電阻與單位換算一起看，才能在配線準確性、電路設計與可讀性之間取得平衡。", example: "範例", exampleText: "電流 10A、電阻 0.5Ω、標準精度（2 位）→ 電壓降 5.00 V，精度餘量 0%，精度分數 100。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "電壓降的下一步工具", premiumTitle: "PRO 配線分析包", premiumText: "解鎖導線截面對照表、溫度電阻修正、線損與功率損耗計算與多段配線壓降推算。", feat1: "導線截面表", feat2: "溫阻修正", feat3: "線損計算", feat4: "多段配線",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供配線計算與教育用途，不取代專業電路鑑定、電氣量測或安規檢驗報告。", relatedTools: "相關工具", relatedToolsText: "Ohms Law · Power · Unit Converter · Heat", references: "參考資料", referencesText: "電壓降物理定義；歐姆定律標準參考；SI 電流電阻電壓單位定義；電路學基礎文獻。",
    q1: "電壓降怎麼算的？", a1: "本工具以 V = I × R，將電流與電阻相乘得到電壓降；已知任兩個量即可反推第三個量。",
    q2: "精度分數多少才合理？", a2: "精度分數達 100 代表有效位數已達所選精度等級；若低於 100，建議提高有效位數或檢查量測精度。",
    q3: "粗略還是精密等級？", a3: "日常估算用粗略（1 位），一般配線計算用標準（2 位），實驗室或精密分析用精密（4 位）。",
    q4: "怎麼判斷壓降量級？", a4: "電壓降低於 5V 屬低壓降常見於短線路，5 至 24V 為中高壓降多需檢查導線截面；比較壓降與量級提示即可判斷。",
    q5: "溫度會影響電壓降嗎？", a5: "會。溫度升高會增加導線電阻使電壓降變大，本工具假設溫度穩定；精密計算需註明溫度與導線材質。",
    q6: "這個工具能取代電路鑑定嗎？", a6: "不能。它只是快速估算與教育用途；正式配線設計應以專業電氣量測與安規標準為準。",
  },
  en: {
    badge: "Science · Voltage Drop · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Voltage Drop Calculator", subtitle: "Compute voltage drop, relative magnitude, and precision score from current, resistance, and precision level",
    intro: "This calculator uses current, resistance, and precision level (rough, standard, or precise) with the voltage-drop formula V = I x R to compute circuit voltage drop, relative magnitude, and precision score, helping you judge whether the drop is reasonable, which magnitude it falls into, and whether to check wire specification, so you compute voltage drop clearly before wiring design and circuit analysis.",
    trustNoteLabel: "Note:", trustNote: "This tool computes V = I x R, assuming constant wire resistance at stable temperature; for formal wiring design, follow actual wire specification, temperature correction, and standard reference data.",
    quickActionCard: "Quick Action Card", tryExample: "Create a voltage-drop example instantly", examplePreview: "Voltage drop preview", examplePerson: "Current (A)", fillExample: "One-click standard example", previewActivePath: "Fill precise example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter current, resistance, and precision level", examplesHelper: "Start with an example to see how current and resistance set the voltage drop and magnitude, then replace with your own circuit data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard drop mode", activeExample: "Precise demo", baselineExampleNote: "10A x 0.5ohm · standard", activeExampleNote: "20A x 0.5ohm · precise", carbsLabel: "Precision margin", carbsName: "percent", proteinLabel: "Precision score", flowDemo: "Resistance (ohm)", calculator: "Calculator",
    weight: "Current (A)", tdee: "Resistance (ohm)", goal: "Precision level", goalCut: "Rough (1 digit)", goalMaintain: "Standard (2 digits)", goalBulk: "Precise (4 digits)",
    resultCard: "Voltage Drop Result", unit: "V (voltage drop)", primaryValue: "Primary Value", maintenanceTarget: "Precision score", actionTarget: "Voltage drop", estimatedTdee: "Resistance", maintenance: "pts", fatLossTarget: "V",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card voltage-drop magnitude interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current voltage drop into common magnitudes. This is wiring guidance, not a circuit identification conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the voltage-drop result into an actionable wiring-design and circuit-analysis strategy", conversionNote: "L9 values update from the computed result: precision score, voltage drop, and magnitude hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current voltage-drop snapshot", dailyGap: "Voltage drop", weeklyTrend: "Precision score", motivation: "Motivation Card", keepMomentum: "Move from voltage-drop calculation to the most precise and consistent wiring-design rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's voltage-drop result to your team", journeyHint: "Review it with the Ohms Law Calculator to fold voltage drop, current, and resistance into wiring-design planning.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Derive current and resistance with the Ohms Law Calculator", nextActionItem2: "Compute line power loss with the Power Calculator", nextActionItem3: "Convert electrical units with the Unit Converter Calculator",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Current → Precision → Level → Voltage Drop", bmrStep: "Current", deficitStep: "Precision", trendStep: "Level", mealStep: "Voltage Drop",
    knowledge: "Knowledge", knowledgeTitle: "What voltage drop means in wiring design", definition: "Definition", definitionText: "Voltage drop is the voltage lost as current flows through wire resistance, expressed as V = I x R; voltage drop reflects the electrical energy loss in a circuit, the core physical quantity for judging whether wiring is adequate, whether wire cross-section is sufficient, and circuit efficiency.", formula: "Formula", formulaText: "Voltage drop V = current I x resistance R, in volts V. Precision score = min(significant digits / target digits x 100, 100). Precision margin = (significant digits - target digits) / target digits x 100%.", limitations: "Limitations", limitationsText: "This tool assumes constant wire resistance at stable temperature; real voltage drop is also affected by wire temperature, length, material, and contact resistance, with larger deviation over long distance or high current.", interpretation: "Interpretation", interpretationText: "Voltage drop in the low range (1 to 5) is common in short wiring, the medium range and above often needs wire cross-section checks, an excessive drop means large line loss, and use the precision score to confirm sufficient significant digits.", context: "Context", contextText: "Voltage-drop results should be evaluated with current, resistance, and unit conversion to balance wiring accuracy, circuit design, and readability.", example: "Example", exampleText: "Current 10A, resistance 0.5 ohm, standard precision (2 digits) gives voltage drop 5.00 V, precision margin 0 percent, precision score 100.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for voltage drop", premiumTitle: "PRO Wiring Analytics Pack", premiumText: "Unlock wire cross-section reference tables, temperature-resistance correction, line-loss and power-loss calculation, and multi-segment wiring voltage-drop estimation.", feat1: "Wire Gauge Tables", feat2: "Temp-Resist Fix", feat3: "Line Loss", feat4: "Multi Segment",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for wiring calculation and education. It does not replace professional circuit identification, electrical measurement, or safety inspection reports.", relatedTools: "Related Tools", relatedToolsText: "Ohms Law · Power · Unit Converter · Heat", references: "References", referencesText: "Physical definition of voltage drop; Ohms law standard references; SI current, resistance, and voltage unit definitions; circuit theory fundamentals.",
    q1: "How is voltage drop calculated?", a1: "This tool uses V = I x R, multiplying current and resistance to get voltage drop; given any two quantities, you can back-calculate the third.",
    q2: "What precision score is reasonable?", a2: "A precision score of 100 means significant digits meet the chosen precision level; if below 100, increase significant digits or check measurement precision.",
    q3: "Rough or precise level?", a3: "Use rough (1 digit) for daily estimates, standard (2 digits) for general wiring calculations, and precise (4 digits) for lab or precision analysis.",
    q4: "How do I judge voltage-drop magnitude?", a4: "Voltage drop below 5V is low common in short wiring, 5 to 24V is medium-high often needing wire cross-section checks; compare the drop with the magnitude hint to decide.",
    q5: "Does temperature affect voltage drop?", a5: "Yes. Rising temperature increases wire resistance and raises voltage drop; this tool assumes stable temperature, and precision calculation needs noted temperature and wire material.",
    q6: "Can this tool replace circuit identification?", a6: "No. It is a quick estimate for education; formal wiring design should follow professional electrical measurement and safety standards.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function targetDigits(mode: TierMode): number {
  if (mode === "relaxed") return 1;
  if (mode === "fast") return 4;
  return 2;
}

export default function VoltageDropCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("10");
  const [tdee, setTdee] = useState("0.5");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const current = Number(weight);
    const resistance = Number(tdee);
    if (!Number.isFinite(current) || !Number.isFinite(resistance) || current < 0 || resistance < 0) return null;
    const digits = targetDigits(goal);
    const voltage = current * resistance;
    const sigDigits = digits;
    const precisionScore = Math.min((sigDigits / digits) * 100, 100);
    const precisionMargin = ((sigDigits - digits) / digits) * 100;
    return { voltage, precisionScore, precisionMargin, digits };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.precisionScore, 1) : "—";
  const fatDisplay = result ? fmt(result.voltage, result.digits) : "—";
  const carbDisplay = result ? fmt(result.precisionMargin, 1) : "—";
  const totalDisplay = result ? fmt(result.voltage, result.digits) : "—";

  function fillStandard() { setUnit("metric"); setWeight("10"); setTdee("0.5"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("20"); setTdee("0.5"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">5.00</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">10.0</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">V</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">%</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">V</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="voltage-drop-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.voltage, result.digits) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.precisionScore, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Current", note: t.bmrStep }, { label: "Precision", note: t.deficitStep }, { label: "Level", note: t.trendStep }, { label: "Voltage Drop", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="voltage-drop-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
