// @profile B
// Profile B · Calculator-Science · PhCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "strongacid", range: "0–2", label: { zh: "強酸級", en: "Strong Acid" }, desc: { zh: "pH 極低，落在強酸區間，常見於鹽酸、硫酸或強酸溶液，腐蝕性高，操作須嚴格防護。", en: "Very low pH in the strong-acid range, common in hydrochloric or sulfuric acid; highly corrosive, requiring strict protection during handling." } },
  { key: "weakacid", range: "2–6", label: { zh: "弱酸級", en: "Weak Acid" }, desc: { zh: "pH 偏酸，適合醋、果汁或弱酸溶液，常見於食品與生活情境，中性 7 為常見參考基準點。", en: "Acidic pH, fit for vinegar, juice, or weak-acid solutions, common in food and daily settings; neutral 7 is the common reference point." } },
  { key: "neutral", range: "6–8", label: { zh: "中性級", en: "Neutral" }, desc: { zh: "pH 落在接近中性的常見區間，多數純水與生理溶液的範圍，數值直觀易估算。", en: "pH in the common near-neutral range, the band for most pure water and physiological solutions, intuitive to estimate." } },
  { key: "weakbase", range: "8–11", label: { zh: "弱鹼級", en: "Weak Base" }, desc: { zh: "pH 偏鹼，涵蓋小蘇打、肥皂或弱鹼溶液，常用於清潔與緩衝體系，鹼性明顯。", en: "Alkaline pH covering baking soda, soap, or weak-base solutions; common in cleaning and buffer systems, noticeably basic." } },
  { key: "strongbase", range: "11–13", label: { zh: "強鹼級", en: "Strong Base" }, desc: { zh: "pH 非常高，常見於氫氧化鈉或強鹼溶液，建議結合濃度與安全規範一併評估。", en: "Very high pH, common in sodium hydroxide or strong-base solutions; evaluate with concentration and safety standards." } },
  { key: "extreme", range: "> 13", label: { zh: "極鹼級", en: "Extreme" }, desc: { zh: "pH 極高，屬於濃強鹼或特殊化學範疇，務必交叉驗證氫離子濃度的單位與量測精度。", en: "Extremely high pH in the concentrated strong-base or special chemical range; always verify hydrogen-ion concentration units and measurement precision." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "莫耳濃度計算機", en: "Molarity Calculator" }, href: "/tools/science/molarity-calculator" },
  { label: { zh: "通用單位換算計算機", en: "Unit Converter Calculator" }, href: "/tools/science/unit-converter-calculator" },
  { label: { zh: "密度計算機", en: "Density Calculator" }, href: "/tools/science/density-calculator" },
  { label: { zh: "理想氣體定律計算機", en: "Ideal Gas Law Calculator" }, href: "/tools/science/ideal-gas-law-calculator" },
];

const ui = {
  zh: {
    badge: "Science · pH · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "pH 值計算機 · pH", subtitle: "用氫離子濃度、稀釋倍數與精度等級算出 pH、相對量級與精度分數",
    intro: "pH Calculator 依據氫離子濃度、稀釋倍數與精度等級（粗略、標準或精密），以 pH 公式 pH = -log10[H+] 計算溶液 pH、相對量級與精度分數，協助您判斷酸鹼度是否合理、落在哪個量級、是酸性還是鹼性、是否需要檢查單位，讓您在化學分析與溶液配製前就把 pH 算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以 pH = -log10[H+] 計算，假設溶液為稀水溶液且溫度恆定；正式化學分析請以實際量測與標準參考資料為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立 pH 範例", examplePreview: "pH 預覽", examplePerson: "氫離子濃度 (M)", fillExample: "一鍵填入標準範例", previewActivePath: "填入精密範例",
    examplesCalculator: "範例 → 計算器", enterValues: "輸入氫離子濃度、稀釋倍數與精度等級", examplesHelper: "先用範例理解濃度與稀釋如何決定 pH 與量級，再改成自己的溶液數據。",
    metric: "公制", imperial: "佔比檢視", exampleCards: "範例卡", baselineExample: "標準 pH 模式", activeExample: "精密示範", baselineExampleNote: "1e-7 M ÷ 1 · 標準", activeExampleNote: "1e-3 M ÷ 1 · 精密", carbsLabel: "精度餘量", carbsName: "百分比", proteinLabel: "精度分數", flowDemo: "稀釋倍數", calculator: "計算器",
    weight: "氫離子濃度 (M)", tdee: "稀釋倍數", goal: "精度等級", goalCut: "粗略 (1 位)", goalMaintain: "標準 (2 位)", goalBulk: "精密 (4 位)",
    resultCard: "pH 結果", unit: "pH (酸鹼度)", primaryValue: "主要數值", maintenanceTarget: "精度分數", actionTarget: "pH", estimatedTdee: "稀釋", maintenance: "分", fatLossTarget: "pH",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格 pH 量級判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前 pH 放進常見量級；這是化學參考，不是水質鑑定結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把 pH 結果轉成可執行的化學分析與配製策略", conversionNote: "L9 會連動目前計算結果，顯示精度分數、pH 與量級提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前 pH 概況", dailyGap: "pH", weeklyTrend: "精度分數", motivation: "動力卡", keepMomentum: "從 pH 計算走向最精確一致的化學分析節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的 pH 結果帶回團隊", journeyHint: "用莫耳濃度計算機一起看，把 pH 與濃度一併納入化學分析規劃。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用莫耳濃度計算機推算溶液濃度", nextActionItem2: "用通用單位換算計算機轉換濃度單位", nextActionItem3: "用密度計算機計算溶液密度",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Concentration → 精度分數 → 等級 → pH", bmrStep: "Concentration", deficitStep: "精度分數", trendStep: "等級", mealStep: "pH",
    knowledge: "知識", knowledgeTitle: "pH 在化學分析中的意義", definition: "定義", definitionText: "pH 是溶液中氫離子活度的負對數，以公式 pH = -log10[H+] 表示；pH 反映溶液的酸鹼度，是判斷溶液性質、緩衝能力與化學反應方向的核心物理量。", formula: "公式", formulaText: "pH = -log10[H+]，[H+] 單位為 mol/L。有效濃度 = 濃度 ÷ 稀釋倍數。精度分數 = min(有效位數 / 目標位數 × 100, 100)。精度餘量 = (有效位數 − 目標位數) / 目標位數 × 100%。", limitations: "限制", limitationsText: "本工具假設溶液為稀水溶液且溫度恆定；真實 pH 還受溫度、離子強度與活度係數影響，高濃度或非水溶液下偏差更明顯。", interpretation: "解讀", interpretationText: "pH 小於 7 為酸性，大於 7 為鹼性，等於 7 為中性；pH 落在中性級（6–8）常見於純水與生理溶液，強酸或強鹼級多需嚴格防護，請用精度分數確認有效位數足夠。", context: "脈絡", contextText: "pH 結果應與濃度、稀釋與單位換算一起看，才能在分析準確性、化學配製與可讀性之間取得平衡。", example: "範例", exampleText: "氫離子濃度 1e-7 M、稀釋倍數 1、標準精度（2 位）→ pH 7.00，精度餘量 0%，精度分數 100。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "pH 的下一步工具", premiumTitle: "PRO pH 分析包", premiumText: "解鎖溫度修正、緩衝體系計算、酸鹼滴定曲線與離子強度活度係數修正。", feat1: "溫度修正", feat2: "緩衝體系", feat3: "滴定曲線", feat4: "離子強度",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供化學計算與教育用途，不取代專業水質鑑定、pH 量測或實驗室分析報告。", relatedTools: "相關工具", relatedToolsText: "Molarity · Unit Converter · Density · Ideal Gas", references: "參考資料", referencesText: "pH 物理定義；酸鹼化學標準參考；SI 濃度單位定義；分析化學基礎文獻。",
    q1: "pH 怎麼算的？", a1: "本工具以 pH = -log10[H+]，將氫離子濃度取以 10 為底的負對數得到 pH；已知濃度即可算出 pH，反之亦然。",
    q2: "精度分數多少才合理？", a2: "精度分數達 100 代表有效位數已達所選精度等級；若低於 100，建議提高有效位數或檢查量測精度。",
    q3: "粗略還是精密等級？", a3: "日常估算用粗略（1 位），一般分析計算用標準（2 位），實驗室或精密分析用精密（4 位）。",
    q4: "怎麼判斷酸鹼性？", a4: "pH 小於 7 為酸性，大於 7 為鹼性，等於 7 為中性；比較 pH 與中性 7 即可判斷酸鹼方向。",
    q5: "溫度會影響 pH 嗎？", a5: "會。溫度升高會改變水的解離常數使中性 pH 偏移，本工具假設溫度恆定；精密量測需註明溫度與離子強度條件。",
    q6: "這個工具能取代水質鑑定嗎？", a6: "不能。它只是快速估算與教育用途；正式水質鑑定應以專業 pH 計與標準參考資料為準。",
  },
  en: {
    badge: "Science · pH · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "pH Calculator", subtitle: "Compute pH, relative magnitude, and precision score from hydrogen-ion concentration, dilution factor, and precision level",
    intro: "This calculator uses hydrogen-ion concentration, dilution factor, and precision level (rough, standard, or precise) with the pH formula pH = -log10[H+] to compute solution pH, relative magnitude, and precision score, helping you judge whether the acidity is reasonable, which magnitude it falls into, whether it is acidic or basic, and whether to check units, so you compute pH clearly before chemical analysis and solution preparation.",
    trustNoteLabel: "Note:", trustNote: "This tool computes pH = -log10[H+], assuming a dilute aqueous solution at constant temperature; for formal chemical analysis, follow actual measurement and standard reference data.",
    quickActionCard: "Quick Action Card", tryExample: "Create a pH example instantly", examplePreview: "pH preview", examplePerson: "H+ concentration (M)", fillExample: "One-click standard example", previewActivePath: "Fill precise example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter hydrogen-ion concentration, dilution factor, and precision level", examplesHelper: "Start with an example to see how concentration and dilution set the pH and magnitude, then replace with your own solution data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard pH mode", activeExample: "Precise demo", baselineExampleNote: "1e-7 M / 1 · standard", activeExampleNote: "1e-3 M / 1 · precise", carbsLabel: "Precision margin", carbsName: "percent", proteinLabel: "Precision score", flowDemo: "Dilution factor", calculator: "Calculator",
    weight: "H+ concentration (M)", tdee: "Dilution factor", goal: "Precision level", goalCut: "Rough (1 digit)", goalMaintain: "Standard (2 digits)", goalBulk: "Precise (4 digits)",
    resultCard: "pH Result", unit: "pH (acidity)", primaryValue: "Primary Value", maintenanceTarget: "Precision score", actionTarget: "pH", estimatedTdee: "Dilution", maintenance: "pts", fatLossTarget: "pH",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card pH magnitude interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current pH into common magnitudes. This is chemistry guidance, not a water-quality identification conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the pH result into an actionable chemical-analysis and preparation strategy", conversionNote: "L9 values update from the computed result: precision score, pH, and magnitude hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current pH snapshot", dailyGap: "pH", weeklyTrend: "Precision score", motivation: "Motivation Card", keepMomentum: "Move from pH calculation to the most precise and consistent chemical-analysis rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's pH result to your team", journeyHint: "Review it with the Molarity Calculator to fold pH and concentration into chemical-analysis planning.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Derive solution concentration with the Molarity Calculator", nextActionItem2: "Convert concentration units with the Unit Converter Calculator", nextActionItem3: "Compute solution density with the Density Calculator",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Concentration → Precision → Level → pH", bmrStep: "Concentration", deficitStep: "Precision", trendStep: "Level", mealStep: "pH",
    knowledge: "Knowledge", knowledgeTitle: "What pH means in chemical analysis", definition: "Definition", definitionText: "pH is the negative logarithm of the hydrogen-ion activity in a solution, expressed as pH = -log10[H+]; pH reflects the acidity of a solution, the core physical quantity for judging solution properties, buffering capacity, and reaction direction.", formula: "Formula", formulaText: "pH = -log10[H+], with [H+] in mol/L. Effective concentration = concentration / dilution factor. Precision score = min(significant digits / target digits x 100, 100). Precision margin = (significant digits - target digits) / target digits x 100%.", limitations: "Limitations", limitationsText: "This tool assumes a dilute aqueous solution at constant temperature; real pH is also affected by temperature, ionic strength, and activity coefficients, with larger deviation at high concentration or in non-aqueous solutions.", interpretation: "Interpretation", interpretationText: "pH below 7 is acidic, above 7 is basic, and equal to 7 is neutral; pH in the neutral range (6 to 8) is common in pure water and physiological solutions, the strong-acid or strong-base range needs strict protection, and use the precision score to confirm sufficient significant digits.", context: "Context", contextText: "pH results should be evaluated with concentration, dilution, and unit conversion to balance analysis accuracy, chemical preparation, and readability.", example: "Example", exampleText: "Hydrogen-ion concentration 1e-7 M, dilution factor 1, standard precision (2 digits) gives pH 7.00, precision margin 0 percent, precision score 100.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for pH", premiumTitle: "PRO pH Analytics Pack", premiumText: "Unlock temperature correction, buffer system calculation, acid-base titration curves, and ionic-strength activity-coefficient correction.", feat1: "Temp Correction", feat2: "Buffer System", feat3: "Titration Curve", feat4: "Ionic Strength",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for chemistry calculation and education. It does not replace professional water-quality identification, pH measurement, or laboratory analysis reports.", relatedTools: "Related Tools", relatedToolsText: "Molarity · Unit Converter · Density · Ideal Gas", references: "References", referencesText: "Physical definition of pH; acid-base chemistry standard references; SI concentration unit definitions; analytical chemistry fundamentals.",
    q1: "How is pH calculated?", a1: "This tool uses pH = -log10[H+], taking the base-10 negative logarithm of the hydrogen-ion concentration to get pH; given the concentration you can compute pH and vice versa.",
    q2: "What precision score is reasonable?", a2: "A precision score of 100 means significant digits meet the chosen precision level; if below 100, increase significant digits or check measurement precision.",
    q3: "Rough or precise level?", a3: "Use rough (1 digit) for daily estimates, standard (2 digits) for general analysis, and precise (4 digits) for lab or precision analysis.",
    q4: "How do I judge acidity or basicity?", a4: "pH below 7 is acidic, above 7 is basic, and equal to 7 is neutral; compare pH with neutral 7 to decide the acid-base direction.",
    q5: "Does temperature affect pH?", a5: "Yes. Rising temperature changes the dissociation constant of water and shifts neutral pH; this tool assumes constant temperature, and precision measurement needs noted temperature and ionic-strength conditions.",
    q6: "Can this tool replace water-quality identification?", a6: "No. It is a quick estimate for education; formal water-quality identification should follow professional pH meters and standard reference data.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function targetDigits(mode: TierMode): number {
  if (mode === "relaxed") return 1;
  if (mode === "fast") return 4;
  return 2;
}

export default function PhCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("0.0000001");
  const [tdee, setTdee] = useState("1");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const concentration = Number(weight);
    const dilution = Number(tdee);
    if (!Number.isFinite(concentration) || !Number.isFinite(dilution) || concentration <= 0 || dilution <= 0) return null;
    const digits = targetDigits(goal);
    const effective = concentration / dilution;
    const ph = -Math.log10(effective);
    const sigDigits = digits;
    const precisionScore = Math.min((sigDigits / digits) * 100, 100);
    const precisionMargin = ((sigDigits - digits) / digits) * 100;
    return { ph, precisionScore, precisionMargin, digits };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.precisionScore, 1) : "—";
  const fatDisplay = result ? fmt(result.ph, result.digits) : "—";
  const carbDisplay = result ? fmt(result.precisionMargin, 1) : "—";
  const totalDisplay = result ? fmt(result.ph, result.digits) : "—";

  function fillStandard() { setUnit("metric"); setWeight("0.0000001"); setTdee("1"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("0.001"); setTdee("1"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">7.00</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">3.00</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">pH</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">%</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">pH</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="ph-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.ph, result.digits) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.precisionScore, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Concentration", note: t.bmrStep }, { label: "Precision", note: t.deficitStep }, { label: "Level", note: t.trendStep }, { label: "pH", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="ph-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
