// ============================================================
// toolsConfig.ts - 工具矩陣設定大腦
// 每個工具必須含 category（對應 categoriesConfig key）
// 與完整三層路徑 /tools/[category]/[tool-name]
// ============================================================

export interface SeoArticle {
  id: string;
  title: string;
  description: string;
}

export interface Tool {
  id: string;
  name: string;
  nameZh?: string;
  category: string; // 對應 categoriesConfig 的 key
  path: string; // 三層路徑：/tools/[category]/[tool-name]
  description: string;
  icon: string;
  isPremium: boolean;
  showAds: boolean;
  rateLimit: number; // 每分鐘最大請求數
  seoArticles: SeoArticle[];
  tags?: string[];
  isNew?: boolean;
  isFeatured?: boolean;
  canonicalId?: string;
  galaxy?: string;
  universe?: string;
  websiteKey?: string;
}

// ============================================================
// 工具清單 - 三層路徑結構
// ============================================================
export const tools: Tool[] = [
  // ── 財經投資 (finance) ────────────────────────────────────
  {
    id: "roi-calculator",
    name: "定期定額 ROI 計算機",
    category: "finance",
    path: "/tools/finance/roi-calculator",
    icon: "TrendingUp",
    description:
      "輸入每月投入金額、年化報酬率與投資年限，即時生成複利成長曲線圖，規劃你的財富自由之路。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isFeatured: true,
    seoArticles: [
      {
        id: "roi-calculator-guide",
        title: "定期定額投資完全指南：如何用 ROI 計算機規劃財富自由",
        description:
          "深入解析定期定額原理，教你善用 ROI 計算機精準預測財富成長軌跡。",
      },
      {
        id: "roi-dca-vs-lumpsum",
        title: "定期定額 vs 單筆投資：哪種方式報酬率更高？",
        description:
          "深度比較定期定額與單筆投資的優缺點，用數據找出最適合你的投資策略。",
      },
      {
        id: "roi-stock-best-price",
        title: "存股族必看：用 ROI 計算機找出最佳買點",
        description:
          "結合殖利率、本益比與技術分析，系統性找出存股最佳進場時機。",
      },
      {
        id: "roi-vs-lump-sum",
        title: "定期定額 vs 單筆投資：哪種策略在台股更賺錢？",
        description:
          "用真實台股數據比較兩種投資策略的風險與報酬，搭配 ROI 計算機找出最適合你的方式。",
      },
      {
        id: "roi-best-buy-point",
        title: "存股族必看：用 ROI 計算機找出最佳買點，讓報酬率翻倍",
        description:
          "殖利率評估法、本益比法與技術分析三管齊下，系統性找出存股最佳買點。",
      },
    ],
  },
  {
    id: "car-depreciation",
    name: "中古車折舊估算器",
    category: "finance",
    path: "/tools/finance/car-depreciation",
    icon: "Car",
    description:
      "輸入新車價、車齡與品牌保值率，計算未來 5 年殘值階梯表，讓你買賣中古車不再吃虧。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isFeatured: true,
    seoArticles: [
      {
        id: "car-depreciation-5-tips",
        title: "買中古車前必做的 5 個殘值評估，避免買到「越開越虧」的車",
        description:
          "從品牌保值率到事故記錄，5 個步驟完整評估中古車殘值，讓你買車不吃虧。",
      },
      {
        id: "car-japan-vs-germany",
        title: "日系 vs 德系中古車折舊率大比較",
        description:
          "Toyota、Honda 對決 BMW、Benz，用數據告訴你哪個品牌 5 年後最保值。",
      },
      {
        id: "car-sell-best-timing",
        title: "中古車怎麼賣最划算？掌握殘值最高點",
        description:
          "從折舊曲線分析最佳賣車時機，讓你的愛車賣出最理想的價格。",
      },
      {
        id: "japan-vs-german-car-depreciation",
        title: "日系 vs 德系中古車折舊率大比較：買哪個品牌最保值？",
        description:
          "用真實數據比較 Toyota、Honda、BMW、Benz 的 5 年保值率，幫你做出最聰明的購車決策。",
      },
      {
        id: "used-car-sell-best-time",
        title: "中古車怎麼賣最划算？掌握殘值最高點的完整攻略",
        description:
          "從折舊曲線到賣車管道，教你找出最佳賣車時機，讓愛車賣出最好的價格。",
      },
    ],
  },
  // ── 財經投資（新增工具）────────────────────────────────────
  {
    id: "mortgage-calculator",
    name: "房貸試算工具",
    category: "finance",
    path: "/tools/finance/mortgage-calculator",
    icon: "Home",
    description:
      "輸入貸款金額、利率與年限，即時計算每月還款金額、總利息與還款走勢圖，讓你購屋前心裡有底。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "retirement-calculator",
    name: "退休金 4% 法則計算機",
    category: "finance",
    path: "/tools/finance/retirement-calculator",
    icon: "PiggyBank",
    description:
      "依 4% 提領法則反推退休所需資產規模，計算距離財務自由還需幾年，規劃你的 FIRE 之路。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "dca-calculator",
    name: "股票平均成本計算機",
    category: "finance",
    path: "/tools/finance/dca-calculator",
    icon: "BarChart2",
    description:
      "多次買入不同價格的股票，自動計算平均成本、損益比例與攤平後的損益平衡點，告別手算錯誤。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "income-tax-calculator",
    name: "薪資所得稅試算器",
    category: "finance",
    path: "/tools/finance/income-tax-calculator",
    icon: "Receipt",
    description:
      "依台灣 2024 年度稅率，輸入年薪、婚姻狀況與扶養人數，快速試算應繳所得稅與實際稅率。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  // ── 財經投資（Phase 11 新增）────────────────────────────────
  {
    id: "rent-vs-buy",
    name: "買房 vs 租房財務效益對比",
    category: "finance",
    path: "/tools/finance/rent-vs-buy",
    icon: "Home",
    description: "比較買房與租房的長期財務效益，含機會成本、房價漲幅與租金走勢分析。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "inflation-calculator",
    name: "通膨調整購買力計算器",
    category: "finance",
    path: "/tools/finance/inflation-calculator",
    icon: "TrendingDown",
    description: "設定通膨率，計算未來購買力縮水幅度，讓你了解通膨對財富的侵蝕效果。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "credit-card-payoff",
    name: "信用卡債務還款計劃",
    category: "finance",
    path: "/tools/finance/credit-card-payoff",
    icon: "CreditCard",
    description: "比較最低還款與加速還款方案，計算利息節省金額與還清日期。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "irr-npv-calculator",
    name: "IRR / NPV 投資評估計算器",
    category: "finance",
    path: "/tools/finance/irr-npv-calculator",
    icon: "Calculator",
    description: "輸入現金流與折現率，計算 IRR 與 NPV，評估投資案是否值得進行。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "education-fund",
    name: "子女教育基金計算器",
    category: "education",
    path: "/tools/education/education-fund",
    icon: "GraduationCap",
    description: "設定教育目標金額與年化報酬率，計算每月需存多少才能準時達標。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "dividend-reinvestment",
    name: "股票股息再投資模擬器（DRIP）",
    category: "finance",
    path: "/tools/finance/dividend-reinvestment",
    icon: "RefreshCw",
    description: "模擬股息再投資複利效果，展示長期持有與 DRIP 策略的資產成長曲線。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "crypto-dca-backtest",
    name: "加密貨幣 DCA 歷史回測工具",
    category: "finance",
    path: "/tools/finance/crypto-dca-backtest",
    icon: "Bitcoin",
    description: "選擇幣種與定投週期，回測歷史 DCA 策略報酬，了解定期定額在加密市場的效果。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  // ── 健康生活 (health) ─────────────────────────────────────
  {
    id: "bmi-calculator",
    name: "BMI 計算機",
    category: "health",
    path: "/tools/health/bmi-calculator",
    icon: "Scale",
    description:
      "輸入身高體重，依台灣衛福部標準分類 BMI，提供理想體重範圍與個人化健康建議。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  // ── 健康生活（Phase 11 新增）────────────────────────────────
  // ── 職場效率（productivity）─────────────────────────────────────
  {
    id: "social-media-checker",
    name: "社群媒體字數與 Emoji 檢查器",
    category: "productivity",
    path: "/tools/productivity/social-media-checker",
    icon: "MessageSquare",
    description: "即時檢查 X/Threads/IG/Facebook 字數限制，統計 Emoji、Hashtag 與 Mention 數量。",
    isPremium: false,
    showAds: true,
    rateLimit: 60,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "roas-cpc-calculator",
    name: "ROAS / CPC 廣告計算機",
    category: "ecommerce",
    path: "/tools/ecommerce/roas-cpc-calculator",
    icon: "BarChart2",
    description: "計算廣告投資報酬率（ROAS）、每次點擊成本（CPC）與完整廣告活動效益分析。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "freelancer-rate-calculator",
    name: "Freelancer 報價時薪轉換器",
    category: "productivity",
    path: "/tools/productivity/freelancer-rate-calculator",
    icon: "Briefcase",
    description: "輸入期望月收入，反推最低時薪與建議報價，含稅務、費用與緩衝係數計算。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "invoice-generator",
    name: "線上發票 PDF 自動生成器",
    category: "productivity",
    path: "/tools/productivity/invoice-generator",
    icon: "FileText",
    description: "填寫發票資訊與服務項目，前端直接列印或存為 PDF，不需安裝任何軟體。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "utm-builder",
    name: "UTM 標籤自動生成器",
    category: "ecommerce",
    path: "/tools/ecommerce/utm-builder",
    icon: "Link2",
    description: "快速生成 UTM 追蹤連結，支援批次生成、複製與歷史記錄，提升廣告追蹤效率。",
    isPremium: false,
    showAds: true,
    rateLimit: 60,
    isNew: true,
    seoArticles: [],
  },
  // ── 財經投資（Phase 12 新增）────────────────────────────────
  {
    id: "insurance-calculator",
    name: "保險／年金給付計算器",
    category: "finance",
    path: "/tools/finance/insurance-calculator",
    icon: "Shield",
    description: "輸入保費、給付條件與年金現值，試算保險效益與年金每月給付金額。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "utility-cost-calculator",
    name: "電費／生活成本計算器（台灣版）",
    category: "finance",
    path: "/tools/finance/utility-cost-calculator",
    icon: "Zap",
    description: "依台電階梯電費計算月電費，加上水費、瓦斯費，統計每月生活基本開銷。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "asset-depreciation",
    name: "固定資產折舊計算器",
    category: "finance",
    path: "/tools/finance/asset-depreciation",
    icon: "TrendingDown",
    description: "支援直線法與定率遞減法，生成完整折舊時程表，符合台灣會計準則。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "currency-converter",
    name: "貨幣匯率轉換器",
    category: "travel",
    path: "/tools/travel/currency-converter",
    icon: "DollarSign",
    description: "主要貨幣即時換算，支援 TWD、USD、EUR、JPY、GBP、CNY 等 20 種貨幣。",
    isPremium: false,
    showAds: true,
    rateLimit: 60,
    isNew: true,
    seoArticles: [],
  },
  // ── 職場效率（Phase 12 新增）────────────────────────────────
  {
    id: "url-shortener",
    name: "縮網址與點擊分析後台",
    category: "productivity",
    path: "/tools/productivity/url-shortener",
    icon: "Link",
    description: "生成短網址並追蹤點擊次數，提供點擊統計後台，提升連結管理效率。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    seoArticles: [],
  },
  {
    id: "markdown-to-html",
    name: "Markdown 轉 HTML 排版工具",
    category: "design",
    path: "/tools/design/markdown-to-html",
    icon: "FileCode",
    description: "即時預覽 Markdown 渲染效果，一鍵複製 HTML 輸出，支援常用語法提示。",
    isPremium: false,
    showAds: true,
    rateLimit: 60,
    isNew: true,
    seoArticles: [],
  },
  // ── 開發工具（dev）─────────────────────────────────────────
  {
    id: "tdee-calculator",
    name: "TDEE 健身熱量計算機",
    category: "health",
    path: "/tools/health/tdee-calculator",
    icon: "Dumbbell",
    description:
      "根據性別、年齡、身高、體重與活動量，計算每日總消耗熱量（TDEE）與三大營養素最佳分配。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isFeatured: true,
    seoArticles: [
      {
        id: "tdee-fat-loss-guide",
        title: "減脂期間怎麼吃？TDEE 熱量缺口完整攻略",
        description:
          "用 TDEE 計算熱量缺口，科學設定三大營養素比例，讓你健康有效地減去多餘體脂。",
      },
      {
        id: "tdee-muscle-gain-guide",
        title: "增肌飲食計畫：用 TDEE 計算每日蛋白質需求，打造理想體態",
        description:
          "增肌期熱量盈餘設定、蛋白質需求計算與三大營養素分配，科學化增肌飲食完整指南。",
      },
      {
        id: "tdee-eating-out-guide",
        title: "外食族如何控制熱量？TDEE 實戰應用指南",
        description:
          "台灣常見外食熱量表、點餐策略與聚餐應對技巧，讓外食族也能輕鬆達成健康目標。",
      },
    ],
  },
  // ── Sninja 新增：缺少工具設定（Finance / Health / Productivity / Developer）──
  {
    id: "credit-score-calculator",
    name: "信用評分計算器",
    category: "finance",
    path: "/tools/finance/credit-score-calculator",
    icon: "CreditCard",
    description: "模擬計算個人信用評分，了解並改善你的信用狀況",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "compound-interest-advanced",
    name: "進階複利計算器",
    category: "finance",
    path: "/tools/finance/compound-interest-advanced",
    icon: "TrendingUp",
    description: "支援多種複利頻率、定期投入與通膨調整的進階複利計算",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "calorie-calculator",
    name: "卡路里計算器",
    category: "health",
    path: "/tools/health/calorie-calculator",
    icon: "Flame",
    description: "根據年齡、性別、身高、體重計算每日卡路里需求",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "water-intake-calculator",
    name: "每日飲水量計算器",
    category: "health",
    path: "/tools/health/water-intake-calculator",
    icon: "Droplets",
    description: "根據體重與活動量計算每日建議飲水量",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "project-roi-calculator",
    name: "專案投資報酬率",
    category: "productivity",
    path: "/tools/productivity/project-roi-calculator",
    icon: "Target",
    description: "計算專案投資報酬率，評估專案是否值得執行",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "productivity-score",
    name: "生產力評分",
    category: "productivity",
    path: "/tools/productivity/productivity-score",
    icon: "Gauge",
    description: "根據任務完成率與專注時間量化個人生產力表現",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "regex-tester",
    name: "正規表達式測試器",
    category: "dev",
    path: "/tools/dev/regex-tester",
    icon: "Code",
    description: "即時測試與驗證正規表達式，支援視覺化比對結果",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "url-encoder",
    name: "URL 編碼解碼器",
    category: "dev",
    path: "/tools/dev/url-encoder",
    icon: "Link",
    description: "將特殊字元編碼為 URL 安全格式或反向解碼",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "timestamp-converter",
    name: "時間戳轉換器",
    category: "dev",
    path: "/tools/dev/timestamp-converter",
    icon: "Clock",
    description: "在 Unix timestamp、毫秒時間戳與日期時間之間快速轉換",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "css-unit-converter",
    name: "CSS 單位轉換器",
    category: "dev",
    path: "/tools/dev/css-unit-converter",
    icon: "Ruler",
    description: "快速換算 px、rem、em、vw 等常用 CSS 單位",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  // ── Sninja 修正：已存在 TSX 元件之工具登記（Developer / Health）──
  {
    id: "base64-encoder-decoder",
    name: "Base64 Encoder/Decoder",
    nameZh: "Base64編碼解碼器",
    category: "dev",
    path: "/tools/dev/base64-encoder-decoder",
    icon: "Binary",
    description: "Encode and decode Base64 strings instantly",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["Base64", "Encoder", "Decoder", "DEV"],
    isNew: true,
    canonicalId: "DEV-000035",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    nameZh: "JSON格式化工具",
    category: "dev",
    path: "/tools/dev/json-formatter",
    icon: "Braces",
    description: "Format and validate JSON with syntax highlighting",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["JSON", "Formatter", "Validator", "DEV"],
    isNew: true,
    canonicalId: "DEV-000132",
  },
  {
    id: "cron-generator",
    name: "Cron排程產生器",
    category: "dev",
    path: "/tools/dev/cron-generator",
    icon: "Clock",
    description: "視覺化產生Cron排程表達式，支援語法說明",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "css-grid-flexbox-generator",
    name: "CSS Grid/Flexbox產生器",
    category: "dev",
    path: "/tools/dev/css-grid-flexbox-generator",
    icon: "Layout",
    description: "視覺化產生CSS Grid與Flexbox排版程式碼",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "image-converter",
    name: "圖片格式轉換器",
    category: "dev",
    path: "/tools/dev/image-converter",
    icon: "Image",
    description: "線上圖片格式轉換，支援PNG、JPG、WebP等格式",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    nameZh: "JWT解碼器",
    category: "dev",
    path: "/tools/dev/jwt-decoder",
    icon: "KeyRound",
    description: "輸入JWT token後解碼顯示header與payload，並檢查簽名段。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "ENC", "JWT Decoder"],
    isNew: true,
    canonicalId: "DEV-000145",
    galaxy: "ENC",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "responsive-breakpoint-tester",
    name: "響應式斷點測試器",
    category: "dev",
    path: "/tools/dev/responsive-breakpoint-tester",
    icon: "Monitor",
    description: "測試網站在不同螢幕尺寸下的響應式表現",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "timezone-converter",
    name: "時區轉換器",
    category: "dev",
    path: "/tools/dev/timezone-converter",
    icon: "Globe",
    description: "全球時區時間轉換，支援夏令時間自動調整",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "uuid-password-generator",
    name: "UUID/密碼產生器",
    category: "dev",
    path: "/tools/dev/uuid-password-generator",
    icon: "Shield",
    description: "產生安全的UUID與隨機密碼，支援自訂規則",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "astrology-calculator",
    name: "星座運勢計算器",
    category: "health",
    path: "/tools/health/astrology-calculator",
    icon: "Star",
    description: "根據生日計算星座與運勢分析",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "calorie-deficit-calculator",
    name: "卡路里赤字計算器",
    category: "health",
    path: "/tools/health/calorie-deficit-calculator",
    icon: "Minus",
    description: "計算減重所需的每日卡路里赤字目標",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "macros-calculator",
    name: "巨量營養素計算器",
    category: "health",
    path: "/tools/health/macros-calculator",
    icon: "PieChart",
    description: "計算每日蛋白質、碳水化合物、脂肪的建議攝取量",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "ovulation-tracker",
    name: "排卵期追蹤器",
    category: "health",
    path: "/tools/health/ovulation-tracker",
    icon: "Calendar",
    description: "根據月經週期計算排卵期與最佳受孕時間",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "sleep-cycle-calculator",
    name: "睡眠週期計算器",
    category: "health",
    path: "/tools/health/sleep-cycle-calculator",
    icon: "Moon",
    description: "根據睡眠週期計算最佳起床時間，減少起床疲勞感",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },

  // ── Sninja 補回：原本應存在於正確分類的工具 ──
  {
    id: "responsive-breakpoint-tester",
    name: "響應式斷點測試器",
    category: "design",
    path: "/tools/design/responsive-breakpoint-tester",
    icon: "Monitor",
    description: "測試網站在不同螢幕尺寸下的響應式表現",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "css-grid-flexbox-generator",
    name: "CSS Grid/Flexbox產生器",
    category: "design",
    path: "/tools/design/css-grid-flexbox-generator",
    icon: "Layout",
    description: "視覺化產生CSS Grid與Flexbox排版程式碼",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "image-converter",
    name: "圖片格式轉換器",
    category: "design",
    path: "/tools/design/image-converter",
    icon: "Image",
    description: "線上圖片格式轉換，支援PNG、JPG、WebP等格式",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "timezone-converter",
    name: "時區轉換器",
    category: "travel",
    path: "/tools/travel/timezone-converter",
    icon: "Globe",
    description: "全球時區時間轉換，支援夏令時間自動調整",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "astrology-calculator",
    name: "星座運勢計算器",
    category: "education",
    path: "/tools/education/astrology-calculator",
    icon: "Star",
    description: "根據生日計算星座與運勢分析",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "pomodoro-tracker",
    name: "番茄鐘追蹤器",
    category: "productivity",
    path: "/tools/productivity/pomodoro-tracker",
    icon: "Timer",
    description: "番茄工作法計時器，提升專注力與工作效率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  // ── Sninja Batch A Finance + Batch F Developer ──
  {
    id: "emergency-fund-calculator",
    name: "緊急預備金計算器",
    category: "finance",
    path: "/tools/finance/emergency-fund-calculator",
    icon: "Shield",
    description: "估算緊急預備金目標、缺口與完成率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "net-worth-calculator",
    name: "淨資產計算器",
    category: "finance",
    path: "/tools/finance/net-worth-calculator",
    icon: "Wallet",
    description: "統計資產、負債與個人淨資產",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "budget-planner",
    name: "預算規劃器",
    category: "finance",
    path: "/tools/finance/budget-planner",
    icon: "PieChart",
    description: "規劃每月收入、支出與儲蓄率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "savings-goal-calculator",
    name: "儲蓄目標計算器",
    category: "finance",
    path: "/tools/finance/savings-goal-calculator",
    icon: "Target",
    description: "計算達成儲蓄目標所需每月存款",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "debt-payoff-calculator",
    name: "債務還清計算器",
    category: "finance",
    path: "/tools/finance/debt-payoff-calculator",
    icon: "CreditCard",
    description: "估算債務還清時間與總利息",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "stock-profit-loss-calculator",
    name: "股票損益計算器",
    category: "finance",
    path: "/tools/finance/stock-profit-loss-calculator",
    icon: "TrendingUp",
    description: "計算股票買賣損益、成本與報酬率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "dividend-yield-calculator",
    name: "股息殖利率計算器",
    category: "finance",
    path: "/tools/finance/dividend-yield-calculator",
    icon: "BadgeDollarSign",
    description: "計算股息殖利率與年股息收入",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "pe-ratio-calculator",
    name: "本益比計算器",
    category: "finance",
    path: "/tools/finance/pe-ratio-calculator",
    icon: "BarChart3",
    description: "用股價與 EPS 評估本益比與合理價",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "compound-interest-calculator",
    name: "複利計算器",
    category: "finance",
    path: "/tools/finance/compound-interest-calculator",
    icon: "LineChart",
    description: "計算本金、定期投入與複利終值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "loan-calculator",
    name: "貸款計算器",
    category: "finance",
    path: "/tools/finance/loan-calculator",
    icon: "Calculator",
    description: "計算貸款月付、總支付與總利息",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "tip-calculator",
    name: "小費計算器",
    category: "finance",
    path: "/tools/finance/tip-calculator",
    icon: "Receipt",
    description: "快速計算小費、總額與分攤金額",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "break-even-calculator",
    name: "損益平衡計算器",
    category: "finance",
    path: "/tools/finance/break-even-calculator",
    icon: "Scale",
    description: "計算固定成本下的損益平衡銷售量",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "profit-margin-calculator",
    name: "利潤率計算器",
    category: "finance",
    path: "/tools/finance/profit-margin-calculator",
    icon: "Percent",
    description: "計算毛利、淨利與利潤率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "exchange-rate-calculator",
    name: "匯率換算器",
    category: "finance",
    path: "/tools/finance/exchange-rate-calculator",
    icon: "RefreshCw",
    description: "依匯率與手續費換算外幣金額",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "gold-price-calculator",
    name: "黃金價格計算器",
    category: "finance",
    path: "/tools/finance/gold-price-calculator",
    icon: "Coins",
    description: "依重量、金價與純度估算黃金價值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "color-picker",
    name: "色彩選擇器",
    category: "dev",
    path: "/tools/dev/color-picker",
    icon: "Palette",
    description: "選取顏色並取得 HEX、RGB 數值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "gradient-generator",
    name: "漸層產生器",
    category: "dev",
    path: "/tools/dev/gradient-generator",
    icon: "Paintbrush",
    description: "產生 CSS linear-gradient 漸層程式碼",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "box-shadow-generator",
    name: "Box Shadow 產生器",
    category: "dev",
    path: "/tools/dev/box-shadow-generator",
    icon: "Layers",
    description: "調整陰影參數並產生 box-shadow CSS",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "border-radius-generator",
    name: "圓角產生器",
    category: "dev",
    path: "/tools/dev/border-radius-generator",
    icon: "Square",
    description: "產生四角 border-radius CSS 設定",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "api-response-formatter",
    name: "API 回應格式化工具",
    category: "dev",
    path: "/tools/dev/api-response-formatter",
    icon: "Braces",
    description: "格式化 JSON API 回應並檢查語法",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "markdown-editor",
    name: "Markdown 編輯器",
    category: "dev",
    path: "/tools/dev/markdown-editor",
    icon: "FileText",
    description: "即時編輯 Markdown 並預覽 HTML",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "diff-checker",
    name: "文字差異比對器",
    category: "dev",
    path: "/tools/dev/diff-checker",
    icon: "GitCompare",
    description: "逐行比對兩段文字差異",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "word-counter",
    name: "字數統計器",
    category: "dev",
    path: "/tools/dev/word-counter",
    icon: "Type",
    description: "統計中英文文字字數、字元與行數",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "character-counter",
    name: "字元計數器",
    category: "dev",
    path: "/tools/dev/character-counter",
    icon: "TextCursorInput",
    description: "統計總字元、不含空白與行數",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "lorem-ipsum-generator",
    name: "假文產生器",
    category: "dev",
    path: "/tools/dev/lorem-ipsum-generator",
    icon: "AlignLeft",
    description: "產生繁體中文測試文案",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "qr-code-generator",
    name: "QR Code 產生器",
    category: "dev",
    path: "/tools/dev/qr-code-generator",
    icon: "QrCode",
    description: "將網址或文字轉為 QR Code 圖片",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "barcode-generator",
    name: "條碼產生器",
    category: "dev",
    path: "/tools/dev/barcode-generator",
    icon: "ScanBarcode",
    description: "依文字產生條碼視覺預覽",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "ip-address-lookup",
    name: "IP 位址查詢器",
    category: "dev",
    path: "/tools/dev/ip-address-lookup",
    icon: "Network",
    description: "檢查 IP 格式、版本與公開私有類型",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "dns-lookup",
    name: "DNS 查詢器",
    category: "dev",
    path: "/tools/dev/dns-lookup",
    icon: "Globe",
    description: "驗證網域格式並產生 DNS 查詢預覽",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "ssl-checker",
    name: "SSL 憑證檢查器",
    category: "dev",
    path: "/tools/dev/ssl-checker",
    icon: "Lock",
    description: "檢查網域 SSL 憑證到期狀態",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  // ── Sninja Batch B Health + Batch C Real Estate ──
  {
    id: "body-fat-calculator",
    name: "體脂率計算器",
    category: "health",
    path: "/tools/health/body-fat-calculator",
    icon: "Activity",
    description: "依身體圍度與身高估算體脂率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "ideal-weight-calculator",
    name: "理想體重計算器",
    category: "health",
    path: "/tools/health/ideal-weight-calculator",
    icon: "Scale",
    description: "依身高與 BMI 目標估算理想體重",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "bmr-calculator",
    name: "基礎代謝率計算器",
    category: "health",
    path: "/tools/health/bmr-calculator",
    icon: "Flame",
    description: "使用 Mifflin-St Jeor 公式估算 BMR 與 TDEE",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "pregnancy-calculator",
    name: "懷孕週數計算器",
    category: "health",
    path: "/tools/health/pregnancy-calculator",
    icon: "Baby",
    description: "依最後月經天數估算懷孕週數",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "due-date-calculator",
    name: "預產期計算器",
    category: "health",
    path: "/tools/health/due-date-calculator",
    icon: "CalendarDays",
    description: "估算預產期剩餘天數與產檢提醒",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "blood-pressure-calculator",
    name: "血壓分級計算器",
    category: "health",
    path: "/tools/health/blood-pressure-calculator",
    icon: "HeartPulse",
    description: "依收縮壓與舒張壓判斷血壓區間",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "heart-rate-calculator",
    name: "目標心率計算器",
    category: "health",
    path: "/tools/health/heart-rate-calculator",
    icon: "Heart",
    description: "依年齡與強度估算運動目標心率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "vitamin-calculator",
    name: "維生素攝取建議計算器",
    category: "health",
    path: "/tools/health/vitamin-calculator",
    icon: "Pill",
    description: "依年齡、日曬與體重估算維生素 D 建議",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "alcohol-calculator",
    name: "酒精代謝估算器",
    category: "health",
    path: "/tools/health/alcohol-calculator",
    icon: "Wine",
    description: "估算酒精克數、BAC 與代謝時間",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "age-calculator",
    name: "年齡計算器",
    category: "health",
    path: "/tools/health/age-calculator",
    icon: "Cake",
    description: "依出生後天數估算年齡與目標天數",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "home-affordability-calculator",
    name: "房屋可負擔能力計算器",
    category: "finance",
    path: "/tools/finance/home-affordability-calculator",
    icon: "Home",
    description: "依收入、負債與利率估算可負擔房價",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "rental-yield-calculator",
    name: "租金收益率計算器",
    category: "finance",
    path: "/tools/finance/rental-yield-calculator",
    icon: "Building2",
    description: "計算房產毛租金與淨租金收益率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "property-tax-calculator",
    name: "房屋稅估算器",
    category: "finance",
    path: "/tools/finance/property-tax-calculator",
    icon: "Landmark",
    description: "依課稅現值與稅率估算房屋稅",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "down-payment-calculator",
    name: "頭期款計算器",
    category: "finance",
    path: "/tools/finance/down-payment-calculator",
    icon: "PiggyBank",
    description: "計算購屋頭期款、交易成本與所需現金",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "refinance-calculator",
    name: "房貸轉貸計算器",
    category: "finance",
    path: "/tools/finance/refinance-calculator",
    icon: "Repeat",
    description: "比較原貸款與新利率的月付與節省金額",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "home-equity-calculator",
    name: "房屋淨值計算器",
    category: "finance",
    path: "/tools/finance/home-equity-calculator",
    icon: "HousePlus",
    description: "估算房屋市值扣除貸款後的淨值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "moving-cost-calculator",
    name: "搬家成本計算器",
    category: "finance",
    path: "/tools/finance/moving-cost-calculator",
    icon: "Truck",
    description: "估算搬家距離、車趟與打包總成本",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "property-roi-calculator",
    name: "房產投資報酬率計算器",
    category: "finance",
    path: "/tools/finance/property-roi-calculator",
    icon: "ChartNoAxesCombined",
    description: "計算房產租金與增值後的投資 ROI",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "stamp-duty-calculator",
    name: "印花稅計算器",
    category: "finance",
    path: "/tools/finance/stamp-duty-calculator",
    icon: "FileStamp",
    description: "依交易金額與稅率估算印花稅",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "land-value-calculator",
    name: "土地價值估算器",
    category: "finance",
    path: "/tools/finance/land-value-calculator",
    icon: "Map",
    description: "依面積、單價與分區係數估算土地價值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  // ── Sninja Batch D Tax + Batch E Marketing + Batch G Productivity ──
  {
    id: "vat-calculator",
    name: "營業稅 / VAT 計算器",
    category: "finance",
    path: "/tools/finance/vat-calculator",
    icon: "ReceiptText",
    description: "計算含稅價、未稅價與 VAT 稅額",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "capital-gains-tax-calculator",
    name: "資本利得稅計算器",
    category: "finance",
    path: "/tools/finance/capital-gains-tax-calculator",
    icon: "TrendingUp",
    description: "依買入、賣出與稅率估算資本利得稅",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "withholding-tax-calculator",
    name: "扣繳稅計算器",
    category: "finance",
    path: "/tools/finance/withholding-tax-calculator",
    icon: "HandCoins",
    description: "計算扣繳稅額、補充費與實領金額",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "corporate-tax-calculator",
    name: "營所稅計算器",
    category: "finance",
    path: "/tools/finance/corporate-tax-calculator",
    icon: "Building",
    description: "依營收成本費用估算公司所得稅",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "gift-tax-calculator",
    name: "贈與稅計算器",
    category: "finance",
    path: "/tools/finance/gift-tax-calculator",
    icon: "Gift",
    description: "估算扣除免稅額後的贈與稅",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "estate-tax-calculator",
    name: "遺產稅計算器",
    category: "finance",
    path: "/tools/finance/estate-tax-calculator",
    icon: "Landmark",
    description: "估算遺產淨額與應納遺產稅",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "tax-refund-calculator",
    name: "退稅估算器",
    category: "finance",
    path: "/tools/finance/tax-refund-calculator",
    icon: "BadgeDollarSign",
    description: "依已扣繳稅額與應納稅額估算退補稅",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "salary-after-tax-calculator",
    name: "稅後薪資計算器",
    category: "finance",
    path: "/tools/finance/salary-after-tax-calculator",
    icon: "WalletCards",
    description: "估算月薪扣除所得稅與保費後的實領薪資",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "ctr-calculator",
    name: "CTR 點擊率計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/ctr-calculator",
    icon: "MousePointerClick",
    description: "用點擊與曝光計算廣告點擊率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "cpc-calculator",
    name: "CPC 每次點擊成本計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/cpc-calculator",
    icon: "CircleDollarSign",
    description: "用廣告花費與點擊數計算 CPC",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "cpm-calculator",
    name: "CPM 千次曝光成本計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/cpm-calculator",
    icon: "Megaphone",
    description: "用花費與曝光計算 CPM",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "conversion-rate-calculator",
    name: "轉換率計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/conversion-rate-calculator",
    icon: "Goal",
    description: "計算訪客轉換成訂單或名單的比例",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "email-open-rate-calculator",
    name: "Email 開信率計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/email-open-rate-calculator",
    icon: "MailOpen",
    description: "計算電子報開信率與未開信數",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "customer-lifetime-value",
    name: "顧客終身價值 CLV 計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/customer-lifetime-value",
    icon: "UserRoundCheck",
    description: "估算平均顧客終身價值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "customer-acquisition-cost",
    name: "顧客取得成本 CAC 計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/customer-acquisition-cost",
    icon: "UserPlus",
    description: "計算取得一位新顧客所需成本",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "churn-rate-calculator",
    name: "顧客流失率計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/churn-rate-calculator",
    icon: "UserMinus",
    description: "計算期間顧客流失比例",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "net-promoter-score",
    name: "NPS 淨推薦值計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/net-promoter-score",
    icon: "SmilePlus",
    description: "依推薦者、被動者與批評者計算 NPS",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "social-media-roi-calculator",
    name: "社群媒體 ROI 計算器",
    category: "ecommerce",
    path: "/tools/ecommerce/social-media-roi-calculator",
    icon: "Share2",
    description: "計算社群活動營收、成本與 ROI",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "meeting-agenda-generator",
    name: "會議議程產生器",
    category: "productivity",
    path: "/tools/productivity/meeting-agenda-generator",
    icon: "ListChecks",
    description: "依主題與時間自動產生會議議程",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "okr-calculator",
    name: "OKR 達成率計算器",
    category: "productivity",
    path: "/tools/productivity/okr-calculator",
    icon: "Target",
    description: "計算 OKR 關鍵結果平均完成率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "reading-time-calculator",
    name: "閱讀時間計算器",
    category: "productivity",
    path: "/tools/productivity/reading-time-calculator",
    icon: "BookOpen",
    description: "估算文章字數與閱讀時間",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "typing-speed-calculator",
    name: "打字速度計算器",
    category: "productivity",
    path: "/tools/productivity/typing-speed-calculator",
    icon: "Keyboard",
    description: "計算 CPM、WPM 與打字正確率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "work-hours-calculator",
    name: "工時計算器",
    category: "productivity",
    path: "/tools/productivity/work-hours-calculator",
    icon: "BriefcaseBusiness",
    description: "計算正常工時、加班與估算薪資",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "deadline-calculator",
    name: "截止日規劃器",
    category: "productivity",
    path: "/tools/productivity/deadline-calculator",
    icon: "CalendarClock",
    description: "依剩餘天數、緩衝與任務數規劃截止日",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "age-at-date-calculator",
    name: "指定日期年齡計算器",
    category: "productivity",
    path: "/tools/productivity/age-at-date-calculator",
    icon: "CalendarDays",
    description: "計算某人在指定日期的年齡",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  {
    id: "email-subject-generator",
    name: "Email 主旨產生器",
    category: "productivity",
    path: "/tools/productivity/email-subject-generator",
    icon: "MailPlus",
    description: "依主題、受眾與利益點產生 Email 主旨",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
  },
  // ── Sninja Batch H Education + Batch I Science + Batch J Travel ──
  {
    id: "gpa-calculator",
    name: "GPA 計算器",
    category: "education",
    path: "/tools/education/gpa-calculator",
    description: "依照總學分與加權分數快速估算 GPA。",
    icon: "📚",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["GPA", "成績", "教育"],
    isNew: true,
  },
  {
    id: "grade-calculator",
    name: "成績計算器",
    category: "education",
    path: "/tools/education/grade-calculator",
    description: "輸入平時、期中、期末分數與權重，計算總成績。",
    icon: "📝",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["成績", "權重", "教育"],
    isNew: true,
  },
  {
    id: "study-time-calculator",
    name: "讀書時間計算器",
    category: "education",
    path: "/tools/education/study-time-calculator",
    description: "依照目標章節、剩餘天數與每日效率安排讀書時數。",
    icon: "⏱️",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["讀書", "時間規劃", "教育"],
    isNew: true,
  },
  {
    id: "flashcard-generator",
    name: "單字卡產生器",
    category: "education",
    path: "/tools/education/flashcard-generator",
    description: "輸入詞語清單，產生可複習的單字卡列表。",
    icon: "🃏",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["單字卡", "複習", "學習"],
    isNew: true,
  },
  {
    id: "essay-word-count",
    name: "作文字數計算器",
    category: "education",
    path: "/tools/education/essay-word-count",
    description: "計算文章字數、句數與預估閱讀時間。",
    icon: "✍️",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["作文", "字數", "閱讀時間"],
    isNew: true,
  },
  {
    id: "citation-generator",
    name: "引用格式產生器",
    category: "education",
    path: "/tools/education/citation-generator",
    description: "輸入作者、標題與年份，產生簡易 APA 引用格式。",
    icon: "🔖",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["引用", "APA", "論文"],
    isNew: true,
  },
  {
    id: "iq-test-calculator",
    name: "IQ 測驗分數換算器",
    category: "education",
    path: "/tools/education/iq-test-calculator",
    description: "用原始分數、平均值與標準差估算 IQ 標準分。",
    icon: "🧠",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["IQ", "標準分", "測驗"],
    isNew: true,
  },
  {
    id: "learning-style-quiz",
    name: "學習風格測驗",
    category: "education",
    path: "/tools/education/learning-style-quiz",
    description: "輸入偏好分數，判斷主要學習風格。",
    icon: "🎓",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["學習風格", "測驗", "教育"],
    isNew: true,
  },
  {
    id: "unit-converter",
    name: "單位換算器",
    category: "science",
    path: "/tools/science/unit-converter",
    description: "公尺、公里、英里與英尺快速換算。",
    icon: "📏",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["單位", "換算", "科學"],
    isNew: true,
  },
  {
    id: "temperature-converter",
    name: "溫度轉換器",
    category: "science",
    path: "/tools/science/temperature-converter",
    description: "攝氏、華氏與開氏溫度互轉。",
    icon: "🌡️",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["溫度", "換算", "科學"],
    isNew: true,
  },
  {
    id: "speed-calculator",
    name: "速度計算器",
    category: "science",
    path: "/tools/science/speed-calculator",
    description: "由距離與時間計算平均速度。",
    icon: "🚀",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["速度", "距離", "物理"],
    isNew: true,
  },
  {
    id: "force-calculator",
    name: "力學計算器",
    category: "science",
    path: "/tools/science/force-calculator",
    description: "使用 F = m × a 計算作用力。",
    icon: "⚙️",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["力學", "牛頓", "物理"],
    isNew: true,
  },
  {
    id: "ohms-law-calculator",
    name: "歐姆定律計算器",
    category: "science",
    path: "/tools/science/ohms-law-calculator",
    description: "使用 V = I × R 計算電壓與功率。",
    icon: "⚡",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["歐姆定律", "電壓", "電學"],
    isNew: true,
  },
  {
    id: "molecular-weight-calculator",
    name: "分子量計算器",
    category: "science",
    path: "/tools/science/molecular-weight-calculator",
    description: "輸入 C/H/O/N 原子數估算分子量。",
    icon: "🧪",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["分子量", "化學", "科學"],
    isNew: true,
  },
  {
    id: "ph-calculator",
    name: "pH 計算器",
    category: "science",
    path: "/tools/science/ph-calculator",
    description: "依照氫離子濃度計算 pH 值與酸鹼性。",
    icon: "🧫",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["pH", "酸鹼", "化學"],
    isNew: true,
  },
  {
    id: "percentage-calculator",
    name: "百分比計算器",
    category: "science",
    path: "/tools/science/percentage-calculator",
    description: "計算占比與數值增減幅度。",
    icon: "％",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["百分比", "比例", "計算"],
    isNew: true,
  },
  {
    id: "flight-time-calculator",
    name: "飛行時間計算器",
    category: "travel",
    path: "/tools/travel/flight-time-calculator",
    description: "依照距離、平均航速與時差估算抵達時間。",
    icon: "✈️",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["飛行", "航程", "旅行"],
    isNew: true,
  },
  {
    id: "travel-budget-calculator",
    name: "旅行預算計算器",
    category: "travel",
    path: "/tools/travel/travel-budget-calculator",
    description: "估算交通、住宿、餐飲與活動總旅費。",
    icon: "💼",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["旅費", "預算", "旅行"],
    isNew: true,
  },
  {
    id: "hotel-cost-calculator",
    name: "飯店費用計算器",
    category: "travel",
    path: "/tools/travel/hotel-cost-calculator",
    description: "計算房價、晚數、稅費與服務費後的住宿成本。",
    icon: "🏨",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["飯店", "住宿", "旅行"],
    isNew: true,
  },
  {
    id: "distance-calculator",
    name: "距離計算器",
    category: "travel",
    path: "/tools/travel/distance-calculator",
    description: "使用兩點經緯度估算大圓距離。",
    icon: "🗺️",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["距離", "經緯度", "旅行"],
    isNew: true,
  },
  {
    id: "fuel-cost-calculator",
    name: "油資計算器",
    category: "travel",
    path: "/tools/travel/fuel-cost-calculator",
    description: "依距離、油耗與油價估算油資。",
    icon: "⛽",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["油資", "自駕", "旅行"],
    isNew: true,
  },
  {
    id: "co2-emission-calculator",
    name: "碳排放計算器",
    category: "travel",
    path: "/tools/travel/co2-emission-calculator",
    description: "依交通距離與排放係數估算 CO₂。",
    icon: "🌿",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["碳排", "永續", "旅行"],
    isNew: true,
  },
  {
    id: "packing-list-generator",
    name: "行李清單產生器",
    category: "travel",
    path: "/tools/travel/packing-list-generator",
    description: "依天數、氣候與活動產生基本打包清單。",
    icon: "🎒",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["行李", "清單", "旅行"],
    isNew: true,
  },
  {
    id: "visa-fee-calculator",
    name: "簽證費用計算器",
    category: "travel",
    path: "/tools/travel/visa-fee-calculator",
    description: "估算多人簽證、服務費與匯率後總成本。",
    icon: "🛂",
    isPremium: false,
    showAds: true,
    rateLimit: 20,
    seoArticles: [],
    tags: ["簽證", "費用", "旅行"],
    isNew: true,
  },

  // ── DEV Priority 1 Expansion CNV/FMT/ENC/VAL/GEN ──
  {
    id: "json-to-xml",
    name: "JSON to XML Converter",
    nameZh: "JSON轉XML轉換器",
    category: "dev",
    path: "/tools/dev/json-to-xml",
    icon: "Code2",
    description: "輸入JSON後輸出格式化XML，支援一鍵複製。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "CNV", "JSON to XML Converter"],
    isNew: true,
    canonicalId: "DEV-000133",
    galaxy: "CNV",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "json-to-yaml",
    name: "JSON to YAML Converter",
    nameZh: "JSON轉YAML轉換器",
    category: "dev",
    path: "/tools/dev/json-to-yaml",
    icon: "FileJson",
    description: "輸入JSON後輸出YAML，支援一鍵複製。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "CNV", "JSON to YAML Converter"],
    isNew: true,
    canonicalId: "DEV-000134",
    galaxy: "CNV",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON Converter",
    nameZh: "CSV轉JSON轉換器",
    category: "dev",
    path: "/tools/dev/csv-to-json",
    icon: "Table",
    description: "輸入CSV後輸出JSON陣列，支援header自動偵測。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "CNV", "CSV to JSON Converter"],
    isNew: true,
    canonicalId: "DEV-000135",
    galaxy: "CNV",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "html-to-markdown",
    name: "HTML to Markdown Converter",
    nameZh: "HTML轉Markdown轉換器",
    category: "dev",
    path: "/tools/dev/html-to-markdown",
    icon: "FileText",
    description: "輸入HTML後輸出Markdown，支援一鍵複製。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "CNV", "HTML to Markdown Converter"],
    isNew: true,
    canonicalId: "DEV-000136",
    galaxy: "CNV",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "hex-to-rgb",
    name: "HEX to RGB Converter",
    nameZh: "HEX轉RGB顏色轉換器",
    category: "dev",
    path: "/tools/dev/hex-to-rgb",
    icon: "Palette",
    description: "輸入HEX色碼後輸出RGB值，支援雙向轉換。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "CNV", "HEX to RGB Converter"],
    isNew: true,
    canonicalId: "DEV-000137",
    galaxy: "CNV",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "sql-formatter",
    name: "SQL Formatter",
    nameZh: "SQL格式化工具",
    category: "dev",
    path: "/tools/dev/sql-formatter",
    icon: "Database",
    description: "輸入原始SQL後輸出縮排美化SQL，支援多種SQL方言。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "FMT", "SQL Formatter"],
    isNew: true,
    canonicalId: "DEV-000138",
    galaxy: "FMT",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "xml-formatter",
    name: "XML Formatter",
    nameZh: "XML格式化工具",
    category: "dev",
    path: "/tools/dev/xml-formatter",
    icon: "FileCode",
    description: "輸入原始XML後輸出美化XML，支援縮排選擇。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "FMT", "XML Formatter"],
    isNew: true,
    canonicalId: "DEV-000139",
    galaxy: "FMT",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "css-beautifier",
    name: "CSS Beautifier",
    nameZh: "CSS美化工具",
    category: "dev",
    path: "/tools/dev/css-beautifier",
    icon: "Braces",
    description: "輸入壓縮CSS後輸出美化CSS，支援縮排設定。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "FMT", "CSS Beautifier"],
    isNew: true,
    canonicalId: "DEV-000140",
    galaxy: "FMT",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "javascript-formatter",
    name: "JavaScript Formatter",
    nameZh: "JavaScript格式化工具",
    category: "dev",
    path: "/tools/dev/javascript-formatter",
    icon: "Code",
    description: "輸入原始JS後輸出格式化JS，支援Prettier風格。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "FMT", "JavaScript Formatter"],
    isNew: true,
    canonicalId: "DEV-000141",
    galaxy: "FMT",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "html-formatter",
    name: "HTML Formatter",
    nameZh: "HTML格式化工具",
    category: "dev",
    path: "/tools/dev/html-formatter",
    icon: "FileCode2",
    description: "輸入原始HTML後輸出縮排美化HTML。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "FMT", "HTML Formatter"],
    isNew: true,
    canonicalId: "DEV-000142",
    galaxy: "FMT",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "hex-encoder-decoder",
    name: "HEX Encoder/Decoder",
    nameZh: "HEX編碼解碼器",
    category: "dev",
    path: "/tools/dev/hex-encoder-decoder",
    icon: "Binary",
    description: "文字與HEX雙向轉換，支援一鍵複製。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "ENC", "HEX Encoder/Decoder"],
    isNew: true,
    canonicalId: "DEV-000143",
    galaxy: "ENC",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "html-entity-encoder",
    name: "HTML Entity Encoder/Decoder",
    nameZh: "HTML實體編碼解碼器",
    category: "dev",
    path: "/tools/dev/html-entity-encoder",
    icon: "Ampersand",
    description: "文字與HTML entities雙向轉換。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "ENC", "HTML Entity Encoder/Decoder"],
    isNew: true,
    canonicalId: "DEV-000144",
    galaxy: "ENC",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "unicode-converter",
    name: "Unicode Converter",
    nameZh: "Unicode轉換器",
    category: "dev",
    path: "/tools/dev/unicode-converter",
    icon: "Languages",
    description: "文字與Unicode code points雙向轉換。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "ENC", "Unicode Converter"],
    isNew: true,
    canonicalId: "DEV-000146",
    galaxy: "ENC",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "binary-converter",
    name: "Binary/Decimal/Hex Converter",
    nameZh: "二進制/十進制/十六進制轉換器",
    category: "dev",
    path: "/tools/dev/binary-converter",
    icon: "Calculator",
    description: "二進制、十進制與十六進制互相轉換，支援整數與浮點數。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "ENC", "Binary/Decimal/Hex Converter"],
    isNew: true,
    canonicalId: "DEV-000147",
    galaxy: "ENC",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "json-validator",
    name: "JSON Validator",
    nameZh: "JSON驗證器",
    category: "dev",
    path: "/tools/dev/json-validator",
    icon: "CheckCircle",
    description: "驗證JSON語法，顯示錯誤行號並提供格式化預覽。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "VAL", "JSON Validator"],
    isNew: true,
    canonicalId: "DEV-000148",
    galaxy: "VAL",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "xml-validator",
    name: "XML Validator",
    nameZh: "XML驗證器",
    category: "dev",
    path: "/tools/dev/xml-validator",
    icon: "BadgeCheck",
    description: "驗證XML語法，顯示錯誤位置。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "VAL", "XML Validator"],
    isNew: true,
    canonicalId: "DEV-000149",
    galaxy: "VAL",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "yaml-validator",
    name: "YAML Validator",
    nameZh: "YAML驗證器",
    category: "dev",
    path: "/tools/dev/yaml-validator",
    icon: "ListChecks",
    description: "驗證YAML語法，顯示錯誤行號。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "VAL", "YAML Validator"],
    isNew: true,
    canonicalId: "DEV-000150",
    galaxy: "VAL",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "email-validator",
    name: "Email Address Validator",
    nameZh: "Email地址驗證器",
    category: "dev",
    path: "/tools/dev/email-validator",
    icon: "MailCheck",
    description: "驗證email格式，支援批量驗證。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "VAL", "Email Address Validator"],
    isNew: true,
    canonicalId: "DEV-000151",
    galaxy: "VAL",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "ip-address-validator",
    name: "IP Address Validator",
    nameZh: "IP地址驗證器",
    category: "dev",
    path: "/tools/dev/ip-address-validator",
    icon: "Network",
    description: "驗證IPv4與IPv6格式，顯示地址類型與範圍。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "VAL", "IP Address Validator"],
    isNew: true,
    canonicalId: "DEV-000152",
    galaxy: "VAL",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    nameZh: "UUID生成器",
    category: "dev",
    path: "/tools/dev/uuid-generator",
    icon: "Fingerprint",
    description: "生成UUID v1/v4，支援批量生成與一鍵複製。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "GEN", "UUID Generator"],
    isNew: true,
    canonicalId: "DEV-000153",
    galaxy: "GEN",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "password-generator",
    name: "Password Generator",
    nameZh: "密碼生成器",
    category: "dev",
    path: "/tools/dev/password-generator",
    icon: "Lock",
    description: "自訂長度、大小寫、數字與符號，提供強度指示器。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "GEN", "Password Generator"],
    isNew: true,
    canonicalId: "DEV-000154",
    galaxy: "GEN",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    nameZh: "Hash生成器",
    category: "dev",
    path: "/tools/dev/hash-generator",
    icon: "Hash",
    description: "輸入文字後生成MD5、SHA1、SHA256與SHA512雜湊。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "GEN", "Hash Generator"],
    isNew: true,
    canonicalId: "DEV-000155",
    galaxy: "GEN",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "mock-data-generator",
    name: "Mock Data Generator",
    nameZh: "模擬資料生成器",
    category: "dev",
    path: "/tools/dev/mock-data-generator",
    icon: "Rows3",
    description: "生成姓名、email、電話與地址假資料，支援JSON與CSV輸出。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "GEN", "Mock Data Generator"],
    isNew: true,
    canonicalId: "DEV-000156",
    galaxy: "GEN",
    universe: "DEV",
    websiteKey: "dev",
  },
  {
    id: "slug-generator",
    name: "Slug Generator",
    nameZh: "Slug生成器",
    category: "dev",
    path: "/tools/dev/slug-generator",
    icon: "Link",
    description: "輸入文字後生成URL-friendly slug，支援多語言。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    seoArticles: [],
    tags: ["DEV", "GEN", "Slug Generator"],
    isNew: true,
    canonicalId: "DEV-000157",
    galaxy: "GEN",
    universe: "DEV",
    websiteKey: "dev",
  },

];

// ============================================================
// 輔助函數
// ============================================================

export function getAllTools(): Tool[] {
  return tools;
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((t) => t.category === category);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((t) => t.id === id);
}

export function getToolByPath(path: string): Tool | undefined {
  return tools.find((t) => t.path === path);
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((t) => t.isFeatured);
}

export const toolMap: Record<string, Tool> = Object.fromEntries(
  tools.map((t) => [t.id, t])
);
