
// toolsConfig.ts - 工具矩陣設定大腦
// 每個工具必須含 category（對應 categoriesConfig key）
// 與完整三層路徑 /tools/[category]/[tool-name]
//
// 憲法 V3 遵循：
// - 只保留已完成重造的工具（BMI、BMR）
// - 保留所有工具的 URL 和名稱（供驗收）
// - 舊工具內容已刪除，顯示「工具正在重造中」
// ============================================================

export interface SeoArticle {
  id: string;
  title: string;
  description: string;
}

export interface Tool {
  id: string;
  name: string;
  nameZh?: string;
  category: string; // 對應 categoriesConfig 的 key
  path: string; // 三層路徑：/tools/[category]/[tool-name]
  description: string;
  icon: string;
  isPremium: boolean;
  showAds: boolean;
  rateLimit: number; // 每分鐘最大請求數
  seoArticles: SeoArticle[];
  tags?: string[];
  isNew?: boolean;
  isFeatured?: boolean;
  canonicalId?: string;
  galaxy?: string;
  universe?: string;
  websiteKey?: string;
  status?: "GOLD" | "REBUILDING" | "LEGACY"; // 工具狀態
}

// ============================================================
// 工具清單 - 三層路徑結構
// ============================================================
export const tools: Tool[] = [
  // ── 健康工具（已完成重造）────────────────────────────────────
  {
    id: "bmi-calculator",
    name: "BMI 計算機",
    category: "health",
    path: "/tools/health/bmi-calculator",
    icon: "Scale",
    description: "輸入身高體重，依台灣衛福部標準分類 BMI，提供理想體重範圍與個人化健康建議。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "bmr-calculator",
    name: "BMR 計算機",
    category: "health",
    path: "/tools/health/bmr-calculator",
    icon: "Flame",
    description: "計算基礎代謝率（BMR），了解身體每日消耗的基礎熱量。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "tdee-calculator",
    name: "TDEE 每日總消耗熱量",
    category: "health",
    path: "/tools/health/tdee-calculator",
    icon: "BarChart3",
    description: "用 Mifflin-St Jeor + 6 段活動量帶估算每日總消耗，並給維持/減脂/增肌目標。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "ideal-weight-calculator",
    name: "理想體重計算機",
    category: "health",
    path: "/tools/health/ideal-weight-calculator",
    icon: "Scale",
    description: "依身高估算常見理想體重區間，對照 Devine、Robinson、Miller 與 Hamwi 公式。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "body-fat-calculator",
    name: "體脂率計算機",
    category: "health",
    path: "/tools/health/body-fat-calculator",
    icon: "Activity",
    description: "使用 U.S. Navy 圍度法，依身高、頸圍、腰圍與臀圍估算體脂率，協助連接 BMI、TDEE 與熱量赤字規劃。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "calorie-deficit-calculator",
    name: "熱量赤字計算機",
    category: "health",
    path: "/tools/health/calorie-deficit-calculator",
    icon: "Flame",
    description: "用 TDEE 減去平均攝取熱量，估算每日赤字、每週赤字與靜態體重變化趨勢，並提示 3500 kcal/lb 模型限制。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "water-intake-calculator",
    name: "飲水量計算機",
    category: "health",
    path: "/tools/health/water-intake-calculator",
    icon: "Droplets",
    description: "用體重與活動量估算每日建議飲水量，並提供公升與液體盎司換算。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "macro-calculator",
    name: "巨量營養素計算機",
    category: "health",
    path: "/tools/health/macro-calculator",
    icon: "Beef",
    description: "用體重、TDEE 與目標模式估算蛋白質、脂肪與碳水化合物分配。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  // ── 財務工具（Profile B 試產第 3 件 · 跨領域驗證樣本）──────────────────────────
  {
    id: "loan-calculator",
    name: "貸款試算機",
    category: "finance",
    path: "/tools/finance/loan-calculator",
    icon: "Banknote",
    description: "等額本息（PMT）公式估算每月還款、總還款金額與總利息支出，含 5/10/15/20/25/30 年六段年期對照。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "mortgage-calculator",
    name: "房貸試算機",
    category: "finance",
    path: "/tools/finance/mortgage-calculator",
    icon: "Home",
    description: "輸入房屋總價、頭期款、年利率、年期與家庭月收入，估算房貸月付、本息總額、總利息、貸款成數與收入負擔率，並提供 5/10/15/20/25/30 年六段對照。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "credit-card-payoff-calculator",
    name: "信用卡還清試算機",
    category: "finance",
    path: "/tools/finance/credit-card-payoff-calculator",
    icon: "CreditCard",
    description: "輸入信用卡餘額、APR、每月付款與最低繳款比例，估算還清月數、總付款與總利息，並比較六段加速還款策略。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "debt-to-income-calculator",
    name: "負債收入比試算機",
    category: "finance",
    path: "/tools/finance/debt-to-income-calculator",
    icon: "Scale",
    description: "輸入每月房貸或房租、其他債務與月總收入，估算 DTI 負債收入比、每月債務總額與目標門檻下的借貸空間。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "compound-interest-calculator",
    name: "複利計算機",
    category: "finance",
    path: "/tools/finance/compound-interest-calculator",
    icon: "LineChart",
    description: "月複利 + 定期投入公式估算終值、總投入、複利收益，含 5/10/15/20/25/30 年六段年期對照，看清時間槓桿。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "retirement-calculator",
    name: "退休金試算機",
    category: "finance",
    path: "/tools/finance/retirement-calculator",
    icon: "PiggyBank",
    description: "輸入年齡 / 退休目標 / 月儲蓄 / 報酬率，估算退休金總額、退休後月領、自備款累計，含 40/50/55/60/65/70 歲退休對照。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "cagr-calculator",
    name: "CAGR 年化報酬率試算",
    category: "finance",
    path: "/tools/finance/cagr-calculator",
    icon: "TrendingUp",
    description: "由起始值與終值反推真實年化報酬率（Compound Annual Growth Rate），含總報酬率、總獲利與 5/10/15/20/25/30 年六段對照。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "savings-goal-calculator",
    name: "存錢目標反推試算",
    category: "finance",
    path: "/tools/finance/savings-goal-calculator",
    icon: "Target",
    description: "已知目標金額、現有本金、預期報酬與年期，反推每月需固定存入多少錢；含累計自備款、利息貢獻與 5/10/15/20/25/30 年六段對照。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "inflation-adjuster",
    name: "通膨調整計算機",
    category: "finance",
    path: "/tools/finance/inflation-adjuster",
    icon: "TrendingUp",
    description: "用通膨率與年數計算貨幣未來購買力與實質價值，協助長期財務規劃。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "net-worth-calculator",
    name: "淨資產計算機",
    category: "finance",
    path: "/tools/finance/net-worth-calculator",
    icon: "Wallet",
    description: "計算總資產扣除總負債後的淨資產與負債比率，全面掌握個人財務健康狀態。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "debt-payoff-calculator",
    name: "債務清償計算機",
    category: "finance",
    path: "/tools/finance/debt-payoff-calculator",
    icon: "CreditCard",
    description: "計算每月固定還款額、總利息支出與清償日期，制定最有效的債務清償策略。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "budget-ratio-calculator",
    name: "預算比例計算機",
    category: "finance",
    path: "/tools/finance/budget-ratio-calculator",
    icon: "PieChart",
    description: "用 50/30/20 法則分配月收入，計算需要、想要與儲蓄比例，掌握財務結構。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "emergency-fund-calculator",
    name: "緊急備用金計算機",
    category: "finance",
    path: "/tools/finance/emergency-fund-calculator",
    icon: "Shield",
    description: "計算緊急備用金目標金額與達成時間，確保財務安全網穩固。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "salary-after-tax-calculator",
    name: "稅後薪資計算機",
    category: "finance",
    path: "/tools/finance/salary-after-tax-calculator",
    icon: "Receipt",
    description: "計算年薪扣除聯邦稅、州稅、社安稅與醫保稅後的實際到手薪資與有效稅率。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "hourly-rate-calculator",
    name: "時薪計算機",
    category: "finance",
    path: "/tools/finance/hourly-rate-calculator",
    icon: "Clock",
    description: "將年薪換算成實際時薪，考量每週工時、工作週數與休假天數。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "meeting-cost-calculator",
    name: "會議成本計算機",
    category: "finance",
    path: "/tools/finance/meeting-cost-calculator",
    icon: "Users",
    description: "根據參與人數、平均時薪、會議時長與頻率估算單場、每月與年度會議成本。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "pomodoro-calculator",
    name: "番茄鐘計算機",
    category: "finance",
    path: "/tools/finance/pomodoro-calculator",
    icon: "Clock",
    description: "計算番茄鐘專注循環、休息時間、總排程長度與專注占比。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "roas-calculator",
    name: "廣告投報率計算機",
    category: "finance",
    path: "/tools/finance/roas-calculator",
    icon: "TrendingUp",
    description: "根據廣告花費、廣告歸因收入、銷貨成本與訂單數計算 ROAS、ROI、CPA、AOV 與損益兩平 ROAS。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "profit-margin-calculator",
    name: "利潤率計算機",
    category: "finance",
    path: "/tools/finance/profit-margin-calculator",
    icon: "Percent",
    description: "根據營收、銷貨成本、營業費用與單價計算毛利率、淨利率、加價率與損益兩平件數。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  // ── 職場效率（Productivity Batch 1）──────────────────────────────────
  {
    id: "pomodoro-planner",
    name: "番茄鐘日程規劃器",
    category: "productivity",
    path: "/tools/productivity/pomodoro-planner",
    icon: "Timer",
    description: "把今日可用工作時數轉成番茄鐘循環、總專注分鐘與週度節奏,協助規劃可持續的深度工作日。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "time-zone-converter",
    name: "時區轉換器",
    category: "productivity",
    path: "/tools/productivity/time-zone-converter",
    icon: "Globe",
    description: "輸入兩地 UTC 偏移與工作時段,計算重疊小時、建議會議時段與週度可同步小時,協助跨國團隊規劃協作節奏。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "word-counter",
    name: "字數統計工具",
    category: "productivity",
    path: "/tools/productivity/word-counter",
    icon: "Type",
    description: "貼上文字內容即時統計英文單字、中文字元、段落、句子與閱讀分鐘,並提供六格長度判讀矩陣。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "date-duration-calculator",
    name: "日期天數計算機",
    category: "productivity",
    path: "/tools/productivity/date-duration-calculator",
    icon: "CalendarDays",
    description: "計算兩個日期之間的天數、週數、月數、年數與工作日(扣除週末),並提供六格時程判讀矩陣。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "age-calculator",
    name: "年齡計算機",
    category: "productivity",
    path: "/tools/productivity/age-calculator",
    icon: "Cake",
    description: "把出生日期換算成精確年/月/日年齡、總天數、總週數與下次生日倒數,並提供六格人生階段判讀矩陣。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "json-formatter",
    name: "JSON 格式化器",
    category: "developer",
    path: "/tools/developer/json-formatter",
    icon: "Braces",
    description: "瀏覽器端 JSON 格式化/最小化/驗證,提供位元組、深度、token 統計與六格大小判讀矩陣;資料不上傳。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
    {
    id: "base64-encoder",
    name: "Base64 編碼器",
    category: "developer",
    path: "/tools/developer/base64-encoder",
    icon: "Binary",
    description: "瀏覽器端 Base64 編碼/解碼，支援 UTF-8 多位元組字元、URL-safe 變體與六格大小判讀矩陣；資料不上傳。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
    {
    id: "url-encoder",
    name: "URL 編碼器",
    category: "developer",
    path: "/tools/developer/url-encoder",
    icon: "Link",
    description: "URL 百分比編碼雙向轉換，支援 component/full URI 模式、UTF-8 多位元組字元與五格膨脹比判讀矩陣；資料不上傳。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
    {
    id: "regex-tester",
    name: "正則表達式測試器",
    category: "developer",
    path: "/tools/developer/regex-tester",
    icon: "Regex",
    description: "即時編譯 ECMAScript regex pattern，視覺化所有 match 與 capture group，並提供六格密度判讀矩陣；資料不上傳。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
    {
    id: "color-converter",
    name: "色彩格式轉換器",
    category: "developer",
    path: "/tools/developer/color-converter",
    icon: "Palette",
    description: "HEX/RGB/HSL/HSV/CMYK 五種色彩格式雙向轉換，內建 WCAG 對比度與六格 hue 分區矩陣；瀏覽器端執行。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "timestamp-converter",
    name: "時間戳轉換器",
    category: "developer",
    path: "/tools/developer/timestamp-converter",
    icon: "Clock",
    description: "Unix 時間戳與人類可讀日期雙向轉換，支援秒/毫秒、UTC、ISO 8601 與 RFC 2822；瀏覽器端執行，並提供時間軸六格分區判讀矩陣。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "markdown-preview",
    name: "Markdown 預覽器",
    category: "developer",
    path: "/tools/developer/markdown-preview",
    icon: "FileText",
    description: "瀏覽器端 CommonMark Markdown 即時預覽,支援標題、清單、連結、程式碼區塊與表格;統計六格內容密度判讀矩陣 (字數、段落、標題、連結、程式碼、表格);資料不上傳。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "diff-checker",
    name: "差異比對器",
    category: "developer",
    path: "/tools/developer/diff-checker",
    icon: "GitCompare",
    description: "瀏覽器端純文字差異比對 (Myers diff 簡化版),逐行標示新增/刪除/相同,並提供六格變更密度判讀矩陣 (相同度、純新增、純刪除、混合修改、結構重排、完全不同);資料不上傳。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "csv-to-json",
    name: "CSV 轉 JSON 工具",
    category: "developer",
    path: "/tools/developer/csv-to-json",
    icon: "Table",
    description: "瀏覽器端 CSV 轉 JSON 結構化陣列(RFC 4180 子集),支援雙引號逸出、自訂分隔字元(逗號/分號/Tab)、型別推斷(數值/布林/null);提供六格列數判讀矩陣 (極小/輕量/標準/中型/倉儲級/超大);資料不上傳。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    nameZh: "雜湊生成器",
    category: "developer",
    path: "/tools/developer/hash-generator",
    icon: "Fingerprint",
    description: "In-browser SHA-1 / SHA-256 / SHA-384 / SHA-512 hash generation via Web Crypto API (SubtleCrypto), with UTF-8 byte counting and a six-band security matrix grounded in NIST FIPS 180-4 and RFC 6234. Inputs never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "html-encoder",
    name: "HTML Encoder",
    nameZh: "HTML 編碼解碼器",
    category: "developer",
    path: "/tools/developer/html-encoder",
    icon: "Code2",
    description: "Browser-side HTML escape / unescape for the five HTML special characters (< > & \" ') with optional non-ASCII full escape, grounded in WHATWG HTML Living Standard §13 and the OWASP HTML Encoding Cheat Sheet. Six-band readout judges escape volume. Inputs never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "jwt-decoder",
    name: "JWT Decoder",
    nameZh: "JWT 解碼器",
    category: "developer",
    path: "/tools/developer/jwt-decoder",
    icon: "KeyRound",
    description: "Browser-side JWT (RFC 7519) decoder — splits header.payload.signature, base64url-decodes (RFC 7515 §2), parses claims, shows exp countdown. Six-band algorithm judgement (none / weak HS256 / RS256 / ES256 / EdDSA / expired) per RFC 8725 BCP and OWASP JWT Cheat Sheet. Tokens never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "gpa-calculator",
    name: "GPA Calculator",
    nameZh: "GPA計算機",
    category: "education",
    path: "/tools/education/gpa-calculator",
    icon: "GraduationCap",
    description: "Compute weighted GPA on the US 4.0 scale with a six-band academic standing matrix; supports Academic Renewal toggle for retake exclusion. Browser-side only, no data uploaded.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "grade-calculator",
    name: "Grade Calculator",
    nameZh: "成績計算機",
    category: "education",
    path: "/tools/education/grade-calculator",
    icon: "Calculator",
    description: "Compute weighted course grades and Final Grade Needed reverse calculation on the US 13-band letter scale (A+ 97 / A 93 / A- 90 ... F <60). Browser-side only, no data uploaded.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "study-time-calculator",
    name: "Study Time Calculator",
    nameZh: "讀書時間計算機",
    category: "education",
    path: "/tools/education/study-time-calculator",
    icon: "Clock",
    description: "Compute weekly study hours from credits, difficulty, and target GPA using the Carnegie Unit standard (2-3 hr per credit). Six-band load matrix: Light / Moderate / Standard / Heavy / Intense / Burnout. Browser-side only.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "math-percentage-calculator",
    name: "Math Percentage Calculator",
    nameZh: "百分比計算機",
    category: "education",
    path: "/tools/education/math-percentage-calculator",
    icon: "Percent",
    description: "Three-mode percentage engine: X% of Y, X is what % of Y, and percent change from X to Y. Six-band real-world matrix covers tip, sales tax, discount, markup, growth, and CPI scenarios. Browser-side only.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "cron-expression",
    name: "Cron Expression Parser",
    nameZh: "Cron 表達式解析器",
    category: "developer",
    path: "/tools/developer/cron-expression",
    icon: "Clock",
    description: "Browser-side cron expression parser supporting POSIX 5-field (Vixie / IEEE 1003.1-2017) and Quartz 6/7-field syntax, with next-fire prediction, per-day frequency calculation, and a six-band scheduling-load matrix grounded in RFC-conformant cron semantics. Inputs never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "ip-calculator",
    name: "IP / CIDR Calculator",
    nameZh: "IP / CIDR 計算器",
    category: "developer",
    path: "/tools/developer/ip-calculator",
    icon: "Network",
    description: "Browser-side IPv4 CIDR calculator deriving network address, broadcast, usable host range, subnet mask, wildcard, and host count from any IP/prefix combination, grounded in RFC 4632 (CIDR), RFC 1918 (private space), and RFC 6890 (special-purpose registry). A six-band scale categorizes subnet size from /32 single host to /8 enterprise blocks. Inputs never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "color-palette-generator",
    name: "Color Palette Generator",
    nameZh: "色彩調色板生成器",
    category: "developer",
    path: "/tools/developer/color-palette-generator",
    icon: "Palette",
    description: "Browser-side color palette generator deriving complementary, analogous, triadic, tetradic, and monochromatic schemes from a single hex/HSL seed, grounded in HSL color theory and WCAG 2.2 contrast ratio (AA / AAA). A six-band luminance matrix categorises palette brightness from near-black to near-white. Inputs never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    nameZh: "密碼生成器",
    category: "developer",
    path: "/tools/developer/password-generator",
    icon: "Key",
    description: "Browser-side cryptographic password generator using Web Crypto API (crypto.getRandomValues), with configurable length, charset (lower/upper/digit/symbol), and Shannon-entropy readout. A six-band entropy matrix grades passwords from disposable to nation-state-resistant, grounded in NIST SP 800-63B and OWASP ASVS 4.0. Inputs never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "qr-code-generator",
    name: "QR Code Generator",
    nameZh: "QR碼生成器",
    category: "developer",
    path: "/tools/developer/qr-code-generator",
    icon: "QrCode",
    description: "Browser-side QR code generator producing scalable SVG QR codes with adjustable error-correction level (L/M/Q/H) and module size, grounded in ISO/IEC 18004:2015 (QR Code 2005). A six-band density matrix grades QR complexity from short URLs to dense vCards, with capacity readouts per Reed-Solomon error level. Inputs never leave the browser.",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "markdown-to-html",
    name: "Markdown to HTML",
    nameZh: "Markdown 轉 HTML",
    description: "Convert CommonMark Markdown to clean HTML in your browser. 17-layer JsonFormatter gold template, Profile B (violet/purple).",
    category: "developer",
    icon: "FileText",
    path: "/tools/developer/markdown-to-html",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isFeatured: true,
    isNew: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "number-base-converter",
    name: "Number Base Converter",
    nameZh: "進位制轉換器",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal in your browser. 17-layer JsonFormatter gold template, Profile B (violet/purple).",
    category: "developer",
    icon: "Hash",
    path: "/tools/developer/number-base-converter",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isFeatured: true,
    isNew: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "tax-bracket-calculator",
    name: "稅率級距計算機",
    category: "finance",
    path: "/tools/finance/tax-bracket-calculator",
    icon: "Calculator",
    description: "輸入年收入、申報身分、扣除額與抵免額，估算邊際稅率、有效稅率與稅後所得。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "investment-return-calculator",
    name: "投資報酬率計算機",
    category: "finance",
    path: "/tools/finance/investment-return-calculator",
    icon: "Calculator",
    description: "輸入初始本金、月加碼、年化報酬與年限，立即得出複利後的未來價值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "break-even-calculator",
    name: "損益兩平計算機",
    category: "finance",
    path: "/tools/finance/break-even-calculator",
    icon: "Calculator",
    description: "輸入固定成本、單位售價、單位變動成本，立即算出回本所需銷量與營收門檻",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "currency-converter",
    name: "匯率換算計算機",
    category: "finance",
    path: "/tools/finance/currency-converter",
    icon: "Calculator",
    description: "輸入原幣金額與雙邊對美元的匯率，立即得出目標幣別的扣費後實得金額",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "stock-profit-calculator",
    name: "股票損益計算機",
    category: "finance",
    path: "/tools/finance/stock-profit-calculator",
    icon: "Calculator",
    description: "輸入買賣股價、股數與手續費，立即得出股票交易的總損益、報酬率與成本",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "rental-yield-calculator",
    name: "租金報酬率計算機",
    category: "finance",
    path: "/tools/finance/rental-yield-calculator",
    icon: "Calculator",
    description: "輸入房屋總價、月租金與年費用，立即算出毛淨租金報酬率與現金流",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "insurance-premium-calculator",
    name: "保費試算計算機",
    category: "finance",
    path: "/tools/finance/insurance-premium-calculator",
    icon: "Calculator",
    description: "輸入保額、年齡、年期與費率，立即估算年保費、月保費與總繳保費",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "pension-calculator",
    name: "退休金試算計算機",
    category: "finance",
    path: "/tools/finance/pension-calculator",
    icon: "Calculator",
    description: "輸入年齡、月薪與提撥率，立即試算退休時累積金額、月退金與薪資替代率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "bond-yield-calculator",
    name: "債券殖利率計算機",
    category: "finance",
    path: "/tools/finance/bond-yield-calculator",
    icon: "Calculator",
    description: "輸入面值、現價、票面利率與剩餘年限，立即估算到期殖利率與當期殖利率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "options-profit-calculator",
    name: "選擇權損益計算機",
    category: "finance",
    path: "/tools/finance/options-profit-calculator",
    icon: "Calculator",
    description: "輸入履約價、權利金、標的價與口數，即時試算 Call/Put 多頭損益與損益兩平點",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "dividend-yield-calculator",
    name: "股息殖利率計算機",
    category: "finance",
    path: "/tools/finance/dividend-yield-calculator",
    icon: "Calculator",
    description: "輸入股價、年度配息、持股數與配息成長率，立即估算殖利率、年領股息與 5 年 YOC",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "net-present-value-calculator",
    name: "淨現值計算機",
    category: "finance",
    path: "/tools/finance/net-present-value-calculator",
    icon: "Calculator",
    description: "輸入初始投資、年現金流、年限與折現率，立即計算 NPV、近似 IRR 與回收期",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "payback-period-calculator",
    name: "回收期計算機",
    category: "finance",
    path: "/tools/finance/payback-period-calculator",
    icon: "Calculator",
    description: "輸入初始投資、月現金流與成長率，立即計算簡單回收期與折現後回收期",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "cash-flow-calculator",
    name: "現金流計算機",
    category: "finance",
    path: "/tools/finance/cash-flow-calculator",
    icon: "Calculator",
    description: "輸入月收入與固定/變動支出，立即估算月淨現金流、儲蓄率與年度節餘",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "financial-ratio-calculator",
    name: "財務比率計算機",
    category: "finance",
    path: "/tools/finance/financial-ratio-calculator",
    icon: "Calculator",
    description: "輸入流動資產、流動負債、總負債、總權益，立即計算流動比率、負債權益比與槓桿指標",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "amortization-schedule-calculator",
    name: "攤還排程計算機",
    category: "finance",
    path: "/tools/finance/amortization-schedule-calculator",
    icon: "Calculator",
    description: "輸入貸款本金、利率與年限，立即估算每月還款、總利息與剩餘本金",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "capital-gains-tax-calculator",
    name: "資本利得稅計算機",
    category: "finance",
    path: "/tools/finance/capital-gains-tax-calculator",
    icon: "Calculator",
    description: "輸入買入價、賣出價、股數與稅率，立即估算資本利得稅與稅後淨利",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "sales-tax-calculator",
    name: "銷售稅計算機",
    category: "finance",
    path: "/tools/finance/sales-tax-calculator",
    icon: "Calculator",
    description: "輸入稅前金額、稅率與數量，立即算出銷售稅、含稅總額與每件含稅單價",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "tip-calculator",
    name: "小費計算機",
    category: "finance",
    path: "/tools/finance/tip-calculator",
    icon: "Calculator",
    description: "輸入帳單金額、小費比例與分攤人數，立即算出小費、總計與每人應付",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "discount-calculator",
    name: "折扣計算機",
    category: "finance",
    path: "/tools/finance/discount-calculator",
    icon: "Calculator",
    description: "輸入原價、折扣與數量，立即算出折後單價、總省金額與實際折扣",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "markup-calculator",
    name: "加成計算機",
    category: "finance",
    path: "/tools/finance/markup-calculator",
    icon: "Calculator",
    description: "輸入成本與加成百分比，立即算出建議售價、單位毛利與毛利率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "vat-calculator",
    name: "加值稅 VAT 計算機",
    category: "finance",
    path: "/tools/finance/vat-calculator",
    icon: "Calculator",
    description: "輸入淨額或含稅金額與 VAT 稅率，立即算出稅額、含稅總額與淨額",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "effective-annual-rate-calculator",
    name: "有效年利率計算機",
    category: "finance",
    path: "/tools/finance/effective-annual-rate-calculator",
    icon: "Calculator",
    description: "輸入名目年利率與複利次數，立即算出有效年利率(EAR)與終值",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "simple-interest-calculator",
    name: "簡單利息計算機",
    category: "finance",
    path: "/tools/finance/simple-interest-calculator",
    icon: "Calculator",
    description: "輸入本金、年利率與年數，立即算出單利利息與本利和",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "future-value-calculator",
    name: "終值計算機",
    category: "finance",
    path: "/tools/finance/future-value-calculator",
    icon: "Calculator",
    description: "輸入現值、年報酬率與年數，立即算出複利終值、總投入與總獲利",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "present-value-calculator",
    name: "現值計算機",
    category: "finance",
    path: "/tools/finance/present-value-calculator",
    icon: "Calculator",
    description: "輸入未來金額、折現率與年數，立即算出今天的現值與折現損失",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "annuity-calculator",
    name: "年金計算機",
    category: "finance",
    path: "/tools/finance/annuity-calculator",
    icon: "Calculator",
    description: "輸入每期投入、利率與年數，立即算出年金終值、總投入與利息收益",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "lease-vs-buy-calculator",
    name: "租賃 vs 購買計算機",
    category: "finance",
    path: "/tools/finance/lease-vs-buy-calculator",
    icon: "Calculator",
    description: "輸入購買總價、月租金、持有年數與殘值，立即比較租賃與購買的真實成本",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "refinance-calculator",
    name: "再融資計算機",
    category: "finance",
    path: "/tools/finance/refinance-calculator",
    icon: "Calculator",
    description: "輸入剩餘本金、原月付與新方案，立即算出新月付、每月省與全期節省",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "home-affordability-calculator",
    name: "購屋負擔能力計算機",
    category: "finance",
    path: "/tools/finance/home-affordability-calculator",
    icon: "Calculator",
    description: "輸入年收入、頭期款、房貸利率與既有債務，立即估算可負擔房價與每月房貸上限",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "student-loan-calculator",
    name: "學生貸款計算機",
    category: "finance",
    path: "/tools/finance/student-loan-calculator",
    icon: "Calculator",
    description: "輸入學貸總額、利率與還款年限,立即算出每月還款、總利息與利息佔本金比",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "auto-loan-calculator",
    name: "汽車貸款計算機",
    category: "finance",
    path: "/tools/finance/auto-loan-calculator",
    icon: "Calculator",
    description: "輸入車價、頭期款、利率與年限,立即算出每月還款、總利息與利息佔貸款比",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "down-payment-calculator",
    name: "頭期款計算機",
    category: "finance",
    path: "/tools/finance/down-payment-calculator",
    icon: "Calculator",
    description: "輸入房價、頭期比例與儲蓄進度,立即算出所需頭期、尚缺金額與達標月數",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "retirement-401k-calculator",
    name: "401k 退休帳戶計算機",
    category: "finance",
    path: "/tools/finance/retirement-401k-calculator",
    icon: "Calculator",
    description: "輸入年薪、提撥比例與雇主相對提撥,立即算出退休帳戶終值與雇主貢獻佔比",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "roth-ira-calculator",
    name: "Roth IRA 計算機",
    category: "finance",
    path: "/tools/finance/roth-ira-calculator",
    icon: "Calculator",
    description: "輸入每年提撥、報酬率與年數,立即算出 Roth IRA 終值、總提撥與免稅獲利佔比",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "sip-calculator",
    name: "定期定額計算機",
    category: "finance",
    path: "/tools/finance/sip-calculator",
    icon: "Calculator",
    description: "輸入每月投資、報酬率與年數,立即算出定期定額終值、總投入與獲利佔比",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "cd-calculator",
    name: "定存單計算機",
    category: "finance",
    path: "/tools/finance/cd-calculator",
    icon: "Calculator",
    description: "輸入本金、利率與存款期間,立即算出到期本利和、利息與有效年利率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "cap-rate-calculator",
    name: "資本化率計算機",
    category: "finance",
    path: "/tools/finance/cap-rate-calculator",
    icon: "Calculator",
    description: "輸入年租金、營運費用與物業總價,立即算出資本化率、淨營運收入與毛租金報酬率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "debt-snowball-calculator",
    name: "債務雪球計算機",
    category: "finance",
    path: "/tools/finance/debt-snowball-calculator",
    icon: "Calculator",
    description: "輸入總債務、平均利率與每月可還,立即算出還清月數、總利息與利息佔債務比",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "gross-margin-calculator",
    name: "毛利計算機",
    category: "finance",
    path: "/tools/finance/gross-margin-calculator",
    icon: "Calculator",
    description: "輸入營收與銷貨成本,立即算出毛利率、毛利金額與單位毛利",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "ebitda-calculator",
    name: "EBITDA 計算機",
    category: "finance",
    path: "/tools/finance/ebitda-calculator",
    icon: "Calculator",
    description: "輸入營收與營業費用,立即算出 EBITDA、EBITDA 利潤率與淨利",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "working-capital-calculator",
    name: "營運資金計算機",
    category: "finance",
    path: "/tools/finance/working-capital-calculator",
    icon: "Calculator",
    description: "輸入流動資產與流動負債,立即算出營運資金、流動比率與速動比率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "quick-ratio-calculator",
    name: "速動比率計算機",
    category: "finance",
    path: "/tools/finance/quick-ratio-calculator",
    icon: "Calculator",
    description: "輸入現金、應收帳款與流動負債,立即算出速動比率、流動比率與現金比率",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "roi-payback-calculator",
    name: "ROI 回本計算機",
    category: "finance",
    path: "/tools/finance/roi-payback-calculator",
    icon: "Calculator",
    description: "輸入初始投資與每年淨收益,立即算出投資報酬率、回本年數與淨獲利",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "burn-rate-calculator",
    name: "燒錢速率計算機",
    category: "finance",
    path: "/tools/finance/burn-rate-calculator",
    icon: "Calculator",
    description: "輸入目前現金、每月支出與收入,立即算出現金跑道、淨燒錢率與距目標差距",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "withdrawal-rate-calculator",
    name: "安全提領率計算機",
    category: "finance",
    path: "/tools/finance/withdrawal-rate-calculator",
    icon: "Calculator",
    description: "輸入退休投資組合、提領率與報酬率,立即算出年度與每月可提領金額、期末餘額與耗盡風險",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "coast-fire-calculator",
    name: "Coast FIRE 計算機",
    category: "finance",
    path: "/tools/finance/coast-fire-calculator",
    icon: "Calculator",
    description: "估算現有本金在不再追加下,複利至退休年齡的資產規模與滑行狀態。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "fire-number-calculator",
    name: "FIRE 目標數字計算機",
    category: "finance",
    path: "/tools/finance/fire-number-calculator",
    icon: "Calculator",
    description: "以安全提領率回推財務自由所需資產,評估目前進度與達標年數。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "social-security-calculator",
    name: "社會安全退休金估算機",
    category: "finance",
    path: "/tools/finance/social-security-calculator",
    icon: "Calculator",
    description: "依提早或延後請領規則,估算社會安全退休金的月給付與長期累計。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "roth-conversion-calculator",
    name: "Roth 轉換稅務試算機",
    category: "finance",
    path: "/tools/finance/roth-conversion-calculator",
    icon: "Calculator",
    description: "估算 Roth 轉換的當年稅負、免稅成長價值與長期稅務節省。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "ltv-ratio-calculator",
    name: "貸款成數 LTV 計算機",
    category: "finance",
    path: "/tools/finance/ltv-ratio-calculator",
    icon: "Calculator",
    description: "計算貸款成數、自有權益與距目標 LTV 的可貸空間。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "home-equity-calculator",
    name: "房屋淨值計算機",
    category: "finance",
    path: "/tools/finance/home-equity-calculator",
    icon: "Calculator",
    description: "計算房屋淨值、淨值比例與 HELOC 可借額度。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "rent-vs-buy-calculator",
    name: "租屋 vs 購屋計算機",
    category: "finance",
    path: "/tools/finance/rent-vs-buy-calculator",
    icon: "Calculator",
    description: "在相同期間內比較租屋與購屋的總成本,找出較划算的選項。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "closing-cost-calculator",
    name: "成交費用計算機",
    category: "finance",
    path: "/tools/finance/closing-cost-calculator",
    icon: "Calculator",
    description: "估算房屋交割的總成交費用與成交所需準備現金。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "property-tax-calculator",
    name: "房產稅計算機",
    category: "finance",
    path: "/tools/finance/property-tax-calculator",
    icon: "Calculator",
    description: "依估值、評估比例與減免,估算年度與每月房產稅。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "capital-gains-calculator",
    name: "資本利得計算機",
    category: "finance",
    path: "/tools/finance/capital-gains-calculator",
    icon: "Calculator",
    description: "計算資本利得、長短期分類與稅後淨收金額。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "estate-tax-calculator",
    name: "遺產稅計算機",
    category: "finance",
    path: "/tools/finance/estate-tax-calculator",
    icon: "Calculator",
    description: "依免稅額與扣除項目,估算聯邦遺產稅與繼承人實得淨額。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "tax-withholding-calculator",
    name: "薪資預扣稅計算機",
    category: "finance",
    path: "/tools/finance/tax-withholding-calculator",
    icon: "Calculator",
    description: "比較全年預扣稅與預估稅負,估算退稅或補稅金額。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "tax-loss-harvesting",
    name: "稅損收割計算機",
    category: "finance",
    path: "/tools/finance/tax-loss-harvesting",
    icon: "Calculator",
    description: "估算以資本虧損抵減利得與一般所得後的節稅金額與結轉。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "purchasing-power-calculator",
    name: "購買力計算機",
    category: "finance",
    path: "/tools/finance/purchasing-power-calculator",
    icon: "Calculator",
    description: "計算通膨侵蝕後的未來實質購買力與流失比例。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "pe-ratio-calculator",
    name: "本益比計算機",
    category: "finance",
    path: "/tools/finance/pe-ratio-calculator",
    icon: "Calculator",
    description: "由股價與每股盈餘計算本益比、盈餘殖利率與合理股價。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "eps-calculator",
    name: "每股盈餘計算機",
    category: "finance",
    path: "/tools/finance/eps-calculator",
    icon: "Calculator",
    description: "由淨利與股數計算每股盈餘、本益比與盈餘殖利率。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "sharpe-ratio-calculator",
    name: "夏普比率計算機",
    category: "finance",
    path: "/tools/finance/sharpe-ratio-calculator",
    icon: "Calculator",
    description: "由報酬率、無風險利率與波動度計算風險調整後的夏普比率。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "beta-calculator",
    name: "Beta 係數計算機",
    category: "finance",
    path: "/tools/finance/beta-calculator",
    icon: "Calculator",
    description: "由共變異數與市場變異數計算股票的系統性風險與預期報酬。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "capm-calculator",
    name: "CAPM 資本資產定價計算機",
    category: "finance",
    path: "/tools/finance/capm-calculator",
    icon: "Calculator",
    description: "由無風險利率、Beta 與市場報酬計算資產的預期必要報酬率。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "price-to-book-calculator",
    name: "股價淨值比計算機",
    category: "finance",
    path: "/tools/finance/price-to-book-calculator",
    icon: "Calculator",
    description: "由每股市價與每股淨值計算股價淨值比與合理股價區間。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "book-value-calculator",
    name: "每股淨值計算機",
    category: "finance",
    path: "/tools/finance/book-value-calculator",
    icon: "Calculator",
    description: "由股東權益、特別股與股數計算普通股每股淨值與市價溢價。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "risk-tolerance-calculator",
    name: "風險承受度計算機",
    category: "finance",
    path: "/tools/finance/risk-tolerance-calculator",
    icon: "Calculator",
    description: "由年齡、年限、可承受跌幅與備用金評估風險承受度與配置建議。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "real-return-calculator",
    name: "實質報酬率計算機",
    category: "finance",
    path: "/tools/finance/real-return-calculator",
    icon: "Calculator",
    description: "由名目報酬、通膨率與稅率計算扣除通膨後的真實購買力成長。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "portfolio-rebalance-calculator",
    name: "投資組合再平衡計算機",
    category: "finance",
    path: "/tools/finance/portfolio-rebalance-calculator",
    icon: "Calculator",
    description: "由組合總值、股票市值與目標比重計算再平衡所需的交易金額。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
  {
    id: "dollar-cost-averaging",
    name: "定期定額投資計算機",
    category: "finance",
    path: "/tools/finance/dollar-cost-averaging",
    icon: "Calculator",
    description: "由每月投入、期間與報酬率計算定期定額的期末總資產與獲利。",
    isPremium: false,
    showAds: true,
    rateLimit: 30,
    isNew: true,
    isFeatured: true,
    status: "GOLD",
    seoArticles: [],
  },
];

// ============================================================
// 工具查詢函數
// ============================================================
export function getToolByPath(path: string): Tool | undefined {
  return tools.find((tool) => tool.path === path);
}

export function getToolsByCategory(category: string): Tool[] {
  return tools.filter((tool) => tool.category === category);
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

export function getAllTools(): Tool[] {
  return tools;
}

export function getFeaturedTools(): Tool[] {
  return tools.filter((tool) => tool.isFeatured);
}

export function getNewTools(): Tool[] {
  return tools.filter((tool) => tool.isNew);
}

// Health Tools
export const bmiCalculator = { id: "bmi-calculator", category: "health", name: "BMI Calculator", path: "/tools/health/bmi-calculator" };
export const bmrCalculator = { id: "bmr-calculator", category: "health", name: "BMR Calculator", path: "/tools/health/bmr-calculator" };
export const tdeeCalculator = { id: "tdee-calculator", category: "health", name: "TDEE Calculator", path: "/tools/health/tdee-calculator" };
export const idealWeightCalculator = { id: "ideal-weight-calculator", category: "health", name: "Ideal Weight Calculator", path: "/tools/health/ideal-weight-calculator" };
export const bodyFatCalculator = { id: "body-fat-calculator", category: "health", name: "Body Fat Calculator", path: "/tools/health/body-fat-calculator" };
export const calorieDeficitCalculator = { id: "calorie-deficit-calculator", category: "health", name: "Calorie Deficit Calculator", path: "/tools/health/calorie-deficit-calculator" };
export const waterIntakeCalculator = { id: "water-intake-calculator", category: "health", name: "Water Intake Calculator", path: "/tools/health/water-intake-calculator" };
export const macroCalculator = { id: "macro-calculator", category: "health", name: "Macro Calculator", path: "/tools/health/macro-calculator" };

// Finance Tools
export const loanCalculator = { id: "loan-calculator", category: "finance", name: "Loan Calculator", path: "/tools/finance/loan-calculator" };
export const mortgageCalculator = { id: "mortgage-calculator", category: "finance", name: "Mortgage Calculator", path: "/tools/finance/mortgage-calculator" };
export const creditCardPayoffCalculator = { id: "credit-card-payoff-calculator", category: "finance", name: "Credit Card Payoff Calculator", path: "/tools/finance/credit-card-payoff-calculator" };
export const debtToIncomeCalculator = { id: "debt-to-income-calculator", category: "finance", name: "Debt-to-Income Calculator", path: "/tools/finance/debt-to-income-calculator" };
export const compoundInterestCalculator = { id: "compound-interest-calculator", category: "finance", name: "Compound Interest Calculator", path: "/tools/finance/compound-interest-calculator" };
export const retirementCalculator = { id: "retirement-calculator", category: "finance", name: "Retirement Calculator", path: "/tools/finance/retirement-calculator" };
export const cagrCalculator = { id: "cagr-calculator", category: "finance", name: "CAGR Calculator", path: "/tools/finance/cagr-calculator" };
export const savingsGoalCalculator = { id: "savings-goal-calculator", category: "finance", name: "Savings Goal Calculator", path: "/tools/finance/savings-goal-calculator" };
export const inflationAdjuster = { id: "inflation-adjuster", category: "finance", name: "Inflation Adjuster", path: "/tools/finance/inflation-adjuster" };
export const netWorthCalculator = { id: "net-worth-calculator", category: "finance", name: "Net Worth Calculator", path: "/tools/finance/net-worth-calculator" };
export const debtPayoffCalculator = { id: "debt-payoff-calculator", category: "finance", name: "Debt Payoff Calculator", path: "/tools/finance/debt-payoff-calculator" };
export const budgetRatioCalculator = { id: "budget-ratio-calculator", category: "finance", name: "Budget Ratio Calculator", path: "/tools/finance/budget-ratio-calculator" };
export const emergencyFundCalculator = { id: "emergency-fund-calculator", category: "finance", name: "Emergency Fund Calculator", path: "/tools/finance/emergency-fund-calculator" };
export const salaryAfterTaxCalculator = { id: "salary-after-tax-calculator", category: "finance", name: "Salary After Tax Calculator", path: "/tools/finance/salary-after-tax-calculator" };
export const hourlyRateCalculator = { id: "hourly-rate-calculator", category: "finance", name: "Hourly Rate Calculator", path: "/tools/finance/hourly-rate-calculator" };
export const meetingCostCalculator = { id: "meeting-cost-calculator", category: "finance", name: "Meeting Cost Calculator", path: "/tools/finance/meeting-cost-calculator" };
export const pomodoroCalculator = { id: "pomodoro-calculator", category: "finance", name: "Pomodoro Calculator", path: "/tools/finance/pomodoro-calculator" };
export const profitMarginCalculator = { id: "profit-margin-calculator", category: "finance", name: "Profit Margin Calculator", path: "/tools/finance/profit-margin-calculator" };
export const roasCalculator = { id: "roas-calculator", category: "finance", name: "ROAS Calculator", path: "/tools/finance/roas-calculator" };

// Productivity Tools
export const pomodoroPlanner = { id: "pomodoro-planner", category: "productivity", name: "Pomodoro Planner", path: "/tools/productivity/pomodoro-planner" };
export const timeZoneConverter = { id: "time-zone-converter", category: "productivity", name: "Time Zone Converter", path: "/tools/productivity/time-zone-converter" };
export const wordCounter = { id: "word-counter", category: "productivity", name: "Word Counter", path: "/tools/productivity/word-counter" };
export const dateDurationCalculator = { id: "date-duration-calculator", category: "productivity", name: "Date Duration Calculator", path: "/tools/productivity/date-duration-calculator" };
export const ageCalculator = { id: "age-calculator", category: "productivity", name: "Age Calculator", path: "/tools/productivity/age-calculator" };
export const jsonFormatter = { id: "json-formatter", category: "developer", name: "JSON Formatter", path: "/tools/developer/json-formatter" };
export const base64Encoder = { id: "base64-encoder", category: "developer", name: "Base64 Encoder", path: "/tools/developer/base64-encoder" };
export const urlEncoder = { id: "url-encoder", category: "developer", name: "URL Encoder", path: "/tools/developer/url-encoder" };
export const regexTester = { id: "regex-tester", category: "developer", name: "Regex Tester", path: "/tools/developer/regex-tester" };
export const colorConverter = { id: "color-converter", category: "developer", name: "Color Converter", path: "/tools/developer/color-converter" };
export const timestampConverter = { id: "timestamp-converter", category: "developer", name: "Timestamp Converter", path: "/tools/developer/timestamp-converter" };
export const markdownPreview = { id: "markdown-preview", category: "developer", name: "Markdown Preview", path: "/tools/developer/markdown-preview" };
export const diffChecker = { id: "diff-checker", category: "developer", name: "Diff Checker", path: "/tools/developer/diff-checker" };
export const csvToJson = { id: "csv-to-json", category: "developer", name: "CSV to JSON Converter", path: "/tools/developer/csv-to-json" };
export const hashGenerator = { id: "hash-generator", category: "developer", name: "Hash Generator", path: "/tools/developer/hash-generator" };
export const htmlEncoder = { id: "html-encoder", category: "developer", name: "HTML Encoder", path: "/tools/developer/html-encoder" };
export const jwtDecoder = { id: "jwt-decoder", category: "developer", name: "JWT Decoder", path: "/tools/developer/jwt-decoder" };
export const gpaCalculator = { id: "gpa-calculator", category: "education", name: "GPA Calculator", path: "/tools/education/gpa-calculator" };
export const gradeCalculator = { id: "grade-calculator", category: "education", name: "Grade Calculator", path: "/tools/education/grade-calculator" };
export const studyTimeCalculator = { id: "study-time-calculator", category: "education", name: "Study Time Calculator", path: "/tools/education/study-time-calculator" };
export const mathPercentageCalculator = { id: "math-percentage-calculator", category: "education", name: "Math Percentage Calculator", path: "/tools/education/math-percentage-calculator" };
export const cronExpression = { id: "cron-expression", category: "developer", name: "Cron Expression Parser", path: "/tools/developer/cron-expression" };
export const ipCalculator = { id: "ip-calculator", category: "developer", name: "IP / CIDR Calculator", path: "/tools/developer/ip-calculator" };
export const colorPaletteGenerator = { id: "color-palette-generator", category: "developer", name: "Color Palette Generator", path: "/tools/developer/color-palette-generator" };
export const passwordGenerator = { id: "password-generator", category: "developer", name: "Password Generator", path: "/tools/developer/password-generator" };
export const qrCodeGenerator = { id: "qr-code-generator", category: "developer", name: "QR Code Generator", path: "/tools/developer/qr-code-generator" };
export const markdownToHtml = { id: "markdown-to-html", category: "developer", name: "Markdown to HTML", path: "/tools/developer/markdown-to-html" };
export const numberBaseConverter = { id: "number-base-converter", category: "developer", name: "Number Base Converter", path: "/tools/developer/number-base-converter" };
export const taxBracketCalculator = { id: "tax-bracket-calculator", category: "finance", name: "Tax Bracket Calculator", path: "/tools/finance/tax-bracket-calculator" };
export const investmentReturnCalculator = { id: "investment-return-calculator", category: "finance", name: "Investment Return Calculator", path: "/tools/finance/investment-return-calculator" };
export const breakEvenCalculator = { id: "break-even-calculator", category: "finance", name: "Break-Even Calculator", path: "/tools/finance/break-even-calculator" };
export const currencyConverter = { id: "currency-converter", category: "finance", name: "Currency Converter", path: "/tools/finance/currency-converter" };
export const stockProfitCalculator = { id: "stock-profit-calculator", category: "finance", name: "Stock Profit Calculator", path: "/tools/finance/stock-profit-calculator" };
export const rentalYieldCalculator = { id: "rental-yield-calculator", category: "finance", name: "Rental Yield Calculator", path: "/tools/finance/rental-yield-calculator" };
export const insurancePremiumCalculator = { id: "insurance-premium-calculator", category: "finance", name: "Insurance Premium Calculator", path: "/tools/finance/insurance-premium-calculator" };
export const pensionCalculator = { id: "pension-calculator", category: "finance", name: "Pension Calculator", path: "/tools/finance/pension-calculator" };
export const bondYieldCalculator = { id: "bond-yield-calculator", category: "finance", name: "Bond Yield Calculator", path: "/tools/finance/bond-yield-calculator" };
export const optionsProfitCalculator = { id: "options-profit-calculator", category: "finance", name: "Options Profit Calculator", path: "/tools/finance/options-profit-calculator" };
export const dividendYieldCalculator = { id: "dividend-yield-calculator", category: "finance", name: "Dividend Yield Calculator", path: "/tools/finance/dividend-yield-calculator" };
export const netPresentValueCalculator = { id: "net-present-value-calculator", category: "finance", name: "Net Present Value Calculator", path: "/tools/finance/net-present-value-calculator" };
export const paybackPeriodCalculator = { id: "payback-period-calculator", category: "finance", name: "Payback Period Calculator", path: "/tools/finance/payback-period-calculator" };
export const cashFlowCalculator = { id: "cash-flow-calculator", category: "finance", name: "Cash Flow Calculator", path: "/tools/finance/cash-flow-calculator" };
export const financialRatioCalculator = { id: "financial-ratio-calculator", category: "finance", name: "Financial Ratio Calculator", path: "/tools/finance/financial-ratio-calculator" };
export const amortizationScheduleCalculator = { id: "amortization-schedule-calculator", category: "finance", name: "Amortization Schedule Calculator", path: "/tools/finance/amortization-schedule-calculator" };
export const capitalGainsTaxCalculator = { id: "capital-gains-tax-calculator", category: "finance", name: "Capital Gains Tax Calculator", path: "/tools/finance/capital-gains-tax-calculator" };
export const salesTaxCalculator = { id: "sales-tax-calculator", category: "finance", name: "Sales Tax Calculator", path: "/tools/finance/sales-tax-calculator" };
export const tipCalculator = { id: "tip-calculator", category: "finance", name: "Tip Calculator", path: "/tools/finance/tip-calculator" };
export const discountCalculator = { id: "discount-calculator", category: "finance", name: "Discount Calculator", path: "/tools/finance/discount-calculator" };
export const markupCalculator = { id: "markup-calculator", category: "finance", name: "Markup Calculator", path: "/tools/finance/markup-calculator" };
export const vatCalculator = { id: "vat-calculator", category: "finance", name: "VAT Calculator", path: "/tools/finance/vat-calculator" };
export const effectiveAnnualRateCalculator = { id: "effective-annual-rate-calculator", category: "finance", name: "Effective Annual Rate Calculator", path: "/tools/finance/effective-annual-rate-calculator" };
export const simpleInterestCalculator = { id: "simple-interest-calculator", category: "finance", name: "Simple Interest Calculator", path: "/tools/finance/simple-interest-calculator" };
export const futureValueCalculator = { id: "future-value-calculator", category: "finance", name: "Future Value Calculator", path: "/tools/finance/future-value-calculator" };
export const presentValueCalculator = { id: "present-value-calculator", category: "finance", name: "Present Value Calculator", path: "/tools/finance/present-value-calculator" };
export const annuityCalculator = { id: "annuity-calculator", category: "finance", name: "Annuity Calculator", path: "/tools/finance/annuity-calculator" };
export const leaseVsBuyCalculator = { id: "lease-vs-buy-calculator", category: "finance", name: "Lease vs Buy Calculator", path: "/tools/finance/lease-vs-buy-calculator" };
export const refinanceCalculator = { id: "refinance-calculator", category: "finance", name: "Refinance Calculator", path: "/tools/finance/refinance-calculator" };
export const homeAffordabilityCalculator = { id: "home-affordability-calculator", category: "finance", name: "Home Affordability Calculator", path: "/tools/finance/home-affordability-calculator" };
export const studentLoanCalculator = { id: "student-loan-calculator", category: "finance", name: "Student Loan Calculator", path: "/tools/finance/student-loan-calculator" };
export const autoLoanCalculator = { id: "auto-loan-calculator", category: "finance", name: "Auto Loan Calculator", path: "/tools/finance/auto-loan-calculator" };
export const downPaymentCalculator = { id: "down-payment-calculator", category: "finance", name: "Down Payment Calculator", path: "/tools/finance/down-payment-calculator" };
export const retirement401kCalculator = { id: "retirement-401k-calculator", category: "finance", name: "401k Retirement Calculator", path: "/tools/finance/retirement-401k-calculator" };
export const rothIraCalculator = { id: "roth-ira-calculator", category: "finance", name: "Roth IRA Calculator", path: "/tools/finance/roth-ira-calculator" };
export const sipCalculator = { id: "sip-calculator", category: "finance", name: "SIP Calculator", path: "/tools/finance/sip-calculator" };
export const cdCalculator = { id: "cd-calculator", category: "finance", name: "CD Calculator", path: "/tools/finance/cd-calculator" };
export const capRateCalculator = { id: "cap-rate-calculator", category: "finance", name: "Cap Rate Calculator", path: "/tools/finance/cap-rate-calculator" };
export const debtSnowballCalculator = { id: "debt-snowball-calculator", category: "finance", name: "Debt Snowball Calculator", path: "/tools/finance/debt-snowball-calculator" };
export const grossMarginCalculator = { id: "gross-margin-calculator", category: "finance", name: "Gross Margin Calculator", path: "/tools/finance/gross-margin-calculator" };
export const ebitdaCalculator = { id: "ebitda-calculator", category: "finance", name: "EBITDA Calculator", path: "/tools/finance/ebitda-calculator" };
export const workingCapitalCalculator = { id: "working-capital-calculator", category: "finance", name: "Working Capital Calculator", path: "/tools/finance/working-capital-calculator" };
export const quickRatioCalculator = { id: "quick-ratio-calculator", category: "finance", name: "Quick Ratio Calculator", path: "/tools/finance/quick-ratio-calculator" };
export const roiPaybackCalculator = { id: "roi-payback-calculator", category: "finance", name: "ROI Payback Calculator", path: "/tools/finance/roi-payback-calculator" };
export const burnRateCalculator = { id: "burn-rate-calculator", category: "finance", name: "Burn Rate Calculator", path: "/tools/finance/burn-rate-calculator" };
export const withdrawalRateCalculator = { id: "withdrawal-rate-calculator", category: "finance", name: "Safe Withdrawal Rate Calculator", path: "/tools/finance/withdrawal-rate-calculator" };
export const coastFireCalculator = { id: "coast-fire-calculator", category: "finance", name: "Coast FIRE Calculator", path: "/tools/finance/coast-fire-calculator" };
export const fireNumberCalculator = { id: "fire-number-calculator", category: "finance", name: "FIRE Number Calculator", path: "/tools/finance/fire-number-calculator" };
export const socialSecurityCalculator = { id: "social-security-calculator", category: "finance", name: "Social Security Calculator", path: "/tools/finance/social-security-calculator" };
export const rothConversionCalculator = { id: "roth-conversion-calculator", category: "finance", name: "Roth Conversion Calculator", path: "/tools/finance/roth-conversion-calculator" };
export const ltvRatioCalculator = { id: "ltv-ratio-calculator", category: "finance", name: "LTV Ratio Calculator", path: "/tools/finance/ltv-ratio-calculator" };
export const homeEquityCalculator = { id: "home-equity-calculator", category: "finance", name: "Home Equity Calculator", path: "/tools/finance/home-equity-calculator" };
export const rentVsBuyCalculator = { id: "rent-vs-buy-calculator", category: "finance", name: "Rent vs Buy Calculator", path: "/tools/finance/rent-vs-buy-calculator" };
export const closingCostCalculator = { id: "closing-cost-calculator", category: "finance", name: "Closing Cost Calculator", path: "/tools/finance/closing-cost-calculator" };
export const propertyTaxCalculator = { id: "property-tax-calculator", category: "finance", name: "Property Tax Calculator", path: "/tools/finance/property-tax-calculator" };
export const capitalGainsCalculator = { id: "capital-gains-calculator", category: "finance", name: "Capital Gains Calculator", path: "/tools/finance/capital-gains-calculator" };
export const estateTaxCalculator = { id: "estate-tax-calculator", category: "finance", name: "Estate Tax Calculator", path: "/tools/finance/estate-tax-calculator" };
export const taxWithholdingCalculator = { id: "tax-withholding-calculator", category: "finance", name: "Tax Withholding Calculator", path: "/tools/finance/tax-withholding-calculator" };
export const taxLossHarvesting = { id: "tax-loss-harvesting", category: "finance", name: "Tax Loss Harvesting Calculator", path: "/tools/finance/tax-loss-harvesting" };
export const purchasingPowerCalculator = { id: "purchasing-power-calculator", category: "finance", name: "Purchasing Power Calculator", path: "/tools/finance/purchasing-power-calculator" };
export const peRatioCalculator = { id: "pe-ratio-calculator", category: "finance", name: "P/E Ratio Calculator", path: "/tools/finance/pe-ratio-calculator" };
export const epsCalculator = { id: "eps-calculator", category: "finance", name: "EPS Calculator", path: "/tools/finance/eps-calculator" };
export const sharpeRatioCalculator = { id: "sharpe-ratio-calculator", category: "finance", name: "Sharpe Ratio Calculator", path: "/tools/finance/sharpe-ratio-calculator" };
export const betaCalculator = { id: "beta-calculator", category: "finance", name: "Beta Calculator", path: "/tools/finance/beta-calculator" };
export const capmCalculator = { id: "capm-calculator", category: "finance", name: "CAPM Calculator", path: "/tools/finance/capm-calculator" };
export const priceToBookCalculator = { id: "price-to-book-calculator", category: "finance", name: "Price-to-Book Ratio Calculator", path: "/tools/finance/price-to-book-calculator" };
export const bookValueCalculator = { id: "book-value-calculator", category: "finance", name: "Book Value Calculator", path: "/tools/finance/book-value-calculator" };
export const riskToleranceCalculator = { id: "risk-tolerance-calculator", category: "finance", name: "Risk Tolerance Calculator", path: "/tools/finance/risk-tolerance-calculator" };
export const realReturnCalculator = { id: "real-return-calculator", category: "finance", name: "Real Return Calculator", path: "/tools/finance/real-return-calculator" };
export const portfolioRebalanceCalculator = { id: "portfolio-rebalance-calculator", category: "finance", name: "Portfolio Rebalance Calculator", path: "/tools/finance/portfolio-rebalance-calculator" };
export const dollarCostAveraging = { id: "dollar-cost-averaging", category: "finance", name: "Dollar-Cost Averaging Calculator", path: "/tools/finance/dollar-cost-averaging" };
