import { readFileSync, writeFileSync } from "fs";
import { join } from "path";

interface RegistryTool {
  canonical_id: string;
  slug: string;
  website_key: string;
  status: string;
}

interface Registry {
  tools: RegistryTool[];
}

function generateRoutes() {
  // 讀取 registry
  const registryPath = join(process.cwd(), "docs/tool-registry.json");
  const registry: Registry = JSON.parse(readFileSync(registryPath, "utf-8").replace(/^\uFEFF/, ""));

  // 只處理 active 狀態的工具
  const activeTools = registry.tools.filter(t => t.status === "active");

  // 生成 ComponentName（slug 轉 PascalCase）
  function toPascalCase(slug: string): string {
    return slug.split("-").map(w => w.charAt(0).toUpperCase() + w.slice(1)).join("");
  }

  // 生成 import 行
  const importLines = activeTools.map(tool => {
    const componentName = toPascalCase(tool.slug);
    const importPath = `@/tools/${tool.website_key}/${componentName}`;
    const routeKey = `${tool.website_key}/${tool.slug}`;
    return `  "${routeKey}": lazy(() => import("${importPath}")),`;
  });

  // 生成完整的 toolComponentMap
  const output = `// AUTO-GENERATED BY scripts/generate-routes.ts
// DO NOT EDIT MANUALLY
// Last generated: ${new Date().toISOString()}

import { lazy } from "react";

export const toolComponentMap: Record<string, React.LazyExoticComponent<any>> = {
${importLines.join("\n")}
};
`;

  // 寫入檔案
  const outputPath = join(process.cwd(), "client/src/generated/toolComponentMap.ts");
  writeFileSync(outputPath, output, "utf-8");

  console.log(`✅ 生成 ${activeTools.length} 個路由`);
  console.log(`📁 輸出：client/src/generated/toolComponentMap.ts`);
}

generateRoutes();
