from pathlib import Path
p=Path('client/src/tools/finance/MeetingCostCalculator/index.tsx')
s=p.read_text()
repls={
'enterValues: "輸入薪資與工時資訊"':'enterValues: "輸入會議人數、時長與頻率"',
'baselineExample: "一般薪資 · $75k"':'baselineExample: "標準會議 · 8 人"',
'activeExample: "高薪型"':'activeExample: "大型會議"',
'conversionNote: "L9 會連動目前計算結果，顯示會議成本、月薪等價與儲蓄提示。"':'conversionNote: "L9 會連動目前計算結果，顯示單場成本、月成本與年度會議成本，協助判斷是否需要縮短、合併或改成非同步。"',
'dailyGap: "日薪", weeklyTrend: "會議成本"':'dailyGap: "年成本", weeklyTrend: "單場成本"',
'journeyHint: "每次調薪或換工作時重新計算，追蹤會議成本成長。"':'journeyHint: "每次調整團隊規模、會議頻率或決策流程時重新計算，追蹤會議成本是否下降。"',
'nextActionItem1: "用稅後薪資計算機了解扣稅後的實際到手"':'nextActionItem1: "用稅後薪資計算機估算參與者稅後薪資基礎"',
'nextActionItem2: "用預算比例計算機規劃到手薪資分配"':'nextActionItem2: "用預算比例計算機評估會議成本對團隊預算的占比"',
'nextActionItem3: "用淨資產計算機檢視整體財務健康"':'nextActionItem3: "用淨資產計算機檢視決策延誤對長期資產的影響"',
'definitionText: "會議成本是將總薪資除以實際工作時數得出的每小時收入，反映工作時間的真實價值。"':'definitionText: "會議成本是把參與者的人力時間轉換成金額，常用於判斷會議是否值得召開、是否需要縮短，或是否可改成文件與非同步更新。"',
'limitationsText: "假設固定工時與薪資；未計算加班費、獎金、非現金福利或自僱稅負差異。"':'limitationsText: "本工具只估算直接人力成本；未納入準備時間、會後追蹤、機會成本、會議室、差旅、工具費與決策品質差異。"',
'interpretationText: "會議成本 $20–40 為一般白領常見範圍；超過 $60 代表高專業度或管理職位。"':'interpretationText: "單場成本低不代表會議有效；單場成本高也不一定應取消。關鍵是是否產生決策、解除阻塞或創造高於成本的價值。"',
'contextText: "會議成本應搭配稅後薪資、預算比例與淨資產一起看。"':'contextText: "會議成本應搭配團隊目標、決策速度、專案價值與替代溝通方式一起看，而不是只看單次金額。"',
'premiumText: "解鎖會議成本成長趨勢圖、同行比較、自由職業估算與個人化收入報告。"':'premiumText: "解鎖會議成本趨勢、部門比較、非同步替代建議與團隊會議成本報告。"',
'張貼': '張貼',
'q1: "會議成本和月薪哪個更準確？", a1: "會議成本更精確地反映工作價值，因為它考慮了實際工作時數，包括加班與休假差異。"':'q1: "會議成本應該看單場還是每月？", a1: "兩者都重要。單場成本能判斷一次會議是否值得；每月成本能看出例行會議是否長期消耗太多團隊時間。"',
'q2: "為什麼我的實際會議成本比帳面低？", a2: "如果經常無償加班，實際工時比合約工時多，會議成本就會被稀釋。計算時應包含所有工作時間。"':'q2: "平均時薪要怎麼估？", a2: "可用年薪除以年度工作時數，或用團隊中位時薪估算。若參與者薪資差異很大，建議分角色估算後加總。"',
'q3: "自由工作者怎麼算會議成本？", a3: "自由工作者的會議成本 = 專案收入 ÷ 專案總時數（含溝通、修改時間）。還需額外扣除自僱稅與業務成本。"':'q3: "要把準備時間也算進去嗎？", a3: "如果會議需要預讀、製作簡報或會後整理，應另外估算準備與追蹤成本。本工具預設只計算會議進行中的人力成本。"',
'q4: "加班費如何影響會議成本？", a4: "有償加班（1.5x 或 2x）會提高加權會議成本；無償加班則降低實際會議成本。計算時應分開考量。"':'q4: "什麼時候應該取消或縮短會議？", a4: "若會議沒有明確議程、決策者不在場、只是單向更新，或成本高於可產生的價值，通常可改成文件、錄影或非同步討論。"',
'q5: "兼職或多份工作的會議成本怎麼算？", a5: "分別計算每份工作的會議成本，再以收入加權平均。高會議成本工作應優先投入時間。"':'q5: "會議成本越低越好嗎？", a5: "不一定。低成本但頻率過高仍會拖慢團隊；高成本但能快速做出高價值決策，反而可能值得保留。"',
'q6: "這個工具能提供薪資談判或職涯建議嗎？", a6: "不能。它只是教育用估算；若需薪資談判、職涯規劃或勞動權益，請諮詢專業人員。"':'q6: "這個工具能取代管理決策嗎？", a6: "不能。它只是教育與規劃用估算；實際會議設計仍應考量團隊文化、決策風險、專案價值與必要協作。"',
'Enter salary and work hours':'Enter meeting size, duration, and frequency',
'Rate preview':'Per-meeting preview',
'Create an meeting cost example instantly':'Create a meeting cost example instantly',
'Fill high-salary example':'Fill large-meeting example',
'Start with an example to understand meeting cost calculation, then replace with your own numbers.':'Start with an example to understand meeting cost calculation, then replace with your own meeting numbers.',
'Median salary · $75k':'Standard meeting · 8 people',
'High-salary type':'Large meeting',
'This calculation assumes standard work hours; actual meeting cost is affected by overtime, bonuses, and non-cash benefits.':'This tool estimates direct people cost only; it excludes prep time, opportunity cost, room cost, tools, and follow-up work.',
'conversionNote: "L9 values update from the computed result: meeting cost, monthly equivalent, and savings hints."':'conversionNote: "L9 values update from the computed result: per-meeting cost, monthly cost, and annual meeting load."',
'dailyGap: "Daily rate", weeklyTrend: "Meeting cost"':'dailyGap: "Annual cost", weeklyTrend: "Per-meeting cost"',
'journeyHint: "Re-calculate after every raise or job change to track meeting cost growth."':'journeyHint: "Re-calculate whenever attendee count, meeting frequency, or decision process changes."',
'definitionText: "Meeting cost is total compensation divided by actual hours worked, reflecting the true value of your work time."':'definitionText: "Meeting cost converts attendee time into money so teams can decide whether a meeting should happen, be shortened, or move to async updates."',
'limitationsText: "Assumes fixed hours and salary; does not account for overtime pay, bonuses, non-cash benefits, or self-employment tax differences."':'limitationsText: "Estimates direct people cost only; excludes prep time, follow-up, opportunity cost, room cost, travel, tools, and decision quality differences."',
'interpretationText: "An meeting cost of $20–40 is common for white-collar workers; above $60 indicates high expertise or management roles."':'interpretationText: "Low cost does not guarantee value, and high cost does not automatically mean cancel. The key question is whether the meeting produces decisions or removes blockers worth more than its cost."',
'contextText: "Meeting cost should be viewed alongside salary after tax, budget ratio, and net worth."':'contextText: "Meeting cost should be viewed with team goals, project value, decision speed, and alternative communication methods."',
'premiumText: "Unlock meeting cost growth trend, peer comparison, freelancer estimator, and personalized income report."':'premiumText: "Unlock meeting cost trends, department comparison, async replacement suggestions, and team meeting cost reports."',
'q1: "Is meeting cost or monthly salary more accurate?", a1: "Meeting cost more precisely reflects work value because it accounts for actual hours worked, including overtime and vacation differences."':'q1: "Should I focus on per-meeting cost or monthly cost?", a1: "Use both. Per-meeting cost shows whether one meeting is worth holding; monthly cost reveals whether recurring meetings quietly consume too much team time."',
'q2: "Why is my actual meeting cost lower than stated?", a2: "Unpaid overtime increases actual hours beyond contract hours, diluting the meeting cost. Include all work time in your calculation."':'q2: "How should I estimate average hourly rate?", a2: "Use annual salary divided by annual work hours, or a team median hourly rate. If pay varies widely by role, estimate each role separately and add them together."',
'q3: "How do freelancers calculate meeting cost?", a3: "Freelancer meeting cost = project income ÷ total project hours (including communication and revisions). Also deduct self-employment tax and business costs."':'q3: "Should prep time be included?", a3: "If people must prepare slides, pre-read documents, or do follow-up work, estimate that separately. This calculator defaults to time spent inside the meeting."',
'q4: "How does overtime affect meeting cost?", a4: "Paid overtime (1.5x or 2x) increases the weighted meeting cost; unpaid overtime decreases it. Calculate them separately."':'q4: "When should a meeting be shortened or canceled?", a4: "If there is no agenda, no decision-maker, only one-way updates, or the expected value is below the cost, consider async documents, recordings, or a shorter decision meeting."',
'q5: "How to calculate meeting cost with multiple jobs?", a5: "Calculate each job\'s meeting cost separately, then income-weighted average. Prioritize time for higher-rate work."':'q5: "Is lower meeting cost always better?", a5: "Not always. A cheap recurring meeting can still slow the team, while an expensive meeting may be worthwhile if it creates a high-value decision quickly."',
'q6: "Can this tool provide salary negotiation or career advice?", a6: "No. It is an educational estimator only. For salary negotiation, career planning, or labor rights, consult a qualified professional."':'q6: "Can this tool replace management judgment?", a6: "No. It is an educational planning estimator. Real meeting design should also consider culture, decision risk, project value, and collaboration needs."',
'PRO Meeting Cost Pack':'PRO Meeting Cost Pack',
'PRO 會議成本追蹤包':'PRO 會議成本治理包',
}
for old,new in repls.items():
    s=s.replace(old,new)
p.write_text(s)
print('polished meeting cost copy')
