// @profile B
// Profile B · Calculator-Science · IdealGasLawCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "vacuum", range: "< 1", label: { zh: "低壓級", en: "Low" }, desc: { zh: "壓力極低，落在接近真空或稀薄氣體區間，常見於高空、真空腔或抽氣系統，分子碰撞稀少。", en: "Very low pressure near vacuum or rarefied gas, common in high altitude, vacuum chambers, or pumped systems with sparse molecular collisions." } },
  { key: "low", range: "1–2", label: { zh: "常壓級", en: "Ambient" }, desc: { zh: "壓力接近一大氣壓，適合一般實驗與日常氣體計算，標準大氣壓 1 atm 為常見參考基準點。", en: "Pressure near one atmosphere, fit for general experiments and everyday gas calculations; standard atmosphere at 1 atm is the common reference point." } },
  { key: "medium", range: "2–5", label: { zh: "中壓級", en: "Medium" }, desc: { zh: "壓力落在常見的中等區間，多數壓縮氣瓶與工業製程的工作壓力範圍，數值直觀易估算。", en: "Pressure in the common medium range, the band for most compressed cylinders and industrial process pressures, intuitive to estimate." } },
  { key: "high", range: "5–10", label: { zh: "高壓級", en: "High" }, desc: { zh: "壓力偏高，涵蓋多數高壓儲氣與反應釜，氣體明顯壓縮，常用於儲存與化工製程。", en: "High pressure covering most high-pressure storage and reactors; the gas is noticeably compressed, common in storage and chemical processes." } },
  { key: "veryhigh", range: "10–20", label: { zh: "超高壓", en: "Very High" }, desc: { zh: "壓力非常高，常見於高壓鋼瓶或特殊製程，建議結合容器強度與安全規範一併評估。", en: "Very high pressure, common in high-pressure cylinders or special processes; evaluate with vessel strength and safety standards." } },
  { key: "extreme", range: "> 20", label: { zh: "極壓級", en: "Extreme" }, desc: { zh: "壓力極高，屬於超高壓設備或實驗範疇，務必交叉驗證莫耳數、體積與溫度的單位與量測精度。", en: "Extremely high pressure in the ultra-high-pressure equipment or experimental range; always verify mole, volume, and temperature units and measurement precision." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "通用單位換算計算機", en: "Unit Converter Calculator" }, href: "/tools/science/unit-converter-calculator" },
  { label: { zh: "莫耳濃度計算機", en: "Molarity Calculator" }, href: "/tools/science/molarity-calculator" },
  { label: { zh: "壓力計算機", en: "Pressure Calculator" }, href: "/tools/science/pressure-calculator" },
  { label: { zh: "密度計算機", en: "Density Calculator" }, href: "/tools/science/density-calculator" },
];

const ui = {
  zh: {
    badge: "Science · 理想氣體 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "理想氣體定律計算機 · Ideal Gas", subtitle: "用莫耳數、體積與精度等級算出壓力、相對量級與精度分數",
    intro: "Ideal Gas Law Calculator 依據莫耳數、體積與精度等級（粗略、標準或精密），以理想氣體定律 P = nRT ÷ V（取 R = 0.0821、T = 273.15 K）計算氣體壓力、相對量級與精度分數，協助你判斷壓力是否合理、落在哪個量級、是否需要檢查單位，讓你在化學計算與製程設計前就把壓力算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以 P = nRT ÷ V 在標準溫度下計算，假設氣體為理想氣體；正式製程分析請以實際溫度、壓縮係數與標準參考資料為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立壓力範例", examplePreview: "壓力預覽", examplePerson: "莫耳數 (mol)", fillExample: "一鍵填入標準範例", previewActivePath: "填入精密範例",
    examplesCalculator: "範例 → 計算器", enterValues: "輸入莫耳數、體積與精度等級", examplesHelper: "先用範例理解莫耳數與體積如何決定壓力與量級，再改成自己的氣體數據。",
    metric: "公制", imperial: "佔比檢視", exampleCards: "範例卡", baselineExample: "標準壓力模式", activeExample: "精密示範", baselineExampleNote: "1mol ÷ 22.4L · 標準", activeExampleNote: "2mol ÷ 22.4L · 精密", carbsLabel: "精度餘量", carbsName: "百分比", proteinLabel: "精度分數", flowDemo: "體積 (L)", calculator: "計算器",
    weight: "莫耳數 (mol)", tdee: "體積 (L)", goal: "精度等級", goalCut: "粗略 (1 位)", goalMaintain: "標準 (2 位)", goalBulk: "精密 (4 位)",
    resultCard: "壓力結果", unit: "atm (壓力)", primaryValue: "主要數值", maintenanceTarget: "精度分數", actionTarget: "壓力", estimatedTdee: "體積", maintenance: "分", fatLossTarget: "atm",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格壓力量級判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前壓力放進常見量級；這是製程參考，不是設備鑑定結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把壓力結果轉成可執行的化學計算與製程策略", conversionNote: "L9 會連動目前計算結果，顯示精度分數、壓力與量級提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前壓力概況", dailyGap: "壓力", weeklyTrend: "精度分數", motivation: "動力卡", keepMomentum: "從壓力計算走向最精確一致的化學計算節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的壓力結果帶回團隊", journeyHint: "用通用單位換算計算機一起看，把壓力與物理量一併納入化學計算規劃。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用通用單位換算計算機轉換壓力單位", nextActionItem2: "用莫耳濃度計算機推算溶液濃度", nextActionItem3: "用壓力計算機計算受力分布",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Moles → 精度分數 → 等級 → Pressure", bmrStep: "Moles", deficitStep: "精度分數", trendStep: "等級", mealStep: "Pressure",
    knowledge: "知識", knowledgeTitle: "理想氣體定律在化學計算中的意義", definition: "定義", definitionText: "理想氣體定律描述壓力、體積、莫耳數與溫度的關係，以公式 PV = nRT 表示；它是判斷氣體狀態、估算壓力與設計製程的核心物理關係。", formula: "公式", formulaText: "壓力 P = nRT ÷ V，本工具取 R = 0.0821 L·atm/(mol·K)、T = 273.15 K。精度分數 = min(有效位數 / 目標位數 × 100, 100)。精度餘量 = (有效位數 − 目標位數) / 目標位數 × 100%。", limitations: "限制", limitationsText: "本工具假設氣體為理想氣體且溫度恆定；真實氣體在高壓低溫下偏離理想行為，須以壓縮係數修正，極端條件下誤差更明顯。", interpretation: "解讀", interpretationText: "壓力接近 1 atm 屬常壓區間，落在中壓級（2–5）常見於壓縮氣瓶，高壓級以上多為工業儲氣，請用精度分數確認有效位數足夠。", context: "脈絡", contextText: "壓力結果應與莫耳數、體積與單位換算一起看，才能在製程準確性、化學計算與可讀性之間取得平衡。", example: "範例", exampleText: "莫耳數 1mol、體積 22.4L、標準精度（2 位）→ 壓力 1.00 atm，精度餘量 0%，精度分數 100。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "理想氣體的下一步工具", premiumTitle: "PRO 氣體分析包", premiumText: "解鎖壓縮係數修正、多溫度狀態對照表、莫耳體積與分壓計算與混合氣體狀態推算。", feat1: "壓縮係數", feat2: "溫度狀態表", feat3: "分壓計算", feat4: "混合氣體狀態",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供化學計算與教育用途，不取代專業製程鑑定、壓力量測或實驗室分析報告。", relatedTools: "相關工具", relatedToolsText: "Unit Converter · Molarity · Pressure · Density", references: "參考資料", referencesText: "理想氣體定律物理定義；標準氣體常數參考；SI 莫耳體積溫度單位定義；物理化學基礎文獻。",
    q1: "壓力怎麼算的？", a1: "本工具以 P = nRT ÷ V，取 R = 0.0821、T = 273.15 K，將莫耳數與體積換算成壓力；已知任三個量即可反推第四個量。",
    q2: "精度分數多少才合理？", a2: "精度分數達 100 代表有效位數已達所選精度等級；若低於 100，建議提高有效位數或檢查量測精度。",
    q3: "粗略還是精密等級？", a3: "日常估算用粗略（1 位），一般製程計算用標準（2 位），實驗室或精密分析用精密（4 位）。",
    q4: "怎麼判斷壓力量級？", a4: "壓力接近 1 atm 為常壓，2–5 屬中壓常見於氣瓶，高於此多為工業高壓儲氣；比較壓力與量級提示即可判斷。",
    q5: "溫度會影響壓力嗎？", a5: "會。理想氣體中溫度升高壓力隨之上升，本工具固定取標準溫度 273.15 K；精密計算需註明實際溫度與壓縮係數。",
    q6: "這個工具能取代製程鑑定嗎？", a6: "不能。它只是快速估算與教育用途；正式製程鑑定應以專業儀器與標準參考資料為準。",
  },
  en: {
    badge: "Science · Ideal Gas · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Ideal Gas Law Calculator", subtitle: "Compute pressure, relative magnitude, and precision score from moles, volume, and precision level",
    intro: "This calculator uses moles, volume, and precision level (rough, standard, or precise) with the ideal gas law P = nRT / V (taking R = 0.0821 and T = 273.15 K) to compute gas pressure, relative magnitude, and precision score, helping you judge whether the pressure is reasonable, which magnitude it falls into, and whether to check units, so you compute pressure clearly before chemistry calculations and process design.",
    trustNoteLabel: "Note:", trustNote: "This tool computes P = nRT / V at standard temperature, assuming an ideal gas; for formal process analysis, follow actual temperature, compressibility factor, and standard reference data.",
    quickActionCard: "Quick Action Card", tryExample: "Create a pressure example instantly", examplePreview: "Pressure preview", examplePerson: "Moles (mol)", fillExample: "One-click standard example", previewActivePath: "Fill precise example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter moles, volume, and precision level", examplesHelper: "Start with an example to see how moles and volume set the pressure and magnitude, then replace with your own gas data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard pressure mode", activeExample: "Precise demo", baselineExampleNote: "1mol / 22.4L · standard", activeExampleNote: "2mol / 22.4L · precise", carbsLabel: "Precision margin", carbsName: "percent", proteinLabel: "Precision score", flowDemo: "Volume (L)", calculator: "Calculator",
    weight: "Moles (mol)", tdee: "Volume (L)", goal: "Precision level", goalCut: "Rough (1 digit)", goalMaintain: "Standard (2 digits)", goalBulk: "Precise (4 digits)",
    resultCard: "Pressure Result", unit: "atm (pressure)", primaryValue: "Primary Value", maintenanceTarget: "Precision score", actionTarget: "Pressure", estimatedTdee: "Volume", maintenance: "pts", fatLossTarget: "atm",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card pressure magnitude interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current pressure into common magnitudes. This is process guidance, not an equipment identification conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the pressure result into an actionable chemistry-calculation and process strategy", conversionNote: "L9 values update from the computed result: precision score, pressure, and magnitude hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current pressure snapshot", dailyGap: "Pressure", weeklyTrend: "Precision score", motivation: "Motivation Card", keepMomentum: "Move from pressure calculation to the most precise and consistent chemistry-calculation rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's pressure result to your team", journeyHint: "Review it with the Unit Converter Calculator to fold pressure and physical quantities into chemistry-calculation planning.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Convert pressure units with the Unit Converter Calculator", nextActionItem2: "Derive solution concentration with the Molarity Calculator", nextActionItem3: "Compute force distribution with the Pressure Calculator",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Moles → Precision → Level → Pressure", bmrStep: "Moles", deficitStep: "Precision", trendStep: "Level", mealStep: "Pressure",
    knowledge: "Knowledge", knowledgeTitle: "What the ideal gas law means in chemistry calculation", definition: "Definition", definitionText: "The ideal gas law describes the relationship among pressure, volume, moles, and temperature, expressed as PV = nRT; it is the core physical relationship for judging gas state, estimating pressure, and designing processes.", formula: "Formula", formulaText: "Pressure P = nRT / V; this tool takes R = 0.0821 L·atm/(mol·K) and T = 273.15 K. Precision score = min(significant digits / target digits x 100, 100). Precision margin = (significant digits - target digits) / target digits x 100%.", limitations: "Limitations", limitationsText: "This tool assumes an ideal gas at constant temperature; real gases deviate from ideal behavior at high pressure and low temperature and need a compressibility correction, with larger error under extreme conditions.", interpretation: "Interpretation", interpretationText: "Pressure near 1 atm is the ambient range, pressure in the medium range (2 to 5) is common in compressed cylinders, above the high range is mostly industrial storage, and use the precision score to confirm sufficient significant digits.", context: "Context", contextText: "Pressure results should be evaluated with moles, volume, and unit conversion to balance process accuracy, chemistry calculation, and readability.", example: "Example", exampleText: "Moles 1mol, volume 22.4L, standard precision (2 digits) gives pressure 1.00 atm, precision margin 0 percent, precision score 100.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for ideal gas", premiumTitle: "PRO Gas Analytics Pack", premiumText: "Unlock compressibility-factor correction, multi-temperature state reference tables, molar volume and partial pressure calculation, and mixture gas state estimation.", feat1: "Compress Factor", feat2: "Temp State Tables", feat3: "Partial Pressure", feat4: "Mixture State",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for chemistry calculation and education. It does not replace professional process identification, pressure measurement, or laboratory analysis reports.", relatedTools: "Related Tools", relatedToolsText: "Unit Converter · Molarity · Pressure · Density", references: "References", referencesText: "Physical definition of the ideal gas law; standard gas constant reference; SI mole, volume, and temperature unit definitions; physical chemistry fundamentals.",
    q1: "How is pressure calculated?", a1: "This tool uses P = nRT / V, taking R = 0.0821 and T = 273.15 K, converting moles and volume to pressure; given any three quantities, you can back-calculate the fourth.",
    q2: "What precision score is reasonable?", a2: "A precision score of 100 means significant digits meet the chosen precision level; if below 100, increase significant digits or check measurement precision.",
    q3: "Rough or precise level?", a3: "Use rough (1 digit) for daily estimates, standard (2 digits) for general process calculations, and precise (4 digits) for lab or precision analysis.",
    q4: "How do I judge pressure magnitude?", a4: "Pressure near 1 atm is ambient, 2 to 5 is medium common in cylinders, above that is mostly industrial high-pressure storage; compare pressure with the magnitude hint to decide.",
    q5: "Does temperature affect pressure?", a5: "Yes. In an ideal gas, as temperature rises pressure rises; this tool fixes standard temperature at 273.15 K, and precision calculation needs noted temperature and compressibility factor.",
    q6: "Can this tool replace process identification?", a6: "No. It is a quick estimate for education; formal process identification should follow professional instruments and standard reference data.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function targetDigits(mode: TierMode): number {
  if (mode === "relaxed") return 1;
  if (mode === "fast") return 4;
  return 2;
}

export default function IdealGasLawCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("1");
  const [tdee, setTdee] = useState("22.4");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const moles = Number(weight);
    const volume = Number(tdee);
    if (!Number.isFinite(moles) || !Number.isFinite(volume) || moles < 0 || volume <= 0) return null;
    const digits = targetDigits(goal);
    const pressure = (moles * 0.0821 * 273.15) / volume;
    const sigDigits = digits;
    const precisionScore = Math.min((sigDigits / digits) * 100, 100);
    const precisionMargin = ((sigDigits - digits) / digits) * 100;
    return { pressure, precisionScore, precisionMargin, digits };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.precisionScore, 1) : "—";
  const fatDisplay = result ? fmt(result.pressure, result.digits) : "—";
  const carbDisplay = result ? fmt(result.precisionMargin, 1) : "—";
  const totalDisplay = result ? fmt(result.pressure, result.digits) : "—";

  function fillStandard() { setUnit("metric"); setWeight("1"); setTdee("22.4"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("2"); setTdee("22.4"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">1.00</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">2.00</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">atm</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">%</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">atm</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="ideal-gas-law-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.pressure, result.digits) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.precisionScore, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Moles", note: t.bmrStep }, { label: "Precision", note: t.deficitStep }, { label: "Level", note: t.trendStep }, { label: "Pressure", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="ideal-gas-law-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
