// @profile B
// Profile B · Calculator-AI · ChatbotCostCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< $50", label: { zh: "極省", en: "Minimal" }, desc: { zh: "整月機器人成本極低，適合小型客服或內部試用，幾乎無預算壓力。", en: "Very low monthly chatbot cost—great for small support or internal trials, almost no budget pressure." } },
  { key: "low", range: "$50–200", label: { zh: "輕量", en: "Light" }, desc: { zh: "輕量對話量區間，成本可控，記得保留尖峰時段流量的緩衝。", en: "Light conversation band; cost is manageable—keep buffer for peak-hour traffic." } },
  { key: "healthy", range: "$200–800", label: { zh: "成長", en: "Growing" }, desc: { zh: "多數成長期機器人常見區間，宜開始監控每對話成本與 token 強度。", en: "Common growth-stage chatbot band; start monitoring per-conversation cost and token intensity." } },
  { key: "good", range: "$800–2500", label: { zh: "規模化", en: "Scaling" }, desc: { zh: "已進入規模化成本，建議縮短上下文、導入快取與較便宜模型分流。", en: "Scaling cost; shorten context, introduce caching, and cheaper-model routing." } },
  { key: "strong", range: "$2500–8000", label: { zh: "高負擔", en: "Heavy" }, desc: { zh: "成本偏高，務必比較模型階層、檢索增強與多輪歷史壓縮策略。", en: "Heavy cost; compare model tiers, retrieval augmentation, and multi-turn history compression." } },
  { key: "elite", range: "> $8000", label: { zh: "企業級", en: "Enterprise" }, desc: { zh: "企業級對話量，建議談量價合約、自建快取層並評估混合模型路由。", en: "Enterprise conversation volume; negotiate volume pricing, build a cache layer, and assess hybrid model routing." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "AI Token成本計算機", en: "AI Token Cost Calculator" }, href: "/tools/ai/ai-token-cost-calculator" },
  { label: { zh: "AI API成本估算器", en: "AI API Cost Estimator" }, href: "/tools/ai/ai-api-cost-estimator" },
  { label: { zh: "Prompt Token計算機", en: "Prompt Token Calculator" }, href: "/tools/ai/prompt-token-calculator" },
  { label: { zh: "AI模型比較器", en: "AI Model Comparison" }, href: "/tools/ai/ai-model-comparison" },
];

const ui = {
  zh: {
    badge: "AI · 機器人成本 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "聊天機器人成本計算機 · Chatbot Cost", subtitle: "用月對話量、每百萬單價與對話複雜度算出整月機器人成本與每對話成本",
    intro: "Chatbot Cost Calculator 依據每月對話量、每百萬 token 單價與對話複雜度（簡短、標準或複雜），算出整月機器人總成本、每對話成本與 token 強度，協助你判斷預算是否合理、對話是否太長、該不該壓縮歷史或改用較便宜模型，讓你在上線任何客服機器人前就把營運花費算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以單一綜合單價與對話複雜度估算，未含輸入輸出分離計價、快取折扣與各家最新調價；實際費用請以各 AI 供應商官方計價頁為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立機器人範例", examplePreview: "成本預覽", examplePerson: "月對話量", fillExample: "一鍵填入標準範例", previewActivePath: "填入複雜對話範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入 月對話量、每百萬單價與對話複雜度", examplesHelper: "先用範例理解對話量、單價與複雜度如何決定總成本與每對話成本，再改成自己的營運數據。",
    metric: "公制", imperial: "占比檢視", exampleCards: "範例卡", baselineExample: "標準對話模式", activeExample: "複雜對話示範", baselineExampleNote: "對話 10000 · 單價 2 · 標準", activeExampleNote: "對話 10000 · 單價 2 · 複雜", carbsLabel: "每對話成本", carbsName: "美分", proteinLabel: "Token 強度", flowDemo: "每百萬單價", calculator: "計算機",
    weight: "月對話量 (次)", tdee: "每百萬單價 (USD)", goal: "對話複雜度", goalCut: "簡短 (2K token)", goalMaintain: "標準 (5K token)", goalBulk: "複雜 (12K token)",
    resultCard: "機器人成本結果", unit: "USD (整月總成本)", primaryValue: "主要數值", maintenanceTarget: "Token 強度", actionTarget: "總成本", estimatedTdee: "每百萬單價", maintenance: "%", fatLossTarget: "USD",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格整月機器人成本判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前整月機器人成本放進常見區間；這是規劃參考，不是會計結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把機器人結果轉成可執行的營運成本控制策略", conversionNote: "L9 會連動目前計算結果，顯示 token 強度、總成本與每百萬單價提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前用量概況", dailyGap: "總成本", weeklyTrend: "Token 強度", motivation: "動力卡", keepMomentum: "從成本分析走向最省的對話 token 節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的機器人結果帶回團隊", journeyHint: "用 AI API 成本估算器一起看，把每對話成本拆成輸入輸出分離計價更精準。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用 AI API 成本估算器拆分輸入輸出", nextActionItem2: "用 Prompt Token 計算機估每對話 token", nextActionItem3: "用 AI 模型比較器找最划算階層",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Conversations → TokenIntensity → Complexity → Price", bmrStep: "月對話量", deficitStep: "Token 強度", trendStep: "對話複雜度", mealStep: "每百萬單價",
    knowledge: "知識", knowledgeTitle: "Token 強度在機器人成本中的意義", definition: "定義", definitionText: "機器人成本估算是把月對話量乘每對話 token 得總 token，再依每百萬單價換算整月成本；token 強度衡量每對話平均消耗 token 相對於基準的比重，是判斷對話是否太長的核心指標。", formula: "公式", formulaText: "總 token = 月對話量 × 每對話 token。整月成本 = 總 token ÷ 100 萬 × 每百萬單價。每對話成本 = 整月成本 ÷ 對話量 × 100 美分。token 強度 = 每對話 token ÷ 基準 × 100%。", limitations: "限制", limitationsText: "本工具以單一綜合單價估算；真實費用還受輸入輸出分離計價、快取折扣、多輪歷史累積、檢索增強與各家調價影響，且每對話 token 變動大。", interpretation: "解讀", interpretationText: "整月成本超過 $800 宜開始優化；可透過壓縮多輪歷史、限制回應長度、快取常見問題、改用較便宜階層或檢索增強只帶相關片段來降低成本。", context: "脈絡", contextText: "機器人成本應與 AI API 成本、Prompt Token 與模型比較一起看，才能在體驗、成本與品質之間取得平衡。", example: "範例", exampleText: "月對話 10000 次、標準複雜度 5K token、單價 $2/1M → 總 token 5000 萬，整月成本約 $100，每對話約 1 美分。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "機器人的下一步工具", premiumTitle: "PRO 機器人成本分析包", premiumText: "解鎖各家即時單價、輸入輸出分離計價、多輪歷史累積模擬與尖峰流量成本預測矩陣。", feat1: "即時報價", feat2: "輸入輸出計價", feat3: "歷史模擬", feat4: "尖峰預測",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供成本規劃與教育用途，不取代各 AI 供應商官方計價、帳單明細或合約報價。", relatedTools: "相關工具", relatedToolsText: "AI Token Cost · AI API Cost · Prompt Token · Model Comparison", references: "參考資料", referencesText: "各 AI 供應商官方計價頁；對話式 AI 成本研究；多輪上下文管理最佳實務；檢索增強生成指南。",
    q1: "整月機器人成本怎麼算的？", a1: "本工具把月對話量乘每對話 token 得總 token，再依每百萬單價換算成本；實際還受輸入輸出分離計價影響。",
    q2: "Token 強度多少要小心？", a2: "強度越高代表每對話越長越貴；若強度偏高，建議壓縮多輪歷史、限制回應長度或改用較便宜階層。",
    q3: "簡短還是複雜對話？", a3: "FAQ 與簡單客服適合簡短設定；需要推理與長文回覆才用複雜設定，並用模型比較器評估性價比。",
    q4: "機器人成本太高怎麼降？", a4: "壓縮多輪歷史、限制最大回應 token、快取常見問題、檢索增強只帶相關片段、改用較便宜階層並監控尖峰流量。",
    q5: "要把輸入輸出分開算嗎？", a5: "建議分開。本工具用綜合單價快速估算；若輸出 token 較貴，請用 AI API 成本估算器分離輸入輸出計價。",
    q6: "這個工具能取代官方帳單嗎？", a6: "不能。它只是快速估算與教育用途；實際費用應以各 AI 供應商官方計價頁與帳單明細為準。",
  },
  en: {
    badge: "AI · Chatbot Cost · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Chatbot Cost Calculator", subtitle: "Compute monthly chatbot cost and per-conversation cost from monthly conversations, price per million, and conversation complexity",
    intro: "This calculator uses monthly conversation volume, price per million tokens, and conversation complexity (brief, standard, or complex) to compute total monthly chatbot cost, per-conversation cost, and token intensity, helping you judge whether the budget is reasonable, whether conversations are too long, whether to compress history or switch to a cheaper model, so you compute operating spend clearly before launching any support chatbot.",
    trustNoteLabel: "Note:", trustNote: "This tool estimates from a single blended price and conversation complexity, excluding split input/output pricing, cache discounts, and each vendor's latest price changes; for actual cost, follow each AI provider's official pricing page.",
    quickActionCard: "Quick Action Card", tryExample: "Create a chatbot example instantly", examplePreview: "Cost preview", examplePerson: "Monthly conversations", fillExample: "One-click standard example", previewActivePath: "Fill complex conversation example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter monthly conversations, price per million, and conversation complexity", examplesHelper: "Start with an example to see how conversation volume, price, and complexity set the total and per-conversation cost, then replace with your own operating data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard conversation mode", activeExample: "Complex conversation demo", baselineExampleNote: "conversations 10000 · price 2 · standard", activeExampleNote: "conversations 10000 · price 2 · complex", carbsLabel: "Per-conversation cost", carbsName: "cents", proteinLabel: "Token intensity", flowDemo: "Price per million", calculator: "Calculator",
    weight: "Monthly conversations (count)", tdee: "Price per million (USD)", goal: "Conversation complexity", goalCut: "Brief (2K tokens)", goalMaintain: "Standard (5K tokens)", goalBulk: "Complex (12K tokens)",
    resultCard: "Chatbot Cost Result", unit: "USD (monthly total cost)", primaryValue: "Primary Value", maintenanceTarget: "Token intensity", actionTarget: "Total cost", estimatedTdee: "Price per million", maintenance: "%", fatLossTarget: "USD",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card monthly chatbot-cost interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current monthly chatbot cost into common zones. This is planning guidance, not an accounting conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the chatbot result into an actionable operating cost-control strategy", conversionNote: "L9 values update from the computed result: token intensity, total cost, and price-per-million hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current usage snapshot", dailyGap: "Total cost", weeklyTrend: "Token intensity", motivation: "Motivation Card", keepMomentum: "Move from cost analysis to the cheapest conversation-token rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's chatbot result to your team", journeyHint: "Review it with the AI API Cost Estimator to split per-conversation cost into input/output pricing for more accuracy.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Split input/output with the AI API Cost Estimator", nextActionItem2: "Estimate per-conversation tokens with the Prompt Token Calculator", nextActionItem3: "Find the best-value tier with AI Model Comparison",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Conversations → TokenIntensity → Complexity → Price", bmrStep: "Monthly conversations", deficitStep: "Token intensity", trendStep: "Conversation complexity", mealStep: "Price per million",
    knowledge: "Knowledge", knowledgeTitle: "What token intensity means in chatbot cost", definition: "Definition", definitionText: "Chatbot cost estimation multiplies monthly conversations by tokens per conversation for total tokens, then converts by price per million into monthly cost; token intensity measures average tokens per conversation relative to a baseline, the core indicator for whether conversations are too long.", formula: "Formula", formulaText: "Total tokens = monthly conversations × tokens per conversation. Monthly cost = total tokens ÷ 1M × price per million. Per-conversation cost = monthly cost ÷ conversations × 100 cents. Token intensity = tokens per conversation ÷ baseline × 100%.", limitations: "Limitations", limitationsText: "This tool estimates from a single blended price; real cost is also affected by split input/output pricing, cache discounts, multi-turn history accumulation, retrieval augmentation, and vendor price changes, and tokens per conversation vary widely.", interpretation: "Interpretation", interpretationText: "Monthly cost over $800 warrants optimization; reduce cost by compressing multi-turn history, capping response length, caching common questions, switching to cheaper tiers, or retrieval-augmenting only relevant chunks.", context: "Context", contextText: "Chatbot cost should be evaluated with AI API cost, prompt tokens, and model comparison to balance experience, cost, and quality.", example: "Example", exampleText: "Monthly 10000 conversations, standard complexity 5K tokens, price $2/1M → total tokens 50M, monthly cost about $100, about 1 cent per conversation.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for the chatbot", premiumTitle: "PRO Chatbot Cost Analytics Pack", premiumText: "Unlock per-vendor live prices, split input/output pricing, multi-turn history accumulation simulation, and a peak-traffic cost forecast matrix.", feat1: "Live Pricing", feat2: "Split IO Pricing", feat3: "History Simulation", feat4: "Peak Forecast",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for cost planning and education. It does not replace each AI provider's official pricing, billing detail, or contract quote.", relatedTools: "Related Tools", relatedToolsText: "AI Token Cost · AI API Cost · Prompt Token · Model Comparison", references: "References", referencesText: "Per-AI-provider official pricing pages; conversational AI cost research; multi-turn context management best practices; retrieval-augmented generation guides.",
    q1: "How is monthly chatbot cost calculated?", a1: "This tool multiplies monthly conversations by tokens per conversation for total tokens, then converts by price per million; actual is also affected by split input/output pricing.",
    q2: "What token intensity should I watch?", a2: "The higher the intensity the longer and pricier each conversation; if intensity is high, compress multi-turn history, cap response length, or switch to a cheaper tier.",
    q3: "Brief or complex conversations?", a3: "FAQ and simple support suit a brief setting; only reasoning and long-form replies need a complex setting—assess value with Model Comparison.",
    q4: "How do I reduce chatbot cost?", a4: "Compress multi-turn history, cap max response tokens, cache common questions, retrieval-augment only relevant chunks, switch to a cheaper tier, and monitor peak traffic.",
    q5: "Should I split input and output?", a5: "Recommended. This tool uses a blended price for a quick estimate; if output tokens are pricier, split input/output pricing with the AI API Cost Estimator.",
    q6: "Can this tool replace the official bill?", a6: "No. It is a quick estimate for education; actual cost should follow each AI provider's official pricing page and billing detail.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function tokensPerConv(mode: TierMode): number {
  if (mode === "relaxed") return 2000;
  if (mode === "fast") return 12000;
  return 5000;
}

export default function ChatbotCostCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("10000");
  const [tdee, setTdee] = useState("2");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const convs = Number(weight);
    const price = Number(tdee);
    if (convs <= 0 || price <= 0) return null;
    const tpc = tokensPerConv(goal);
    const totalTokens = convs * tpc;
    const monthlyCost = (totalTokens / 1_000_000) * price;
    const costPerConvCents = (monthlyCost / convs) * 100;
    const tokenIntensity = Math.min((tpc / 5000) * 100, 240);
    return { monthlyCost, costPerConvCents, tokenIntensity, totalTokens };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.tokenIntensity, 0) : "—";
  const fatDisplay = result ? fmt(result.monthlyCost, 2) : "—";
  const carbDisplay = result ? fmt(result.costPerConvCents, 2) : "—";
  const totalDisplay = result ? fmt(result.monthlyCost, 2) : "—";

  function fillStandard() { setUnit("metric"); setWeight("10000"); setTdee("2"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("10000"); setTdee("2"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">100.00</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">240.00</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">%</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">$</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">¢</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">$</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="chatbot-cost-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.monthlyCost, 2) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.tokenIntensity, 0) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Conversations", note: t.bmrStep }, { label: "TokenIntensity", note: t.deficitStep }, { label: "Complexity", note: t.trendStep }, { label: "Price", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="chatbot-cost-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
