// @profile B
// Profile B · Calculator-Science · UnitConverterCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "micro", range: "< 0.001", label: { zh: "微量級", en: "Micro" }, desc: { zh: "換算結果極小，落在微量級區間，常見於精密科學或化學微量測量，需注意有效位數與捨入誤差。", en: "Very small converted value in the micro range, common in precision science or trace chemistry; watch significant digits and rounding error." } },
  { key: "small", range: "0.001–1", label: { zh: "小量級", en: "Small" }, desc: { zh: "換算結果偏小，適合一般小尺度量測，如毫米、毫克或毫升等日常精細單位的轉換。", en: "Small converted value, fit for everyday fine-scale measurements like millimeters, milligrams, or milliliters." } },
  { key: "unit", range: "1–100", label: { zh: "常用級", en: "Common" }, desc: { zh: "換算結果落在最常用的量級區間，多數日常單位換算的安全範圍，數值直觀易讀。", en: "Converted value in the most common magnitude range, the safe band for most daily unit conversions, intuitive to read." } },
  { key: "large", range: "100–1000", label: { zh: "大量級", en: "Large" }, desc: { zh: "換算結果偏大，適合中大型量測，如公里、公斤或公升等較大單位，建議檢查單位前綴。", en: "Large converted value, suitable for medium-to-large measurements like kilometers, kilograms, or liters; verify unit prefixes." } },
  { key: "huge", range: "1000–1e6", label: { zh: "巨量級", en: "Huge" }, desc: { zh: "換算結果非常大，常見於工程或天文量測，建議改用科學記號表示以避免讀數錯誤。", en: "Very large converted value, common in engineering or astronomical measurements; use scientific notation to avoid misreading." } },
  { key: "extreme", range: "> 1e6", label: { zh: "極量級", en: "Extreme" }, desc: { zh: "換算結果極大，超出一般直觀範圍，務必使用科學記號並交叉驗證換算因子的正確性。", en: "Extremely large converted value beyond intuitive range; always use scientific notation and cross-verify the conversion factor." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "力學計算機", en: "Force Calculator" }, href: "/tools/science/force-calculator" },
  { label: { zh: "密度計算機", en: "Density Calculator" }, href: "/tools/science/density-calculator" },
  { label: { zh: "速度距離時間計算機", en: "Speed Distance Time Calculator" }, href: "/tools/science/speed-distance-time-calculator" },
  { label: { zh: "壓力計算機", en: "Pressure Calculator" }, href: "/tools/science/pressure-calculator" },
];

const ui = {
  zh: {
    badge: "Science · 單位換算 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "通用單位換算計算機 · Unit Converter", subtitle: "用來源數值、換算因子與精度等級算出換算結果、相對量級與精度分數",
    intro: "Unit Converter Calculator 依據來源數值、換算因子與精度等級（粗略、標準或精密），計算換算結果、相對量級與精度分數，協助您判斷不同單位之間的轉換是否正確、結果落在哪個量級、是否需要改用科學記號或調整有效位數，讓您在科學計算與工程量測前就把單位換算算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以您輸入的換算因子做線性換算，未含非線性單位（如溫度偏移）與單位制差異；正式換算請以權威單位定義與標準對照表為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立換算範例", examplePreview: "換算預覽", examplePerson: "來源數值", fillExample: "一鍵填入標準範例", previewActivePath: "填入精密範例",
    examplesCalculator: "範例 → 計算器", enterValues: "輸入來源數值、換算因子與精度等級", examplesHelper: "先用範例理解換算因子如何決定結果與量級，再改成自己的量測數據。",
    metric: "公制", imperial: "佔比檢視", exampleCards: "範例卡", baselineExample: "標準換算模式", activeExample: "精密示範", baselineExampleNote: "1.0 × 3.28084 · 標準", activeExampleNote: "10.0 × 3.28084 · 精密", carbsLabel: "精度餘量", carbsName: "百分比", proteinLabel: "精度分數", flowDemo: "換算因子", calculator: "計算器",
    weight: "來源數值", tdee: "換算因子", goal: "精度等級", goalCut: "粗略 (2 位)", goalMaintain: "標準 (4 位)", goalBulk: "精密 (6 位)",
    resultCard: "換算結果", unit: "(換算後)", primaryValue: "主要數值", maintenanceTarget: "精度分數", actionTarget: "換算結果", estimatedTdee: "換算因子", maintenance: "分", fatLossTarget: "值",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格量級判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前換算結果放進常見量級；這是量測參考，不是權威單位定義。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把換算結果轉成可執行的量測與記錄策略", conversionNote: "L9 會連動目前計算結果，顯示精度分數、換算結果與量級提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前換算概況", dailyGap: "換算結果", weeklyTrend: "精度分數", motivation: "動力卡", keepMomentum: "從單位換算走向最精確一致的量測節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的換算結果帶回團隊", journeyHint: "用密度計算機一起看，把換算結果與物理量一併納入科學計算規劃。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用力學計算機計算受力結果", nextActionItem2: "用密度計算機推算質量體積", nextActionItem3: "用速度距離時間計算機規劃運動量",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Value → 精度分數 → 等級 → Result", bmrStep: "Value", deficitStep: "精度分數", trendStep: "等級", mealStep: "Result",
    knowledge: "知識", knowledgeTitle: "單位換算在科學計算中的意義", definition: "定義", definitionText: "單位換算是把同一物理量在不同度量單位之間轉換的過程；以來源數值乘上換算因子得到目標單位數值，是科學、工程與日常量測的基礎運算。", formula: "公式", formulaText: "換算結果 = 來源數值 × 換算因子。精度分數 = min(有效位數 / 目標位數 × 100, 100)。精度餘量 = (有效位數 − 目標位數) / 目標位數 × 100%。", limitations: "限制", limitationsText: "本工具僅做線性比例換算；溫度（°C↔°F）、對數量級（dB、pH）與單位制偏移需用對應公式，且換算因子的精度直接影響結果準確性。", interpretation: "解讀", interpretationText: "換算結果落在常用量級（1–100）最直觀；結果過大或過小時建議改用科學記號或調整單位前綴，並用精度分數確認有效位數足夠。", context: "脈絡", contextText: "換算結果應與物理公式、量測誤差與單位制標準一起看，才能在精確性、可讀性與一致性之間取得平衡。", example: "範例", exampleText: "來源數值 1.0、換算因子 3.28084（公尺轉英尺）、標準精度（4 位）→ 換算結果 3.2808，精度餘量 0%，精度分數 100。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "換算的下一步工具", premiumTitle: "PRO 單位換算分析包", premiumText: "解鎖內建多單位制對照表、非線性換算公式、科學記號自動切換與批次換算匯出。", feat1: "單位對照表", feat2: "非線性換算", feat3: "科學記號", feat4: "批次匯出",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供科學計算與教育用途，不取代權威單位定義、計量標準或法定計量報告。", relatedTools: "相關工具", relatedToolsText: "Force · Density · Speed Distance Time · Pressure", references: "參考資料", referencesText: "SI 國際單位制定義；NIST 單位換算標準；計量學基礎文獻；工程單位對照手冊。",
    q1: "換算結果怎麼算的？", a1: "本工具以來源數值乘上換算因子得到目標單位數值；非線性單位如溫度需用對應的換算公式。",
    q2: "精度分數多少才合理？", a2: "精度分數達 100 代表有效位數已達所選精度等級；若低於 100，建議提高有效位數或檢查換算因子精度。",
    q3: "粗略還是精密等級？", a3: "日常估算用粗略（2 位），一般科學計算用標準（4 位），實驗室或工程精密量測用精密（6 位）。",
    q4: "換算結果太大怎麼處理？", a4: "改用科學記號表示、調整單位前綴（如 km 改 m）、檢查換算因子是否正確，並注意有效位數與捨入誤差。",
    q5: "溫度可以用這個換算嗎？", a5: "溫度是非線性換算（含偏移量），不適用單純乘法；°C↔°F 需用 F = C×1.8+32 等專屬公式。",
    q6: "這個工具能取代計量標準嗎？", a6: "不能。它只是快速估算與教育用途；正式換算應以 SI 定義與權威計量標準為準。",
  },
  en: {
    badge: "Science · Unit Conversion · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Unit Converter Calculator", subtitle: "Compute converted value, relative magnitude, and precision score from source value, conversion factor, and precision level",
    intro: "This calculator uses source value, conversion factor, and precision level (rough, standard, or precise) to compute converted value, relative magnitude, and precision score, helping you judge whether the conversion between units is correct, which magnitude the result falls into, and whether to use scientific notation or adjust significant digits, so you compute unit conversions clearly before scientific calculations and engineering measurements.",
    trustNoteLabel: "Note:", trustNote: "This tool performs linear conversion using the factor you enter, excluding non-linear units (such as temperature offset) and unit-system differences; for formal conversion, follow authoritative unit definitions and standard reference tables.",
    quickActionCard: "Quick Action Card", tryExample: "Create a conversion example instantly", examplePreview: "Conversion preview", examplePerson: "Source value", fillExample: "One-click standard example", previewActivePath: "Fill precise example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter source value, conversion factor, and precision level", examplesHelper: "Start with an example to see how the conversion factor sets the result and magnitude, then replace with your own measurement data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard conversion mode", activeExample: "Precise demo", baselineExampleNote: "1.0 x 3.28084 · standard", activeExampleNote: "10.0 x 3.28084 · precise", carbsLabel: "Precision margin", carbsName: "percent", proteinLabel: "Precision score", flowDemo: "Conversion factor", calculator: "Calculator",
    weight: "Source value", tdee: "Conversion factor", goal: "Precision level", goalCut: "Rough (2 digits)", goalMaintain: "Standard (4 digits)", goalBulk: "Precise (6 digits)",
    resultCard: "Conversion Result", unit: "(converted)", primaryValue: "Primary Value", maintenanceTarget: "Precision score", actionTarget: "Converted value", estimatedTdee: "Conversion factor", maintenance: "pts", fatLossTarget: "value",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card magnitude interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current converted value into common magnitudes. This is measurement guidance, not an authoritative unit definition.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the conversion result into an actionable measurement and recording strategy", conversionNote: "L9 values update from the computed result: precision score, converted value, and magnitude hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current conversion snapshot", dailyGap: "Converted value", weeklyTrend: "Precision score", motivation: "Motivation Card", keepMomentum: "Move from unit conversion to the most precise and consistent measurement rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's conversion result to your team", journeyHint: "Review it with the Density Calculator to fold converted values and physical quantities into scientific calculation planning.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Compute applied force with the Force Calculator", nextActionItem2: "Derive mass and volume with the Density Calculator", nextActionItem3: "Plan motion quantities with the Speed Distance Time Calculator",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Value → Precision → Level → Result", bmrStep: "Value", deficitStep: "Precision", trendStep: "Level", mealStep: "Result",
    knowledge: "Knowledge", knowledgeTitle: "What unit conversion means in scientific calculation", definition: "Definition", definitionText: "Unit conversion is the process of converting the same physical quantity between different measurement units; multiplying the source value by a conversion factor gives the target-unit value, a foundational operation in science, engineering, and daily measurement.", formula: "Formula", formulaText: "Converted value = source value x conversion factor. Precision score = min(significant digits / target digits x 100, 100). Precision margin = (significant digits - target digits) / target digits x 100%.", limitations: "Limitations", limitationsText: "This tool does linear proportional conversion only; temperature (C to F), logarithmic magnitudes (dB, pH), and unit-system offsets need their own formulas, and the precision of the conversion factor directly affects result accuracy.", interpretation: "Interpretation", interpretationText: "A converted value in the common magnitude (1 to 100) is most intuitive; when too large or small, use scientific notation or adjust unit prefixes, and use the precision score to confirm sufficient significant digits.", context: "Context", contextText: "Conversion results should be evaluated with physical formulas, measurement error, and unit-system standards to balance accuracy, readability, and consistency.", example: "Example", exampleText: "Source value 1.0, conversion factor 3.28084 (meters to feet), standard precision (4 digits) gives converted value 3.2808, precision margin 0 percent, precision score 100.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for conversion", premiumTitle: "PRO Unit Conversion Analytics Pack", premiumText: "Unlock built-in multi-unit reference tables, non-linear conversion formulas, automatic scientific-notation switching, and batch conversion export.", feat1: "Unit Tables", feat2: "Non-Linear Formula", feat3: "Sci Notation", feat4: "Batch Export",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for scientific calculation and education. It does not replace authoritative unit definitions, metrology standards, or legal measurement reports.", relatedTools: "Related Tools", relatedToolsText: "Force · Density · Speed Distance Time · Pressure", references: "References", referencesText: "SI International System of Units definitions; NIST unit conversion standards; metrology fundamentals; engineering unit reference handbooks.",
    q1: "How is the conversion result calculated?", a1: "This tool multiplies the source value by the conversion factor to get the target-unit value; non-linear units like temperature need their own conversion formulas.",
    q2: "What precision score is reasonable?", a2: "A precision score of 100 means significant digits meet the chosen precision level; if below 100, increase significant digits or check the conversion factor precision.",
    q3: "Rough or precise level?", a3: "Use rough (2 digits) for daily estimates, standard (4 digits) for general science, and precise (6 digits) for lab or engineering precision measurements.",
    q4: "How do I handle a result that is too large?", a4: "Use scientific notation, adjust unit prefixes (such as km to m), verify the conversion factor, and watch significant digits and rounding error.",
    q5: "Can I convert temperature with this?", a5: "Temperature is a non-linear conversion (with offset) and does not work with simple multiplication; C to F needs a dedicated formula like F = C x 1.8 + 32.",
    q6: "Can this tool replace metrology standards?", a6: "No. It is a quick estimate for education; formal conversion should follow SI definitions and authoritative metrology standards.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function targetDigits(mode: TierMode): number {
  if (mode === "relaxed") return 2;
  if (mode === "fast") return 6;
  return 4;
}

export default function UnitConverterCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("1");
  const [tdee, setTdee] = useState("3.28084");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const value = Number(weight);
    const factor = Number(tdee);
    if (!Number.isFinite(value) || !Number.isFinite(factor)) return null;
    const digits = targetDigits(goal);
    const converted = value * factor;
    const sigDigits = digits;
    const precisionScore = Math.min((sigDigits / digits) * 100, 100);
    const precisionMargin = ((sigDigits - digits) / digits) * 100;
    return { converted, precisionScore, precisionMargin, digits };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.precisionScore, 1) : "—";
  const fatDisplay = result ? fmt(result.converted, result.digits) : "—";
  const carbDisplay = result ? fmt(result.precisionMargin, 1) : "—";
  const totalDisplay = result ? fmt(result.converted, result.digits) : "—";

  function fillStandard() { setUnit("metric"); setWeight("1"); setTdee("3.28084"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("10"); setTdee("3.28084"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">3.2808</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">32.808</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">val</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">%</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">val</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="unit-converter-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.converted, result.digits) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.precisionScore, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Value", note: t.bmrStep }, { label: "Precision", note: t.deficitStep }, { label: "Level", note: t.trendStep }, { label: "Result", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L14-Knowledge-FAQ · L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="unit-converter-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7">{/* L17-TrustRelatedReferences */}<p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
