// @profile B
// Profile B · Calculator-AI · AiErrorRateCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< 0.5%", label: { zh: "極穩", en: "Rock-solid" }, desc: { zh: "錯誤率極低，系統高度可靠，幾乎不需額外重試或人工介入。", en: "Very low error rate; the system is highly reliable with almost no extra retries or manual intervention." } },
  { key: "low", range: "0.5–2%", label: { zh: "穩健", en: "Stable" }, desc: { zh: "穩健區間，多數生產服務可接受，建議保留簡單重試與監控告警。", en: "Stable band; acceptable for most production services—keep simple retries and monitoring alerts." } },
  { key: "healthy", range: "2–5%", label: { zh: "需留意", en: "Watch" }, desc: { zh: "需留意區間，重試成本開始累積，宜分析錯誤類型並加上後備路徑。", en: "Watch band; retry cost starts accumulating—analyze error types and add fallback paths." } },
  { key: "good", range: "5–10%", label: { zh: "偏高", en: "Elevated" }, desc: { zh: "偏高，建議檢視提示穩定性、輸出格式驗證與超時設定，降低失敗。", en: "Elevated; review prompt stability, output-format validation, and timeout settings to reduce failures." } },
  { key: "strong", range: "10–20%", label: { zh: "不穩", en: "Unstable" }, desc: { zh: "不穩定，務必排查模型、輸入品質與速率限制，並設計降級策略。", en: "Unstable; investigate model, input quality, and rate limits, and design a graceful-degradation strategy." } },
  { key: "elite", range: "> 20%", label: { zh: "嚴重", en: "Critical" }, desc: { zh: "嚴重失敗，須暫緩擴量、更換模型或重構提示與驗證流程後再上線。", en: "Critical failures; pause scaling, switch model, or rebuild prompts and validation before going live." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "AI準確率計算機", en: "AI Accuracy Calculator" }, href: "/tools/ai/ai-accuracy-calculator" },
  { label: { zh: "模型延遲計算機", en: "Model Latency Calculator" }, href: "/tools/ai/model-latency-calculator" },
  { label: { zh: "AI模型比較器", en: "AI Model Comparison" }, href: "/tools/ai/ai-model-comparison" },
  { label: { zh: "AI Token成本計算機", en: "AI Token Cost Calculator" }, href: "/tools/ai/ai-token-cost-calculator" },
];

const ui = {
  zh: {
    badge: "AI · Error Rate · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "AI 錯誤率計算機 · Error Rate", subtitle: "用總請求數、錯誤率與重試策略算出失敗請求數、重試成本與可靠度分數",
    intro: "AI Error Rate Calculator 依據月總請求數、錯誤率與重試策略（保守、標準或積極），計算每月失敗請求數、重試額外成本與可靠度分數，協助你判斷服務穩定度是否達標、該採哪種重試與降級策略、是否需要加上輸出驗證與後備路徑，讓你在擴大 AI 服務前就把失敗成本算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以你輸入的平均錯誤率估算失敗與重試成本，未含錯誤類型分布、速率限制、超時退避與下游連鎖失敗；實際可靠度請以真實監控與事故報告為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立錯誤率範例", examplePreview: "可靠度預覽", examplePerson: "月總請求數", fillExample: "一鍵填入標準重試範例", previewActivePath: "填入積極重試範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入月總請求數、錯誤率與重試策略", examplesHelper: "先用範例理解請求數與錯誤率如何決定失敗數與重試成本，再改成自己的服務數據。",
    metric: "公制", imperial: "占比檢視", exampleCards: "範例卡", baselineExample: "標準重試模式", activeExample: "積極重試示範", baselineExampleNote: "請求 100000 · 錯誤 3% · 標準", activeExampleNote: "請求 100000 · 錯誤 3% · 積極", carbsLabel: "重試成本", carbsName: "美元", proteinLabel: "可靠度分數", flowDemo: "錯誤率", calculator: "計算機",
    weight: "月總請求數", tdee: "錯誤率 (%)", goal: "重試策略", goalCut: "保守 (×1 重試)", goalMaintain: "標準 (×2 重試)", goalBulk: "積極 (×4 重試)",
    resultCard: "錯誤率結果", unit: "次 (每月失敗請求)", primaryValue: "主要數值", maintenanceTarget: "可靠度分數", actionTarget: "失敗數", estimatedTdee: "錯誤率", maintenance: "分", fatLossTarget: "次",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格錯誤率水準判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前錯誤率放進常見區間；這是規劃參考，不是事故結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把錯誤率結果轉成可執行的可靠度改善策略", conversionNote: "L9 會連動目前計算結果，顯示可靠度分數、失敗數與重試成本提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前服務概況", dailyGap: "失敗數", weeklyTrend: "可靠度分數", motivation: "動力卡", keepMomentum: "從錯誤分析走向最穩定的服務可靠度節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的錯誤率結果帶回團隊", journeyHint: "用 AI 準確率計算機一起看，把錯誤率與模型品質一併納入上線決策。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用 AI 準確率計算機評估模型品質", nextActionItem2: "用模型延遲計算機評估重試延遲成本", nextActionItem3: "用 AI 模型比較器找出最可靠模型",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Requests → Reliability → Retry → ErrorRate", bmrStep: "請求數", deficitStep: "可靠度分數", trendStep: "重試策略", mealStep: "錯誤率",
    knowledge: "知識", knowledgeTitle: "錯誤率與可靠度分數在服務營運中的意義", definition: "定義", definitionText: "失敗請求數是月總請求乘以錯誤率所得；重試成本則把失敗數乘以重試倍數與單次成本估算；可靠度分數把錯誤率對照五個百分點門檻換算，衡量服務穩定度相對目標的達成度。", formula: "公式", formulaText: "失敗數 = 月總請求 × 錯誤率 ÷ 100。重試成本 = 失敗數 × 重試倍數 × 單次成本（$0.002）。可靠度分數 = (1 − 錯誤率 ÷ 20) × 100，下限 0 分。", limitations: "限制", limitationsText: "本工具以平均錯誤率估算；真實可靠度還受錯誤類型分布、速率限制、超時退避、下游連鎖失敗與尖峰負載影響，且不同錯誤的重試成本差異大。", interpretation: "解讀", interpretationText: "錯誤率超過五個百分點多需優化；可透過輸出格式驗證、提示穩定化、超時退避、後備模型與降級策略來降低失敗與重試成本。", context: "脈絡", contextText: "錯誤率結果應與模型準確率、延遲與模型比較一起看，才能在可靠度、速度與成本之間取得平衡。", example: "範例", exampleText: "月請求 100000、錯誤率 3%、標準重試（×2）→ 失敗 3000 次，重試成本約 $12，可靠度分數約 85 分。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "錯誤率的下一步工具", premiumTitle: "PRO 可靠度分析包", premiumText: "解鎖錯誤類型分布、超時退避模擬、下游連鎖失敗估算與多模型可靠度比較矩陣。", feat1: "錯誤類型分佈", feat2: "退避模擬", feat3: "串接估算", feat4: "可靠度矩陣",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供可靠度規劃與教育用途，不取代真實監控數據、事故報告或正式 SLA 審查。", relatedTools: "相關工具", relatedToolsText: "AI Accuracy · Model Latency · Model Comparison · Token Cost", references: "參考資料", referencesText: "服務可靠度工程文件；重試與退避策略指南；速率限制規格；SLA 與錯誤預算方法。",
    q1: "失敗數怎麼算的？", a1: "本工具以月總請求乘以錯誤率得失敗數，再乘重試倍數與單次成本估算重試成本；實際還受錯誤類型影響。",
    q2: "可靠度分數多少才合理？", a2: "可靠度分數越高代表越穩定；若分數偏低，建議加上輸出驗證、超時退避與後備模型路徑。",
    q3: "保守還是積極重試？", a3: "成本敏感場景用保守重試；高可用要求才用積極重試，並用模型比較評估可靠度與成本取捨。",
    q4: "錯誤率太高怎麼降低？", a4: "驗證輸出格式、穩定化提示、設定超時退避、改用較可靠模型、加後備路徑並監控錯誤類型分布。",
    q5: "要不要算重試延遲？", a5: "建議要。本工具估算重試成本；若重視體感速度，請另用模型延遲計算機評估重試帶來的額外延遲。",
    q6: "這個工具能取代監控嗎？", a6: "不能。它只是快速估算與教育用途；實際可靠度應以真實監控數據與事故報告為準。",
  },
  en: {
    badge: "AI · Error Rate · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "AI Error Rate Calculator", subtitle: "Compute failed requests, retry cost, and reliability score from total requests, error rate, and retry policy",
    intro: "This calculator uses monthly total requests, error rate, and retry policy (conservative, standard, or aggressive) to compute monthly failed requests, extra retry cost, and a reliability score, helping you judge whether service stability meets the bar, which retry and degradation strategy to adopt, and whether to add output validation and fallback paths, so you compute failure cost clearly before scaling an AI service.",
    trustNoteLabel: "Note:", trustNote: "This tool estimates failures and retry cost from the average error rate you enter, excluding error-type distribution, rate limits, timeout backoff, and downstream cascading failures; for real reliability, follow actual monitoring and incident reports.",
    quickActionCard: "Quick Action Card", tryExample: "Create an error-rate example instantly", examplePreview: "Reliability preview", examplePerson: "Monthly total requests", fillExample: "One-click standard retry example", previewActivePath: "Fill aggressive retry example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter monthly total requests, error rate, and retry policy", examplesHelper: "Start with an example to see how request count and error rate set failures and retry cost, then replace with your own service data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard retry mode", activeExample: "Aggressive retry demo", baselineExampleNote: "requests 100000 · error 3% · standard", activeExampleNote: "requests 100000 · error 3% · aggressive", carbsLabel: "Retry cost", carbsName: "USD", proteinLabel: "Reliability score", flowDemo: "Error rate", calculator: "Calculator",
    weight: "Monthly total requests", tdee: "Error rate (%)", goal: "Retry policy", goalCut: "Conservative (×1 retry)", goalMaintain: "Standard (×2 retries)", goalBulk: "Aggressive (×4 retries)",
    resultCard: "Error Rate Result", unit: "count (monthly failed requests)", primaryValue: "Primary Value", maintenanceTarget: "Reliability score", actionTarget: "Failures", estimatedTdee: "Error rate", maintenance: "pts", fatLossTarget: "count",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card error-rate interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place current error rate into common zones. This is planning guidance, not an incident conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the error-rate result into an actionable reliability-improvement strategy", conversionNote: "L9 values update from the computed result: reliability score, failures, and retry-cost hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current service snapshot", dailyGap: "Failures", weeklyTrend: "Reliability score", motivation: "Motivation Card", keepMomentum: "Move from error analysis to the most stable service-reliability rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's error-rate result to your team", journeyHint: "Review it with the AI Accuracy Calculator to fold error rate and model quality into the deployment decision.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Assess model quality with the AI Accuracy Calculator", nextActionItem2: "Assess retry latency cost with the Model Latency Calculator", nextActionItem3: "Find the most reliable model with AI Model Comparison",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Requests → Reliability → Retry → ErrorRate", bmrStep: "Requests", deficitStep: "Reliability score", trendStep: "Retry policy", mealStep: "Error rate",
    knowledge: "Knowledge", knowledgeTitle: "What error rate and reliability score mean in service operations", definition: "Definition", definitionText: "Failed requests are monthly total requests times error rate; retry cost is failures times the retry multiplier and per-retry cost; the reliability score maps error rate against a five-percentage-point threshold, measuring how close service stability is to the target.", formula: "Formula", formulaText: "Failures = monthly requests × error rate ÷ 100. Retry cost = failures × retry multiplier × per-retry cost ($0.002). Reliability score = (1 − error rate ÷ 20) × 100, floored at 0 points.", limitations: "Limitations", limitationsText: "This tool estimates from an average error rate; real reliability is also affected by error-type distribution, rate limits, timeout backoff, downstream cascading failures, and peak load, and retry cost varies widely between error types.", interpretation: "Interpretation", interpretationText: "Error rate over five percentage points usually warrants optimization; reduce failures and retry cost with output-format validation, prompt stabilization, timeout backoff, fallback models, and degradation strategies.", context: "Context", contextText: "Error-rate results should be evaluated with model accuracy, latency, and model comparison to balance reliability, speed, and cost.", example: "Example", exampleText: "Monthly requests 100000, error rate 3%, standard retry (×2) → failures 3000, retry cost about $12, reliability score about 85 points.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for error rate", premiumTitle: "PRO Reliability Analytics Pack", premiumText: "Unlock error-type distribution, timeout-backoff simulation, downstream cascading-failure estimation, and a multi-model reliability comparison matrix.", feat1: "Error Type Dist", feat2: "Backoff Sim", feat3: "Cascade Estimate", feat4: "Reliability Matrix",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for reliability planning and education. It does not replace real monitoring data, incident reports, or formal SLA review.", relatedTools: "Related Tools", relatedToolsText: "AI Accuracy · Model Latency · Model Comparison · Token Cost", references: "References", referencesText: "Service reliability engineering docs; retry and backoff strategy guides; rate-limit specs; SLA and error-budget methods.",
    q1: "How are failures calculated?", a1: "This tool multiplies monthly requests by error rate for failures, then by the retry multiplier and per-retry cost for retry cost; actual is also affected by error types.",
    q2: "What reliability score is reasonable?", a2: "The higher the reliability score the more stable; if the score is low, add output validation, timeout backoff, and fallback model paths.",
    q3: "Conservative or aggressive retries?", a3: "Use conservative retries for cost-sensitive scenarios; use aggressive retries only for high-availability requirements, and assess reliability-cost trade-offs with Model Comparison.",
    q4: "How do I reduce a high error rate?", a4: "Validate output format, stabilize prompts, set timeout backoff, switch to a more reliable model, add fallback paths, and monitor error-type distribution.",
    q5: "Should I compute retry latency?", a5: "Recommended. This tool estimates retry cost; if perceived speed matters, use the Model Latency Calculator to assess the extra latency retries add.",
    q6: "Can this tool replace monitoring?", a6: "No. It is a quick estimate for education; real reliability should follow actual monitoring data and incident reports.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function retryMultiplier(mode: TierMode): number {
  if (mode === "relaxed") return 1;
  if (mode === "fast") return 4;
  return 2;
}

export default function AiErrorRateCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("100000");
  const [tdee, setTdee] = useState("3");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const requests = Number(weight);
    const errorRate = Number(tdee);
    if (requests <= 0 || errorRate < 0) return null;
    const failures = (requests * errorRate) / 100;
    const retryCost = failures * retryMultiplier(goal) * 0.002;
    const reliabilityScore = Math.max((1 - errorRate / 20) * 100, 0);
    return { failures, retryCost, reliabilityScore };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.reliabilityScore, 0) : "—";
  const fatDisplay = result ? fmt(result.failures, 0) : "—";
  const carbDisplay = result ? fmt(result.retryCost, 2) : "—";
  const totalDisplay = result ? fmt(result.failures, 0) : "—";

  function fillStandard() { setUnit("metric"); setWeight("100000"); setTdee("3"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("100000"); setTdee("3"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">3000</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">3000</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">#</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">$</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">#</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="ai-error-rate-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.failures, 0) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.reliabilityScore, 0) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Requests", note: t.bmrStep }, { label: "Reliability", note: t.deficitStep }, { label: "Retry", note: t.trendStep }, { label: "ErrorRate", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="ai-error-rate-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
