/**
 * Tier-analysis + first-page-preview smoke test for analyzePdf.ts.
 *
 * Exercises the real PyMuPDF worker:
 *   - a generated multi-line text PDF must classify as L1 (free path)
 *   - an invalid (non-PDF) buffer must be rejected
 *   - every successful analyze must return a non-empty first-page preview
 *     data URL (the L1+ paywall "hook")
 *
 * Honest environment handling: the analyze worker needs python3 + PyMuPDF
 * (fitz). If python3 is unavailable the suite SKIPS rather than failing — a
 * missing engine is an environment gap, not a code regression. Both this
 * sandbox and the Railway runtime (via nixpacks pyengine phase) provide it.
 *
 * The simple-text fixture is generated BY PyMuPDF itself (not a hand-crafted
 * PDF), so the embedded text layer is laid out across multiple lines exactly
 * as the analyzer reads it — a reliable representation of a real text page.
 */
import { describe, it, expect } from "vitest";
import { execFileSync } from "node:child_process";

function pythonAvailable(): boolean {
  const bin = process.env.PYTHON_BIN || "python3";
  for (const candidate of [bin, "python3", "python"]) {
    try {
      execFileSync(candidate, ["-c", "import fitz"], { stdio: "ignore", timeout: 15_000 });
      return true;
    } catch {
      /* try next */
    }
  }
  return false;
}

/** Generate a genuine multi-line single-column text PDF via PyMuPDF. */
function makeSimpleTextPdf(): Buffer {
  const bin = process.env.PYTHON_BIN || "python3";
  const code = [
    "import sys, fitz",
    "d = fitz.open()",
    "p = d.new_page()",
    "line = 'This is a simple single column text PDF used for the L1 tier test. '",
    "y = 72",
    "for i in range(30):",
    "    p.insert_text((72, y), line + str(i)); y += 18",
    "sys.stdout.buffer.write(d.tobytes())",
  ].join("\n");
  return execFileSync(bin, ["-c", code], { maxBuffer: 16 * 1024 * 1024 });
}

const HAVE_PY = pythonAvailable();

describe.skipIf(!HAVE_PY)("analyzePdf", () => {
  it("classifies a simple text PDF as L1 and returns a first-page preview", async () => {
    const { analyzePdf } = await import("./analyzePdf");
    const pdf = makeSimpleTextPdf();
    const res = await analyzePdf(pdf, "simple.pdf");
    expect(res.tier).toBe("L1");
    expect(res.previewUrl.startsWith("data:image/png;base64,")).toBe(true);
    expect(res.previewUrl.length).toBeGreaterThan(100);
  }, 60_000);

  it("rejects a non-PDF buffer", async () => {
    const { analyzePdf } = await import("./analyzePdf");
    await expect(analyzePdf(Buffer.from("not a pdf"), "x.txt")).rejects.toThrow(/valid PDF/i);
  });
});
