// @profile B
// Profile B · Calculator-AI · AiAccuracyCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< 60%", label: { zh: "不及格", en: "Failing" }, desc: { zh: "準確率偏低，模型尚未可用，建議重新檢視標註品質、特徵工程與訓練資料量。", en: "Low accuracy; the model is not usable yet—revisit label quality, feature engineering, and training data size." } },
  { key: "low", range: "60–75%", label: { zh: "起步", en: "Early" }, desc: { zh: "起步水準，可作概念驗證，但離上線仍有距離，需持續迭代與資料擴充。", en: "Early-stage level; fine for proof of concept but far from production—keep iterating and expanding data." } },
  { key: "healthy", range: "75–85%", label: { zh: "可用", en: "Usable" }, desc: { zh: "多數一般任務可用區間，建議搭配人工複核與信心門檻把關高風險樣本。", en: "Usable band for many general tasks; pair with human review and a confidence threshold for high-risk samples." } },
  { key: "good", range: "85–92%", label: { zh: "良好", en: "Good" }, desc: { zh: "良好水準，已適合多數產品場景，可開始監控漂移與分群表現差異。", en: "Good level; suitable for most product scenarios—start monitoring drift and per-segment performance gaps." } },
  { key: "strong", range: "92–97%", label: { zh: "優異", en: "Strong" }, desc: { zh: "優異表現，接近商用高標，注意是否過擬合並用獨立測試集驗證。", en: "Strong performance near commercial high bar; watch for overfitting and validate on an independent test set." } },
  { key: "elite", range: "> 97%", label: { zh: "頂尖", en: "Elite" }, desc: { zh: "頂尖水準，務必確認測試集無洩漏、樣本具代表性，並評估邊界案例的真實表現。", en: "Elite level; confirm no test-set leakage, representative samples, and assess real edge-case behavior." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "模型延遲計算機", en: "Model Latency Calculator" }, href: "/tools/ai/model-latency-calculator" },
  { label: { zh: "AI錯誤率計算機", en: "AI Error Rate Calculator" }, href: "/tools/ai/ai-error-rate-calculator" },
  { label: { zh: "AI模型比較器", en: "AI Model Comparison" }, href: "/tools/ai/ai-model-comparison" },
  { label: { zh: "AI Token成本計算機", en: "AI Token Cost Calculator" }, href: "/tools/ai/ai-token-cost-calculator" },
];

const ui = {
  zh: {
    badge: "AI · Accuracy · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "AI 準確率計算機 · Accuracy", subtitle: "用正確預測數、總預測數與評估嚴格度算出準確率、誤判率與品質分數",
    intro: "AI Accuracy Calculator 依據正確預測數、總預測數與評估嚴格度（寬鬆、標準或嚴格），計算模型準確率、誤判率與綜合品質分數，協助您判斷模型是否達到上線水準、該選哪種信心門檻、是否需要更多訓練資料與人工複核，讓您在部署 AI 模型前就把準確率衡量清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以您輸入的正確數與總數估算整體準確率，未含精確率、召回率、F1、混淆矩陣與分群表現；實際模型品質請以完整評估報告與獨立測試集為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立準確率範例", examplePreview: "品質預覽", examplePerson: "正確預測數", fillExample: "一鍵填入標準評估範例", previewActivePath: "填入嚴格評估範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入正確預測數、總預測數與評估嚴格度", examplesHelper: "先用範例理解正確數與總數如何決定準確率與品質分數，再改成自己的評估數據。",
    metric: "公制", imperial: "占比檢視", exampleCards: "範例卡", baselineExample: "標準評估模式", activeExample: "嚴格評估示範", baselineExampleNote: "正確 900 · 總數 1000 · 標準", activeExampleNote: "正確 900 · 總數 1000 · 嚴格", carbsLabel: "誤判率", carbsName: "百分比", proteinLabel: "品質分數", flowDemo: "總預測數", calculator: "計算機",
    weight: "正確預測數", tdee: "總預測數", goal: "評估嚴格度", goalCut: "寬鬆 (門檻 0.85)", goalMaintain: "標準 (門檻 0.92)", goalBulk: "嚴格 (門檻 0.98)",
    resultCard: "準確率結果", unit: "% (整體準確率)", primaryValue: "主要數值", maintenanceTarget: "品質分數", actionTarget: "準確率", estimatedTdee: "總預測數", maintenance: "分", fatLossTarget: "%",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格準確率水準判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前準確率放進常見區間；這是規劃參考，不是統計結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把準確率結果轉成可執行的模型改善策略", conversionNote: "L9 會連動目前計算結果，顯示品質分數、準確率與誤判率提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前評估概況", dailyGap: "準確率", weeklyTrend: "品質分數", motivation: "動力卡", keepMomentum: "從準確率分析走向最穩定的模型表現節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的準確率結果帶回團隊", journeyHint: "用模型延遲計算機一起看，把準確率與延遲一併納入上線決策。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用模型延遲計算機評估即時回應能力", nextActionItem2: "用 AI 錯誤率計算機拆解誤判成本", nextActionItem3: "用 AI 模型比較器找出性價比最佳模型",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Correct → Quality → Tier → Total", bmrStep: "正確數", deficitStep: "品質分數", trendStep: "嚴格度", mealStep: "總數",
    knowledge: "知識", knowledgeTitle: "準確率與品質分數在模型評估中的意義", definition: "定義", definitionText: "準確率是正確預測數除以總預測數的比例；品質分數則把準確率對照評估嚴格度門檻換算，衡量模型相對目標標準的達成度，是判斷是否可上線的核心指標。", formula: "公式", formulaText: "準確率 = 正確預測數 ÷ 總預測數 × 100%。誤判率 = 100% − 準確率。品質分數 = 準確率 ÷ 嚴格度門檻 × 100，上限 100 分。", limitations: "限制", limitationsText: "本工具以單一整體準確率估算；真實品質還受類別不平衡、精確率與召回率取捨、混淆矩陣、資料漂移與測試集代表性影響，且高風險場景需更嚴格的指標。", interpretation: "解讀", interpretationText: "準確率低於 85% 多需再優化；可透過擴充訓練資料、改善標註品質、特徵工程、模型微調與信心門檻把關來提升表現。", context: "脈絡", contextText: "準確率結果應與模型延遲、錯誤率成本與模型比較一起看，才能在品質、速度與成本之間取得平衡。", example: "範例", exampleText: "正確 900、總數 1000、標準門檻（0.92）→ 準確率 90%，誤判率 10%，品質分數約 98 分。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "準確率的下一步工具", premiumTitle: "PRO 模型評估分析包", premiumText: "解鎖精確率召回率 F1、混淆矩陣、分群表現比較與信心門檻校正模擬矩陣。", feat1: "精確率召回", feat2: "混淆矩陣", feat3: "分群比較", feat4: "閾值校準",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供模型評估規劃與教育用途，不取代完整評估報告、獨立測試集驗證或正式上線審查。", relatedTools: "相關工具", relatedToolsText: "Model Latency · AI Error Rate · Model Comparison · Token Cost", references: "參考資料", referencesText: "機器學習評估指標標準文件；精確率召回率定義；混淆矩陣方法；測試集設計與資料漂移監控指南。",
    q1: "準確率怎麼算的？", a1: "本工具以正確預測數除以總預測數得整體準確率；實際還受類別不平衡與精確率召回率取捨影響。",
    q2: "品質分數多少才合理？", a2: "品質分數越高代表越接近評估嚴格度門檻；若分數偏低，建議擴充資料、改善標註或調整信心門檻。",
    q3: "寬鬆還是嚴格門檻？", a3: "一般任務可用寬鬆或標準門檻；醫療、金融等高風險場景才用嚴格門檻，並搭配模型比較評估取捨。",
    q4: "準確率太低怎麼提升？", a4: "擴充訓練資料、改善標註品質、特徵工程、模型微調、設定信心門檻並對高風險樣本加人工複核。",
    q5: "要不要看精確率召回率？", a5: "建議要。本工具用整體準確率快速估算；若類別不平衡，請改看精確率、召回率與 F1 才不會誤判。",
    q6: "這個工具能取代正式評估嗎？", a6: "不能。它只是快速估算與教育用途；實際品質應以完整評估報告與獨立測試集驗證為準。",
  },
  en: {
    badge: "AI · Accuracy · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "AI Accuracy Calculator", subtitle: "Compute accuracy, error rate, and quality score from correct predictions, total predictions, and evaluation strictness",
    intro: "This calculator uses correct predictions, total predictions, and evaluation strictness (relaxed, standard, or strict) to compute model accuracy, error rate, and a composite quality score, helping you judge whether the model reaches production level, which confidence threshold to choose, and whether more training data and human review are needed, so you measure accuracy clearly before deploying an AI model.",
    trustNoteLabel: "Note:", trustNote: "This tool estimates overall accuracy from the correct count and total you enter, excluding precision, recall, F1, confusion matrix, and per-segment performance; for true model quality, follow a full evaluation report and an independent test set.",
    quickActionCard: "Quick Action Card", tryExample: "Create an accuracy example instantly", examplePreview: "Quality preview", examplePerson: "Correct predictions", fillExample: "One-click standard evaluation example", previewActivePath: "Fill strict evaluation example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter correct predictions, total predictions, and evaluation strictness", examplesHelper: "Start with an example to see how correct count and total set accuracy and quality score, then replace with your own evaluation data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard evaluation mode", activeExample: "Strict evaluation demo", baselineExampleNote: "correct 900 · total 1000 · standard", activeExampleNote: "correct 900 · total 1000 · strict", carbsLabel: "Error rate", carbsName: "percent", proteinLabel: "Quality score", flowDemo: "Total predictions", calculator: "Calculator",
    weight: "Correct predictions", tdee: "Total predictions", goal: "Evaluation strictness", goalCut: "Relaxed (threshold 0.85)", goalMaintain: "Standard (threshold 0.92)", goalBulk: "Strict (threshold 0.98)",
    resultCard: "Accuracy Result", unit: "% (overall accuracy)", primaryValue: "Primary Value", maintenanceTarget: "Quality score", actionTarget: "Accuracy", estimatedTdee: "Total predictions", maintenance: "pts", fatLossTarget: "%",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card accuracy-level interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place current accuracy into common zones. This is planning guidance, not a statistical conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the accuracy result into an actionable model-improvement strategy", conversionNote: "L9 values update from the computed result: quality score, accuracy, and error-rate hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current evaluation snapshot", dailyGap: "Accuracy", weeklyTrend: "Quality score", motivation: "Motivation Card", keepMomentum: "Move from accuracy analysis to the most stable model-performance rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's accuracy result to your team", journeyHint: "Review it with the Model Latency Calculator to fold accuracy and latency into the deployment decision.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Assess real-time response with the Model Latency Calculator", nextActionItem2: "Break down misclassification cost with the AI Error Rate Calculator", nextActionItem3: "Find the best-value model with AI Model Comparison",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Correct → Quality → Tier → Total", bmrStep: "Correct", deficitStep: "Quality score", trendStep: "Strictness", mealStep: "Total",
    knowledge: "Knowledge", knowledgeTitle: "What accuracy and quality score mean in model evaluation", definition: "Definition", definitionText: "Accuracy is correct predictions divided by total predictions; the quality score maps accuracy against the strictness threshold, measuring how close the model is to the target bar, the core indicator of production readiness.", formula: "Formula", formulaText: "Accuracy = correct predictions ÷ total predictions × 100%. Error rate = 100% − accuracy. Quality score = accuracy ÷ strictness threshold × 100, capped at 100 points.", limitations: "Limitations", limitationsText: "This tool estimates from a single overall accuracy; real quality is also affected by class imbalance, precision-recall trade-offs, confusion matrix, data drift, and test-set representativeness, and high-risk scenarios need stricter metrics.", interpretation: "Interpretation", interpretationText: "Accuracy below 85% usually warrants more optimization; improve performance by expanding training data, better labeling, feature engineering, fine-tuning, and confidence-threshold gating.", context: "Context", contextText: "Accuracy results should be evaluated with model latency, error-rate cost, and model comparison to balance quality, speed, and cost.", example: "Example", exampleText: "Correct 900, total 1000, standard threshold (0.92) → accuracy 90%, error rate 10%, quality score about 98 points.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for accuracy", premiumTitle: "PRO Model Evaluation Analytics Pack", premiumText: "Unlock precision-recall-F1, confusion matrix, per-segment performance comparison, and a confidence-threshold calibration simulation matrix.", feat1: "Precision Recall", feat2: "Confusion Matrix", feat3: "Segment Compare", feat4: "Threshold Calib",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for model-evaluation planning and education. It does not replace a full evaluation report, independent test-set validation, or formal production review.", relatedTools: "Related Tools", relatedToolsText: "Model Latency · AI Error Rate · Model Comparison · Token Cost", references: "References", referencesText: "Standard machine-learning evaluation-metric docs; precision-recall definitions; confusion-matrix methods; test-set design and data-drift monitoring guides.",
    q1: "How is accuracy calculated?", a1: "This tool divides correct predictions by total predictions for overall accuracy; actual is also affected by class imbalance and precision-recall trade-offs.",
    q2: "What quality score is reasonable?", a2: "The higher the quality score the closer to the strictness threshold; if the score is low, expand data, improve labeling, or adjust the confidence threshold.",
    q3: "Relaxed or strict threshold?", a3: "Use relaxed or standard thresholds for general tasks; use strict thresholds only for high-risk medical or financial scenarios, and assess trade-offs with Model Comparison.",
    q4: "How do I improve low accuracy?", a4: "Expand training data, improve label quality, feature engineering, fine-tuning, set a confidence threshold, and add human review for high-risk samples.",
    q5: "Should I look at precision and recall?", a5: "Recommended. This tool uses overall accuracy for a quick estimate; if classes are imbalanced, look at precision, recall, and F1 to avoid misjudgment.",
    q6: "Can this tool replace formal evaluation?", a6: "No. It is a quick estimate for education; real quality should follow a full evaluation report and independent test-set validation.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function strictnessThreshold(mode: TierMode): number {
  if (mode === "relaxed") return 0.85;
  if (mode === "fast") return 0.98;
  return 0.92;
}

export default function AiAccuracyCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("900");
  const [tdee, setTdee] = useState("1000");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const correct = Number(weight);
    const total = Number(tdee);
    if (correct < 0 || total <= 0 || correct > total) return null;
    const accuracy = (correct / total) * 100;
    const errorRate = 100 - accuracy;
    const qualityScore = Math.min((accuracy / 100 / strictnessThreshold(goal)) * 100, 100);
    return { accuracy, errorRate, qualityScore };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.qualityScore, 0) : "—";
  const fatDisplay = result ? fmt(result.accuracy, 1) : "—";
  const carbDisplay = result ? fmt(result.errorRate, 1) : "—";
  const totalDisplay = result ? fmt(result.accuracy, 1) : "—";

  function fillStandard() { setUnit("metric"); setWeight("900"); setTdee("1000"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("900"); setTdee("1000"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl text-4xl font-black tracking-tight text-slate-950 md:text-6xl">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">90.0</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">90.0</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">pts</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">%</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">%</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">%</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="ai-accuracy-calculator-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.accuracy, 1) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.qualityScore, 0) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Correct", note: t.bmrStep }, { label: "Quality", note: t.deficitStep }, { label: "Tier", note: t.trendStep }, { label: "Total", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L14-Knowledge-FAQ · L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section aria-label="L14 FAQ after ad slot: AD 廣告位 · Advertisement" className="rounded-[2rem] border border-slate-200 bg-white p-4 shadow-sm md:p-5"><AdSlot slot="ai-accuracy-calculator-faq" position="inline" /></section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7">{/* L17-TrustRelatedReferences */}<p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
