// @profile B
// Profile B · Calculator-AI · FineTuningCostCalculator（GOLD-STANDARD-001 compatible）

import { useMemo, useState } from "react";
import { AdSenseWrapper } from "@/components/AdSenseWrapper";
import { AdSlot } from "@/components/business/AdSlot";
import { PremiumGate } from "@/components/business/PremiumGate";
import { useLanguage } from "@/contexts/LanguageContext";

type Lang = "zh" | "en";
type LocalText = { zh: string; en: string };
type AffiliateItem = { label: LocalText; href: string };
type TierMode = "relaxed" | "standard" | "fast";
const l = (v: LocalText, lang: Lang) => v[lang];
const fmt = (v: number, d = 0) => Number.isFinite(v) ? v.toFixed(d) : "—";

const bands = [
  { key: "tiny", range: "< $50", label: { zh: "極省", en: "Minimal" }, desc: { zh: "微調成本極低，適合小資料集驗證或提示工程替代，財務風險小。", en: "Very low fine-tuning cost—great for small-dataset validation or prompt-engineering alternative, low risk." } },
  { key: "low", range: "$50–200", label: { zh: "輕量", en: "Light" }, desc: { zh: "輕量微調區間，成本可控，記得保留多輪實驗與驗證集的緩衝。", en: "Light fine-tuning band; cost is manageable—keep buffer for multiple experiments and validation sets." } },
  { key: "healthy", range: "$200–800", label: { zh: "標準", en: "Standard" }, desc: { zh: "多數正式微調常見區間，宜開始監控每輪成本與資料集品質回報。", en: "Common production fine-tuning band; start monitoring per-epoch cost and dataset-quality returns." } },
  { key: "good", range: "$800–2500", label: { zh: "大型", en: "Large" }, desc: { zh: "已進入大型微調成本，建議比較輪數收斂、LoRA 與較小基座模型。", en: "Large fine-tuning cost; compare epoch convergence, LoRA, and smaller base models." } },
  { key: "strong", range: "$2500–8000", label: { zh: "重量級", en: "Heavy" }, desc: { zh: "成本偏高，務必比較全參數與參數高效微調、資料蒸餾與外包訓練。", en: "Heavy cost; compare full vs parameter-efficient fine-tuning, data distillation, and outsourced training." } },
  { key: "elite", range: "> $8000", label: { zh: "企業級", en: "Enterprise" }, desc: { zh: "企業級訓練投資，建議談量價、評估自建 GPU 叢集並嚴格控管實驗。", en: "Enterprise training investment; negotiate volume pricing, assess self-hosted GPU clusters, and strictly control experiments." } },
] as const;

const affiliateItems: AffiliateItem[] = [
  { label: { zh: "AI Token成本計算機", en: "AI Token Cost Calculator" }, href: "/tools/ai/ai-token-cost-calculator" },
  { label: { zh: "AI專案成本計算機", en: "AI Project Cost Calculator" }, href: "/tools/ai/ai-project-cost-calculator" },
  { label: { zh: "AI模型比較器", en: "AI Model Comparison" }, href: "/tools/ai/ai-model-comparison" },
  { label: { zh: "AI投報率計算機", en: "AI ROI Calculator" }, href: "/tools/ai/ai-roi-calculator" },
];

const ui = {
  zh: {
    badge: "AI · 微調成本 · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "微調成本計算機 · Fine-Tuning Cost", subtitle: "用資料集 token 量、訓練輪數與模型大小階層算出微調總成本與每輪成本",
    intro: "Fine-Tuning Cost Calculator 依據資料集 token 量（以百萬為單位）、訓練輪數與模型大小階層（小型、標準或大型），算出微調訓練總成本、每輪成本與訓練 token 總量占比，協助您判斷預算是否合理、輪數是否過多、該用全參數還是參數高效微調，讓您在啟動任何微調前就把訓練花費算清楚。",
    trustNoteLabel: "注意事項：", trustNote: "本工具以每百萬 token 訓練單價估算，未含資料清洗、驗證集、多次實驗與託管推論費；實際費用請以各平台官方訓練計價頁為準。",
    quickActionCard: "快速範例卡", tryExample: "一鍵建立微調範例", examplePreview: "成本預覽", examplePerson: "資料集 (M token)", fillExample: "一鍵填入標準範例", previewActivePath: "填入大型模型範例",
    examplesCalculator: "範例 → 計算機", enterValues: "輸入 資料集 token 量、訓練輪數與模型階層", examplesHelper: "先用範例理解資料量、輪數與模型階層如何決定總成本與每輪成本，再改成自己的訓練數據。",
    metric: "公制", imperial: "占比檢視", exampleCards: "範例卡", baselineExample: "標準微調模式", activeExample: "大型模型示範", baselineExampleNote: "資料 5M · 輪數 3 · 標準", activeExampleNote: "資料 5M · 輪數 3 · 大型", carbsLabel: "每輪成本", carbsName: "美元", proteinLabel: "每輪成本占比", flowDemo: "訓練輪數", calculator: "計算機",
    weight: "資料集 (百萬 token)", tdee: "訓練輪數 (輪)", goal: "模型大小階層", goalCut: "小型 ($8/1M)", goalMaintain: "標準 ($25/1M)", goalBulk: "大型 ($60/1M)",
    resultCard: "微調成本結果", unit: "USD (微調總成本)", primaryValue: "主要數值", maintenanceTarget: "每輪成本占比", actionTarget: "總成本", estimatedTdee: "訓練輪數", maintenance: "%", fatLossTarget: "USD",
    resultIntelligence: "結果解讀", tdeeMatrix: "六格微調總成本判讀矩陣", tdeeMatrixNote: "L7 固定六格，將目前微調總成本放進常見區間；這是規劃參考，不是會計結論。",
    emotionConversionLayer: "情緒與轉換層", turnIntoPlan: "把微調結果轉成可執行的訓練成本控制策略", conversionNote: "L9 會連動目前計算結果，顯示每輪成本占比、總成本與訓練輪數提示。",
    progressInsight: "進度洞察卡", possibleTarget: "目前用量概況", dailyGap: "總成本", weeklyTrend: "每輪占比", motivation: "動力卡", keepMomentum: "從成本分析走向最划算的微調輪數節奏",
    saveShareJourney: "儲存 / 分享", journeyTitle: "把今天的微調結果帶回團隊", journeyHint: "用 AI 投報率計算機一起看，把微調成本對照預期效益決定是否值得訓練。",
    nextActionLabel: "下一步行動", nextActionTitle: "將結果接到下一個工具", nextActionItem1: "用 AI Token 成本計算機比較直接 API 推論", nextActionItem2: "用 AI 模型比較器評估基座模型性價比", nextActionItem3: "用 AI 投報率計算機評估微調是否值得",
    shareLinkBtn: "📋 複製結果連結", shareNativeBtn: "📤 分享給團隊", shareCopiedToast: "已複製到剪貼簿 ✓",
    decisionPath: "決策路徑", decisionTitle: "Dataset → EpochShare → ModelSize → Epochs", bmrStep: "資料集 token", deficitStep: "每輪占比", trendStep: "模型階層", mealStep: "訓練輪數",
    knowledge: "知識", knowledgeTitle: "每輪成本占比在微調預算中的意義", definition: "定義", definitionText: "微調成本估算是把資料集 token 量乘訓練輪數得訓練總 token，再依模型大小單價換算成本；每輪成本占比衡量單輪訓練花費相對於總成本的比重，是判斷輪數是否過多的核心指標。", formula: "公式", formulaText: "訓練總 token = 資料集 token(百萬) × 100 萬 × 輪數。微調總成本 = 訓練總 token ÷ 100 萬 × 每百萬單價。每輪成本 = 總成本 ÷ 輪數。每輪占比 = 每輪成本 ÷ 總成本 × 100%。", limitations: "限制", limitationsText: "本工具以訓練 token 單價估算；真實費用還受資料清洗、驗證集、多次超參數搜尋、託管推論與不同平台計價差異影響，且全參數與 LoRA 成本差距很大。", interpretation: "解讀", interpretationText: "微調總成本超過 $800 宜開始優化；可透過減少輪數、使用 LoRA 等參數高效微調、精簡資料集或改用較小基座模型來降低訓練花費。", context: "脈絡", contextText: "微調成本應與 AI Token 成本、模型比較與投報率一起看，才能在效果、成本與維運之間取得平衡。", example: "範例", exampleText: "資料集 5M token、標準階層 $25/1M、訓練 3 輪 → 訓練總 token 1500 萬，總成本 $375，每輪成本 $125。",
    faq: "FAQ", commonQuestions: "常見問題", affiliate: "推薦工具", affiliateTitle: "微調的下一步工具", premiumTitle: "PRO 微調成本分析包", premiumText: "解鎖各平台即時訓練單價、LoRA 與全參數成本比較、超參數搜尋預算與託管推論長期成本矩陣。", feat1: "即時報價", feat2: "LoRA對全量", feat3: "超參搜尋", feat4: "代管矩陣",
    trustReferences: "信任聲明 · 相關工具 · 參考資料", trust: "信任聲明", trustText: "本工具只供成本規劃與教育用途，不取代各平台官方訓練計價、帳單明細或合約報價。", relatedTools: "相關工具", relatedToolsText: "AI Token Cost · AI Project Cost · Model Comparison · AI ROI", references: "參考資料", referencesText: "各平台官方微調計價頁；LoRA 與參數高效微調研究；訓練輪數收斂分析；GPU 訓練成本指南。",
    q1: "微調總成本怎麼算的？", a1: "本工具把資料集 token 量乘訓練輪數得訓練總 token，再依模型大小單價換算成本；實際還受清洗與多次實驗影響。",
    q2: "每輪成本占比多少才合理？", a2: "輪數越多單輪占比越低但總成本越高；若已收斂仍增加輪數只會浪費預算，應監控驗證集表現決定停點。",
    q3: "該用全參數還是 LoRA？", a3: "小資料集與快速迭代適合 LoRA 等參數高效微調，成本低很多；大幅改變行為才考慮全參數，並用模型比較器評估。",
    q4: "微調成本太高怎麼降？", a4: "減少訓練輪數、使用 LoRA、精簡與去重資料集、改用較小基座模型，並先用提示工程驗證是否真的需要微調。",
    q5: "微調一定比直接 API 划算嗎？", a5: "不一定。低頻使用時直接 API 推論常更划算；高頻且需穩定風格時微調才有規模效益，請用投報率計算機評估。",
    q6: "這個工具能取代官方報價嗎？", a6: "不能。它只是快速估算與教育用途；實際費用應以各平台官方訓練計價頁與帳單明細為準。",
  },
  en: {
    badge: "AI · Fine-Tuning Cost · Gold Tool", switchToEnglish: "Switch to English", switchToChinese: "切換到中文", chineseShort: "中", englishShort: "EN",
    title: "Fine-Tuning Cost Calculator", subtitle: "Compute total fine-tuning cost and per-epoch cost from dataset token volume, training epochs, and model-size tier",
    intro: "This calculator uses dataset token volume (in millions), training epochs, and model-size tier (small, standard, or large) to compute total fine-tuning training cost, per-epoch cost, and training-token share, helping you judge whether the budget is reasonable, whether epochs are excessive, and whether to use full or parameter-efficient fine-tuning, so you compute training spend clearly before launching any fine-tuning run.",
    trustNoteLabel: "Note:", trustNote: "This tool estimates from a per-million-token training price, excluding data cleaning, validation sets, multiple experiments, and hosted inference fees; for actual cost, follow each platform's official training pricing page.",
    quickActionCard: "Quick Action Card", tryExample: "Create a fine-tuning example instantly", examplePreview: "Cost preview", examplePerson: "Dataset (M tokens)", fillExample: "One-click standard example", previewActivePath: "Fill large model example",
    examplesCalculator: "Examples → Calculator", enterValues: "Enter dataset token volume, training epochs, and model tier", examplesHelper: "Start with an example to see how data volume, epochs, and model tier set the total and per-epoch cost, then replace with your own training data.",
    metric: "Metric", imperial: "Share view", exampleCards: "Example cards", baselineExample: "Standard fine-tuning mode", activeExample: "Large model demo", baselineExampleNote: "data 5M · epochs 3 · standard", activeExampleNote: "data 5M · epochs 3 · large", carbsLabel: "Per-epoch cost", carbsName: "USD", proteinLabel: "Per-epoch cost share", flowDemo: "Training epochs", calculator: "Calculator",
    weight: "Dataset (million tokens)", tdee: "Training epochs (epochs)", goal: "Model-size tier", goalCut: "Small ($8/1M)", goalMaintain: "Standard ($25/1M)", goalBulk: "Large ($60/1M)",
    resultCard: "Fine-Tuning Cost Result", unit: "USD (total fine-tuning cost)", primaryValue: "Primary Value", maintenanceTarget: "Per-epoch cost share", actionTarget: "Total cost", estimatedTdee: "Training epochs", maintenance: "%", fatLossTarget: "USD",
    resultIntelligence: "Result Intelligence", tdeeMatrix: "Six-card total fine-tuning-cost interpretation matrix", tdeeMatrixNote: "L7 uses six fixed cards to place the current total fine-tuning cost into common zones. This is planning guidance, not an accounting conclusion.",
    emotionConversionLayer: "Emotion + Conversion Layer", turnIntoPlan: "Turn the fine-tuning result into an actionable training cost-control strategy", conversionNote: "L9 values update from the computed result: per-epoch cost share, total cost, and training-epochs hint.",
    progressInsight: "Progress Insight Card", possibleTarget: "Current usage snapshot", dailyGap: "Total cost", weeklyTrend: "Per-epoch share", motivation: "Motivation Card", keepMomentum: "Move from cost analysis to the best-value fine-tuning epoch rhythm",
    saveShareJourney: "Save / Share", journeyTitle: "Take today's fine-tuning result to your team", journeyHint: "Review it with the AI ROI Calculator to weigh fine-tuning cost against expected benefits and decide if it is worth training.",
    nextActionLabel: "Next actions", nextActionTitle: "Connect this result to the next tool", nextActionItem1: "Compare direct API inference with the AI Token Cost Calculator", nextActionItem2: "Assess base-model value with AI Model Comparison", nextActionItem3: "Assess whether fine-tuning is worth it with the AI ROI Calculator",
    shareLinkBtn: "📋 Copy result link", shareNativeBtn: "📤 Share with team", shareCopiedToast: "Copied to clipboard ✓",
    decisionPath: "Decision Path", decisionTitle: "Dataset → EpochShare → ModelSize → Epochs", bmrStep: "Dataset tokens", deficitStep: "Per-epoch share", trendStep: "Model tier", mealStep: "Training epochs",
    knowledge: "Knowledge", knowledgeTitle: "What per-epoch cost share means in fine-tuning budgets", definition: "Definition", definitionText: "Fine-tuning cost estimation multiplies dataset token volume by training epochs for total training tokens, then converts by model-size unit price into cost; per-epoch cost share measures single-epoch spend relative to total cost, the core indicator for whether epochs are excessive.", formula: "Formula", formulaText: "Total training tokens = dataset tokens (millions) × 1M × epochs. Total fine-tuning cost = total training tokens ÷ 1M × price per million. Per-epoch cost = total cost ÷ epochs. Per-epoch share = per-epoch cost ÷ total cost × 100%.", limitations: "Limitations", limitationsText: "This tool estimates from a training-token unit price; real cost is also affected by data cleaning, validation sets, multiple hyperparameter searches, hosted inference, and platform pricing differences, and full vs LoRA costs differ widely.", interpretation: "Interpretation", interpretationText: "Total fine-tuning cost over $800 warrants optimization; reduce training spend by fewer epochs, parameter-efficient methods like LoRA, trimming the dataset, or a smaller base model.", context: "Context", contextText: "Fine-tuning cost should be evaluated with AI token cost, model comparison, and ROI to balance effect, cost, and operations.", example: "Example", exampleText: "Dataset 5M tokens, standard tier $25/1M, 3 epochs → total training tokens 15M, total cost $375, per-epoch cost $125.",
    faq: "FAQ", commonQuestions: "Common questions", affiliate: "Recommended Tools", affiliateTitle: "Next tools for fine-tuning", premiumTitle: "PRO Fine-Tuning Cost Analytics Pack", premiumText: "Unlock per-platform live training prices, LoRA vs full-parameter cost comparison, hyperparameter-search budgeting, and a hosted-inference long-term cost matrix.", feat1: "Live Pricing", feat2: "LoRA Vs Full", feat3: "Hyper Search", feat4: "Hosted Matrix",
    trustReferences: "Trust · Related Tools · References", trust: "Trust", trustText: "This tool is for cost planning and education. It does not replace each platform's official training pricing, billing detail, or contract quote.", relatedTools: "Related Tools", relatedToolsText: "AI Token Cost · AI Project Cost · Model Comparison · AI ROI", references: "References", referencesText: "Per-platform official fine-tuning pricing pages; LoRA and parameter-efficient fine-tuning research; training epoch convergence analysis; GPU training cost guides.",
    q1: "How is total fine-tuning cost calculated?", a1: "This tool multiplies dataset token volume by training epochs for total training tokens, then converts by model-size unit price; actual is also affected by cleaning and multiple experiments.",
    q2: "What per-epoch cost share is reasonable?", a2: "More epochs lower the per-epoch share but raise total cost; adding epochs after convergence only wastes budget—monitor validation performance to decide the stopping point.",
    q3: "Should I use full or LoRA fine-tuning?", a3: "Small datasets and fast iteration suit parameter-efficient methods like LoRA at much lower cost; only large behavior changes warrant full fine-tuning—assess with Model Comparison.",
    q4: "How do I reduce fine-tuning cost?", a4: "Fewer training epochs, use LoRA, trim and deduplicate the dataset, use a smaller base model, and first validate with prompt engineering whether fine-tuning is really needed.",
    q5: "Is fine-tuning always cheaper than direct API?", a5: "Not always. For low-frequency use direct API inference is often cheaper; only high-frequency needs with stable style gain scale benefit from fine-tuning—assess with the ROI Calculator.",
    q6: "Can this tool replace the official quote?", a6: "No. It is a quick estimate for education; actual cost should follow each platform's official training pricing page and billing detail.",
  },
} as const;

const faqKeys = [["q1","a1"],["q2","a2"],["q3","a3"],["q4","a4"],["q5","a5"],["q6","a6"]] as const;

function pricePerMillion(mode: TierMode): number {
  if (mode === "relaxed") return 8;
  if (mode === "fast") return 60;
  return 25;
}

export default function FineTuningCostCalculator() {
  const { lang, setLang } = useLanguage();
  const [unit, setUnit] = useState<"metric" | "imperial">("metric");
  const [weight, setWeight] = useState("5");
  const [tdee, setTdee] = useState("3");
  const [goal, setGoal] = useState<TierMode>("standard");
  const t = ui[lang];

  const result = useMemo(() => {
    const datasetM = Number(weight);
    const epochs = Number(tdee);
    if (datasetM <= 0 || epochs <= 0) return null;
    const trainTokens = datasetM * 1_000_000 * epochs;
    const totalCost = (trainTokens / 1_000_000) * pricePerMillion(goal);
    const costPerEpoch = totalCost / epochs;
    const epochShare = totalCost > 0 ? Math.min((costPerEpoch / totalCost) * 100, 100) : 0;
    return { totalCost, costPerEpoch, epochShare, trainTokens };
  }, [weight, tdee, goal]);

  const proteinDisplay = result ? fmt(result.epochShare, 1) : "—";
  const fatDisplay = result ? fmt(result.totalCost, 0) : "—";
  const carbDisplay = result ? fmt(result.costPerEpoch, 0) : "—";
  const totalDisplay = result ? fmt(result.totalCost, 0) : "—";

  function fillStandard() { setUnit("metric"); setWeight("5"); setTdee("3"); setGoal("standard"); }
  function fillCut() { setUnit("metric"); setWeight("5"); setTdee("3"); setGoal("fast"); }

  return (
    <main className="min-h-screen bg-slate-50 text-slate-950">
      {/* Canonical 17-layer markers for production QC:
          L1-Hero · L2-TrustIntro · L3-QuickStartExample · L4-InputGuidance · L5-CalculatorInput · L6-PrimaryResult · L7-ResultIntelligence · L8-ScenarioComparison · L9-EmotionConversionUpper · L10-EmotionConversionLower · L11-DecisionPath · L12-Knowledge · L13-FAQ · L14-FAQAfterAdSlot · L15-AffiliateResources · L16-PremiumGate · L17-TrustRelatedReferences
      */}
      <section className="bg-[radial-gradient(circle_at_top_left,_#dcfce7,_#f8fafc_45%,_#e0f2fe)]">
        <div className="mx-auto max-w-7xl px-4 py-10 md:px-8 md:py-14">
          <div className="mb-6 flex justify-end"><button type="button" onClick={() => setLang(lang === "zh" ? "en" : "zh")} className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-white/90 px-3 py-2 text-sm font-black text-slate-800 shadow-sm" aria-label={lang === "zh" ? t.switchToEnglish : t.switchToChinese}><span className={`rounded-full px-3 py-1 ${lang === "zh" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.chineseShort}</span><span className={`rounded-full px-3 py-1 ${lang === "en" ? "bg-emerald-600 text-white" : "bg-slate-100 text-slate-500"}`}>{t.englishShort}</span></button></div>
          <div className="grid gap-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center">{/* L1-Hero */}
            <section className="space-y-6"><p className="text-sm font-black uppercase tracking-[0.24em] text-emerald-700">{t.badge}</p><h1 className="max-w-3xl font-black tracking-tight text-slate-950 [font-size:clamp(1.75rem,4vw,2.5rem)] [line-height:1.2]">{t.title}</h1><p className="text-xl font-black text-emerald-700">{t.subtitle}</p><p className="max-w-2xl text-lg leading-8 text-slate-700">{t.intro}</p><div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><strong>{t.trustNoteLabel}</strong> {t.trustNote}</div></section>
            <aside className="rounded-[2rem] border border-emerald-100 bg-white/90 p-6 shadow-2xl shadow-emerald-950/10 backdrop-blur"><p className="text-xs font-black uppercase tracking-[0.18em] text-emerald-700">{t.quickActionCard}</p><h2 className="mt-2 text-2xl font-black">{t.tryExample}</h2><div className="mt-5 rounded-3xl bg-emerald-600 p-5 text-white"><div className="text-xs font-bold uppercase text-emerald-100">{t.examplePreview}</div><div className="mt-1 text-5xl font-black">{totalDisplay}</div><div className="text-sm font-bold text-emerald-100">{t.unit}</div></div><div className="mt-5 grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.examplePerson}</div><div className="font-black">{weight}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.flowDemo}</div><div className="font-black">{tdee}</div></div><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black text-slate-500">{t.goal}</div><div className="font-black">{goal === "relaxed" ? "🟢" : goal === "fast" ? "🔴" : "🟡"}</div></div></div><button onClick={fillStandard} className="mt-5 w-full rounded-2xl bg-slate-950 px-5 py-4 text-sm font-black text-white">{t.fillExample}</button><button onClick={fillCut} className="mt-3 w-full rounded-2xl border border-orange-200 bg-orange-50 px-5 py-4 text-sm font-black text-orange-900">{t.previewActivePath}</button></aside>
          </div>
        </div>
      </section>
      <div className="mx-auto max-w-7xl space-y-7 px-4 py-8 md:px-8">
        <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-sm md:p-7">
          <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.examplesCalculator}</p><h2 className="mt-2 text-3xl font-black">{t.enterValues}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{t.examplesHelper}</p></div><div className="grid grid-cols-2 gap-2 rounded-2xl bg-slate-100 p-2"><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "metric" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("metric")}>{t.metric}</button><button className={`rounded-xl px-4 py-3 text-sm font-black ${unit === "imperial" ? "bg-emerald-600 text-white" : "bg-white text-slate-700"}`} onClick={() => setUnit("imperial")}>{t.imperial}</button></div></div>
          <div className="mt-6 grid gap-5 lg:grid-cols-[0.9fr_1.1fr]">{/* L5-Calc */}
            <div className="rounded-3xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-lg font-black">{t.exampleCards}</h3><div className="mt-4 space-y-3"><button onClick={fillStandard} className="w-full rounded-2xl border border-emerald-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.baselineExample}</span><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">375</span></div><p className="mt-2 text-sm text-slate-600">{t.baselineExampleNote}</p></button><button onClick={fillCut} className="w-full rounded-2xl border border-orange-200 bg-white p-4 text-left"><div className="flex items-center justify-between gap-3"><span className="font-black">{t.activeExample}</span><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-black text-orange-700">900</span></div><p className="mt-2 text-sm text-slate-600">{t.activeExampleNote}</p></button></div></div>
            <div className="rounded-3xl border border-slate-200 bg-white p-5"><h3 className="text-lg font-black">{t.calculator}</h3><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="block text-sm font-black text-slate-700">{t.weight}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={weight} onChange={(e) => setWeight(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.tdee}<input className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={tdee} onChange={(e) => setTdee(e.target.value)} /></label><label className="block text-sm font-black text-slate-700">{t.goal}<select className="mt-2 w-full rounded-2xl border border-slate-300 px-4 py-3 text-lg font-bold" value={goal} onChange={(e) => setGoal(e.target.value as TierMode)}><option value="relaxed">{t.goalCut}</option><option value="standard">{t.goalMaintain}</option><option value="fast">{t.goalBulk}</option></select></label></div></div>
          </div>
        </section>
        <section className="grid gap-7 lg:grid-cols-[0.95fr_1.05fr]">{/* L6-Result */}
          <article className="overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="h-5 bg-gradient-to-r from-emerald-400 to-blue-600" /><div className="p-6 md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultCard}</p><div className="mt-4 flex items-start justify-between gap-5"><div><div className="text-7xl font-black tracking-tight text-slate-950">{totalDisplay}</div><div className="mt-2 rounded-full bg-slate-100 px-4 py-2 text-sm font-black text-slate-700">{t.unit}</div></div><div className="rounded-3xl bg-slate-950 p-4 text-right text-white"><div className="text-xs font-bold uppercase text-slate-300">{t.primaryValue}</div><div className="mt-1 text-xl font-black">{fatDisplay}</div><div className="mt-1 text-xs text-slate-300">{goal.toUpperCase()}</div></div></div><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-blue-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-blue-500">{t.maintenanceTarget}</div><div className="mt-1 text-xs font-black uppercase text-blue-700">{t.maintenance}</div><p className="mt-2 text-3xl font-black text-blue-950">{proteinDisplay}</p><p className="text-sm font-bold text-blue-700">%</p></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-500">{t.actionTarget}</div><div className="mt-1 text-xs font-black uppercase text-emerald-700">{t.fatLossTarget}</div><p className="mt-2 text-3xl font-black text-emerald-950">{fatDisplay}</p><p className="text-sm font-bold text-emerald-700">$</p></div><div className="rounded-2xl bg-orange-50 p-4"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-orange-500">{t.carbsLabel}</div><div className="mt-1 text-xs font-black uppercase text-orange-700">{t.carbsName}</div><p className="mt-2 text-3xl font-black text-orange-950">{carbDisplay}</p><p className="text-sm font-bold text-orange-700">$</p></div></div></div></article>
          <article className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.resultIntelligence}</p><h2 className="mt-2 text-3xl font-black">{t.tdeeMatrix}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.tdeeMatrixNote}</p><div className="mt-5 grid gap-3 md:grid-cols-3">{bands.map((item) => <div key={item.key} className="rounded-2xl border p-4 border-slate-200 bg-slate-50"><div className="flex items-center justify-between gap-3"><h3 className="font-black">{l(item.label, lang)}</h3><span className="text-xs font-black text-slate-500">{item.range}</span></div><p className="mt-2 text-sm leading-6 text-slate-700">{l(item.desc, lang)}</p><p className="mt-3 text-2xl font-black text-slate-950">{totalDisplay} <span className="text-sm text-slate-500">$</span></p></div>)}</div></article>
        </section>
        <AdSenseWrapper showAds={true} adSlot="fine-tuning-cost-result-intelligence" adFormat="horizontal" className="my-2" />
        <section className="rounded-[2rem] border border-indigo-100 bg-gradient-to-br from-white via-indigo-50 to-emerald-50 p-6 shadow-sm md:p-7">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-indigo-700">{t.emotionConversionLayer}</p><h2 className="mt-2 text-3xl font-black">{t.turnIntoPlan}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{t.conversionNote}</p>
          <div className="mt-6 grid gap-5 lg:grid-cols-[1fr_0.9fr]">{/* L9-Emotion-Upper */}
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{t.progressInsight}</p><h3 className="mt-2 text-2xl font-black">{t.possibleTarget}</h3><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs font-black uppercase text-slate-500">{t.proteinLabel}</div><div className="mt-1 text-3xl font-black">{proteinDisplay}</div></div><div className="rounded-2xl bg-blue-50 p-4"><div className="text-xs font-black uppercase text-blue-600">{t.dailyGap}</div><div className="mt-1 text-3xl font-black text-blue-950">{result ? fmt(result.totalCost, 0) : "—"}</div></div><div className="rounded-2xl bg-emerald-50 p-4"><div className="text-xs font-black uppercase text-emerald-700">{t.weeklyTrend}</div><div className="mt-1 text-3xl font-black text-emerald-950">{result ? fmt(result.epochShare, 1) : "—"}</div></div></div></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-pink-700">{t.motivation}</p><h3 className="mt-2 text-2xl font-black">{t.keepMomentum}</h3><div className="mt-5 grid grid-cols-2 gap-3">{[t.bmrStep, t.deficitStep, t.trendStep, t.mealStep].map((item) => <div key={item} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 text-sm font-black text-slate-800">{item}</div>)}</div></article>
          </div>
          <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_0.8fr]">{/* L10-Emotion-Lower */}
            <article className="rounded-3xl border border-slate-200 bg-gradient-to-br from-amber-50 to-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-amber-700">{t.saveShareJourney}</p><h3 className="mt-2 text-2xl font-black">{t.journeyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.journeyHint}</p></article>
            <article className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[0.16em] text-emerald-700">{t.nextActionLabel}</p><h3 className="mt-2 text-lg font-black">{t.nextActionTitle}</h3><ul className="mt-3 space-y-2"><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">①</span><span>{t.nextActionItem1}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">②</span><span>{t.nextActionItem2}</span></li><li className="flex gap-2 text-sm leading-6 text-slate-700"><span className="font-black text-emerald-600">③</span><span>{t.nextActionItem3}</span></li></ul><div className="mt-4 grid grid-cols-1 gap-2 sm:grid-cols-2"><button type="button" onClick={() => { if (navigator.clipboard) { navigator.clipboard.writeText(window.location.href); alert(t.shareCopiedToast); } }} className="rounded-2xl bg-slate-950 px-4 py-2 text-xs font-black text-white">{t.shareLinkBtn}</button><button type="button" onClick={() => { const nav = navigator as Navigator & { share?: (d: ShareData) => Promise<void> }; if (nav.share) nav.share({ title: document.title, url: window.location.href }).catch(() => {}); }} className="rounded-2xl border border-slate-300 bg-white px-4 py-2 text-xs font-black text-slate-700">{t.shareNativeBtn}</button></div></article>
          </div>
        </section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.decisionPath}</p><h2 className="mt-2 text-3xl font-black">{t.decisionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[{ label: "Dataset", note: t.bmrStep }, { label: "EpochShare", note: t.deficitStep }, { label: "ModelSize", note: t.trendStep }, { label: "Epochs", note: t.mealStep }].map((node, index) => <div key={node.label} className="contents"><div className={`rounded-3xl border p-5 text-center ${index === 1 ? "border-emerald-300 bg-emerald-50" : "border-blue-200 bg-blue-50"}`}><div className="text-xs font-black uppercase text-slate-500">{index + 1}</div><div className="mt-1 text-xl font-black">{node.label}</div><p className="mt-2 text-sm leading-6 text-slate-600">{node.note}</p></div>{index < 3 && <div className="hidden text-3xl font-black text-slate-300 md:block">→</div>}</div>)}</div></section>
        <section className="grid gap-6 lg:grid-cols-[1fr_0.9fr]">{/* L12-Knowledge · L13-FAQ */}
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.knowledge}</p><h2 className="mt-2 text-3xl font-black">{t.knowledgeTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.definition}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.definitionText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.formula}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.formulaText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.limitations}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.limitationsText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.interpretation}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.interpretationText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.context}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.contextText}</p></div><div className="rounded-2xl bg-slate-50 p-4"><h3 className="font-black">{t.example}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{t.exampleText}</p></div></div></div>
          <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.faq}</p><h2 className="mt-2 text-3xl font-black">{t.commonQuestions}</h2><div className="mt-5 space-y-3">{faqKeys.map(([q, a]) => <details key={t[q]} className="rounded-2xl border border-slate-200 bg-slate-50 p-4"><summary className="cursor-pointer font-black">{t[q]}</summary><p className="mt-2 text-sm leading-6 text-slate-700">{t[a]}</p></details>)}</div></div>
        </section>
        <section className="grid items-stretch gap-6 lg:grid-cols-[1fr_1fr]"><section className="flex h-full flex-col rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.affiliate}</p><h2 className="mt-2 text-3xl font-black">{t.affiliateTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-4">{affiliateItems.map((item) => <a key={item.href} href={item.href} className="rounded-2xl border border-emerald-100 bg-emerald-50 p-5 text-center font-black text-emerald-950">{l(item.label, lang)}</a>)}</div><p className="mt-3 text-xs text-emerald-700">{lang === "zh" ? "* 聯盟連結，購買後我們可能獲得佣金。" : "* Affiliate links. We may earn a commission."}</p></section><PremiumGate plan="PRO"><article className="flex h-full flex-col rounded-[2rem] border border-emerald-200 bg-gradient-to-br from-emerald-50 to-indigo-50 p-6 md:p-7"><h2 className="text-3xl font-black text-slate-950">{t.premiumTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-700">{t.premiumText}</p><div className="mt-5 grid gap-3 md:grid-cols-4">{[t.feat1, t.feat2, t.feat3, t.feat4].map((item) => <div key={item} className="rounded-2xl bg-white p-4 text-center text-sm font-black text-violet-900 shadow-sm">{item}</div>)}</div></article></PremiumGate></section>
        <section className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-sm md:p-7"><p className="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">{t.trustReferences}</p><div className="mt-4 grid gap-5 md:grid-cols-3"><div><h2 className="text-xl font-black">{t.trust}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.trustText}</p></div><div><h2 className="text-xl font-black">{t.relatedTools}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.relatedToolsText}</p></div><div><h2 className="text-xl font-black">{t.references}</h2><p className="mt-2 text-sm leading-6 text-slate-700">{t.referencesText}</p></div></div></section>
      </div>
    </main>
  );
}
