// Batch 2 (F-35~F-49) brief generator. Writes 15 complete finance briefs.
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BRIEFS = path.join(__dirname, "briefs");

const aff = (z, e, h) => ({ label_zh: z, label_en: e, href: h });
const COMMON_AFF = [
  aff("複利計算機", "Compound Interest Calculator", "/tools/finance/compound-interest-calculator"),
  aff("投資報酬率計算機", "Investment Return Calculator", "/tools/finance/investment-return-calculator"),
  aff("通膨調整計算機", "Inflation Adjuster", "/tools/finance/inflation-adjuster"),
  aff("退休計算機", "Retirement Calculator", "/tools/finance/retirement-calculator"),
];

// Each tool: full domain content.
const tools = [
  // F-35 amortization-schedule
  {
    file: "F35-amortization-schedule.json",
    id: "amortization-schedule-calculator", nameZh: "攤還排程計算機", nameEn: "Amortization Schedule Calculator", color: "sky",
    inputs: ["貸款本金", "年利率%", "貸款年限", "已繳期數"],
    inputsEn: ["Loan Principal", "Annual Rate Pct", "Loan Years", "Months Paid"],
    defaults: ["500000", "5", "30", "12"], steps: ["10000", "0.1", "1", "1"], accentIdx: 1,
    compute: "依本金、年利率、年限計算每月還款、總利息與目前剩餘本金",
    computeFn: "    const P = Number(loanPrincipal) || 0;\n    const r = (Number(annualRatePct) || 0) / 100 / 12;\n    const n = (Number(loanYears) || 1) * 12;\n    const paid = Number(monthsPaid) || 0;\n    const monthly = r > 0 ? (P * r) / (1 - Math.pow(1 + r, -n)) : P / n;\n    const totalPaid = monthly * n;\n    const totalInterest = totalPaid - P;\n    const balance = r > 0 ? (P * Math.pow(1 + r, paid) - monthly * (Math.pow(1 + r, paid) - 1) / r) : P - monthly * paid;\n    return { monthly, totalInterest, balance: Math.max(0, balance), totalPaid };",
    computeFnOverride: "    const P = Number(loanPrincipal) || 0;\n    const r = (Number(annualRatePct) || 0) / 100 / 12;\n    const n = (Number(loanYears) || 1) * 12;\n    const paid = Number(monthsPaid) || 0;\n    const monthly = r > 0 ? (P * r) / (1 - Math.pow(1 + r, -n)) : P / n;\n    const totalPaid = monthly * n;\n    const totalInterest = totalPaid - P;\n    const interestRatio = P > 0 ? (totalInterest / P) * 100 : 0;\n    const balance = r > 0 ? (P * Math.pow(1 + r, paid) - monthly * (Math.pow(1 + r, paid) - 1) / r) : P - monthly * paid;\n    return { interestRatio, monthly, totalInterest, balance: Math.max(0, balance) };",
    primaryKey: "interestRatio", primaryDecimals: 1, primaryUnit: "%", secondaryKey: "monthly", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "totalInterest", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "balance", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "利息佔本金比", primaryLabelEn: "Interest-to-Principal", secondaryLabelZh: "每月還款", secondaryLabelEn: "Monthly Payment",
    tertiaryLabelZh: "總利息", tertiaryLabelEn: "Total Interest", quaternaryLabelZh: "剩餘本金", quaternaryLabelEn: "Remaining Balance",
    bands: ["極低", "低", "中等", "偏高", "高", "極高"], bandThresholds: [20, 40, 60, 80, 100],
    bandHints: [
      "利息佔本金 < 20%,屬於短年限或低利率,還款壓力極小。",
      "20-40%,利息合理,常見於 10-15 年期中利率貸款。",
      "40-60%,屬於 20-30 年期典型房貸區間,可考慮提前還款。",
      "60-80%,利息負擔偏高,建議評估再融資或縮短年限。",
      "80-100%,利息接近本金,長年限高利率,務必比較其他方案。",
      "> 100%,利息超過本金,通常為超長年限或高利率,強烈建議重新規劃。",
    ],
    faqTitles: ["攤還表怎麼看?", "前幾年為什麼幾乎都在還利息?", "提前還款能省多少?", "本息均攤和本金均攤差在哪?", "資料會上傳嗎?", "可以匯出完整每期攤還表嗎?"],
    faqAnswers: [
      "攤還表列出每一期的還款金額、其中多少還利息、多少還本金,以及剩餘本金。本工具計算總覽指標:每月還款、總利息、目前剩餘本金,讓你快速掌握還款結構。",
      "本息均攤(等額本息)在前期剩餘本金最大,因此利息佔比最高。以 30 年期 5% 房貸為例,第一年約 80% 的還款都在繳利息,本金減少緩慢,這是複利的數學結果,並非銀行多收。",
      "提前還款直接減少剩餘本金,後續利息按新本金重算。越早還、省越多。一般在貸款前 1/3 期間提前還款的省息效果最大。建議搭配再融資計算機比較。",
      "**本息均攤**每月還款固定,前期利息多、後期本金多;**本金均攤**每月還相同本金,利息隨剩餘本金遞減,初期還款最高、之後遞減,總利息較低但前期壓力大。",
      "完全不會。所有計算都在你的瀏覽器內以 JavaScript 完成,本金、利率等資料不會傳送到任何伺服器。",
      "完整逐期攤還表(每期本金/利息/餘額)、提前還款情境模擬與 PDF 匯出屬於專業版功能,免費版提供總覽指標。",
    ],
    affiliates: [
      aff("貸款計算機", "Loan Calculator", "/tools/finance/loan-calculator"),
      aff("房貸計算機", "Mortgage Calculator", "/tools/finance/mortgage-calculator"),
      aff("再融資計算機", "Refinance Calculator", "/tools/finance/refinance-calculator"),
      aff("複利計算機", "Compound Interest Calculator", "/tools/finance/compound-interest-calculator"),
    ],
    exampleSolid: ["500000", "5", "30", "12"], exampleHigh: ["300000", "3", "15", "24"],
    solidLabelZh: "本金 50 萬 · 5% · 30 年", solidLabelEn: "P 500k · 5% · 30y",
    highLabelZh: "本金 30 萬 · 3% · 15 年", highLabelEn: "P 300k · 3% · 15y",
    subtitleZh: "輸入貸款本金、利率與年限，立即估算每月還款、總利息與剩餘本金",
    subtitleEn: "Enter loan principal, rate, and term to estimate monthly payment, total interest, and remaining balance",
    definitionZh: "攤還排程計算機以貸款本金、年利率、年限計算本息均攤下的每月還款、總利息與目前剩餘本金,適用房貸、車貸、信貸等等額還款貸款。",
    formulaZh: "每月還款 = P × r / (1 − (1+r)^−n);剩餘本金 = P × (1+r)^k − 每月還款 × ((1+r)^k − 1) / r",
    limitationsZh: "本工具假設固定利率與本息均攤,不計寬限期、浮動利率、提前還款違約金與手續費;實際請以銀行攤還表為準。",
    interpretationZh: "總利息越高代表年限越長或利率越高,可考慮縮短年限或提前還款;剩餘本金為再融資與提前清償的計算基礎。",
    premiumTitleZh: "專業版 攤還與再融資工具組", premiumTextZh: "解鎖逐期攤還明細、提前還款情境模擬、本金均攤 vs 本息均攤比較、再融資省息分析與 PDF 匯出。",
    premiumChipsZh: "逐期明細|提前還款|攤還比較|PDF匯出",
    premiumTitleEn: "Pro Amortization Suite", premiumTextEn: "Unlock per-period schedule, prepayment scenarios, equal-principal vs equal-payment comparison, refinance savings, and PDF export.",
    premiumChipsEn: "Schedule|Prepayment|Compare|PDF",
  },
  // F-36 capital-gains-tax
  {
    file: "F36-capital-gains-tax.json",
    id: "capital-gains-tax-calculator", nameZh: "資本利得稅計算機", nameEn: "Capital Gains Tax Calculator", color: "emerald",
    inputs: ["買入價", "賣出價", "持有股數", "稅率%"],
    inputsEn: ["Buy Price", "Sell Price", "Shares Held", "Tax Rate Pct"],
    defaults: ["100", "150", "100", "15"], steps: ["1", "1", "10", "1"], accentIdx: 3,
    compute: "依買入、賣出價、股數與稅率計算資本利得、應繳稅額與稅後淨利",
    computeFn: "    const buy = Number(buyPrice) || 0;\n    const sell = Number(sellPrice) || 0;\n    const sh = Number(sharesHeld) || 0;\n    const rate = (Number(taxRatePct) || 0) / 100;\n    const gain = (sell - buy) * sh;\n    const tax = gain > 0 ? gain * rate : 0;\n    const netProfit = gain - tax;\n    const effRate = gain > 0 ? (tax / gain) * 100 : 0;\n    return { gain, tax, netProfit, effRate };",
    primaryKey: "effRate", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "tax", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "gain", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "netProfit", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "有效稅率", primaryLabelEn: "Effective Rate", secondaryLabelZh: "應繳資本利得稅", secondaryLabelEn: "Capital Gains Tax",
    tertiaryLabelZh: "資本利得", tertiaryLabelEn: "Capital Gain", quaternaryLabelZh: "稅後淨利", quaternaryLabelEn: "Net Profit",
    bandKey: "effRate",
    bands: ["免稅", "極低", "低", "中等", "高", "極高"], bandThresholds: [0.01, 10, 15, 25, 35],
    bandHints: [
      "有效稅率 ≈ 0%,代表無利得或適用免稅(如長期持有優惠或虧損)。",
      "< 10%,屬於低稅率區,常見於長期持有優惠或低所得級距。",
      "10-15%,美國長期資本利得常見區間,稅負相對輕。",
      "15-25%,屬於中等稅負,常見於短期持有或中高所得。",
      "25-35%,偏高,接近短期資本利得併入一般所得稅率。",
      "> 35%,極高稅負,務必檢視持有期間與節稅策略。",
    ],
    faqTitles: ["短期和長期資本利得稅差多少?", "虧損可以抵稅嗎?", "台灣股票要繳資本利得稅嗎?", "怎麼合法節省資本利得稅?", "資料會上傳嗎?", "可以一次算多筆交易嗎?"],
    faqAnswers: [
      "在美國,**短期(持有 ≤ 1 年)**資本利得併入一般所得,稅率最高 37%;**長期(持有 > 1 年)**享優惠稅率 0%/15%/20%。光是多持有幾天跨過一年門檻,稅率可能從 37% 降到 15%,差距巨大。",
      "可以。資本損失可先抵銷資本利得,若損失大於利得,美國每年最多可用 3000 美元抵一般所得,剩餘部分結轉至未來年度(tax-loss harvesting)。本工具僅算單筆利得稅,虧損抵稅請用專業版情境模擬。",
      "台灣現行**證券交易所得停徵**,個人買賣上市櫃股票不課資本利得稅,僅課 0.3% 證交稅(賣出時)。但未上市股票、海外所得、ETF 配息等另有規定,本工具以通用稅率模型計算,請依當地法規調整。",
      "常見策略:**(1) 長期持有**跨過一年門檻享優惠稅率、**(2) tax-loss harvesting** 用虧損抵利得、**(3) 善用免稅帳戶**(如美國 Roth IRA、401k)、**(4) 分年實現利得**控制級距。建議諮詢稅務專業人士。",
      "完全不會。所有計算都在你的瀏覽器內完成,買入價、賣出價等資料不會傳送到任何伺服器。",
      "批次計算多筆交易、自動分類短期/長期、tax-loss harvesting 模擬與年度稅務彙總屬於專業版功能。",
    ],
    affiliates: [
      aff("稅率級距計算機", "Tax Bracket Calculator", "/tools/finance/tax-bracket-calculator"),
      aff("股票獲利計算機", "Stock Profit Calculator", "/tools/finance/stock-profit-calculator"),
      aff("投資報酬率計算機", "Investment Return Calculator", "/tools/finance/investment-return-calculator"),
      aff("稅後薪資計算機", "Salary After Tax Calculator", "/tools/finance/salary-after-tax-calculator"),
    ],
    exampleSolid: ["100", "150", "100", "15"], exampleHigh: ["50", "120", "200", "32"],
    solidLabelZh: "買 100 · 賣 150 · 100 股 · 15%", solidLabelEn: "Buy 100 · Sell 150 · 100sh · 15%",
    highLabelZh: "買 50 · 賣 120 · 200 股 · 32%", highLabelEn: "Buy 50 · Sell 120 · 200sh · 32%",
    subtitleZh: "輸入買入價、賣出價、股數與稅率，立即估算資本利得稅與稅後淨利",
    subtitleEn: "Enter buy price, sell price, shares, and tax rate to estimate capital gains tax and net profit",
    definitionZh: "資本利得稅計算機以買入價、賣出價、股數與稅率,計算資本利得、應繳稅額與稅後淨利,適用股票、ETF、基金等投資出售的稅負估算。",
    formulaZh: "資本利得 = (賣出價 − 買入價) × 股數;稅額 = 利得 × 稅率(利得為正才課稅);稅後淨利 = 利得 − 稅額",
    limitationsZh: "本工具採單一稅率模型,不分短期/長期、不計手續費、證交稅、虧損抵減與分級稅率;各國法規差異大,請以當地稅法與會計師意見為準。",
    interpretationZh: "有效稅率越高代表稅負越重,可透過長期持有、虧損抵減與免稅帳戶降低;稅後淨利為實際入袋金額。",
    premiumTitleZh: "專業版 資本利得稅務工具組", premiumTextZh: "解鎖短期/長期分類、tax-loss harvesting 模擬、多筆交易批次計算、分級稅率與年度稅務彙總報表。",
    premiumChipsZh: "長短期分類|虧損抵稅|批次計算|年度彙總",
    premiumTitleEn: "Pro Capital Gains Suite", premiumTextEn: "Unlock short/long-term classification, tax-loss harvesting, batch trades, tiered rates, and annual tax summary.",
    premiumChipsEn: "ST/LT|Loss Harvest|Batch|Summary",
  },
  // F-37 sales-tax
  {
    file: "F37-sales-tax.json",
    id: "sales-tax-calculator", nameZh: "銷售稅計算機", nameEn: "Sales Tax Calculator", color: "rose",
    inputs: ["稅前金額", "銷售稅率%", "數量", "額外費用"],
    inputsEn: ["Pre Tax Amount", "Sales Tax Rate Pct", "Quantity", "Extra Fee"],
    defaults: ["100", "8", "1", "0"], steps: ["1", "0.1", "1", "1"], accentIdx: 1,
    compute: "依稅前金額、稅率、數量與額外費用計算銷售稅、含稅總額與每件含稅單價",
    computeFn: "    const amt = Number(preTaxAmount) || 0;\n    const rate = (Number(salesTaxRatePct) || 0) / 100;\n    const qty = Number(quantity) || 1;\n    const fee = Number(extraFee) || 0;\n    const subtotal = amt * qty;\n    const tax = subtotal * rate;\n    const total = subtotal + tax + fee;\n    const perUnit = qty > 0 ? total / qty : 0;\n    return { total, tax, subtotal, perUnit };",
    computeFnOverride: "    const amt = Number(preTaxAmount) || 0;\n    const rate = (Number(salesTaxRatePct) || 0) / 100;\n    const qty = Number(quantity) || 1;\n    const fee = Number(extraFee) || 0;\n    const subtotal = amt * qty;\n    const tax = subtotal * rate;\n    const total = subtotal + tax + fee;\n    const ratePct = rate * 100;\n    return { ratePct, total, tax, subtotal };",
    primaryKey: "ratePct", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "total", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "tax", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "subtotal", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "適用稅率", primaryLabelEn: "Applied Rate", secondaryLabelZh: "含稅總額", secondaryLabelEn: "Total With Tax",
    tertiaryLabelZh: "銷售稅", tertiaryLabelEn: "Sales Tax", quaternaryLabelZh: "稅前小計", quaternaryLabelEn: "Subtotal",
    bands: ["免稅", "極低", "低", "中等", "高", "極高"], bandThresholds: [0.01, 5, 8, 12, 20],
    bandHints: [
      "稅率 0%,免銷售稅地區(如美國 Oregon、Delaware)。",
      "< 5%,屬於低銷售稅區,常見於部分美國州。",
      "5-8%,美國多數州的綜合銷售稅常見區間。",
      "8-12%,屬於中高稅率,含地方加徵的大城市常見。",
      "12-20%,偏高,接近部分國家的標準消費稅/VAT。",
      "> 20%,極高,常見於北歐等高福利國家的 VAT。",
    ],
    faqTitles: ["銷售稅和 VAT 差在哪?", "美國各州銷售稅率一樣嗎?", "含稅價怎麼反推稅前價?", "服務也要課銷售稅嗎?", "資料會上傳嗎?", "可以一次算多種稅率嗎?"],
    faqAnswers: [
      "**銷售稅(Sales Tax)**只在最終零售環節對消費者課徵,常見於美國;**VAT(加值稅)**在生產到零售每一環節對加值部分課徵,可進項抵扣,常見於歐洲、亞洲多國。對最終消費者而言金額類似,但機制不同。",
      "不一樣。美國沒有全國統一銷售稅,各州+郡+市各自加徵,綜合稅率從 0%(Oregon)到超過 10%(部分加州、伊利諾城市)。同一州不同城市稅率也可能不同,網購則依收貨地課稅。",
      "稅前價 = 含稅價 ÷ (1 + 稅率)。例如含稅 108 元、稅率 8%,稅前價 = 108 ÷ 1.08 = 100 元,稅額 8 元。本工具預設由稅前推含稅,反推功能在專業版。",
      "視地區而定。美國多數州對「有形商品」課銷售稅,但部分服務(如理髮、顧問)在某些州免稅或另有規定;數位商品、SaaS 的課稅規則各州差異很大。請查當地稅務局公告。",
      "完全不會。所有計算都在你的瀏覽器內完成,金額與稅率資料不會傳送到任何伺服器。",
      "多稅率比較、含稅反推稅前、發票批次計算與多州/多國稅率資料庫屬於專業版功能。",
    ],
    affiliates: [
      aff("VAT 加值稅計算機", "VAT Calculator", "/tools/finance/vat-calculator"),
      aff("折扣計算機", "Discount Calculator", "/tools/finance/discount-calculator"),
      aff("小費計算機", "Tip Calculator", "/tools/finance/tip-calculator"),
      aff("利潤率計算機", "Profit Margin Calculator", "/tools/finance/profit-margin-calculator"),
    ],
    exampleSolid: ["100", "8", "1", "0"], exampleHigh: ["250", "20", "3", "15"],
    solidLabelZh: "100 元 · 8% · 1 件", solidLabelEn: "$100 · 8% · 1",
    highLabelZh: "250 元 · 20% · 3 件 · 費 15", highLabelEn: "$250 · 20% · 3 · fee 15",
    subtitleZh: "輸入稅前金額、稅率與數量，立即算出銷售稅、含稅總額與每件含稅單價",
    subtitleEn: "Enter pre-tax amount, tax rate, and quantity to compute sales tax, total, and per-unit price",
    definitionZh: "銷售稅計算機以稅前金額、銷售稅率、數量與額外費用,計算應繳銷售稅、含稅總額與每件含稅單價,適用零售、報價、發票試算。",
    formulaZh: "稅前小計 = 金額 × 數量;銷售稅 = 小計 × 稅率;含稅總額 = 小計 + 稅 + 額外費用",
    limitationsZh: "本工具採單一稅率,不處理多級稅率、免稅品項、進項抵扣與跨區課稅規則;實際稅額請以當地稅法與收銀系統為準。",
    interpretationZh: "稅率越高含稅總額越高;每件含稅單價可用於比較不同數量或包裝的實際成本。",
    premiumTitleZh: "專業版 稅務試算工具組", premiumTextZh: "解鎖含稅反推稅前、多稅率比較、發票批次計算、多州/多國稅率資料庫與報表匯出。",
    premiumChipsZh: "含稅反推|多稅率|批次發票|稅率庫",
    premiumTitleEn: "Pro Sales Tax Suite", premiumTextEn: "Unlock reverse tax extraction, multi-rate compare, batch invoicing, multi-jurisdiction rate database, and export.",
    premiumChipsEn: "Reverse|Multi-rate|Batch|Rate DB",
  },
  // F-38 tip-calculator
  {
    file: "F38-tip-calculator.json",
    id: "tip-calculator", nameZh: "小費計算機", nameEn: "Tip Calculator", color: "violet",
    inputs: ["帳單金額", "小費比例%", "分攤人數", "稅率%"],
    inputsEn: ["Bill Amount", "Tip Percent", "Split People", "Tax Rate Pct"],
    defaults: ["100", "18", "2", "0"], steps: ["1", "1", "1", "0.1"], accentIdx: 1,
    compute: "依帳單、小費比例、人數與稅率計算小費、含稅含小費總額與每人應付",
    computeFn: "    const bill = Number(billAmount) || 0;\n    const tipPct = (Number(tipPercent) || 0) / 100;\n    const people = Number(splitPeople) || 1;\n    const taxPct = (Number(taxRatePct) || 0) / 100;\n    const tax = bill * taxPct;\n    const tip = bill * tipPct;\n    const total = bill + tax + tip;\n    const perPerson = people > 0 ? total / people : total;\n    return { total, tip, perPerson, tax };",
    computeFnOverride: "    const bill = Number(billAmount) || 0;\n    const tipPct = (Number(tipPercent) || 0) / 100;\n    const people = Number(splitPeople) || 1;\n    const taxPct = (Number(taxRatePct) || 0) / 100;\n    const tax = bill * taxPct;\n    const tip = bill * tipPct;\n    const total = bill + tax + tip;\n    const perPerson = people > 0 ? total / people : total;\n    const tipRate = tipPct * 100;\n    return { tipRate, perPerson, total, tip };",
    primaryKey: "tipRate", primaryDecimals: 1, primaryUnit: "%", secondaryKey: "perPerson", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "total", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "tip", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "小費比例", primaryLabelEn: "Tip Rate", secondaryLabelZh: "每人應付", secondaryLabelEn: "Per Person",
    tertiaryLabelZh: "總計", tertiaryLabelEn: "Total", quaternaryLabelZh: "小費", quaternaryLabelEn: "Tip",
    bands: ["無小費", "偏低", "標準", "良好", "慷慨", "極慷慨"], bandThresholds: [1, 12, 18, 22, 25],
    bandHints: [
      "0% 小費,部分國家(如日本、台灣多數場合)不收小費。",
      "< 12%,偏低,在美國通常代表服務不滿意或快餐。",
      "12-18%,標準範圍,一般餐廳服務的常見比例。",
      "18-22%,良好服務的合理回報,美國正餐常見。",
      "22-25%,慷慨,適合優質服務或特殊場合。",
      "> 25%,極慷慨,通常保留給卓越服務或大型團體。",
    ],
    faqTitles: ["美國小費一般給多少?", "小費要不要含稅計算?", "外送、外帶也要給小費嗎?", "分帳怎麼算最公平?", "資料會上傳嗎?", "可以記錄常用比例嗎?"],
    faqAnswers: [
      "美國餐廳正餐通常 **15-20%**,18% 是常見標準;吧檯每杯 1-2 美元;外送約 10-15%;計程車/Uber 約 10-20%。服務特別好可給 25%+。歐洲、亞洲多數國家小費文化較淡或已含服務費。",
      "兩派做法都有:**算稅前**(只對食物服務給小費,較常見且合理)或**算稅後**(對含稅總額給,較大方)。本工具預設對帳單金額計算小費、稅另計,你可調整稅率欄位觀察差異。",
      "美國外送通常給 10-15% 或至少 3-5 美元,惡劣天氣可加給;外帶傳統上不強制,但若店家有特別包裝服務,給 10% 是禮貌。各地文化不同,本工具讓你自由設定比例。",
      "最公平是**含小費含稅的總額平分**(本工具預設),適合大家點得差不多時;若有人點很貴,則建議按各自消費比例分攤,專業版支援逐人項目分帳。",
      "完全不會。所有計算都在你的瀏覽器內完成,帳單金額不會傳送到任何伺服器。",
      "逐人項目分帳、常用比例記憶、四捨五入到整數與多幣別屬於專業版功能。",
    ],
    affiliates: [
      aff("銷售稅計算機", "Sales Tax Calculator", "/tools/finance/sales-tax-calculator"),
      aff("折扣計算機", "Discount Calculator", "/tools/finance/discount-calculator"),
      aff("貨幣轉換器", "Currency Converter", "/tools/finance/currency-converter"),
      aff("預算比例計算機", "Budget Ratio Calculator", "/tools/finance/budget-ratio-calculator"),
    ],
    exampleSolid: ["100", "18", "2", "0"], exampleHigh: ["240", "20", "4", "8"],
    solidLabelZh: "帳單 100 · 18% · 2 人", solidLabelEn: "Bill 100 · 18% · 2",
    highLabelZh: "帳單 240 · 20% · 4 人 · 稅 8%", highLabelEn: "Bill 240 · 20% · 4 · tax 8%",
    subtitleZh: "輸入帳單金額、小費比例與分攤人數，立即算出小費、總計與每人應付",
    subtitleEn: "Enter bill amount, tip percent, and number of people to compute tip, total, and per-person",
    definitionZh: "小費計算機以帳單金額、小費比例、分攤人數與稅率,計算應給小費、含稅含小費總額與每人應付金額,適用餐廳、外送、聚餐分帳。",
    formulaZh: "小費 = 帳單 × 小費比例;總計 = 帳單 + 稅 + 小費;每人應付 = 總計 ÷ 人數",
    limitationsZh: "本工具平均分攤總額,不處理逐人不同消費、自動服務費(gratuity)重複計算與多幣別;特殊分帳請依實際協議。",
    interpretationZh: "小費比例反映服務滿意度與地區文化;每人應付為快速分帳依據,人數越多單人負擔越低。",
    premiumTitleZh: "專業版 聚餐分帳工具組", premiumTextZh: "解鎖逐人項目分帳、按消費比例分攤、常用比例記憶、整數進位與多幣別即時換算。",
    premiumChipsZh: "逐人分帳|比例分攤|比例記憶|多幣別",
    premiumTitleEn: "Pro Bill Split Suite", premiumTextEn: "Unlock per-item splitting, proportional split, saved tip presets, rounding, and multi-currency.",
    premiumChipsEn: "Per-item|Proportional|Presets|Multi-FX",
  },
  // F-39 discount-calculator
  {
    file: "F39-discount-calculator.json",
    id: "discount-calculator", nameZh: "折扣計算機", nameEn: "Discount Calculator", color: "teal",
    inputs: ["原價", "折扣百分比%", "額外折抵", "數量"],
    inputsEn: ["Original Price", "Discount Percent", "Extra Off", "Quantity"],
    defaults: ["1000", "20", "0", "1"], steps: ["10", "1", "10", "1"], accentIdx: 1,
    compute: "依原價、折扣百分比、額外折抵與數量計算折後單價、總省金額與最終總額",
    computeFn: "    const price = Number(originalPrice) || 0;\n    const disc = (Number(discountPercent) || 0) / 100;\n    const extra = Number(extraOff) || 0;\n    const qty = Number(quantity) || 1;\n    const afterPct = price * (1 - disc);\n    const finalUnit = Math.max(0, afterPct - extra);\n    const total = finalUnit * qty;\n    const saved = (price - finalUnit) * qty;\n    const effDisc = price > 0 ? ((price - finalUnit) / price) * 100 : 0;\n    return { finalUnit, total, saved, effDisc };",
    primaryKey: "effDisc", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "finalUnit", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "total", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "saved", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "實際折扣", primaryLabelEn: "Effective Discount", secondaryLabelZh: "折後單價", secondaryLabelEn: "Final Unit Price",
    tertiaryLabelZh: "最終總額", tertiaryLabelEn: "Final Total", quaternaryLabelZh: "總共省下", quaternaryLabelEn: "Total Saved",
    bands: ["無折扣", "小折", "中折", "大折", "超殺", "出清"], bandThresholds: [1, 15, 30, 50, 70],
    bandHints: [
      "0% 折扣,原價購買,可考慮搭配優惠券或會員價。",
      "< 15%,小幅折扣,常見於一般促銷或會員小折。",
      "15-30%,中等折扣,季節性促銷的常見幅度。",
      "30-50%,大折扣,換季出清或週年慶的吸引力區間。",
      "50-70%,超殺價,通常為清庫存或限時搶購。",
      "> 70%,出清等級,務必確認是否為原價灌水後的假折扣。",
    ],
    faqTitles: ["先打折還是先折抵划算?", "買一送一等於幾折?", "怎麼看穿假折扣?", "多重折扣怎麼疊加?", "資料會上傳嗎?", "可以比較多家價格嗎?"],
    faqAnswers: [
      "通常**先按百分比折扣、再扣固定金額折抵**對消費者較有利(本工具預設此順序)。例如原價 1000、打 8 折後 800、再折 100 = 700。若順序相反(先折 100 = 900、再打 8 折 = 720)反而較貴。結帳前留意系統的折抵順序。",
      "**買一送一**等於兩件均價 5 折(50% off);**買二送一**等於三件均價約 67 折(33% off);**第二件半價**等於兩件均價 75 折(25% off)。換算成單件實際折扣才能跨檔比較,本工具的「實際折扣」欄位即此用途。",
      "假折扣手法:**(1) 先抬高原價再打折**、(2) 標示「最高」折扣但僅限少數品項、(3) 加價購門檻。破解方法:查歷史價格(如比價網)、算實際折後單價、比較不同通路同品項,別只看折扣數字。",
      "多重折扣是**相乘**而非相加。例如「打 8 折再打 9 折」= 0.8 × 0.9 = 0.72,即實際 72 折(28% off),不是 8+1=9 折也不是 7 折。本工具的百分比折扣與額外折抵可組合計算。",
      "完全不會。所有計算都在你的瀏覽器內完成,價格資料不會傳送到任何伺服器。",
      "多通路比價、優惠券疊加模擬、歷史價格追蹤與單位價格比較屬於專業版功能。",
    ],
    affiliates: [
      aff("加成計算機", "Markup Calculator", "/tools/finance/markup-calculator"),
      aff("銷售稅計算機", "Sales Tax Calculator", "/tools/finance/sales-tax-calculator"),
      aff("利潤率計算機", "Profit Margin Calculator", "/tools/finance/profit-margin-calculator"),
      aff("小費計算機", "Tip Calculator", "/tools/finance/tip-calculator"),
    ],
    exampleSolid: ["1000", "20", "0", "1"], exampleHigh: ["2500", "40", "200", "2"],
    solidLabelZh: "原價 1000 · 8 折", solidLabelEn: "List 1000 · 20% off",
    highLabelZh: "原價 2500 · 6 折 · 折 200 · 2 件", highLabelEn: "List 2500 · 40% off · -200 · 2",
    subtitleZh: "輸入原價、折扣與數量，立即算出折後單價、總省金額與實際折扣",
    subtitleEn: "Enter original price, discount, and quantity to compute final price, total savings, and effective discount",
    definitionZh: "折扣計算機以原價、折扣百分比、額外固定折抵與數量,計算折後單價、最終總額、總省金額與實際折扣率,適用購物、促銷比價與報價。",
    formulaZh: "折後單價 = 原價 × (1 − 折扣%) − 額外折抵;最終總額 = 折後單價 × 數量;實際折扣% = (原價 − 折後單價) / 原價",
    limitationsZh: "本工具採先百分比後固定折抵的順序,不含稅、運費與多重優惠券疊加規則;實際結帳金額請以商家系統為準。",
    interpretationZh: "實際折扣率讓你跨檔比較不同促銷的真實優惠;折後單價可用於與其他通路同品項比價。",
    premiumTitleZh: "專業版 購物比價工具組", premiumTextZh: "解鎖多通路比價、優惠券疊加模擬、買N送M換算、單位價格比較與歷史價格追蹤。",
    premiumChipsZh: "多通路比價|優惠疊加|買N送M|單位比價",
    premiumTitleEn: "Pro Shopping Compare Suite", premiumTextEn: "Unlock multi-store compare, coupon stacking, buy-N-get-M conversion, unit pricing, and price history.",
    premiumChipsEn: "Compare|Stacking|BOGO|Unit Price",
  },
  // F-40 markup-calculator
  {
    file: "F40-markup-calculator.json",
    id: "markup-calculator", nameZh: "加成計算機", nameEn: "Markup Calculator", color: "lime",
    inputs: ["商品成本", "加成百分比%", "目標毛利%", "數量"],
    inputsEn: ["Item Cost", "Markup Percent", "Target Margin Pct", "Quantity"],
    defaults: ["100", "50", "0", "1"], steps: ["1", "1", "1", "1"], accentIdx: 1,
    compute: "依成本與加成百分比計算售價、單位毛利、毛利率與總毛利",
    computeFn: "    const cost = Number(itemCost) || 0;\n    const mk = (Number(markupPercent) || 0) / 100;\n    const qty = Number(quantity) || 1;\n    const price = cost * (1 + mk);\n    const unitProfit = price - cost;\n    const margin = price > 0 ? (unitProfit / price) * 100 : 0;\n    const totalProfit = unitProfit * qty;\n    return { margin, price, unitProfit, totalProfit };",
    primaryKey: "margin", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "price", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "unitProfit", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "totalProfit", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "毛利率", primaryLabelEn: "Margin", secondaryLabelZh: "建議售價", secondaryLabelEn: "Selling Price",
    tertiaryLabelZh: "單位毛利", tertiaryLabelEn: "Unit Profit", quaternaryLabelZh: "總毛利", quaternaryLabelEn: "Total Profit",
    bands: ["虧損", "微利", "普通", "健康", "高利", "超高"], bandThresholds: [1, 20, 35, 50, 65],
    bandHints: [
      "毛利率 ≤ 0%,售價低於成本,賠本銷售,務必檢視定價。",
      "< 20%,微利,常見於量大薄利的零售或大宗商品。",
      "20-35%,普通毛利,多數實體零售的常見區間。",
      "35-50%,健康毛利,品牌商品或差異化產品常見。",
      "50-65%,高毛利,常見於軟體、服務或精品。",
      "> 65%,超高毛利,常見於數位產品、奢侈品或專利商品。",
    ],
    faqTitles: ["加成和毛利率差在哪?", "成本加 100% 等於毛利率多少?", "怎麼定價才合理?", "毛利率多少算健康?", "資料會上傳嗎?", "可以反推目標毛利的售價嗎?"],
    faqAnswers: [
      "**加成(Markup)**以成本為基準:加成% = (售價 − 成本) / 成本;**毛利率(Margin)**以售價為基準:毛利率% = (售價 − 成本) / 售價。兩者常被混淆但數字不同。例如成本 100、售價 150,加成 50% 但毛利率只有 33%。",
      "成本加成 100%(售價 = 成本 × 2)等於毛利率 50%。換算公式:毛利率 = 加成 / (1 + 加成)。常見對照:加成 25%→毛利 20%、加成 50%→毛利 33%、加成 100%→毛利 50%、加成 200%→毛利 67%。",
      "合理定價需考量:**(1) 成本**(含進貨、運費、人工、攤提)、**(2) 市場行情**(競品價格)、**(3) 目標毛利**(覆蓋營運費用後仍獲利)、**(4) 顧客願付價格**。本工具幫你從成本快速算出不同加成下的售價與毛利。",
      "因產業而異:超市生鮮 5-15%、一般零售 30-50%、服飾 50-60%、餐飲 60-70%(食材成本佔比反推)、軟體/數位 80%+。健康毛利需能覆蓋固定成本並留淨利,建議對照同業基準。",
      "完全不會。所有計算都在你的瀏覽器內完成,成本與售價資料不會傳送到任何伺服器。",
      "由目標毛利率反推售價、批量定價、含稅含運加成與多階定價(批發/零售)屬於專業版功能。",
    ],
    affiliates: [
      aff("利潤率計算機", "Profit Margin Calculator", "/tools/finance/profit-margin-calculator"),
      aff("折扣計算機", "Discount Calculator", "/tools/finance/discount-calculator"),
      aff("損益兩平計算機", "Break-Even Calculator", "/tools/finance/break-even-calculator"),
      aff("ROAS 計算機", "ROAS Calculator", "/tools/finance/roas-calculator"),
    ],
    exampleSolid: ["100", "50", "0", "1"], exampleHigh: ["40", "150", "0", "100"],
    solidLabelZh: "成本 100 · 加成 50%", solidLabelEn: "Cost 100 · 50% markup",
    highLabelZh: "成本 40 · 加成 150% · 100 件", highLabelEn: "Cost 40 · 150% · 100",
    subtitleZh: "輸入成本與加成百分比，立即算出建議售價、單位毛利與毛利率",
    subtitleEn: "Enter cost and markup percent to compute selling price, unit profit, and margin",
    definitionZh: "加成計算機以成本與加成百分比,計算建議售價、單位毛利、毛利率與總毛利,並釐清加成與毛利率的差異,適用零售、批發與電商定價。",
    formulaZh: "售價 = 成本 × (1 + 加成%);單位毛利 = 售價 − 成本;毛利率% = 單位毛利 / 售價",
    limitationsZh: "本工具僅算單一成本加成,不含稅、運費、平台抽成、退貨損耗與分階定價;實際定價請納入完整營運成本與市場因素。",
    interpretationZh: "毛利率反映每元銷售的獲利空間;加成% 是定價工具,毛利率是獲利指標,兩者需搭配市場行情判斷。",
    premiumTitleZh: "專業版 定價策略工具組", premiumTextZh: "解鎖目標毛利反推售價、含稅含運加成、批發/零售多階定價、平台抽成試算與競品比價。",
    premiumChipsZh: "毛利反推|含稅含運|多階定價|抽成試算",
    premiumTitleEn: "Pro Pricing Strategy Suite", premiumTextEn: "Unlock target-margin reverse pricing, tax/shipping markup, wholesale/retail tiers, platform fees, and competitor compare.",
    premiumChipsEn: "Reverse|Tax/Ship|Tiers|Fees",
  },
  // F-41 vat-calculator
  {
    file: "F41-vat-calculator.json",
    id: "vat-calculator", nameZh: "加值稅 VAT 計算機", nameEn: "VAT Calculator", color: "cyan",
    inputs: ["淨額", "VAT 稅率%", "數量", "是否含稅金額"],
    inputsEn: ["Net Amount", "VAT Rate Pct", "Quantity", "Gross Amount"],
    defaults: ["100", "20", "1", "0"], steps: ["1", "0.5", "1", "1"], accentIdx: 1,
    compute: "依淨額或含稅金額與 VAT 稅率，計算 VAT 稅額、含稅總額與淨額",
    computeFn: "    const net = Number(netAmount) || 0;\n    const rate = (Number(vatRatePct) || 0) / 100;\n    const qty = Number(quantity) || 1;\n    const gross = Number(grossAmount) || 0;\n    let baseNet, vat, grossTotal;\n    if (gross > 0) {\n      baseNet = gross / (1 + rate);\n      vat = gross - baseNet;\n      grossTotal = gross * qty;\n    } else {\n      baseNet = net;\n      vat = net * rate;\n      grossTotal = (net + vat) * qty;\n    }\n    const vatTotal = vat * qty;\n    const netTotal = baseNet * qty;\n    return { grossTotal, vatTotal, netTotal, vat };",
    computeFnOverride: "    const net = Number(netAmount) || 0;\n    const rate = (Number(vatRatePct) || 0) / 100;\n    const qty = Number(quantity) || 1;\n    const gross = Number(grossAmount) || 0;\n    let baseNet, vat, grossTotal;\n    if (gross > 0) {\n      baseNet = gross / (1 + rate);\n      vat = gross - baseNet;\n      grossTotal = gross * qty;\n    } else {\n      baseNet = net;\n      vat = net * rate;\n      grossTotal = (net + vat) * qty;\n    }\n    const vatTotal = vat * qty;\n    const netTotal = baseNet * qty;\n    const ratePct = rate * 100;\n    return { ratePct, grossTotal, vatTotal, netTotal };",
    primaryKey: "ratePct", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "grossTotal", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "vatTotal", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "netTotal", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "適用稅率", primaryLabelEn: "Applied Rate", secondaryLabelZh: "含稅總額", secondaryLabelEn: "Gross Total",
    tertiaryLabelZh: "VAT 稅額", tertiaryLabelEn: "VAT Amount", quaternaryLabelZh: "淨額合計", quaternaryLabelEn: "Net Total",
    bands: ["免稅", "極低", "低", "標準", "高", "極高"], bandThresholds: [0.01, 8, 15, 21, 25],
    bandHints: [
      "0% VAT,零稅率或免稅商品(如出口、特定民生品)。",
      "< 8%,低稅率,常見於部分國家的優惠稅率品項。",
      "8-15%,中低稅率,部分亞洲國家標準 VAT 區間。",
      "15-21%,標準 VAT 區間,多數歐盟國家的標準稅率。",
      "21-25%,偏高,北歐與部分歐洲國家的標準稅率。",
      "> 25%,極高,匈牙利等少數國家的標準稅率。",
    ],
    faqTitles: ["VAT 和銷售稅差在哪?", "含稅價怎麼算出 VAT?", "台灣營業稅是 VAT 嗎?", "出口為什麼是零稅率?", "資料會上傳嗎?", "可以含稅反推淨額嗎?"],
    faqAnswers: [
      "**VAT(加值稅)**在生產到銷售每一環節對「加值部分」課徵,企業可進項抵扣,最終由消費者負擔;**銷售稅(Sales Tax)**只在零售端一次性課徵,無進項抵扣。VAT 常見於歐洲、亞洲,Sales Tax 常見於美國。",
      "含稅價反推:淨額 = 含稅價 ÷ (1 + 稅率),VAT = 含稅價 − 淨額。例如含稅 120、稅率 20%,淨額 = 120 ÷ 1.2 = 100,VAT = 20。本工具填入「含稅金額」欄位即自動反推,留空則由淨額正推。",
      "台灣的**營業稅**本質上就是 VAT(加值型營業稅),標準稅率 5%,企業可扣抵進項稅額,最終由消費者承擔。少數行業適用非加值型(總額型)營業稅。本工具可設定 5% 計算台灣情境。",
      "出口適用**零稅率(zero-rated)**是為避免重複課稅與維持出口競爭力——商品在他國消費,由進口國課稅。零稅率仍可退還進項 VAT,與「免稅(exempt,不可退進項)」不同,這是 VAT 制度的關鍵設計。",
      "完全不會。所有計算都在你的瀏覽器內完成,金額與稅率資料不會傳送到任何伺服器。",
      "含稅反推淨額(本工具已支援)、進項/銷項抵扣試算、多國 VAT 稅率庫與發票批次計算屬於專業版功能。",
    ],
    affiliates: [
      aff("銷售稅計算機", "Sales Tax Calculator", "/tools/finance/sales-tax-calculator"),
      aff("利潤率計算機", "Profit Margin Calculator", "/tools/finance/profit-margin-calculator"),
      aff("加成計算機", "Markup Calculator", "/tools/finance/markup-calculator"),
      aff("貨幣轉換器", "Currency Converter", "/tools/finance/currency-converter"),
    ],
    exampleSolid: ["100", "20", "1", "0"], exampleHigh: ["0", "20", "1", "120"],
    solidLabelZh: "淨額 100 · 20%", solidLabelEn: "Net 100 · 20%",
    highLabelZh: "含稅 120 · 20% 反推", highLabelEn: "Gross 120 · 20% reverse",
    subtitleZh: "輸入淨額或含稅金額與 VAT 稅率，立即算出稅額、含稅總額與淨額",
    subtitleEn: "Enter net or gross amount with VAT rate to compute VAT, gross total, and net total",
    definitionZh: "加值稅 VAT 計算機支援由淨額正推或由含稅金額反推,計算 VAT 稅額、含稅總額與淨額合計,適用歐盟、英國、台灣營業稅等加值稅情境的報價與發票。",
    formulaZh: "正推:VAT = 淨額 × 稅率,含稅 = 淨額 + VAT;反推:淨額 = 含稅 ÷ (1 + 稅率),VAT = 含稅 − 淨額",
    limitationsZh: "本工具採單一稅率,不處理多級稅率、進項抵扣、免稅/零稅率混合與跨境逆向課稅;申報請以當地稅法與會計系統為準。",
    interpretationZh: "填入含稅金額時自動反推淨額,適合驗證收據;留空則由淨額正推,適合報價;VAT 稅額為應申報金額參考。",
    premiumTitleZh: "專業版 VAT 申報工具組", premiumTextZh: "解鎖進項/銷項抵扣試算、多國 VAT 稅率庫、發票批次計算、跨境逆向課稅與申報報表匯出。",
    premiumChipsZh: "進銷抵扣|多國稅率|批次發票|申報報表",
    premiumTitleEn: "Pro VAT Filing Suite", premiumTextEn: "Unlock input/output VAT, multi-country rate database, batch invoicing, reverse-charge, and filing reports.",
    premiumChipsEn: "Input/Output|Rate DB|Batch|Reports",
  },
  // F-42 effective-annual-rate
  {
    file: "F42-effective-annual-rate.json",
    id: "effective-annual-rate-calculator", nameZh: "有效年利率計算機", nameEn: "Effective Annual Rate Calculator", color: "fuchsia",
    inputs: ["名目年利率%", "每年複利次數", "本金", "年數"],
    inputsEn: ["Nominal Rate Pct", "Compounds Per Year", "Principal", "Years"],
    defaults: ["12", "12", "10000", "1"], steps: ["0.1", "1", "1000", "1"], accentIdx: 0,
    compute: "依名目年利率與複利次數計算有效年利率(EAR)、期利率與終值",
    computeFn: "    const nominal = (Number(nominalRatePct) || 0) / 100;\n    const m = Number(compoundsPerYear) || 1;\n    const P = Number(principal) || 0;\n    const yrs = Number(years) || 1;\n    const periodRate = (nominal / m) * 100;\n    const ear = (Math.pow(1 + nominal / m, m) - 1) * 100;\n    const fv = P * Math.pow(1 + nominal / m, m * yrs);\n    const interest = fv - P;\n    return { ear, periodRate, fv, interest };",
    primaryKey: "ear", primaryDecimals: 4, primaryUnit: "%", secondaryKey: "periodRate", secondaryDecimals: 4, secondaryUnit: "%",
    tertiaryKey: "fv", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "interest", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "有效年利率 (EAR)", primaryLabelEn: "Effective Annual Rate", secondaryLabelZh: "每期利率", secondaryLabelEn: "Period Rate",
    tertiaryLabelZh: "終值", tertiaryLabelEn: "Future Value", quaternaryLabelZh: "利息", quaternaryLabelEn: "Interest",
    bandKey: "ear",
    bands: ["極低", "低", "中等", "偏高", "高", "極高"], bandThresholds: [2, 5, 10, 20, 36],
    bandHints: [
      "EAR < 2%,屬於低利環境,常見於定存或高評級債。",
      "2-5%,溫和利率,常見於穩健投資或優質債券。",
      "5-10%,中等,常見於股市長期平均報酬或信貸利率。",
      "10-20%,偏高,常見於信用卡循環或高息信貸。",
      "20-36%,高,接近信用卡循環利率上限,負擔沉重。",
      "> 36%,極高,常見於發薪日貸款或高利貸,務必避免。",
    ],
    faqTitles: ["EAR 和 APR 差在哪?", "為什麼複利越頻繁 EAR 越高?", "信用卡實際利率是多少?", "怎麼用 EAR 比較不同貸款?", "資料會上傳嗎?", "可以連續複利嗎?"],
    faqAnswers: [
      "**APR(名目年利率)**是把期利率簡單乘以期數,不計複利;**EAR(有效年利率)**把複利效果算進去,反映實際成本。例如月息 1%、APR 12%,但 EAR = (1.01)^12 − 1 = 12.68%。借貸要看 EAR 才知真實成本。",
      "因為利息會「利滾利」。複利越頻繁,每次計息後的本金越快變大,後續利息也越多。同樣名目 12%:年複利 EAR=12%、月複利 EAR=12.68%、日複利 EAR≈12.75%、連續複利 EAR≈12.75%。次數越多越逼近上限。",
      "信用卡常標示「月息」或「日息」誤導消費者。以日息 0.04%(年化看似 14.6%)為例,因每日複利,EAR 可能達 15-16%;若標 APR 18% 按日複利,EAR 接近 19.7%。本工具幫你算出真實的 EAR。",
      "把不同貸款的名目利率與複利次數都換算成 EAR,再比較。EAR 把複利頻率統一,是唯一能公平比較的指標。月複利 12% 比季複利 12% 實際更貴,只看名目會誤判。",
      "完全不會。所有計算都在你的瀏覽器內完成,利率與本金資料不會傳送到任何伺服器。",
      "連續複利(e^r − 1)、APR↔EAR 雙向換算、含手續費的真實年利率(APRC)與多貸款比較屬於專業版功能。",
    ],
    affiliates: [
      aff("複利計算機", "Compound Interest Calculator", "/tools/finance/compound-interest-calculator"),
      aff("簡單利息計算機", "Simple Interest Calculator", "/tools/finance/simple-interest-calculator"),
      aff("貸款計算機", "Loan Calculator", "/tools/finance/loan-calculator"),
      aff("信用卡還款計算機", "Credit Card Payoff Calculator", "/tools/finance/credit-card-payoff-calculator"),
    ],
    exampleSolid: ["12", "12", "10000", "1"], exampleHigh: ["18", "365", "5000", "2"],
    solidLabelZh: "名目 12% · 月複利", solidLabelEn: "Nom 12% · monthly",
    highLabelZh: "名目 18% · 日複利 · 2 年", highLabelEn: "Nom 18% · daily · 2y",
    subtitleZh: "輸入名目年利率與複利次數，立即算出有效年利率(EAR)與終值",
    subtitleEn: "Enter nominal rate and compounding frequency to compute the effective annual rate and future value",
    definitionZh: "有效年利率計算機以名目年利率與每年複利次數,計算有效年利率(EAR)、每期利率與終值,用於公平比較不同複利頻率的存款與貸款真實成本。",
    formulaZh: "EAR = (1 + 名目利率 / m)^m − 1;終值 = 本金 × (1 + 名目利率 / m)^(m × 年數);其中 m 為每年複利次數",
    limitationsZh: "本工具不含手續費、開辦費與保險,因此非完整 APRC(實質年利率);連續複利需用 e^r 公式,屬專業版。",
    interpretationZh: "EAR 越高代表存款收益越好或貸款成本越高;比較不同產品時,務必統一看 EAR 而非名目利率。",
    premiumTitleZh: "專業版 利率分析工具組", premiumTextZh: "解鎖連續複利、APR↔EAR 雙向換算、含手續費的實質年利率(APRC)、多貸款比較與利率敏感度分析。",
    premiumChipsZh: "連續複利|APR換算|APRC|多貸比較",
    premiumTitleEn: "Pro Rate Analysis Suite", premiumTextEn: "Unlock continuous compounding, APR↔EAR conversion, fee-inclusive APRC, multi-loan compare, and rate sensitivity.",
    premiumChipsEn: "Continuous|APR↔EAR|APRC|Compare",
  },
  // F-43 simple-interest
  {
    file: "F43-simple-interest.json",
    id: "simple-interest-calculator", nameZh: "簡單利息計算機", nameEn: "Simple Interest Calculator", color: "indigo",
    inputs: ["本金", "年利率%", "年數", "額外提存"],
    inputsEn: ["Principal", "Annual Rate Pct", "Years", "Extra Deposit"],
    defaults: ["10000", "5", "3", "0"], steps: ["1000", "0.1", "1", "100"], accentIdx: 1,
    compute: "依本金、年利率與年數計算單利利息、本利和與年化利息",
    computeFn: "    const P = Number(principal) || 0;\n    const r = (Number(annualRatePct) || 0) / 100;\n    const t = Number(years) || 0;\n    const extra = Number(extraDeposit) || 0;\n    const base = P + extra;\n    const interest = base * r * t;\n    const total = base + interest;\n    const yearlyInterest = base * r;\n    return { interest, total, yearlyInterest, base };",
    computeFnOverride: "    const P = Number(principal) || 0;\n    const r = (Number(annualRatePct) || 0) / 100;\n    const t = Number(years) || 0;\n    const extra = Number(extraDeposit) || 0;\n    const base = P + extra;\n    const interest = base * r * t;\n    const total = base + interest;\n    const growthPct = base > 0 ? (interest / base) * 100 : 0;\n    return { growthPct, total, interest, base };",
    primaryKey: "growthPct", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "total", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "interest", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "base", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "總成長率", primaryLabelEn: "Total Growth", secondaryLabelZh: "本利和", secondaryLabelEn: "Total Amount",
    tertiaryLabelZh: "總利息", tertiaryLabelEn: "Total Interest", quaternaryLabelZh: "計息本金", quaternaryLabelEn: "Base Principal",
    bands: ["極低", "低", "中等", "偏高", "高", "極高"], bandThresholds: [5, 15, 30, 50, 100],
    bandHints: [
      "總成長 < 5%,屬於短期或低利,利息貢獻有限。",
      "5-15%,溫和成長,常見於 1-3 年定存或穩健票券。",
      "15-30%,中等,常見於中天期或中利率單利商品。",
      "30-50%,偏高,反映較長年限或較高利率的累積。",
      "50-100%,高,單利下需長年限或高利率才能達到。",
      "> 100%,利息超過本金,通常為極長年限或極高利率,務必確認計息方式。",
    ],
    faqTitles: ["單利和複利差多少?", "什麼情況用單利?", "短期借貸算單利划算嗎?", "怎麼從單利反推年利率?", "資料會上傳嗎?", "可以加上定期提存嗎?"],
    faqAnswers: [
      "**單利**只對原始本金計息,利息不再生息:利息 = 本金 × 利率 × 年數;**複利**利息會滾入本金再生息,長期下複利遠超單利。例如 10000 元、5%、10 年:單利 = 5000,複利 ≈ 6289,差距隨時間擴大。",
      "單利常見於:**(1) 短期票券、國庫券**、(2) 部分**汽車貸款、消費貸款**、(3) **公債、定存單**的計息、(4) 法律上的遲延利息計算。長期投資與儲蓄則多用複利,效果更佳。",
      "短期(< 1 年)時單利與複利差異極小,選擇影響不大;但若是借款,單利通常對借款人較有利(總利息較低)。關鍵看合約寫的是單利還是複利,以及計息頻率。",
      "由單利反推年利率:利率 = 利息 / (本金 × 年數)。例如本金 10000、3 年共得利息 1500,年利率 = 1500 / (10000 × 3) = 5%。本工具可正算利息,反推請用專業版。",
      "完全不會。所有計算都在你的瀏覽器內完成,本金與利率資料不會傳送到任何伺服器。",
      "定期提存、單利vs複利對照、利率反推與分期付款的單利攤還屬於專業版功能。",
    ],
    affiliates: [
      aff("複利計算機", "Compound Interest Calculator", "/tools/finance/compound-interest-calculator"),
      aff("有效年利率計算機", "Effective Annual Rate Calculator", "/tools/finance/effective-annual-rate-calculator"),
      aff("貸款計算機", "Loan Calculator", "/tools/finance/loan-calculator"),
      aff("儲蓄目標計算機", "Savings Goal Calculator", "/tools/finance/savings-goal-calculator"),
    ],
    exampleSolid: ["10000", "5", "3", "0"], exampleHigh: ["50000", "8", "5", "0"],
    solidLabelZh: "本金 1 萬 · 5% · 3 年", solidLabelEn: "P 10k · 5% · 3y",
    highLabelZh: "本金 5 萬 · 8% · 5 年", highLabelEn: "P 50k · 8% · 5y",
    subtitleZh: "輸入本金、年利率與年數，立即算出單利利息與本利和",
    subtitleEn: "Enter principal, annual rate, and years to compute simple interest and total amount",
    definitionZh: "簡單利息計算機以本金、年利率與年數,依單利公式計算總利息、本利和與每年利息,適用短期票券、部分車貸消費貸與遲延利息的計算。",
    formulaZh: "利息 = 本金 × 年利率 × 年數;本利和 = 本金 + 利息;每年利息 = 本金 × 年利率",
    limitationsZh: "本工具採單利(利息不複利),不適用會複利的儲蓄或信用卡;若實際為複利計息,請改用複利計算機以免低估。",
    interpretationZh: "單利下利息與時間成正比,適合短期;長期儲蓄複利效果遠優於單利,選擇產品時請確認計息方式。",
    premiumTitleZh: "專業版 利息對照工具組", premiumTextZh: "解鎖單利 vs 複利對照、定期提存、利率反推、分期單利攤還與多情境利息比較。",
    premiumChipsZh: "單複利對照|定期提存|利率反推|分期攤還",
    premiumTitleEn: "Pro Interest Compare Suite", premiumTextEn: "Unlock simple vs compound compare, recurring deposits, rate reverse-solve, installment schedule, and scenarios.",
    premiumChipsEn: "Compare|Deposits|Reverse|Schedule",
  },
  // F-44 future-value
  {
    file: "F44-future-value.json",
    id: "future-value-calculator", nameZh: "終值計算機", nameEn: "Future Value Calculator", color: "orange",
    inputs: ["現值本金", "年報酬率%", "年數", "每年提存"],
    inputsEn: ["Present Value", "Annual Return Pct", "Years", "Annual Deposit"],
    defaults: ["10000", "7", "20", "0"], steps: ["1000", "0.1", "1", "1000"], accentIdx: 1,
    compute: "依現值、年報酬率、年數與每年提存計算終值、總投入與總獲利",
    computeFn: "    const PV = Number(presentValue) || 0;\n    const r = (Number(annualReturnPct) || 0) / 100;\n    const n = Number(years) || 0;\n    const pmt = Number(annualDeposit) || 0;\n    const fvLump = PV * Math.pow(1 + r, n);\n    const fvAnnuity = r > 0 ? pmt * ((Math.pow(1 + r, n) - 1) / r) : pmt * n;\n    const fv = fvLump + fvAnnuity;\n    const contributed = PV + pmt * n;\n    const gain = fv - contributed;\n    return { fv, contributed, gain, fvLump };",
    computeFnOverride: "    const PV = Number(presentValue) || 0;\n    const r = (Number(annualReturnPct) || 0) / 100;\n    const n = Number(years) || 0;\n    const pmt = Number(annualDeposit) || 0;\n    const fvLump = PV * Math.pow(1 + r, n);\n    const fvAnnuity = r > 0 ? pmt * ((Math.pow(1 + r, n) - 1) / r) : pmt * n;\n    const fv = fvLump + fvAnnuity;\n    const contributed = PV + pmt * n;\n    const gain = fv - contributed;\n    const gainPct = contributed > 0 ? (gain / contributed) * 100 : 0;\n    return { gainPct, fv, gain, contributed };",
    primaryKey: "gainPct", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "fv", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "gain", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "contributed", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "總成長率", primaryLabelEn: "Total Growth", secondaryLabelZh: "終值", secondaryLabelEn: "Future Value",
    tertiaryLabelZh: "總獲利", tertiaryLabelEn: "Total Gain", quaternaryLabelZh: "總投入", quaternaryLabelEn: "Total Contributed",
    bands: ["保守", "溫和", "穩健", "成長", "強勁", "驚人"], bandThresholds: [25, 60, 120, 250, 500],
    bandHints: [
      "總成長 < 25%,屬於短期或低報酬,複利尚未顯威。",
      "25-60%,溫和成長,常見於 5-10 年期穩健配置。",
      "60-120%,穩健,複利開始發揮,資產接近翻倍。",
      "120-250%,成長,長年限複利成果,資產數倍成長。",
      "250-500%,強勁,長期高報酬累積的可觀成果。",
      "> 500%,驚人,超長年限或高報酬,複利威力充分展現。",
    ],
    faqTitles: ["終值是什麼?", "為什麼複利時間越長越驚人?", "7% 報酬率合理嗎?", "終值和現值怎麼互換?", "資料會上傳嗎?", "可以模擬通膨調整後的終值嗎?"],
    faqAnswers: [
      "**終值(Future Value)**是一筆現有資金或定期投入,在特定報酬率與時間後成長到的金額。它回答「現在投入,未來會變多少」,是退休規劃、儲蓄目標、投資決策的核心概念。本工具同時支援一次性本金與每年提存。",
      "因為複利是指數成長。72 法則:本金翻倍所需年數 ≈ 72 / 報酬率%。以 7% 為例約 10 年翻倍、20 年變 4 倍、30 年變約 8 倍。時間是複利最大的盟友,越早開始差距越驚人。",
      "美股長期(扣通膨前)年化約 7-10%,扣通膨後實質約 5-7%。但這是長期平均,單年波動極大(可能 −30% 到 +30%)。規劃時用 6-7% 較保守合理,別用近期牛市的高報酬外推。",
      "終值 = 現值 × (1 + r)^n;反過來現值 = 終值 ÷ (1 + r)^n。終值算「未來會變多少」,現值算「未來的錢現在值多少」。兩者是同一公式的正反運算,搭配使用可做完整財務規劃。",
      "完全不會。所有計算都在你的瀏覽器內完成,本金與報酬率資料不會傳送到任何伺服器。",
      "通膨調整後實質終值、月提存、報酬率區間蒙地卡羅模擬與多情境比較屬於專業版功能。",
    ],
    affiliates: [
      aff("現值計算機", "Present Value Calculator", "/tools/finance/present-value-calculator"),
      aff("複利計算機", "Compound Interest Calculator", "/tools/finance/compound-interest-calculator"),
      aff("退休計算機", "Retirement Calculator", "/tools/finance/retirement-calculator"),
      aff("儲蓄目標計算機", "Savings Goal Calculator", "/tools/finance/savings-goal-calculator"),
    ],
    exampleSolid: ["10000", "7", "20", "0"], exampleHigh: ["10000", "8", "30", "6000"],
    solidLabelZh: "本金 1 萬 · 7% · 20 年", solidLabelEn: "PV 10k · 7% · 20y",
    highLabelZh: "本金 1 萬 · 8% · 30 年 · 年存 6 千", highLabelEn: "PV 10k · 8% · 30y · +6k/yr",
    subtitleZh: "輸入現值、年報酬率與年數，立即算出複利終值、總投入與總獲利",
    subtitleEn: "Enter present value, annual return, and years to compute compound future value, contributions, and gain",
    definitionZh: "終值計算機以現值本金、年報酬率、年數與每年提存,計算複利成長後的終值、總投入與總獲利,適用退休、儲蓄目標與長期投資的成長預估。",
    formulaZh: "終值 = 現值 × (1 + r)^n + 每年提存 × ((1 + r)^n − 1) / r;其中 r 為年報酬率、n 為年數",
    limitationsZh: "本工具假設固定年報酬率與年複利,不計通膨、稅負、手續費與報酬波動;實際市場報酬逐年不同,結果僅供長期規劃參考。",
    interpretationZh: "總獲利為終值減總投入,反映複利貢獻;報酬率與年數對終值的影響呈指數放大,越早投入效果越強。",
    premiumTitleZh: "專業版 財富成長工具組", premiumTextZh: "解鎖通膨調整實質終值、月提存、報酬率區間蒙地卡羅模擬、多情境比較與目標達成機率。",
    premiumChipsZh: "通膨調整|月提存|蒙地卡羅|達成機率",
    premiumTitleEn: "Pro Wealth Growth Suite", premiumTextEn: "Unlock inflation-adjusted FV, monthly deposits, Monte Carlo return ranges, scenario compare, and goal probability.",
    premiumChipsEn: "Inflation|Monthly|Monte Carlo|Probability",
  },
  // F-45 present-value
  {
    file: "F45-present-value.json",
    id: "present-value-calculator", nameZh: "現值計算機", nameEn: "Present Value Calculator", color: "yellow",
    inputs: ["未來金額", "折現率%", "年數", "每年現金流"],
    inputsEn: ["Future Amount", "Discount Rate Pct", "Years", "Annual Cash Flow"],
    defaults: ["100000", "6", "10", "0"], steps: ["1000", "0.1", "1", "1000"], accentIdx: 1,
    compute: "依未來金額、折現率與年數計算現值、折現總額與折現損失",
    computeFn: "    const FV = Number(futureAmount) || 0;\n    const r = (Number(discountRatePct) || 0) / 100;\n    const n = Number(years) || 0;\n    const cf = Number(annualCashFlow) || 0;\n    const pvLump = FV / Math.pow(1 + r, n);\n    const pvAnnuity = r > 0 ? cf * ((1 - Math.pow(1 + r, -n)) / r) : cf * n;\n    const pv = pvLump + pvAnnuity;\n    const nominalTotal = FV + cf * n;\n    const discountLoss = nominalTotal - pv;\n    return { pv, discountLoss, nominalTotal, pvLump };",
    computeFnOverride: "    const FV = Number(futureAmount) || 0;\n    const r = (Number(discountRatePct) || 0) / 100;\n    const n = Number(years) || 0;\n    const cf = Number(annualCashFlow) || 0;\n    const pvLump = FV / Math.pow(1 + r, n);\n    const pvAnnuity = r > 0 ? cf * ((1 - Math.pow(1 + r, -n)) / r) : cf * n;\n    const pv = pvLump + pvAnnuity;\n    const nominalTotal = FV + cf * n;\n    const discountLoss = nominalTotal - pv;\n    const lossPct = nominalTotal > 0 ? (discountLoss / nominalTotal) * 100 : 0;\n    return { lossPct, pv, discountLoss, nominalTotal };",
    primaryKey: "lossPct", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "pv", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "discountLoss", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "nominalTotal", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "折現損失比", primaryLabelEn: "Discount Loss", secondaryLabelZh: "現值", secondaryLabelEn: "Present Value",
    tertiaryLabelZh: "折現損失", tertiaryLabelEn: "Discount Loss $", quaternaryLabelZh: "名目總額", quaternaryLabelEn: "Nominal Total",
    bands: ["極小", "小", "中等", "偏大", "大", "極大"], bandThresholds: [10, 25, 40, 55, 70],
    bandHints: [
      "折現損失 < 10%,折現率低或時間短,現值幾乎等於名目。",
      "10-25%,小幅,常見於中低折現率或中天期。",
      "25-40%,中等,反映一般企業折現率與中長天期。",
      "40-55%,偏大,折現率高或時間長,現值明顯縮水。",
      "55-70%,大,高風險或超長天期,未來金額大打折扣。",
      "> 70%,極大,折現率極高或時間極長,現值僅剩零頭。",
    ],
    faqTitles: ["現值是什麼?為什麼錢會變薄?", "折現率怎麼選?", "現值在投資決策怎麼用?", "樂透分期 vs 一次領哪個划算?", "資料會上傳嗎?", "可以做不規則現金流嗎?"],
    faqAnswers: [
      "**現值(Present Value)**是未來一筆錢「換算到今天」的價值。因為錢有時間價值(可投資生息、有通膨),未來的 100 元不如現在的 100 元值錢。折現率越高、時間越長,現值縮水越多。這是金融估值的基石。",
      "折現率反映「機會成本與風險」:無風險可用公債利率(2-4%);企業評估專案常用加權平均資本成本 WACC(8-12%);高風險新創可達 15-30%。折現率越高代表你要求越高的報酬補償風險,現值越低。",
      "投資決策用現值比較「未來收益的今天價值」與「現在投入成本」:若未來現金流的現值 > 投入成本(即 NPV > 0),專案值得做。本工具算單筆與年金現值,完整 NPV 請用 NPV 計算機。",
      "要比現值。樂透常給「一次領(打折)」或「30 年分期(名目較高)」。把分期年金按合理折現率算現值,再與一次領金額比。通常一次領+自行投資,長期可能優於分期,但需紀律與稅務考量。",
      "完全不會。所有計算都在你的瀏覽器內完成,金額與折現率資料不會傳送到任何伺服器。",
      "不規則現金流現值、NPV/IRR、敏感度分析與多情境折現比較屬於專業版功能。",
    ],
    affiliates: [
      aff("終值計算機", "Future Value Calculator", "/tools/finance/future-value-calculator"),
      aff("淨現值計算機", "Net Present Value Calculator", "/tools/finance/net-present-value-calculator"),
      aff("年金計算機", "Annuity Calculator", "/tools/finance/annuity-calculator"),
      aff("通膨調整計算機", "Inflation Adjuster", "/tools/finance/inflation-adjuster"),
    ],
    exampleSolid: ["100000", "6", "10", "0"], exampleHigh: ["0", "8", "20", "12000"],
    solidLabelZh: "未來 10 萬 · 6% · 10 年", solidLabelEn: "FV 100k · 6% · 10y",
    highLabelZh: "年金 1.2 萬 · 8% · 20 年", highLabelEn: "CF 12k · 8% · 20y",
    subtitleZh: "輸入未來金額、折現率與年數，立即算出今天的現值與折現損失",
    subtitleEn: "Enter future amount, discount rate, and years to compute today's present value and discount loss",
    definitionZh: "現值計算機以未來金額、折現率、年數與每年現金流,計算今天的現值、折現損失與名目總額,適用投資估值、年金折現與一次領 vs 分期的比較。",
    formulaZh: "現值 = 未來金額 ÷ (1 + r)^n + 每年現金流 × (1 − (1 + r)^−n) / r;其中 r 為折現率、n 為年數",
    limitationsZh: "本工具假設固定折現率與規律現金流,不處理不規則現金流、通膨變動與稅負;不規則現金流請用 NPV 計算機。",
    interpretationZh: "現值越低代表未來金額在今天越不值錢(折現率高或時間長);折現損失反映時間價值的侵蝕程度。",
    premiumTitleZh: "專業版 估值折現工具組", premiumTextZh: "解鎖不規則現金流現值、NPV/IRR、折現率敏感度分析、多情境比較與一次領 vs 分期決策。",
    premiumChipsZh: "不規則現金流|NPV/IRR|敏感度|分期決策",
    premiumTitleEn: "Pro Valuation Suite", premiumTextEn: "Unlock irregular cash flow PV, NPV/IRR, discount-rate sensitivity, scenario compare, and lump-vs-annuity decision.",
    premiumChipsEn: "Irregular CF|NPV/IRR|Sensitivity|Decision",
  },
  // F-46 annuity
  {
    file: "F46-annuity.json",
    id: "annuity-calculator", nameZh: "年金計算機", nameEn: "Annuity Calculator", color: "green",
    inputs: ["每期投入", "年利率%", "年數", "每年期數"],
    inputsEn: ["Payment Per Period", "Annual Rate Pct", "Years", "Periods Per Year"],
    defaults: ["1000", "6", "20", "12"], steps: ["100", "0.1", "1", "1"], accentIdx: 1,
    compute: "依每期投入、利率、年數與期數計算年金終值、總投入與利息收益",
    computeFn: "    const pmt = Number(paymentPerPeriod) || 0;\n    const annual = (Number(annualRatePct) || 0) / 100;\n    const yrs = Number(years) || 0;\n    const m = Number(periodsPerYear) || 1;\n    const i = annual / m;\n    const N = yrs * m;\n    const fv = i > 0 ? pmt * ((Math.pow(1 + i, N) - 1) / i) : pmt * N;\n    const pv = i > 0 ? pmt * ((1 - Math.pow(1 + i, -N)) / i) : pmt * N;\n    const contributed = pmt * N;\n    const interest = fv - contributed;\n    return { fv, interest, contributed, pv };",
    computeFnOverride: "    const pmt = Number(paymentPerPeriod) || 0;\n    const annual = (Number(annualRatePct) || 0) / 100;\n    const yrs = Number(years) || 0;\n    const m = Number(periodsPerYear) || 1;\n    const i = annual / m;\n    const N = yrs * m;\n    const fv = i > 0 ? pmt * ((Math.pow(1 + i, N) - 1) / i) : pmt * N;\n    const contributed = pmt * N;\n    const interest = fv - contributed;\n    const growthPct = contributed > 0 ? (interest / contributed) * 100 : 0;\n    return { growthPct, fv, interest, contributed };",
    primaryKey: "growthPct", primaryDecimals: 2, primaryUnit: "%", secondaryKey: "fv", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "interest", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "contributed", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "複利成長率", primaryLabelEn: "Compound Growth", secondaryLabelZh: "年金終值", secondaryLabelEn: "Annuity FV",
    tertiaryLabelZh: "利息收益", tertiaryLabelEn: "Interest Earned", quaternaryLabelZh: "總投入", quaternaryLabelEn: "Total Contributed",
    bands: ["極低", "低", "中等", "偏高", "高", "極高"], bandThresholds: [15, 40, 80, 150, 300],
    bandHints: [
      "成長 < 15%,屬於短年限或低利率,複利效果尚未顯現。",
      "15-40%,溫和,常見於 5-10 年期穩健年金累積。",
      "40-80%,中等,複利開始發揮,常見於 10-20 年期。",
      "80-150%,偏高,長年限複利成果,利息接近本金。",
      "150-300%,高,長期高報酬累積,利息遠超投入。",
      "> 300%,極高,超長年限或高報酬,複利威力充分展現。",
    ],
    faqTitles: ["年金是什麼?有哪些種類?", "期初年金和期末年金差在哪?", "年金商品費用高嗎?", "定期定額和年金一樣嗎?", "資料會上傳嗎?", "可以算遞延年金嗎?"],
    faqAnswers: [
      "**年金(Annuity)**是一連串等額、定期的現金流。常見種類:**(1) 累積型**(定期投入、未來領回,如退休儲蓄)、**(2) 給付型**(一次投入、定期領取,如退休年金)、**(3) 固定 vs 變額**(報酬固定或隨投資波動)。本工具計算累積型的終值與現值。",
      "**期末年金(ordinary annuity)**在每期「期末」付款(如房貸、多數儲蓄),本工具預設此類;**期初年金(annuity due)**在每期「期初」付款(如租金、保費),因每筆早一期生息,終值較高(乘以 1+i)。差異隨利率與期數放大。",
      "保險公司的年金商品常含**前置費用、管理費、解約費、附約成本**,可能侵蝕 1-3% 年報酬。購買前務必看清費用結構與保證內容。本工具算的是純數學年金,實際商品報酬需扣除費用。",
      "定期定額投資(如每月買 ETF/基金)本質上就是累積型年金的應用——固定金額、固定頻率投入。差別在年金常指保險商品(有保證但費用高),而定期定額多指自行投資(彈性高但無保證)。計算邏輯相同。",
      "完全不會。所有計算都在你的瀏覽器內完成,投入金額與利率資料不會傳送到任何伺服器。",
      "期初/期末年金切換、遞延年金、給付型年金提領與含費用的淨報酬屬於專業版功能。",
    ],
    affiliates: [
      aff("退休計算機", "Retirement Calculator", "/tools/finance/retirement-calculator"),
      aff("現值計算機", "Present Value Calculator", "/tools/finance/present-value-calculator"),
      aff("終值計算機", "Future Value Calculator", "/tools/finance/future-value-calculator"),
      aff("退休金計算機", "Pension Calculator", "/tools/finance/pension-calculator"),
    ],
    exampleSolid: ["1000", "6", "20", "12"], exampleHigh: ["500", "8", "30", "12"],
    solidLabelZh: "每月 1000 · 6% · 20 年", solidLabelEn: "1000/mo · 6% · 20y",
    highLabelZh: "每月 500 · 8% · 30 年", highLabelEn: "500/mo · 8% · 30y",
    subtitleZh: "輸入每期投入、利率與年數，立即算出年金終值、總投入與利息收益",
    subtitleEn: "Enter payment per period, rate, and years to compute annuity future value, contributions, and interest",
    definitionZh: "年金計算機以每期投入、年利率、年數與每年期數,計算累積型年金的終值、現值、總投入與利息收益,適用退休儲蓄、定期定額與年金商品試算。",
    formulaZh: "年金終值 = 每期投入 × ((1 + i)^N − 1) / i;年金現值 = 每期投入 × (1 − (1 + i)^−N) / i;i = 年利率 / 期數,N = 年數 × 期數",
    limitationsZh: "本工具採期末年金與固定利率,不含商品費用、解約成本、稅負與期初年金;保險年金請另扣費用,實際請以保單條款為準。",
    interpretationZh: "年金終值反映長期定期投入的複利成果;利息收益佔比越高,代表時間與複利貢獻越大,越早開始越有利。",
    premiumTitleZh: "專業版 年金規劃工具組", premiumTextZh: "解鎖期初/期末年金切換、遞延年金、給付型提領模擬、含費用淨報酬與通膨調整。",
    premiumChipsZh: "期初期末|遞延年金|提領模擬|淨報酬",
    premiumTitleEn: "Pro Annuity Planning Suite", premiumTextEn: "Unlock annuity-due toggle, deferred annuity, payout simulation, fee-adjusted net return, and inflation adjustment.",
    premiumChipsEn: "Due/Ordinary|Deferred|Payout|Net Return",
  },
  // F-47 lease-vs-buy
  {
    file: "F47-lease-vs-buy.json",
    id: "lease-vs-buy-calculator", nameZh: "租賃 vs 購買計算機", nameEn: "Lease vs Buy Calculator", color: "blue",
    inputs: ["購買總價", "每月租金", "持有年數", "殘值"],
    inputsEn: ["Purchase Price", "Monthly Lease", "Hold Years", "Resale Value"],
    defaults: ["1000000", "20000", "5", "400000"], steps: ["10000", "1000", "1", "10000"], accentIdx: 0,
    compute: "比較購買淨成本與租賃總成本，計算差額與每月等值成本",
    computeFn: "    const price = Number(purchasePrice) || 0;\n    const lease = Number(monthlyLease) || 0;\n    const yrs = Number(holdYears) || 1;\n    const resale = Number(resaleValue) || 0;\n    const months = yrs * 12;\n    const buyCost = price - resale;\n    const leaseCost = lease * months;\n    const diff = leaseCost - buyCost;\n    const buyMonthly = months > 0 ? buyCost / months : 0;\n    return { buyCost, leaseCost, diff, buyMonthly };",
    primaryKey: "diff", primaryDecimals: 2, primaryUnit: "$", secondaryKey: "buyCost", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "leaseCost", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "buyMonthly", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "租賃多付", primaryLabelEn: "Lease Premium", secondaryLabelZh: "購買淨成本", secondaryLabelEn: "Buy Net Cost",
    tertiaryLabelZh: "租賃總成本", tertiaryLabelEn: "Lease Total Cost", quaternaryLabelZh: "購買每月等值", quaternaryLabelEn: "Buy Monthly",
    bandKey: "diffSign", // custom: based on diff value bucket
    bands: ["租賃大省", "租賃略省", "接近", "購買略省", "購買大省", "購買壓倒"], bandThresholds: [-100000, -10000, 10000, 100000, 300000],
    bandHints: [
      "租賃總成本遠低於購買淨成本,且省去殘值風險與維護,租賃明顯划算。",
      "租賃略省,加上彈性與免維護,短期或不確定需求時租賃較佳。",
      "兩者接近,決策應看彈性、現金流、稅務與使用習慣等非價格因素。",
      "購買略省,若長期使用且殘值穩定,購買開始占優。",
      "購買大幅省,長期持有下擁有資產並回收殘值,購買明顯划算。",
      "購買壓倒性勝出,租賃成本遠超購買淨成本,除非極度需要彈性否則應購買。",
    ],
    faqTitles: ["租好還是買好?關鍵看什麼?", "為什麼要算殘值?", "租賃的隱藏成本有哪些?", "這個工具適用車、房、設備嗎?", "資料會上傳嗎?", "可以加上利息與稅務嗎?"],
    faqAnswers: [
      "關鍵看**持有期間與使用確定性**:長期、確定使用→購買(回收殘值、長期攤提便宜);短期、需求不確定、技術快速汰換→租賃(彈性、免處分風險)。本工具用「購買淨成本(售價−殘值)vs 租賃總成本」做直觀比較。",
      "因為購買後資產仍有價值,結束使用時可賣出回收。**購買淨成本 = 購買價 − 殘值**,才是真正的「擁有成本」。忽略殘值會嚴重高估購買成本——例如百萬車 5 年後殘值 40 萬,實際成本只有 60 萬。",
      "租賃常見隱藏成本:**(1) 超里程/超用量費**、(2) 還車時的耗損賠償、(3) 提前解約違約金、(4) 保險與保證金要求、(5) 合約綁定期間的彈性限制。簽約前務必看清條款,別只比月租金。",
      "適用任何「可租可買」的資產:汽車、房產(租 vs 買房)、辦公設備、機器、伺服器、軟體授權等。只要能填入購買價、月租、持有期與殘值即可比較。房產比較建議另計增值與機會成本。",
      "完全不會。所有計算都在你的瀏覽器內完成,價格與租金資料不會傳送到任何伺服器。",
      "貸款利息、稅務折抵、機會成本(自有資金投資報酬)與通膨折現的完整 TCO 分析屬於專業版功能。",
    ],
    affiliates: [
      aff("貸款計算機", "Loan Calculator", "/tools/finance/loan-calculator"),
      aff("房貸計算機", "Mortgage Calculator", "/tools/finance/mortgage-calculator"),
      aff("淨現值計算機", "Net Present Value Calculator", "/tools/finance/net-present-value-calculator"),
      aff("攤還排程計算機", "Amortization Schedule Calculator", "/tools/finance/amortization-schedule-calculator"),
    ],
    exampleSolid: ["1000000", "20000", "5", "400000"], exampleHigh: ["1500000", "18000", "8", "300000"],
    solidLabelZh: "買 100 萬 · 租 2 萬/月 · 5 年", solidLabelEn: "Buy 1M · 20k/mo · 5y",
    highLabelZh: "買 150 萬 · 租 1.8 萬/月 · 8 年", highLabelEn: "Buy 1.5M · 18k/mo · 8y",
    subtitleZh: "輸入購買總價、月租金、持有年數與殘值，立即比較租賃與購買的真實成本",
    subtitleEn: "Enter purchase price, monthly lease, hold years, and resale value to compare lease vs buy total cost",
    definitionZh: "租賃 vs 購買計算機以購買總價、每月租金、持有年數與殘值,計算購買淨成本與租賃總成本的差額,協助判斷汽車、房產、設備等資產該租還是該買。",
    formulaZh: "購買淨成本 = 購買價 − 殘值;租賃總成本 = 每月租金 × 持有月數;租賃多付 = 租賃總成本 − 購買淨成本",
    limitationsZh: "本工具為簡化比較,不計貸款利息、稅務折抵、保險、維護、機會成本與通膨折現;完整 TCO 與含財務成本分析請用專業版。",
    interpretationZh: "「租賃多付」為正表示購買較省、為負表示租賃較省;但決策還需納入彈性、現金流與風險偏好等非價格因素。",
    premiumTitleZh: "專業版 租買決策工具組", premiumTextZh: "解鎖貸款利息、稅務折抵、機會成本、通膨折現的完整 TCO 分析與多情境敏感度比較。",
    premiumChipsZh: "貸款利息|稅務折抵|機會成本|TCO分析",
    premiumTitleEn: "Pro Lease/Buy Decision Suite", premiumTextEn: "Unlock loan interest, tax deductions, opportunity cost, inflation-discounted full TCO, and scenario sensitivity.",
    premiumChipsEn: "Interest|Tax|Opp Cost|TCO",
  },
  // F-48 refinance
  {
    file: "F48-refinance.json",
    id: "refinance-calculator", nameZh: "再融資計算機", nameEn: "Refinance Calculator", color: "pink",
    inputs: ["剩餘本金", "原月付", "新年利率%", "新年限"],
    inputsEn: ["Remaining Balance", "Current Payment", "New Rate Pct", "New Years"],
    defaults: ["400000", "2500", "4", "20"], steps: ["10000", "100", "0.1", "1"], accentIdx: 2,
    compute: "依剩餘本金、新利率與新年限計算新月付、月省金額與總利息節省",
    computeFn: "    const bal = Number(remainingBalance) || 0;\n    const oldPay = Number(currentPayment) || 0;\n    const r = (Number(newRatePct) || 0) / 100 / 12;\n    const n = (Number(newYears) || 1) * 12;\n    const newPay = r > 0 ? (bal * r) / (1 - Math.pow(1 + r, -n)) : bal / n;\n    const monthlySave = oldPay - newPay;\n    const newTotalInterest = newPay * n - bal;\n    const lifetimeSave = monthlySave * n;\n    return { newPay, monthlySave, newTotalInterest, lifetimeSave };",
    primaryKey: "monthlySave", primaryDecimals: 2, primaryUnit: "$", secondaryKey: "newPay", secondaryDecimals: 2, secondaryUnit: "$",
    tertiaryKey: "newTotalInterest", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "lifetimeSave", quaternaryDecimals: 2, quaternaryUnit: "$",
    primaryLabelZh: "每月省", primaryLabelEn: "Monthly Savings", secondaryLabelZh: "新月付", secondaryLabelEn: "New Payment",
    tertiaryLabelZh: "新總利息", tertiaryLabelEn: "New Total Interest", quaternaryLabelZh: "全期省", quaternaryLabelEn: "Lifetime Savings",
    bandKey: "monthlySave",
    bands: ["反而貴", "持平", "小省", "中省", "大省", "超省"], bandThresholds: [0.01, 100, 300, 600, 1000],
    bandHints: [
      "每月省 ≤ 0,新方案反而更貴,通常因延長年限抵銷利率優勢,不建議。",
      "0-100,月省微薄,需確認手續費與閉鎖成本是否值得。",
      "100-300,小幅節省,計算回本期後再決定。",
      "300-600,中等節省,通常值得,留意一次性費用攤回。",
      "600-1000,大幅節省,再融資吸引力高。",
      "> 1000,超大節省,強烈建議評估再融資(確認費用後)。",
    ],
    faqTitles: ["什麼時候該再融資?", "再融資的成本有哪些?", "降月付 vs 省總利息怎麼選?", "延長年限是陷阱嗎?", "資料會上傳嗎?", "可以算回本期嗎?"],
    faqAnswers: [
      "常見再融資時機:**(1) 市場利率明顯下降**(一般降 0.75-1% 以上才划算)、**(2) 信用評分提升**可拿到更好利率、**(3) 想縮短年限**加速還清、**(4) 浮動轉固定**鎖定利率。關鍵是「省下的利息 > 再融資成本」且能在持有期內回本。",
      "再融資成本包含:**(1) 開辦費/手續費**(常見本金 0.5-2%)、**(2) estimation/鑑價費**、**(3) 代書/過戶費**、**(4) 原貸款提前清償違約金**。把這些一次性成本除以每月省的金額,就是回本月數,超過持有期就不划算。",
      "**降月付**改善現金流(適合手頭緊、想增加投資),但若靠延長年限換來,總利息可能反增;**省總利息**靠降利率或縮年限達成,長期更省但月付可能不降甚至上升。看你重視現金流還是總成本。",
      "不一定是陷阱,但要警覺。延長年限(如剩 20 年再融資成 30 年)能大幅降月付,但總利息可能不減反增。聰明做法:**再融資成更低利率,但維持或縮短年限**,才能同時降月付與省總息。本工具讓你試不同年限觀察。",
      "完全不會。所有計算都在你的瀏覽器內完成,本金與利率資料不會傳送到任何伺服器。",
      "含手續費的回本期、降月付 vs 縮年限情境比較、剩餘利息精算與最佳再融資時機屬於專業版功能。",
    ],
    affiliates: [
      aff("房貸計算機", "Mortgage Calculator", "/tools/finance/mortgage-calculator"),
      aff("攤還排程計算機", "Amortization Schedule Calculator", "/tools/finance/amortization-schedule-calculator"),
      aff("貸款計算機", "Loan Calculator", "/tools/finance/loan-calculator"),
      aff("有效年利率計算機", "Effective Annual Rate Calculator", "/tools/finance/effective-annual-rate-calculator"),
    ],
    exampleSolid: ["400000", "2500", "4", "20"], exampleHigh: ["600000", "3800", "3.5", "25"],
    solidLabelZh: "餘額 40 萬 · 舊月付 2500 · 4% · 20 年", solidLabelEn: "Bal 400k · old 2500 · 4% · 20y",
    highLabelZh: "餘額 60 萬 · 舊月付 3800 · 3.5% · 25 年", highLabelEn: "Bal 600k · old 3800 · 3.5% · 25y",
    subtitleZh: "輸入剩餘本金、原月付與新方案，立即算出新月付、每月省與全期節省",
    subtitleEn: "Enter remaining balance, current payment, and new terms to compute new payment and total savings",
    definitionZh: "再融資計算機以剩餘本金、原月付、新利率與新年限,計算再融資後的新月付、每月節省、新總利息與全期節省,協助判斷房貸或貸款是否值得再融資。",
    formulaZh: "新月付 = 餘額 × r / (1 − (1+r)^−n);每月省 = 原月付 − 新月付;全期省 = 每月省 × 新期數(未扣手續費)",
    limitationsZh: "本工具未計再融資手續費、開辦費與提前清償違約金,因此「全期省」為毛節省;務必扣除一次性成本並計算回本期再決定。",
    interpretationZh: "每月省為正且能在持有期內回本(一次性成本÷每月省)才值得;留意延長年限可能使總利息不減反增。",
    premiumTitleZh: "專業版 再融資決策工具組", premiumTextZh: "解鎖含手續費的回本期、降月付 vs 縮年限情境比較、剩餘利息精算與最佳再融資時機分析。",
    premiumChipsZh: "回本期|情境比較|利息精算|最佳時機",
    premiumTitleEn: "Pro Refinance Decision Suite", premiumTextEn: "Unlock fee-inclusive break-even, lower-payment vs shorter-term scenarios, exact interest, and optimal timing.",
    premiumChipsEn: "Break-even|Scenarios|Exact|Timing",
  },
  // F-49 home-affordability
  {
    file: "F49-home-affordability.json",
    id: "home-affordability-calculator", nameZh: "購屋負擔能力計算機", nameEn: "Home Affordability Calculator", color: "stone",
    inputs: ["年收入", "頭期款", "房貸利率%", "每月債務"],
    inputsEn: ["Annual Income", "Down Payment", "Mortgage Rate Pct", "Monthly Debt"],
    defaults: ["1200000", "2000000", "4", "10000"], steps: ["50000", "100000", "0.1", "1000"], accentIdx: 0,
    compute: "依年收入、頭期、利率與既有債務，估算可負擔房價與每月房貸上限",
    computeFn: "    const income = Number(annualIncome) || 0;\n    const down = Number(downPayment) || 0;\n    const r = (Number(mortgageRatePct) || 0) / 100 / 12;\n    const debt = Number(monthlyDebt) || 0;\n    const monthlyIncome = income / 12;\n    const maxHousing = monthlyIncome * 0.28;\n    const maxTotal = monthlyIncome * 0.36 - debt;\n    const maxPayment = Math.max(0, Math.min(maxHousing, maxTotal));\n    const n = 360;\n    const maxLoan = r > 0 ? maxPayment * (1 - Math.pow(1 + r, -n)) / r : maxPayment * n;\n    const maxHomePrice = maxLoan + down;\n    return { maxHomePrice, maxPayment, maxLoan, monthlyIncome };",
    computeFnOverride: "    const income = Number(annualIncome) || 0;\n    const down = Number(downPayment) || 0;\n    const r = (Number(mortgageRatePct) || 0) / 100 / 12;\n    const debt = Number(monthlyDebt) || 0;\n    const monthlyIncome = income / 12;\n    const maxHousing = monthlyIncome * 0.28;\n    const maxTotal = monthlyIncome * 0.36 - debt;\n    const maxPayment = Math.max(0, Math.min(maxHousing, maxTotal));\n    const n = 360;\n    const maxLoan = r > 0 ? maxPayment * (1 - Math.pow(1 + r, -n)) / r : maxPayment * n;\n    const maxHomePrice = maxLoan + down;\n    const priceToIncome = income > 0 ? maxHomePrice / income : 0;\n    return { priceToIncome, maxHomePrice, maxPayment, maxLoan };",
    primaryKey: "priceToIncome", primaryDecimals: 1, primaryUnit: "x", secondaryKey: "maxHomePrice", secondaryDecimals: 0, secondaryUnit: "$",
    tertiaryKey: "maxPayment", tertiaryDecimals: 2, tertiaryUnit: "$", quaternaryKey: "maxLoan", quaternaryDecimals: 0, quaternaryUnit: "$",
    primaryLabelZh: "房價所得倍數", primaryLabelEn: "Price-to-Income", secondaryLabelZh: "可負擔房價", secondaryLabelEn: "Affordable Price",
    tertiaryLabelZh: "每月房貸上限", tertiaryLabelEn: "Max Payment", quaternaryLabelZh: "可貸金額", quaternaryLabelEn: "Max Loan",
    bands: ["保守", "穩健", "標準", "偏緊", "吃緊", "超貸"], bandThresholds: [3, 5, 7, 9, 12],
    bandHints: [
      "房價約年收入 < 3 倍,非常保守,財務彈性充裕,易核貸。",
      "3-5 倍,穩健,符合傳統可負擔範圍,壓力可控。",
      "5-7 倍,標準上限,常見於大城市,需穩定收入支撐。",
      "7-9 倍,偏緊,房貸佔比高,對利率與收入變動敏感。",
      "9-12 倍,吃緊,接近放款極限,風險顯著上升。",
      "> 12 倍,超貸,房價遠超合理負擔,極可能被拒貸或陷入困境。",
    ],
    faqTitles: ["28/36 法則是什麼?", "頭期款要準備多少?", "我能借多少房貸?", "除了房貸還要算哪些成本?", "資料會上傳嗎?", "可以含房屋稅與保險嗎?"],
    faqAnswers: [
      "**28/36 法則**是傳統放款基準:**前端比(28%)**——每月房貸(本息+稅+保險)不超過月毛收入的 28%;**後端比(36%)**——房貸加上所有債務(車貸、卡債、學貸)不超過月毛收入的 36%。本工具取兩者較嚴格者算出可負擔上限。",
      "傳統建議頭期款 **20%**(可免額外貸款保險 PMI),但首購方案可低至 3-5%(需付 PMI)。頭期越高:月付越低、總利息越少、核貸越易。除頭期外還需預留**過戶費(2-5%)+ 緊急預備金(3-6 個月支出)**。",
      "可貸金額取決於:**收入、既有債務、利率、年限、信用評分**。本工具用 28/36 法則反推可負擔月付,再依利率與 30 年期反推可貸本金。實際核貸還看信用、工作穩定性與銀行政策,建議多家比較。",
      "購屋總成本遠不只房貸:**(1) 房屋稅、(2) 房屋保險、(3) 管理費/HOA、(4) 維護修繕(年約房價 1%)、(5) 過戶與代書費、(6) 搬遷與裝潢**。買房前務必把這些算進每月與年度預算,別只看月付。",
      "完全不會。所有計算都在你的瀏覽器內完成,收入與債務資料不會傳送到任何伺服器。",
      "房屋稅、保險、HOA、PMI 的完整 PITI 計算、多情境壓力測試與利率變動分析屬於專業版功能。",
    ],
    affiliates: [
      aff("房貸計算機", "Mortgage Calculator", "/tools/finance/mortgage-calculator"),
      aff("負債收入比計算機", "Debt-to-Income Calculator", "/tools/finance/debt-to-income-calculator"),
      aff("攤還排程計算機", "Amortization Schedule Calculator", "/tools/finance/amortization-schedule-calculator"),
      aff("緊急預備金計算機", "Emergency Fund Calculator", "/tools/finance/emergency-fund-calculator"),
    ],
    exampleSolid: ["1200000", "2000000", "4", "10000"], exampleHigh: ["2400000", "5000000", "3.5", "5000"],
    solidLabelZh: "年收 120 萬 · 頭期 200 萬 · 4%", solidLabelEn: "Inc 1.2M · Down 2M · 4%",
    highLabelZh: "年收 240 萬 · 頭期 500 萬 · 3.5%", highLabelEn: "Inc 2.4M · Down 5M · 3.5%",
    subtitleZh: "輸入年收入、頭期款、房貸利率與既有債務，立即估算可負擔房價與每月房貸上限",
    subtitleEn: "Enter annual income, down payment, mortgage rate, and debts to estimate affordable home price and max payment",
    definitionZh: "購屋負擔能力計算機依年收入、頭期款、房貸利率與既有每月債務,套用 28/36 黃金法則,估算可負擔的房價、每月房貸上限與可貸金額,協助購屋前的預算規劃。",
    formulaZh: "每月房貸上限 = min(月收入 × 28%, 月收入 × 36% − 既有債務);可貸金額 = 月付上限 × (1 − (1+r)^−360) / r;可負擔房價 = 可貸金額 + 頭期款",
    limitationsZh: "本工具採 28/36 法則與 30 年期假設,未含房屋稅、保險、HOA、PMI 與信用評分影響;實際核貸金額請以銀行評估為準。",
    interpretationZh: "可負擔房價為上限參考,實務上建議保守抓 8 成以保留彈性;房貸佔比越低財務越穩健,越高則對利率與收入變動越敏感。",
    premiumTitleZh: "專業版 購屋規劃工具組", premiumTextZh: "解鎖含房屋稅、保險、HOA、PMI 的完整 PITI 計算、收入/利率壓力測試與多情境購屋預算比較。",
    premiumChipsZh: "PITI計算|壓力測試|多情境|稅險HOA",
    premiumTitleEn: "Pro Home Buying Suite", premiumTextEn: "Unlock full PITI with tax/insurance/HOA/PMI, income/rate stress tests, and multi-scenario budget comparison.",
    premiumChipsEn: "PITI|Stress Test|Scenarios|Tax/Ins",
  },
];

for (const t of tools) {
  const obj = { ...t };
  delete obj.file;
  // honor computeFnOverride if present (replaces computeFn)
  if (obj.computeFnOverride) {
    obj.computeFn = obj.computeFnOverride;
    delete obj.computeFnOverride;
  }
  // bandKey is unused by spec-builder (it bands on primary value); drop it
  delete obj.bandKey;
  const fp = path.join(BRIEFS, t.file);
  fs.writeFileSync(fp, JSON.stringify(obj, null, 2));
  console.log("wrote", t.file, "primary=" + obj.primaryKey + obj.primaryUnit + " thr=[" + obj.bandThresholds.join(",") + "]");
}
console.log("Batch 2 briefs written:", tools.length);
